### PR TITLE
Don't fire SBP events until min cluster is met for the first time

### LINKED ISSUE #17038: QuorumListener is triggered during member startup but before it has joined a cluster
**Describe the bug**
Tested on 3.12.2 which is customer's version.
In a cluster with Quorum defined, without touching any maps, just calling `Hazelcast.newHazelcastInstance();` causes `QuorumListener` to be triggered, before the member joins anyone and forms the cluster initially. 

**Expected behavior**
We shouldn’t fire any quorum listener events after a member starts until quorum is met initially.

**To Reproduce**

1. Define a quorum of 3 with a listener attached 
```
    <quorum enabled="true" name="myquorum">
        <quorum-size>3</quorum-size>
        <quorum-listeners>
            <quorum-listener>MyQuoLis</quorum-listener>
        </quorum-listeners>
    </quorum>
```
2. Start one member
3. Observe how member logs a quorum event before join:
```
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Hazelcast 3.12.2 (20190802 - e34b163) starting at [127.0.0.1]:5701
Jun 01, 2020 4:22:40 PM com.hazelcast.system
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
Jun 01, 2020 4:22:40 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Backpressure is disabled
Jun 01, 2020 4:22:40 PM com.hazelcast.instance.Node
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Creating TcpIpJoiner
Jun 01, 2020 4:22:40 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Starting 8 partition threads and 5 generic threads (1 dedicated for priority tasks)
Jun 01, 2020 4:22:40 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Jun 01, 2020 4:22:40 PM com.hazelcast.core.LifecycleService
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] [127.0.0.1]:5701 is STARTING
Listener triggered: QuorumEvent{threshold=3, currentMembers=com.hazelcast.internal.cluster.impl.MemberSelectingCollection@1d30e322, presence=false}
Jun 01, 2020 4:22:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Connecting to /127.0.0.1:5703, timeout: 10000, bind-any: true
Jun 01, 2020 4:22:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Connecting to /127.0.0.1:5702, timeout: 10000, bind-any: true
Jun 01, 2020 4:22:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Could not connect to: /127.0.0.1:5702. Reason: SocketException[Connection refused to address /127.0.0.1:5702]
Jun 01, 2020 4:22:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Could not connect to: /127.0.0.1:5703. Reason: SocketException[Connection refused to address /127.0.0.1:5703]
Jun 01, 2020 4:22:40 PM com.hazelcast.cluster.impl.TcpIpJoiner
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] [127.0.0.1]:5703 is added to the blacklist.
Jun 01, 2020 4:22:40 PM com.hazelcast.cluster.impl.TcpIpJoiner
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] [127.0.0.1]:5702 is added to the blacklist.
Jun 01, 2020 4:22:41 PM com.hazelcast.internal.cluster.ClusterService
INFO: [127.0.0.1]:5701 [sertug] [3.12.2]

Members {size:1, ver:1} [
Member [127.0.0.1]:5701 - 3a89efeb-9da0-4a08-8b54-f6f7632387d5 this
]
```

### PR DESCRIPTION
**Pull request by mdogan**
SBP = SplitBrainProtection

Fixes #17038

3.12.z: #17082
4.1: #17089

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1122/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1122/Hazelcast-pr-builder-1122.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientCacheEventJournalBasicTest>AbstractEventJournalBasicTest.allowReadingWithFutureSeq:511->HazelcastTestSupport.assertOpenEventually:1222->HazelcastTestSupport.assertOpenEventually:1237 CountDownLatch failed to complete within 30 seconds, count left: 1
[ERROR]   CPMemberAddRemoveTest.when_snapshotIsTakenWhileRemovingCPMember_newMemberInstallsSnapshot:767->HazelcastTestSupport.assertTrueEventually:1458->HazelcastTestSupport.assertTrueEventually:1356->lambda$when_snapshotIsTakenWhileRemovingCPMember_newMemberInstallsSnapshot$17:770 expected:<[CPMember{uuid=caa51161-4bf2-4432-bb17-61c99305b6cc, address=[127.0.0.1]:5702}, CPMember{uuid=7b93a2ef-242e-4996-8b55-e9ee96dddabe, address=[127.0.0.1]:5703}, CPMember{uuid=ed1ac6ae-b0ee-450f-af92-200fe8704bb7, address=[127.0.0.1]:5704}]> but was:<[CPMember{uuid=b59644b6-033c-4e87-9561-b7805a31fda3, address=[127.0.0.1]:5701}, CPMember{uuid=caa51161-4bf2-4432-bb17-61c99305b6cc, address=[127.0.0.1]:5702}, CPMember{uuid=7b93a2ef-242e-4996-8b55-e9ee96dddabe, address=[127.0.0.1]:5703}]>
[INFO] 
[ERROR] Tests run: 27446, Failures: 2, Errors: 0, Skipped: 996
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1123/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1123/Hazelcast-pr-builder-1123.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TransactionQueueTest.testIssue859And863_WhenInQueueOnSecondInstance_OutQueueOnFirstInstance:378->testIssue859And863:411->HazelcastTestSupport.assertTrueEventually:1458->HazelcastTestSupport.assertTrueEventually:1356 expected:<3000> but was:<2999>
[INFO] 
[ERROR] Tests run: 27446, Failures: 1, Errors: 0, Skipped: 996
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by mdogan** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1132/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1132/Hazelcast-pr-builder-1132.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientCacheEventJournalBasicTest>AbstractEventJournalBasicTest.allowReadingWithFutureSeq:511->HazelcastTestSupport.assertOpenEventually:1222->HazelcastTestSupport.assertOpenEventually:1237 CountDownLatch failed to complete within 30 seconds, count left: 1
[INFO] 
[ERROR] Tests run: 27456, Failures: 1, Errors: 0, Skipped: 996
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by mmedenjak** [comment]
Simple forward-port of an already approved PR, merging with known test failure.

**Pull request merged**
