### PR TITLE
Unsigned masking

### PR DESCRIPTION
**Pull request by jpaw**
readUnsignedByte() returned a negative number, causing a test in my repository bonaparte-java to fail. This small pull request should fix the issue.

### CODE REVIEW

**Comment by sancar** [comment]
Hi @jpaw , thanks for the fix.  

We are gonna need you to sign our contributor agreement to accept your pull request.
https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by sancar** [comment]
verify

**Comment by jpaw** [comment]
Hi,
thanks a lot. I have just mailed the contributor agreement.

**Comment by jerrinot** [comment]
@jpaw: Thanks a lot for your contribution!

**Pull request merged**
