### PR TITLE
fixed client connection retry operations and reconnection problems. fixe...

### LINKED ISSUE #4647: [TEST-FAILURE]ClientRegressionTest.testIssue493
```
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> <not-locked>
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.ensureUnlocked(UnlockOperation.java:71)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:65)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:57)
	at com.hazelcast.spi.impl.BasicOperationService$BasicOperationHandler.process(BasicOperationService.java:707)
	at 
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/347/testReport/junit/com.hazelcast.client/ClientRegressionTest/testIssue493/

### PR DESCRIPTION
**Pull request by eminn**
...d the test failure that led us to find those bugs. fixes #4647 , #4692 , #4693

### CODE REVIEW

**Comment by sancar** [comment]
verify

**Comment by eminn** [comment]
verify

**Comment by eminn** [comment]
Test failure : com.hazelcast.client.map.ClientMapIssueTest.testOperationNotBlockingAfterClusterShutdown

which will be fixed by the pull request #4702. This pull request should be merged after #4702 is merged.

**Comment by eminn** [comment]
verify

**Comment by eminn** [comment]
verify

**Comment by eminn** [comment]
verify

**Pull request closed without merging**
