### PR TITLE
fix NullPointerException in IndexCopyBehavior.NEVER mode

### PR DESCRIPTION
**Pull request by HugeOrangeDev**
when copyOn == IndexCopyBehavior.NEVER.   
then resultCopyFunctor is PassThroughFunctor
when index query result is null.  the null value will be passed to ExpirationAwareHashMapDelegate. 
so delegateMap of ExpirationAwareHashMapDelegate is null

then AbstractIndex line:186 .   variable [result]  is a Set which contains the ExpirationAwareHashMapDelegate whose delegateMap is null

the size() will throw NullPointerException.
then the query will scan the whole partition

### CODE REVIEW

**Comment by HugeOrangeDev** [comment]
> Can one of the admins verify this patch?

no option of reviewers

> Can one of the admins verify this patch?

no optional reviewers

**Comment by taburet** [comment]
run-lab-run

**Comment by taburet** [comment]
The PR build is failing with checkstyle error: `BaseIndexStore.java:166:21: '!=' is not followed by whitespace. [WhitespaceAround]`

**Comment by HugeOrangeDev** [comment]
> Looks good, thanks for the fix. It also might make sense to add a check for `!map.isEmpty()`.

emmmm. map is null.  `!map.isEmpty()` may also throw NullPointerException

**Comment by taburet** [comment]
> emmmm. map is null. !map.isEmpty() may also throw NullPointerException
`map != null && !map.isEmpty() && isExpirable()`? but in the end, that's not a good idea to skip the empty maps, since the raw map contents may change and we won't be tracking the expiration.

**Comment by mmedenjak** [comment]
Hi @HugeOrangeDev !

Thank you for your contribution.
Before we can merge, can you please follow the instructions to sign and send the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)?

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by HugeOrangeDev** [comment]
> Hi @HugeOrangeDev !
> 
> Thank you for your contribution.
> Before we can merge, can you please follow the instructions to sign and send the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)?

That's ok! Email sent already.

**Comment by mmedenjak** [comment]
Thank you for signing the CLA and thank you for your contribution @HugeOrangeDev ! 

cc @Holmistr

**Pull request merged**
