### PR TITLE
Fixes sorted probes problem

### LINKED ISSUE #7445: MetricsPluginTest.testRunWithProblematicProbe
```
java.lang.AssertionError: 'Metrics[
                          classloading.loadedClassesCount=10,735
                          classloading.totalLoadedClassesCount=11,253
                          classloading.unloadedClassCount=518
                          client.endpoint.count=0
                          client.endpoint.totalRegistrations=0
                          cluster.clock.clusterTimeDiff=0
                          executor.hz:async.queueSize=0
                          executor.hz:client.queueSize=0
                          executor.hz:cluster.queueSize=0
                          executor.hz:cluster:event.queueSize=0
                          executor.hz:scheduled.queueSize=0
                          executor.hz:system.queueSize=0
                          gc.majorCount=24
                          gc.majorTime=13,576
                          gc.minorCount=517
                          gc.minorTime=17,599
                          gc.unknownCount=0
                          gc.unknownTime=0
                          operation.callTimeoutCount=0
                          operation.completed.count=0
                          operation.invocations.backupTimeouts=0
                          operation.invocations.normalTimeouts=0
                          operation.invocations.pending=0
                          operation.operationTimeoutCount=0
                          operation.priority-queue.size=0
                          operation.queue.size=0
                          operation.response-queue.size=0
                          operation.response.backup.count=0
                          operation.response.error.count=0
                          operation.response.normal.count=0
                          operation.response.timeout.count=0
                          operation.retryCount=0
                          os.committedVirtualMemorySize=10,185,711,616
                          os.freePhysicalMemorySize=0
                          os.freeSwapSpaceSize=32,212,250,624
                          os.maxFileDescriptorCount=32,768
                          os.openFileDescriptorCount=102
                          os.processCpuTime=746,920,000,000
                          os.systemLoadAverage=143.0
                          os.totalPhysicalMemorySize=4,294,967,296
                          os.totalSwapSpaceSize=32,212,250,624
                          proxy.createdCount=0
                          proxy.destroyedCount=0
                          runtime.availableProcessors=16
                          runtime.freeMemory=465,823,528
                          runtime.maxMemory=954,466,304
                          runtime.totalMemory=954,007,552
                          runtime.uptime=1,825,363
                          runtime.usedMemory=488,184,024
                          thread.daemonThreadCount=8
                          thread.peakThreadCount=2,225
                          thread.threadCount=144
                          thread.totalStartedThreadCount=149,345]' doesn't contains 'broken=java.lang.RuntimeException:error'
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.internal.monitors.AbstractPerformanceMonitorPluginTest.assertContains(AbstractPerformanceMonitorPluginTest.java:20)
	at com.hazelcast.internal.monitors.MetricsPluginTest.testRunWithProblematicProbe(MetricsPluginTest.java:61)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/809/testReport/junit/com.hazelcast.internal.monitors/MetricsPluginTest/testRunWithProblematicProbe/

### PR DESCRIPTION
**Pull request by pveentjer**
fix #7445

Minor improvement in the sorted probes that resolves a spurious test failure.

### CODE REVIEW

**Comment by jerrinot** [comment]
Why is it touching the XMLs?

**Comment by pveentjer** [comment]
Let me fix that. I cleaned up my idea due to some slowdown issues.

**Comment by jerrinot** [comment]
:+1:

**Comment by pveentjer** [comment]
run-lab-run

**Pull request merged**
