### PR TITLE
revert setting creation time for enterprise part

### PR DESCRIPTION
**Pull request by gurbuzali**

### CODE REVIEW

**Comment by jerrinot** [comment]
what's the reasoning behind this?

**Comment by gurbuzali** [comment]
we've merged a PR moving `setCreationTime` logic into constructor of `AbstractRecord`, since `HDRecord` does not extend from `AbstractRecord`, enterprise tests start to fail.

**Comment by metanet** [comment]
:+1:

**Comment by jerrinot** [comment]
:+1:

**Comment by ahmetmircik** [comment]
:+1:

**Pull request merged**
