### PR TITLE
Replaced FindBugs with SpotBugs

### PR DESCRIPTION
**Pull request by Donnerbart**
* replaced FindBugs with SpotBugs
* removed the exclude XML file, because we never used it
* adapted documentation

<hr/>

FindBugs is not actively developed anymore. SpotBugs is a forked successor, which is in active development: https://github.com/spotbugs/spotbugs

The migration is very painless and everything still works the same.

<hr/>

Sample output by removing an existing suppression:

FindBugs:

```
[INFO] Done FindBugs Analysis....
[INFO] 
[INFO] <<< findbugs-maven-plugin:3.0.1:check (default) < :findbugs @ hazelcast <<<
[INFO] 
[INFO] --- findbugs-maven-plugin:3.0.1:check (default) @ hazelcast ---
[INFO] BugInstance size is 1
[INFO] Error size is 0
[INFO] Total bugs: 1
[INFO] com.hazelcast.map.impl.InternalMapListenerAdapter.getListenerAdapters() may expose
  internal representation by returning InternalMapListenerAdapter.listenerAdapters
  [com.hazelcast.map.impl.InternalMapListenerAdapter]
  At InternalMapListenerAdapter.java:[line 59]
```

SpotBugs:
```
[INFO] Done SpotBugs Analysis....
[INFO] 
[INFO] <<< spotbugs-maven-plugin:3.1.1:check (default) < :spotbugs @ hazelcast <<<
[INFO] 
[INFO] --- spotbugs-maven-plugin:3.1.1:check (default) @ hazelcast ---
[INFO] BugInstance size is 1
[INFO] Error size is 0
[INFO] Total bugs: 1
[INFO] com.hazelcast.map.impl.InternalMapListenerAdapter.getListenerAdapters() may expose
  internal representation by returning InternalMapListenerAdapter.listenerAdapters
  [com.hazelcast.map.impl.InternalMapListenerAdapter]
  At InternalMapListenerAdapter.java:[line 59] EI_EXPOSE_REP
```

A small but important difference is, that SpotBugs tells us directly the name of the violated rule. This helps a lot to find the correct suppression (if this is the way to go):
```java
@SuppressFBWarnings(value = "EI_EXPOSE_REP",
    justification = "listenerAdapters internal state is never changed")
```

<hr/>

The only downside I could find is that a JDK 8 is required to execute SpotBugs. Our FindBugs build on Jenkins is already on a JDK 8. And if you start FindBugs from IDEA you can also easily set another JDK for that run configuration. So this should just be an issue on a terminal, when you have configured JDK 6 or 7 as default. But I guess this is not a show stopper.

If we decide to switch to the new tool, the only must-have requirement is to adapt the FindBugs job in Cloudbees to use the new profile.
And of course everyone has to do it locally (I don't intend to support the `findbugs` profile anymore, we should not have the term anywhere in the code).

Is there anything to consider for OSGi or the shading configuration?

### CODE REVIEW

**Comment by Donnerbart** [comment]
Yes, I'm also in favor to move this to 3.11. No need to introduce a risk for 3.10 now. I've set the milestone accordingly, so we don't forget about it then.

**Comment by pveentjer** [comment]
My main worry is if Spotbugs is a superset of Findbugs. It would be a loss if it doesn't catch all bugs that Findbugs catches. I realize that it is a successor, but that doesn't need to imply it is a superset.

**Comment by Donnerbart** [comment]
It's a fork of the original project, which is not maintaned for years.
> SpotBugs is the spiritual successor of FindBugs, carrying on from the point where it left off with support of its community.
> SpotBugs is licensed under the GNU LESSER GENERAL PUBLIC LICENSE.
> More information at the official website. A lot of things can still be found at the old FindBugs website.

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Holmistr** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
SpotsBugs ran fine without any errors or warnings :tada:

**Pull request merged**
