### PR TITLE
[DO NOT MERGE] Added containsValue to TransactionalMap

### PR DESCRIPTION
**Pull request by c2v4**
Fixes Issue #1027 TransactionalMap has no containsValue(Object value) method

### CODE REVIEW

**Comment by tombujok** [comment]
Thx for the contribution!
Client side has to be added due to the fact that the guys couldn't build the protocol on a windows host.

**Comment by mmedenjak** [comment]
Hello @c2v4  ,

thanks for this contribution. Can you please sign our [contributor agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)? We will then review and merge the PR.

From the looks of it, the PR looks mostly fine. You will just have to add rolling upgrade checks to throw an exception if the cluster version is less than 3.10.

Many thanks!

**Comment by mmedenjak** [comment]
@c2v4 can you work on getting this PR in shape? 3.10 is close to being complete. If you can't work on it, we will move it to 3.11

**Comment by mmedenjak** [comment]
Moving to 3.11, I believe someone will need to take over your commit if you are no longer able to work on it.

**Comment by Holmistr** [comment]
@mmedenjak Any plans for this PR?

**Comment by Holmistr** [comment]
I'm going to close this PR, since there's no activity on it.
@c2v4  I'm sorry it got abandoned. Please, feel free to comment if you're willing to pick it up again. We appreciate your effort to contribute! :)

**Pull request closed without merging**
