### PR TITLE
Remove client side code related to MC operations

### PR DESCRIPTION
**Pull request by emre-aydin**
In a previous PR on MC repository (https://github.com/hazelcast/management-center/pull/2849), we have added client side
methods that execute MC related client operations. This PR deletes code
that was already added to MC code from IMDG code.

* ManagementCenterService is moved from IMDG to MC code (renamed to
MCClient)
* DTOs used on client side while executing MC operations are moved to MC
 code
* MC related tests except ScriptingProtectionTest are moved to MC code
(This test is mostly concerned about whether member rejects script
execution client operation on server side, so it makes sense to keep it
in IMDG.)

EE PR: https://github.com/hazelcast/hazelcast-enterprise/pull/3548

### CODE REVIEW

**Comment by sancar** [comment]
Are you gonna move the MC message tasks as well ?

**Comment by emre-aydin** [comment]
> Are you gonna move the MC message tasks as well ?

@sancar no, `MessageTask`s will stay in IMDG code. The idea is to have client side code (minus the protocol definitions) in MC and server code (both IMDG and Jet) in their respective codebases. This way, we will be able to evolve and release MC in its own pace while keeping it independent from IMDG/Jet server code. See the relevant [TDD](https://hazelcast.atlassian.net/wiki/spaces/EN/pages/2042789889/TDD+MC+Jet+Unification+Technical+Design) for more details. A TDD review would also be appreciated :)

**Comment by emre-aydin** [comment]
@asimarslan addressed your comments, can you have another look?

**Comment by emre-aydin** [comment]
run-lab-run

**Comment by emre-aydin** [comment]
Test fails on other PR builder runs in unrelated PRs. Concluding it's not related to this change.

**Pull request merged**
