### PR TITLE
[FORWARD PORT] Added stopping WAN replication from MC

### PR DESCRIPTION
**Pull request by emre-aydin**
Forward port of https://github.com/hazelcast/hazelcast/pull/13275

### CODE REVIEW

**Comment by emre-aydin** [comment]
verify

**Comment by emre-aydin** [comment]
verify

**Comment by mmedenjak** [comment]
Test `com.hazelcast.osgi.HazelcastOSGiIntegrationTest.serviceRetrievedSuccessfully:com.hazelcast.osgi.HazelcastOSGiIntegrationTest.serviceRetrievedSuccessfully:PaxRunnerTestContainer{felix}` failed becuase it tried to download dependencies from maven with JDK6. This is not supported anymore as of recently:

```
javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:190)
	at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:136)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1822)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1004)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1188)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1215)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1199)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:434)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1195)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:379)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:318)
	at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:115)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:64)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
```

AFAIK this is being worked on by @Holmistr

**Comment by emre-aydin** [comment]
@Holmistr no specific reason, didn't know we had two separate PR builders. I thought that both commands run the same PR builder.

**Comment by mmedenjak** [comment]
`verify` starts the PR builder on a cloudbees machine
`run-lab-run` is what is automatically triggered, and runs on our own build machine in the testlab in Docker containers
`verify` can be used as fallback, if there is sth wrong with our build machine, but otherwise `run-lab-run` is preferred

**Pull request merged**
