### PR TITLE
Remove unused constructors in lite-member related exceptions

### PR DESCRIPTION
**Pull request by metanet**
This is a very trivial change but I am sending it as a PR to make sure that it doesn't break anything.

### CODE REVIEW

**Comment by Donnerbart** [comment]
:+1:

It's a trivial change to improve code coverage by removed dead code. I think it can be merged right away once green.

**Comment by metanet** [comment]
verify

**Comment by metanet** [comment]
verify

**Comment by hasancelik** [comment]
run-lab

**Comment by mdogan** [comment]
:+1:

**Pull request merged**
