### PR TITLE
Fixed MapAttributeConfig cannot be loaded in an OSGi environment by @chuspb

### PR DESCRIPTION
**Pull request by tombujok**
Fix for https://github.com/hazelcast/hazelcast/issues/8482

### CODE REVIEW

**Comment by pveentjer** [comment]
:+1: but I'm not an OSGI expert (or care to be one)

**Comment by tombujok** [comment]
@chuspb BTW, Could we get your contributor agreement signed? https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement?preview=/6357071/6619138/Hazelcast%2C%20Inc.%20Individual%20Contrbutor%20License%20Agreement%20v100113.pdf

**Comment by tombujok** [comment]
@chuspb unfortunately, officially if I don't get the Contributor Agreement signed I'll have to revert and rework your change. It would be great if you could send the CA signed, since you'll keep the ownership of your commit. Could you do it ASAP?

**Comment by chuspb** [comment]
Sorry, I have been outside work since afternoon. I will send you the agreement before midnight.

**Comment by chuspb** [comment]
[Hazelcast, Inc. Individual Contrbutor License Agreement v100113.pdf](https://github.com/hazelcast/hazelcast/files/346730/Hazelcast.Inc.Individual.Contrbutor.License.Agreement.v100113.pdf)

**Comment by tombujok** [comment]
@chuspb Thx! I downloaded it and removed it from the ticket. Thx for your contribution. Plz, let me know if you're willing to work on other issues ;)

**Pull request merged**
