### PR TITLE
Fixing setAttribute so that any attribute that was removed from session ...

### PR DESCRIPTION
**Pull request by davidsiefert**
...can be re-set.  Paired by David Siefert and Matt Bague.  Closes issue #5186

### CODE REVIEW

**Comment by davidsiefert** [comment]
Okay, now what happens?  Kinda new to this....

**Comment by mesutcelik** [comment]
Thanks for the fix.
Can you please sign our contributor agreement?
https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by davidsiefert** [comment]
Just submitted--hooray!

**Comment by mesutcelik** [comment]
Thanks for the contribution!

**Pull request merged**
