### PR TITLE
Enhance exception handling in compatibility tests

### PR DESCRIPTION
**Pull request by taburet**
Before this change custom Hazelcast exceptions thrown by older versions
were not catchable by regular catch statements in the tests because
their classes were loaded by class loaders different from the class
loader hosting the tests.

Fixes: https://github.com/hazelcast/hazelcast-enterprise/issues/1589

### CODE REVIEW

**Comment by taburet** [comment]
TBH, I'm still not sure about this change, in some sense it implies some level of binary compatibility of exceptions among Hazelcast versions.

**Comment by taburet** [comment]
run-lab-run

**Comment by taburet** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
The only downside to this PR is that the `serialVersionUid` of any `Exception` class may change across versions (eg after addition of a new public method etc). In this case, assuming the change is compatible with previous versions of the same exception class, we can explicitly set the `serialVersionUid` of the `Exception` class to be compatible with the previous version or, as last resort, change the test to match exception class by name like we already do in some cases (via `Utils#assertInstanceOfByClassName`). I also tested this PR with `LockCompatibilityTest` (having removed the overriden `testDestroyLockWhenOtherWaitingOnLock` method that matches by class name) and works as expected. I am in favor of merging this PR.

**Comment by Holmistr** [comment]
Merged as reviews were done :)

**Pull request merged**
