### PR TITLE
Minor cleanup of rolling upgrade checks

### PR DESCRIPTION
**Pull request by mmedenjak**
- add assertions for cluster version in methods with conditional
serialization/deserialization
- add missing RU_COMPAT comments
- add missing Versioned interface

### CODE REVIEW

**Comment by Donnerbart** [comment]
Those asserts are bad in terms of code coverage. They cause a branch on the class level. So if they are not tested, you'll have an (1/2) branches tested on the class level in Sonar. It's also easy to forget them, like the `Versioned` interface itself.

We have the reflections library already onboard. Let me try out a generic test to find those buggers automatically. Shouldn't be impossible.

**Comment by mmedenjak** [comment]
We must definitely have some way by which a replication or migration operation throws an exception rather than erroneously writing the serialized format.
If there is no other option than assertions, I would keep them, even though they lower the code coverage.

**Comment by Donnerbart** [comment]
I'm just giving reflections a short try (have another idea for an automated test as well). I'll be right back :D

**Comment by Donnerbart** [comment]
Looks scary, but promising. I also just found the missing interface in `QueueConfig` ;)

**Comment by vbekiaris** [comment]
I think you cannot statically detect these kinds of errors reliably, one would have to detect them at runtime (ie. a non-`Versioned` class executes `ObjectDataInput/Output.getVersion` during serialization operations). I've been thinking something like [`SamplingSerializationService`](https://github.com/hazelcast/hazelcast/blob/0a02de0cff51da3b501bf21b86150535699aaf9f/hazelcast/src/test/java/com/hazelcast/test/compatibility/SamplingSerializationService.java#L49) -- wrap `VersionAware` object in/out streams to detect invocations to their `getVersion` method.

**Comment by mmedenjak** [comment]
@vbekiaris that would be wonderful. I also believe it's hard to detect this, sometimes a class is `Versioned` but it does not do any version checks at all but rather directly invokes `DataSerializable#writeData/readData` of some containing object which then makes version checks. So a custom serialization service could detect that it is calling `getVersion` but the version is `UNKNOWN`. OTOH some classes might also expect `UNKNOWN`, i.e. `PostJoinMapOperation#readInternal`.
But I agree a more permanent approach would be better which would detect issues on new classes.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
Mockito with `spy` and `verify` works. I cannot guarantee 100%, since sometimes a `readData()` or `writeData()` throws an error before `getVersion()` might be called, but it should be better than nothing and it's automated. It's also a super quick test, suitable for the PR builder.

**Comment by mmedenjak** [comment]
Closing in favour of https://github.com/hazelcast/hazelcast/pull/12476

**Pull request closed without merging**
