### PR TITLE
MorphingPortableReader should check for existence of ClassDefinition for UTF_ARRAY types

### PR DESCRIPTION
**Pull request by aborshik**
I have emailed signed CLA as per the contribution guidelines.

### CODE REVIEW

**Comment by pveentjer** [comment]
@asimarslan can you have a look at this one.

**Comment by tombujok** [comment]
@pveentjer @asimarslan This is rather for me.

**Comment by tombujok** [comment]
@aborshik the PR looks good. I would like to ask you however to provide a test that would reproduce #7926. It would be great to have some more tests around it.

**Comment by noctarius** [comment]
@aborshik Did you see @tombujok's request? Can you please add a test so that this PR can be merged? :)

**Comment by tombujok** [comment]
Would be great @aborshik I mean i can always add a test case, but it would be great to have a real-life scenario.

**Comment by tombujok** [comment]
run-lab-run

**Comment by tombujok** [comment]
verify

**Comment by hasancelik** [comment]
verify

**Comment by hasancelik** [comment]
verify

**Comment by hasancelik** [comment]
verify

**Comment by asimarslan** [comment]
👍

**Comment by hasancelik** [comment]
verify

**Comment by tombujok** [comment]
verify

**Comment by tombujok** [comment]
👍

**Comment by aborshik** [comment]
Sorry guys, just seen the comments. Appreciate the merge, I'll try and get some higher level tests done and raise another PR for you

**Comment by tombujok** [comment]
@aborshik cool, thx. Additional tests appreciated.

**Pull request merged**
