### PR TITLE
Fixes memory leaks on the map

### LINKED ISSUE #6803: MapMemoryUsageStressTest.voidCacher
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/776/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.map/MapMemoryUsageStressTest/voidCacher/

**Older aborted build with different cause:**
```
java.lang.AssertionError: Timeout waiting for thread Thread-22 to terminate
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:722)
	at com.hazelcast.client.map.MapMemoryUsageStressTest.voidCacher(MapMemoryUsageStressTest.java:56)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/763/testReport/junit/com.hazelcast.client.map/MapMemoryUsageStressTest/voidCacher/

### PR DESCRIPTION
**Pull request by eminn**
Fixes made on this PR :
- Local map statistics were leaking
- Map containers were leaking by near cache invalidation mechanism by re-creating  to check whether near cache enabled or not
- Map containers were leaking by `MapPartitionDestroyOperation `  by re-creating and trying to get backup count 
- Near cache invalidation queues were leaking 

Below the results from MapMemoryUsageStressTest 

Heap usage on current master
screen shot 2015-12-02 at 6 31 54 pm

Heap usage with the fixes in this PR
screen shot 2015-12-02 at 6 32 17 pm

Fixes #6803 ,  #6972

Backport : #6971

### CODE REVIEW

**Comment by eminn** [comment]
verify

**Comment by ahmetmircik** [comment]
:+1:

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
run-lab-run

**Comment by metanet** [comment]
good work 

:+1:

**Pull request merged**
