### PR TITLE
Increased code coverage of LegacyCacheConfig and LegacyCacheEvictionConfig

### PR DESCRIPTION
**Pull request by Donnerbart**

### CODE REVIEW

**Comment by Donnerbart** [comment]
Did I do something wrong in the test?

```
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, id: 0, class: 'com.hazelcast.config.CacheEvictionConfig', exception: java.lang.Class cannot be cast to com.hazelcast.internal.eviction.EvictionPolicyComparator
	at com.hazelcast.config.EvictionConfig.readData(EvictionConfig.java:260)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:151)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:104)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:54)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:251)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
	at com.hazelcast.config.CacheConfig.readData(CacheConfig.java:561)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:151)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:104)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:54)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
	at com.hazelcast.config.LegacyCacheConfigTest.testSerialization(LegacyCacheConfigTest.java:58)
```

**Comment by vbekiaris** [comment]
`LegacyCacheConfig` is serialized as a `CacheConfig` would, see [LegacyCacheConfig#getClassType](https://github.com/hazelcast/hazelcast/blob/75ef0bd6959363a4d204ed3e71e67f81ad1fbcd9/hazelcast/src/main/java/com/hazelcast/config/LegacyCacheConfig.java#L143-L145). This is necessary to achieve backward compatibility with 3.6.x clients.

In your test you should let `SerializationService` know which type you expect the deserialized object to be:

`LegacyCacheConfig deserializedConfig = serializationService.toObject(serializedConfig, LegacyCacheConfig.class);`

A sidenote, `LegacyCacheConfig` does not implement `equals` so the assertion will still fail.

**Comment by Donnerbart** [comment]
Yes, I remember the discussion, I just didn't remember the details. So thanks for the hint how to fix this! And yes, the assertion will probably be the next thing to fix. One step after another :)

**Comment by pveentjer** [comment]
:+1:

**Pull request merged**
