### PR TITLE
Update configuration to use version previously in confluence

### PR DESCRIPTION
**Pull request by JackPGreen**
Update IntelliJ IDE configuration to use the formatter [referenced in Confluence](https://hazelcast.atlassian.net/wiki/spaces/EN/pages/5374373/Codestyle+Code-Formatter).

Once merged, the above page can be removed from confluence.

### CODE REVIEW

**Review by kwart — APPROVED** [review]
LGTM, but I don't use IntelliJ, so I can't check the behavior.

**Comment by JackPGreen** [comment]
run-lab-run

**Review by JamesHazelcast — CHANGES_REQUESTED** [review]
Thanks for sorting this Jack - after importing the Intellij project.xml file I noticed it is missing some properties; I went ahead and exported a new xml based on the `Hazelcast.xml` code style in Confluence, you can find it here: https://gist.github.com/JamesHazelcast/ed7caf2609e8d08ed5df7f88555aed15

GH doesn't let me make a suggestion to replace the entire file, so you'll have to handle that - I did make a quick update to the README as well, hope you don't mind.

**Comment by JackPGreen** [comment]
> Thanks for sorting this Jack - after importing the Intellij project.xml file I noticed it is missing some properties; I went ahead and exported a new xml based on the `Hazelcast.xml` code style in Confluence, you can find it here: https://gist.github.com/JamesHazelcast/ed7caf2609e8d08ed5df7f88555aed15
> 
> GH doesn't let me make a suggestion to replace the entire file, so you'll have to handle that

Thanks, the scope of this PR was just to sync the repo with the file in Confluence, but your changes don't look contentious (mostly IntelliJ just repeating the setts for some reason) so I've added it - 4f1b38263850c238217379a596ba34d2d86c3ead

>  I did make a quick update to the README as well, hope you don't mind.

Thanks, I copied the path directly from IntelliJ but [there's a bug that means it's incorrect](https://youtrack.jetbrains.com/issue/IDEA-331437/OSX-Copy-Settings-Path-incorrectly-references-Preferences-not-Settings).

**Review by JamesHazelcast — APPROVED** [review]

**Pull request merged**
