### PR TITLE
Collection querying in Portables (squashed) - backport

### PR DESCRIPTION
**Pull request by tombujok**
The merge was seamless. Just a cherry-pick with minor conflicts related to the renaming of the `SerializationService` to `InternalSerializationService` on master.

### CODE REVIEW

**Comment by tombujok** [comment]
run-lab-run

**Comment by tombujok** [comment]
verify

**Comment by tombujok** [comment]
run-lab-run

**Comment by tombujok** [comment]
verify

**Comment by tombujok** [comment]
verify

**Comment by vbekiaris** [comment]
👍

**Pull request merged**
