### PR TITLE
Change the test to send second batch of messages synchronously [HZ-2779]

### PR DESCRIPTION
**Pull request by orcunc**
The test is probably failing because the second batch of messages are not sent synchronously. 

Fixes : https://github.com/hazelcast/hazelcast/issues/24852

I have also test by putting a sleep as suggested in the Github issue. It seems to work, the test is passing
````
Pipeline p = Pipeline.create();
p.readFrom(KafkaSources.<Integer, String, String>kafka(kafkaProperties, ConsumerRecord::value, topicsConfig))
  .withoutTimestamps()
  .map(f -> {
    System.out.println("Sleep for " + f);
    Thread.sleep(500);
    return f;
})
.writeTo(Sinks.list(sinkListName));
````
Breaking changes (list specific methods/types/messages):
* API
* client protocol format
* serialized form
* snapshot format

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

**Comment by TomaszGaweda** [comment]
+1 for the fix, but I think the comments are not necessary; there are no such comments in other tests plus they provide very little information above what code says. The explanation in the PR description makes sense though.

CC @anestoruk I guess that produce vs produceSync was a typo, can you confirm?

**Review by TomaszGaweda — CHANGES_REQUESTED** [review]
As above, please remove unnecessary comments

**Comment by orcunc** [comment]
> As above, please remove unnecessary comments

rev : fadbbd9abd4e8fe67bbae9ed3090cb1e733d41a6

**Review by TomaszGaweda — APPROVED** [review]

**Comment by orcunc** [comment]
run-lab-run

**Comment by orcunc** [comment]
run-lab-run

**Review by ldziedziul — APPROVED** [review]

**Comment by anestoruk** [comment]
> CC @anestoruk I guess that produce vs produceSync was a typo, can you confirm?

@TomaszGaweda to be exactly precise, in my initial version I used `produce()` twice (https://github.com/hazelcast/hazelcast/commit/a90f3c2d354b9bd977b0e4a92b43cc01445122b0), the `produceSync()` method was introduced a bit later by @ldziedziul (https://github.com/hazelcast/hazelcast/commit/5ca781cd8c481f965f4ed69ff6637fe0e599334e). 
Nevertheless - this change looks good to me :+1:

**Comment by orcunc** [comment]
run-lab-run

**Comment by orcunc** [comment]
run-lab-run

**Comment by orcunc** [comment]
run-lab-run

**Pull request merged**
