### PR TITLE
DefaultRecordStore.getStateMessage() rewrite for OpenJ9

### LINKED ISSUE #24718: com.hazelcast.client.impl.spi.impl.ClientInvocationTest
_master_ (commit 5f414fa3ad03417e0b9078c8d9f249904003c936)

Failed on openj9-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-17/69/testReport/com.hazelcast.client.impl.spi.impl/ClientInvocationTest/invokeOnMemberRedirectsToRandom_whenMemberIsNotInMemberList/
<details><summary>Stacktrace:</summary>

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.invokeExact(java.lang.invoke.MethodHandle, java.lang.Object[])"
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:121)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:618)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationTest.invokeOnMemberRedirectsToRandom_whenMemberIsNotInMemberList(ClientInvocationTest.java:213)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:858)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.invokeExact(java.lang.invoke.MethodHandle, java.lang.Object[])"
	at java.lang.StringConcatHelper.stringOf(StringConcatHelper.java)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.getStateMessage(DefaultRecordStore.java:1411)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.startLoading(DefaultRecordStore.java:1333)
	at com.hazelcast.map.impl.PartitionContainer.lambda$new$0(PartitionContainer.java:59)
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:140)
	at com.hazelcast.map.impl.PartitionContainer.getRecordStore(PartitionContainer.java:150)
	at com.hazelcast.map.impl.operation.MapOperation.getRecordStoreOrNull(MapOperation.java:312)
	at com.hazelcast.map.impl.operation.MapOperation.beforeRun(MapOperation.java:108)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:269)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:219)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:180)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:144)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.loop(OperationThread.java:134)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:115)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:348)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	... 16 more

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: invokeOnPartitionOwnerRedirectsToRandom_WhenPartitionOwnerIsnull in 0.556 seconds.

No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-17/69/

The similar issue was for`invokeOnPartitionOwnerRedirectsToRandom_WhenPartitionOwnerIsnull` test

### PR DESCRIPTION
**Pull request by TomaszGaweda**
Due to some weird issue on OpenJ9, which method failed - looked like an issue with OpenJ9's String.concat implementation. 

To overcome this I've changed the code to use StringBuilder. Even if the issue with partially stay, we will have more precise place where it fails.

Fixes #24718

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

### CODE REVIEW

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
can we please have only relevant changes that fixes the issue?

**Comment by TomaszGaweda** [comment]
other changes are simple generics info (only possible type there) and simplification of always-true statement, tiny boyscout cleanup of warnings. I can revert it if you insist, but I'd keep it personally, as the changes does not change any behaviour (only get rid of warnings)

**Pull request merged**
