### PR TITLE
IOBalancer minor cleanup

### PR DESCRIPTION
**Pull request by pveentjer**

### CODE REVIEW

**Comment by jerrinot** [comment]
:+1:

**Comment by Donnerbart** [comment]
Looks like 100% JavaDoc changes and renaming by IDEA, so risk is very low.

:+1:

**Comment by jerrinot** [comment]
still :+1:

**Comment by jerrinot** [comment]
I took a liberty to merge this one - it's just a minor cleanup - mostly renames, etc.

**Pull request merged**
