### PR TITLE
Do not overwrite SYNC_WAITING_REPLICA flag on migration commit

### LINKED ISSUE #8505: MapPartitionLostListener not working
Hi,

it looks as if the MapPartitionLostListener is not working. We simply can not get it to fire - at all... We tested on 3.6.5-dev (a version from 2016-06-29).

here is a test.

Thanks for checking and best,
Lukas

```java
package com.nm.test.hazelcast.map;

import com.hazelcast.config.Config;
import com.hazelcast.config.MapPartitionLostListenerConfig;
import com.hazelcast.config.XmlConfigBuilder;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;
import com.hazelcast.core.PartitionService;
import com.hazelcast.map.MapPartitionLostEvent;
import com.hazelcast.map.listener.MapPartitionLostListener;
import com.nm.test.hazelcast.TestHazelcast;
import com.nm.test.hazelcast.utils.Sleep;
import org.apache.log4j.BasicConfigurator;
import org.apache.log4j.Logger;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import junit.framework.TestCase;

/**
 * Test to ensure MapPartitionLostListener works as expected.
 */
@RunWith(JUnit4.class)
public class TestMap11 extends TestCase {

	private static final Logger logger = Logger.getLogger(TestMap11.class);

	private static final String mapName = "testMap" + TestMap11.class.getSimpleName();

	private static final int MAP_SIZE = 100000;

	private HazelcastInstance hcInstance1;
	private HazelcastInstance hcInstance2;

	private final AtomicInteger mapSize = new AtomicInteger();
	private final AtomicBoolean isLossDetected = new AtomicBoolean();

	@Before
	public void setUp() throws Exception {

		// configure logging
		if (!TestHazelcast.loggingInitialized) {
			TestHazelcast.loggingInitialized = true;
			BasicConfigurator.configure();
		}

		mapSize.set(0);
		isLossDetected.set(false);
	}

	@After
	public void tearDown() {
		try {
			hcInstance1 = null;
			hcInstance2 = null;
			Thread.sleep(5000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}

	@Test
	public void testMapPartitionLostEventStatic() throws Exception {
		testInternal(false);
	}

	@Test
	public void testMapPartitionLostEventDynamic() throws Exception {
		testInternal(true);
	}

	private void testInternal(final boolean registerDynamically) throws Exception {

		// thread 1: start a first node
		Thread thread1 = new Thread(new Runnable() {

			@Override
			public void run() {
				final String threadName = Thread.currentThread().getName();

				// create listener
				CountingMapPartitionLostListener listener = new CountingMapPartitionLostListener(threadName, isLossDetected);

				// create config
				Config config = createInitialConfig();
				if (!registerDynamically) {
					MapPartitionLostListenerConfig listenerConfig = new MapPartitionLostListenerConfig();
					listenerConfig.setImplementation(listener);
					config.getMapConfig(mapName).addMapPartitionLostListenerConfig(listenerConfig);
					logger.info(threadName + " map partition lost listener configured before starting.");
				}

				// start cluster
				hcInstance1 = Hazelcast.newHazelcastInstance(config);

				// try-finally to stop hazelcast instance
				try {

					// log started
					logger.info(threadName + " started.");

					// create map
					final IMap<String, String> map = hcInstance1.getMap(mapName);
					logger.info(threadName + " map created.");

					// add listener dynamically
					if (registerDynamically) {
						map.addPartitionLostListener(listener);
						logger.info(threadName + " map partition lost listener registered dynamically.");
					}

					// populate map
					for (int i = 0; i < MAP_SIZE; i++) {
						map.put(String.valueOf(i), "value" + i);
					}
					logger.info(threadName + " map populated.");

					// print size
					int size = map.size();
					mapSize.set(size);
					logger.info(threadName + " Map size 1 = " + size);

					// wait 30s (during this time a second node joins and dies)
					Sleep.sleep(30000, true);

					// print size
					size = map.size();
					mapSize.set(size);
					logger.info(threadName + " Map size 2 = " + size);

				} finally {
					hcInstance1.getLifecycleService().shutdown();
				}
				logger.info(threadName + " done.");
			}
		}, "Thread 1");
		thread1.start();

		// wait 20s after starting first thread
		Sleep.sleep(20000, true);

		// thread 2: start a second node
		// - this joins the cluster and kills itself while parition migrations are happening
		Thread thread2 = new Thread(new Runnable() {

			@Override
			public void run() {
				final String threadName = Thread.currentThread().getName();

				// create listener
				CountingMapPartitionLostListener listener = new CountingMapPartitionLostListener(threadName, isLossDetected);

				// create config
				Config config = createInitialConfig();
				if (!registerDynamically) {
					MapPartitionLostListenerConfig listenerConfig = new MapPartitionLostListenerConfig();
					listenerConfig.setImplementation(listener);
					config.getMapConfig(mapName).addMapPartitionLostListenerConfig(listenerConfig);
					logger.info(threadName + " map partition lost listener configured before starting.");
				}

				// join
				hcInstance2 = Hazelcast.newHazelcastInstance(config);
				logger.info(threadName + " hazelcast instance joined.");

				// try-finally to kill hazelcast instance
				try {

					// get map
					IMap<String, String> map = hcInstance2.getMap(mapName);

					// add listener dynamically
					if (registerDynamically) {
						map.addPartitionLostListener(listener);
						logger.info(threadName + " map partition lost listener registered dynamically.");
					}

					// print size
					int size = map.size();
					mapSize.set(size);
					logger.info(threadName + " Map size = " + size);

					// wait before kill
					PartitionService ps = hcInstance2.getPartitionService();
					Sleep.sleep(3000, true);
					logger.info(threadName + " Is local member safe? " + ps.isLocalMemberSafe());

				} finally {

					// use terminate here to stop before partition migrations are done
					hcInstance2.getLifecycleService().terminate();
				}
				logger.info(threadName + " done.");
			}
		}, "Thread 2");
		thread2.start();

		// join threads
		thread1.join();
		thread2.join();

		// ensure valid execution
		// - 1st condition: the test execution is only valid if the final map size is *not* equal to the initial map size
		// - 2nd condition: we detected the data loss
		final int mapSizeFinal = mapSize.get();
		final boolean isLossDetectedFinal = isLossDetected.get();
		logger.info("Final map size = " + mapSizeFinal);
		logger.info("Was data loss detected? " + isLossDetectedFinal);
		assertTrue("Invalid test execution: No data loss produced.", mapSizeFinal != MAP_SIZE);
		assertTrue("Data loss produced, but not detected.", isLossDetectedFinal);
	}

	private static class CountingMapPartitionLostListener implements MapPartitionLostListener {

		private final String threadName;

		private final AtomicBoolean isLossDetected;

		private final AtomicInteger numPartitionsLost;

		public CountingMapPartitionLostListener(String threadName, AtomicBoolean isLossDetected) {
			this.threadName = threadName;
			this.isLossDetected = isLossDetected;
			this.numPartitionsLost = new AtomicInteger(0);
		}

		@Override
		public void partitionLost(MapPartitionLostEvent event) {
			numPartitionsLost.incrementAndGet();

			// log and remember
			logger.info(threadName + " has lost a partition. Current call count = " + numPartitionsLost);
			isLossDetected.set(true);
		}

	}

	private Config createInitialConfig() {
		Config config = new XmlConfigBuilder().build();
		config.setProperty("hazelcast.logging.type", "log4j");
		config.setProperty("hazelcast.jmx", "false");
		config.setProperty("hazelcast.version.check.enabled", "false");
		config.setProperty("hazelcast.phone.home.enabled", "false");
		return config;
	}

}


package com.nm.test.hazelcast.utils;

import org.apache.log4j.Logger;

public class Sleep {

	private static final Logger logger = Logger.getLogger(Sleep.class);

	/**
	 * Tries to sleep for the desired number of milliseconds, throwing a RuntimeException in case
	 * the thread is interrupted.
	 * 
	 * @param ms Number of milliseconds to sleep
	 * @param log true to log, false otherwise.
	 */
	public static void sleep(long ms, boolean log) {
		if (ms <= 0) {
			return;
		}
		try {
			if (log) {
				logger.info("Starting to sleep for " + (ms / 1000) + "s...");
			}
			Thread.sleep(ms);
			if (log) {
				logger.info("Slept " + (ms / 1000) + "s.");
			}
		} catch (InterruptedException e) {
			throw new RuntimeException(e);
		}
	}

}
```

### PR DESCRIPTION
**Pull request by metanet**
If a source node commits a migration, it clears its replica indices. However, it should keep SYNC_WAITING_REPLICA flags if it moves to a backup index in the committed partition.

This behavior doesn't exist in the master branch.

Fixes #8505

### CODE REVIEW

**Comment by metanet** [comment]
unrelated test failure

**Comment by metanet** [comment]
run-lab-run

**Comment by mdogan** [comment]
👍

**Comment by gurbuzali** [comment]
👍

**Pull request merged**
