### PR TITLE
Fire CLEAR_ALL event from Map and MultiMap

### PR DESCRIPTION
**Pull request by Andu033**
Fixes: https://github.com/hazelcast/hazelcast/issues/16687

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by Holmistr** [comment]
Hi @Andu033 , thank you very much for the PR! :tada: There are checkstyle errors, see below. Could you please fix them?
```
08:28:50 [INFO] --- maven-checkstyle-plugin:3.1.1:checkstyle (default) @ hazelcast ---
08:29:26 [INFO] Starting audit...
08:29:26 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapProxyImpl.java:26:8: Unused import - com.hazelcast.map.impl.MapService. [UnusedImports]
08:29:26 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapProxyImpl.java:27:8: Unused import - com.hazelcast.map.impl.event.MapEventPublisher. [UnusedImports]
```

You can check locally to make sure you're clean from checkstyle errors with
`mvn clean install -DskipTests -Pcheckstyle`.

**Comment by Holmistr** [comment]
run-lab-run

**Comment by Holmistr** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
What about using `DistributedObjectListener` instead of firing `CLEAR_ALL`? By using it object destructions can be watched. 
 Firing `CLEAR_ALL` gives false assumption of after receiving clear-all event relevant map is still useful but actually it was destroyed. Replicated map implementation does this wrongly not others.

**Comment by mmedenjak** [comment]
Good point @ahmetmircik ! Destroy is definitely part of the "lifecycle" of a distributed object and `CLEAR_ALL` can be misleading, I agree.

**Comment by Holmistr** [comment]
Hi @Andu033 , did you have time to look at the review comments? Is there anything we could help you out with? :)

**Comment by mmedenjak** [comment]
Hi @Andu033 ! Have you been able to take a look if we can try out another approach in line with the comments?

**Comment by mmedenjak** [comment]
Hi @Andu033 ! Have you been able to take a look at the suggestions?

**Comment by pveentjer** [comment]
Closing PR since it seems to be abandoned.

**Pull request closed without merging**
