### PR TITLE
Ensure ClientConfigs in ClientFailoverConfig has non-OFF ReconnectMode

### PR DESCRIPTION
**Pull request by pertsodian**
Fix https://github.com/hazelcast/hazelcast/issues/16834

### CODE REVIEW

**Comment by sancar** [comment]
run-lab-run

**Comment by Holmistr** [comment]
@pertsodian Checkstyle errors :)
```
15:26:49 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/test/java/com/hazelcast/client/config/ClientFailoverConfigTest.java:1: File does not end with a newline. [NewlineAtEndOfFile]
15:26:49 --------------------------
15:26:49 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/test/java/com/hazelcast/client/config/ClientFailoverConfigTest.java:1: Line does not match expected header line of '\''/*'\''. [Header]
15:26:49 --------------------------
15:26:49 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/test/java/com/hazelcast/client/config/ClientFailoverConfigTest.java:16: Using the '\''.*'\'' form of import should be avoided - org.hamcrest.Matchers.*. [AvoidStarImport]
15:26:49 --------------------------'
```

**Comment by sancar** [comment]
```
_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/test/java/com/hazelcast/client/config/ClientFailoverConfigTest.java:1: Line does not match expected header line of '\''/*'\''. [Header]
```
This means, we need a license on top of the test class. Can you copy from the other files ? 
The other warnings should be self-descriptive enough. 
Thanks for the contribution.

**Comment by pertsodian** [comment]
Updated. Sorry my bad, need to make this a habit.

**Comment by mmedenjak** [comment]
Thank you for your contribution @pertsodian ! cc @Holmistr

**Pull request merged**
