### PR TITLE
Renamed PerformanceMonitor to Diagnostics

### PR DESCRIPTION
**Pull request by pveentjer**
PerformanceMonitor was renamed to Diagnostics since the plugins can be used for other purposes than just dealing with performance issues. The ClusterLogPlugin for example will show a lot of member/connection/partition related information.

### CODE REVIEW

**Comment by pveentjer** [comment]
@jerrinot can you have a look at this PR so I can get my clusterlog pr rebased?

**Comment by pveentjer** [comment]
run-lab-run

**Comment by tombujok** [comment]
👍

**Comment by pveentjer** [comment]
I already discussed the naming with Jaromir (he suggested Diagnostics in the first place). So I'm going to merge this one.

**Pull request merged**
