### PR TITLE
map entry merge events should be sent to clients

### LINKED ISSUE #6802: Map entry event listeners are not invoked on clients of WAN replication target cluster
[#5058](https://github.com/hazelcast/hazelcast/pull/5058) fixes similar issue but on target cluster itself. Clients of such cluster receive ```REMOVED``` events only. It's fairly easy to reproduce by adding client to ```clusterB``` in ```WanReplicationTest.willFireNewOnMergeEventAtReceivingCluster```.

### PR DESCRIPTION
**Pull request by emrahkocaman**
Fixes #6802 ,

Forward-port is not needed as it's already fixed in 3.6. (I'll only add new tests to master later)

### CODE REVIEW

**Comment by emrahkocaman** [comment]
@sancar Can you have a look at this?

**Comment by sancar** [comment]
:+1:

**Comment by mesutcelik** [comment]
:+1:

**Comment by mesutcelik** [comment]
waiting for the test on master... Thanks!

**Comment by emrahkocaman** [comment]
PR for tests on master -> https://github.com/hazelcast/hazelcast/pull/6959

**Pull request merged**
