### PR TITLE
Consider clients properly during default SPI dicovery

### PR DESCRIPTION
**Pull request by uladzimirFilipchanka**
Fix for issue #10089

### CODE REVIEW

**Comment by uladzimirFilipchanka** [comment]
Unfortunately, I haven't implemented any simple understandable test for the issue.

**Comment by jerrinot** [comment]
Hello @uladzimirFilipchanka,

thanks for this contribution. I'd like to merge your PR, but before I can do so I'd need you to sign our [contributor agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement). 

many thanks!

**Comment by mesutcelik** [comment]
run-lab-run

**Comment by uladzimirFilipchanka** [comment]
@jerrinot, signed and sent to jaromir AT hazelcast.com

**Comment by jerrinot** [comment]
@uladzimirFilipchanka: thanks for the PR and signing the contributor agreement. 
@mesutcelik: are you ok with merging this one?

**Pull request merged**
