### PR TITLE
Fix the tests JdbcSqlConnectorStabilityTest [HZ-1686]

### PR DESCRIPTION
**Pull request by orcunc**
There is a hierarchy of tests for H2, MySQL and PostgreSQL. 
MySQL and PostgreSQL tests are not using JDBC URL testcontainers because there is no way to shutdown these DBs.
As soon as a new JDBC connection is created the container is fired up automatically. 

Also I have performed the same procedure manually by creating a dockerized MySQL and shutting it down, then executing HZ SQLs that don't need a DB, such as SHOW MAPPING, SELECT * FROM TABLE(generate_series(0, 5)) etc.

These HZ SQLs work but the response is coming late. Because these SQLs still try to access the DB and Hikari's connection timeout is 30 seconds. So response is received 30 seconds later.

If the DB is up, the response is received immediately 

Fixes : https://hazelcast.atlassian.net/browse/HZ-1686
GH : https://github.com/hazelcast/hazelcast/issues/22651

Breaking changes (list specific methods/types/messages):
* API
* client protocol format
* serialized form
* snapshot format

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

**Comment by orcunc** [comment]
run-lab-run

**Comment by orcunc** [comment]
run-lab-run

**Comment by sumnerib** [comment]
> These HZ SQLs work but the response is coming late. Because these SQLs still try to access the DB and Hikari is connection timeout is 30 seconds. So response is received 30 seconds later.

Looks like this situation was improved as a side-effect of some other change. Previously the queries would completely fail with `Could not determine dialect for externalDataStoreRef: <ref-name>`. Will there be another PR to address this slow response? This still seems like an issue to me.

**Review by sumnerib — APPROVED** [review]

**Review by frant-hartm — APPROVED** [review]

**Comment by frant-hartm** [comment]
I have pushed some changes based on @TomaszGaweda comment.

>Maybe instead make MySQLDatabaseProvider etc. manually open and close containers, not using tc jdbc urls

I think it results in a simpler setup in the subclasses. @orcunc @TomaszGaweda please re-review

**Comment by orcunc** [comment]
@frant-hartm Good job. The only issue was Postgre and MySQL tests were not creating the mapping. For these tests the table name was null. So I pulled the common code to initializeStabilityTest() method. Also assigned the container variable to null in MySQLDatabaseProvider.

**Review by ldziedziul — APPROVED** [review]

**Pull request merged**
