### PR TITLE
Delete AllTest.java and LongRunningTest.java

### PR DESCRIPTION
**Pull request by orcunc**
These are not test files. They have main methods they have not been updated for very long time

Jira : https://hazelcast.atlassian.net/browse/HZ-3408

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

**Comment by JamesHazelcast** [comment]
Hi @orcunc, did you check with QE to confirm these tests aren't part of their process anywhere? I don't see them referenced, and I imagine our ITs cover this now, but better safe than sorry 😄 cc @olukas

**Comment by olukas** [comment]
Thanks @JamesHazelcast for letting me know. I don't know about any of use for them so I have no concerns about it.

**Comment by JackPGreen** [comment]
> > @orcunc these files are replicated in [hazelcast-code-samples](https://github.com/hazelcast/hazelcast-code-samples/tree/master/demo/src/main/java/com/hazelcast/demo) - but the versions there are older.
> > Should they be deleted too? Or should they be updated with what (was) here?
> 
> I'd rather not touch other files.

Then I don’t think we should delete them, sorry

**Comment by orcunc** [comment]
> > > @orcunc these files are replicated in [hazelcast-code-samples](https://github.com/hazelcast/hazelcast-code-samples/tree/master/demo/src/main/java/com/hazelcast/demo) - but the versions there are older.
> > > Should they be deleted too? Or should they be updated with what (was) here?
> > 
> > 
> > I'd rather not touch other files.
> 
> Then I don’t think we should delete them, sorry

What purpose do these files server then ? They are not unit tests.  They are ignored. 
They have other copies. Nobody updated them for 10 years.

**Comment by JackPGreen** [comment]
> > > @orcunc these files are replicated in [hazelcast-code-samples](https://github.com/hazelcast/hazelcast-code-samples/tree/master/demo/src/main/java/com/hazelcast/demo) - but the versions there are older.
> > > Should they be deleted too? Or should they be updated with what (was) here?
> > 
> > 
> > I'd rather not touch other files.
> 
> Then I don’t think we should delete them, sorry



> > > > @orcunc these files are replicated in [hazelcast-code-samples](https://github.com/hazelcast/hazelcast-code-samples/tree/master/demo/src/main/java/com/hazelcast/demo) - but the versions there are older.
> > > > Should they be deleted too? Or should they be updated with what (was) here?
> > > 
> > > 
> > > I'd rather not touch other files.
> > 
> > 
> > Then I don’t think we should delete them, sorry
> 
> What purpose do these files server then ? They are not unit tests. They are ignored. They have other copies. Nobody updated them for 10 years.

They were previously in hazelcast/src/main/java/com/hazelcast/examples, so they should be in the code-samples repo. But they are duplicated and outdated there.

I’d support removing them if we update them there. I’ll take a look later :)

**Review by JamesHazelcast — APPROVED** [review]
It looks like the code samples have been more regularly maintained than this version (and we could always use git history to find these versions if we need them) - so LGTM 👍

**Comment by JackPGreen** [comment]
> > > > @orcunc these files are replicated in [hazelcast-code-samples](https://github.com/hazelcast/hazelcast-code-samples/tree/master/demo/src/main/java/com/hazelcast/demo) - but the versions there are older.
> > > > Should they be deleted too? Or should they be updated with what (was) here?
> > > 
> > > 
> > > I'd rather not touch other files.
> > 
> > 
> > Then I don’t think we should delete them, sorry
> 
> > > > > @orcunc these files are replicated in [hazelcast-code-samples](https://github.com/hazelcast/hazelcast-code-samples/tree/master/demo/src/main/java/com/hazelcast/demo) - but the versions there are older.
> > > > > Should they be deleted too? Or should they be updated with what (was) here?
> > > > 
> > > > 
> > > > I'd rather not touch other files.
> > > 
> > > 
> > > Then I don’t think we should delete them, sorry
> > 
> > 
> > What purpose do these files server then ? They are not unit tests. They are ignored. They have other copies. Nobody updated them for 10 years.
> 
> They were previously in hazelcast/src/main/java/com/hazelcast/examples, so they should be in the code-samples repo. But they are duplicated and outdated there.
> 
> I’d support removing them if we update them there. I’ll take a look later :)

I tried merging the changes from `hazelcast` into `hazelcast-code-samples`, but even after merging each commit I could find, there are still differences.

https://github.com/JackPGreen/hazelcast-code-samples/tree/update-demo-tests

I think we should remove `hazelcast-code-samples/demos` too but I've had enough for now.

**Review by JackPGreen — APPROVED** [review]

**Comment by orcunc** [comment]
Thanks guys.

**Pull request merged**
