### PR TITLE
Fix stuck client authentication

### PR DESCRIPTION
**Pull request by eminn**
send data over connection as long as connection is live

#6371

### CODE REVIEW

**Comment by sancar** [comment]
:+1:

**Comment by metanet** [comment]
:+1:

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
run-lab-run

**Pull request merged**
