### PR TITLE
Removed unused method

### PR DESCRIPTION
**Pull request by ahmetmircik**

### CODE REVIEW

**Comment by Donnerbart** [comment]
:+1:

**Comment by pveentjer** [comment]
Can this cause problems in HZ Enterprise?

Apart from that ---> deleted code  is the best code.

**Comment by ahmetmircik** [comment]
@pveentjer no enterprise effect.

**Comment by ahmetmircik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/17286/

```
Test Result (2 failures / +1)
com.hazelcast.cluster.impl.BasicClusterStateTest.joinAllowed_whenKnownMemberReJoins_whenClusterState_isPassive
com.hazelcast.executor.SingleNodeTest.timeOut_thenCancel
```

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Pull request merged**
