### PR TITLE
#4233 Add ITopic.publishAll batch method #4233

### PR DESCRIPTION
**Pull request by andrewoelfing**
Hello Team,
please review it. Any feedback is welcome. 

Fixes: https://github.com/hazelcast/hazelcast/issues/4233

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by Holmistr** [comment]
Fixes: https://github.com/hazelcast/hazelcast/issues/4233

**Comment by vbekiaris** [comment]
@andrewoelfing thanks for creating this PR! Dispatching the items one-by-one will result in a lot of network overhead which could dominate execution time. Instead I think I would opt for batching the items so we could have a single network roundtrip per a maximum fixed amount of items. I believe this requires a new client message codec for client proxy and a new operation for member-side proxy.

You can look for inspiration at the member- and client-side implementations of [`Ringbuffer#addAllAsync`](https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/main/java/com/hazelcast/ringbuffer/Ringbuffer.java#L331).

**Comment by andrewoelfing** [comment]
Hello @vbekiaris, thanks for the feedback. For the first PR I wanted to avoid a more complex implementation with a complete new client message codec (in another repository). Splitting up the `addAll` and the `async` implementation had made sense to me.
Ok, as I understand, this new message codec is only necessary in the `Client*TopicProxy`-classes, right?

**Comment by mmedenjak** [comment]
@andrewoelfing there's no way around it - the implementation must use batching and should be async because the users want to avoid sending items one-by-one (this is what they are able to do with the current interface).

For the client codec, you'll need to checkout the https://github.com/hazelcast/hazelcast-client-protocol repository in addition to the IMDG OS repository. There, you can see how other client messages are implemented. For instance, messages for `ClientTopicProxy` are defined [here in YAML](https://github.com/hazelcast/hazelcast-client-protocol/blob/6027126a526773e70a8313a66dc0f9478ca31501/protocol-definitions/Topic.yaml).
Here is where you'll need to add one more message and regenerate the codecs. Regenerating the codecs is explained [in the README](https://github.com/hazelcast/hazelcast-client-protocol/blob/master/README.md). You can see how these codecs are used in `ClientTopicProxy`.
You'll then have to send two pull requests - one for client protocol and another for this repository. Both will be reviewed and merged roughly around the same time.

`ClientReliableTopicProxy` uses ringbuffer under the hood so there you probably will be able to use `ringbuffer.addAllAsync()` instead of adding a new client message.

And yes, codecs and messages are only used on client proxies. Member proxies (`TopicProxy`, `ReliableTopicProxy`) use operations and you can introduce new operations more easily by only changing this repository.

**Comment by andrewoelfing** [comment]
Ok, I will close the PR in this case because I have to implement this in a complete other way (an open a new one). 
Sorry for the inconvenience.

**Comment by mmedenjak** [comment]
No problem, thank you for your effort!

**Pull request closed without merging**
