### PR TITLE
Supporting [any] operator in the built-in aggregators

### PR DESCRIPTION
**Pull request by tombujok**
Once approved will be backported to 3.8 branch.

Relies on https://github.com/hazelcast/hazelcast/pull/9900

### CODE REVIEW

**Comment by tombujok** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
```
java.lang.IllegalArgumentException: Can't extract age from the given input
	at com.hazelcast.aggregation.impl.AbstractAggregator.extract(AbstractAggregator.java:73)
	at com.hazelcast.aggregation.impl.AbstractAggregator.accumulate(AbstractAggregator.java:49)
	at com.hazelcast.aggregation.CountAggregationTest.testCountAggregator_withAttributePath(CountAggregationTest.java:65)
```

**Comment by tombujok** [comment]
@vbekiaris Thx, it was a wrong data input in the test. Fixed.

**Comment by tombujok** [comment]
@vbekiaris could you review again?
@jerrinot could you review?
still thinking if not to backport to 3.8

**Comment by vbekiaris** [comment]
It would be great to extend the spec test to cover also aggregations on the client side `IMap` (my version fails on the client side in `Distinct` aggregation assertion) , and maybe parameterize to cover also `BINARY` in-memory format.

**Comment by tombujok** [comment]
run-lab-run

**Pull request merged**
