### PR TITLE
Tests for CP Membership restart issues

### PR DESCRIPTION
**Pull request by lprimak**
Demos CP member restart and rejoin issues
Relates to #24897

### CODE REVIEW

**Comment by arodionov** [comment]
If a cluster lost the majority of its members it will be blocked and should be recovered manually https://docs.hazelcast.com/hazelcast/5.3/cp-subsystem/management#handling-a-lost-majority

**Comment by lprimak** [comment]
@arodionov I think it's premature to close this for the following reasons:

- There is no event sent by Hazelcast when members shut down normally and majority is lost, thus there is no concrete way to find out when the "unsafe state" occurs.
- There is no way (even manually) to recover the cluster to a working state unless at east 3 members exist and are functioning.
- "Unrecoverable state" is dubious at best
- 100% CPU usage is seen under certain cicrumstances
- Requiring manual recovery is also dubious.

I would suggest reopening this PR.

**Comment by arodionov** [comment]
@lprimak thanks for your points!

Regarding,

> There is no event sent by Hazelcast when members shut down normally and majority is lost, thus there is no concrete way to find out when the "unsafe state" occurs.

there is a CP Group Availability Listeners https://docs.hazelcast.com/hazelcast/5.3/cp-subsystem/management#cp-group-availability-listeners

Other points, I'll copy to https://github.com/hazelcast/hazelcast/issues/24912

**Comment by lprimak** [comment]
Thanks @arodionov All of this is already described in #24897

> there is a CP Group Availability Listeners https://docs.hazelcast.com/hazelcast/5.3/cp-subsystem/management#cp-group-availability-listeners

Just want to reiterate that those listeners are **not** called when members are shut down properly, only when they die / freeze unexpectedly. This is why the above *cannot* relied upon currently.

If you run https://github.com/flowlogix/hazelcast-issues on 3 terminals, (stop/restart, use Ctrl-z) in about 10 minutes you will see all those issues in action.

**Comment by lprimak** [comment]
Please reopen. Still valid

**Comment by lprimak** [comment]
Well, I am not sure if I can test this anymore since the feature is EE-only
So it's up to you if you want to reopen this,
but IMHO the issues are still valid and still exist

**Pull request closed without merging**
