### PR TITLE
Adds the ringbuffer to the 'old' client. 

### PR DESCRIPTION
**Pull request by pveentjer**
Will be backported to 3.5.1 once merged.

### CODE REVIEW

**Comment by asimarslan** [comment]
:+1:

**Comment by bwzhang2011** [comment]
well done. hope reliable topic with hzclient afterwards.

**Comment by sancar** [comment]
:+1:

**Comment by asimarslan** [comment]
verify

**Comment by bwzhang2011** [comment]
@pveentjer, any progress with the support for reliable topic towards hazelcast client ?  hope it could be provided and merged as ringbuffer did,best wishes.

**Comment by bwzhang2011** [comment]
@pveentjer, notice that hz3.5.1 is going to be released not long in the future. but in hazelcast client component, I did not see ringbuffer or reliable topic is backported. as we're going to upgrade to such branch to replace the IQueue and ITopic most of the cases, any plan to leave us more message.

**Comment by pveentjer** [comment]
The ringbuffer is backported to 3.5.1. The reliable topic will be part of 3.5.2.

**Comment by bwzhang2011** [comment]
@pveentjer, the ringbuffer implementation is not backported to 3.5.1 with hazelcastclientImpl. maybe it has been postponed to 3.5.2

**Pull request merged**
