### PR TITLE
Cleanup for MapSplitBrainHandlerService and CacheSplitBrainHandlerSer…

### PR DESCRIPTION
**Pull request by ahmetmircik**
…vice

### CODE REVIEW

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Pull request merged**
