### PR TITLE
Added serialisation step to MapProxy.loadAll

### LINKED ISSUE #7090: MapProxySupport's loadInternal method requires dataKeys
I found this bug when i was trying to increase code coverage of NearCachedMapProxyImpl. Line that test calls map.loadAll threw `ClassCastException` due to NearCachedMapProxyImpl's invalidateCache.

Test is not directly related to bug it calls problematic methods.
```
    @Test
    public void testAfterLoadInvalidateNearCache() {
        int mapSize = 100;
        String mapName = "testLoad";

        Config config = createNearCachedMapConfig(mapName);
        MapStoreTest.SimpleMapStore store = new MapStoreTest.SimpleMapStore();
        MapStoreConfig mapStoreConfig = new MapStoreConfig();
        mapStoreConfig.setEnabled(true);
        mapStoreConfig.setImplementation(store3);
        config.getMapConfig(mapName).setMapStoreConfig(mapStoreConfig);

        HazelcastInstance instance = createHazelcastInstance(config);

        IMap<Integer, Integer> map = instance.getMap(mapName);
        HashSet<Integer> keys = new HashSet<Integer>();
        for (int i = 0; i < mapSize; i++) {
            map.put(i, i);
            keys.add(i);
        }

        for (int i = 0; i < mapSize; i++) {
            map.get(i);
        }

        map.loadAll(keys, true);

        NearCacheStats nearCacheStats = map.getLocalMapStats().getNearCacheStats();
        assertEquals(0, nearCacheStats.getOwnedEntryCount());
    }
```

### PR DESCRIPTION
**Pull request by hasancelik**
fixes #7090

I made changes on MapProxyImpl (and Support) that are super class of NearCachedClientMapProxy to prevent double serialisation.

### CODE REVIEW

**Comment by hasancelik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
Seems mergeable once green :+1:

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by eminn** [comment]
:+1:

**Comment by eminn** [comment]
Do we need a backport ?

**Comment by hasancelik** [comment]
I do not think so. @ahmetmircik WDYT?

**Comment by ahmetmircik** [comment]
@hasancelik @eminn the bug was only on master branch.

**Pull request merged**
