### PR TITLE
Use patched htrace-core4 dependency

### LINKED ISSUE #19573: Vulnerabilities in htrace-core4 used by Jet in HZ 5.0
This issue was migrated from issue https://github.com/hazelcast/hazelcast-jet/issues/2980. See the original issue for more details.

Related Apache issue: https://issues.apache.org/jira/browse/HDFS-15333

### PR DESCRIPTION
**Pull request by kwart**
Fixes #19573

This PR explicitly defines the `htrace-core4` dependency version to avoid having vulnerable jackson-databind library on the classpath. 

Sources of the patched module:
https://github.com/hazelcast/thirdparty-security-fixes/tree/org.apache.htrace_htrace-core4_4.2.0-incubating-v4.2.0-incubating.hazelcast-1/org.apache.htrace_htrace-core4_4.2.0-incubating

### CODE REVIEW

**Review by olukas — APPROVED** [review]

**Comment by frant-hartm** [comment]
We got the same failure as the commenter on the issue:

```
Caused by: java.lang.NoClassDefFoundError: org/apache/htrace/core/Tracer$Builder
 at org.apache.hadoop.fs.FsTracer.get(FsTracer.java:42)
 at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3460)
 ```
 
 Seems we actually need this.

**Comment by kwart** [comment]
Sad. It won't be so simple with this patch. I have to investigate it more.

**Comment by frant-hartm** [comment]
May it be because you used `4.2.0-incubating`, but we actually depend on `4.1.0-incubating`?

**Comment by kwart** [comment]
It's not a version problem. The test passes OK with the 4.2.0-incubating.
The failures start when I remove the dependencies shading. I didn't find what went wrong as I failed to find Hadoop logs. 

If I don't find where the issue lies, I'll rebuild the `htrace-core4` module with shaded newer jackson deps.

**Comment by kwart** [comment]
Finally, I found the issue. The Hadoop 3.3.1 wrongly imports one of the shaded classes.
```
$ grep -R ByteBufferBackedInputStream
org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/FsDatasetUtil.java:import org.apache.htrace.shaded.fasterxml.jackson.databind.util.ByteBufferBackedInputStream;
```

It should be resolved in Hadoop 3.3.2, which removes the htrace dependency completely (https://issues.apache.org/jira/browse/HADOOP-17424).
I hope the 3.3.2 release will be out in a few days, the RC2 was tagged last week. Till then, I'll prepare the `.hazelcast-2` htrace-core4 version with shaded jackson.

And for the record. Frantisek helped to resolve the mysteriously missing Hadoop logs:

> That's because of org.slf4j.impl.StaticLoggerBinder in sql module
> locally you can remove that and add something like
```xml
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>${log4j2.version}</version>
            <scope>test</scope>
        </dependency>
```
> to sql module deps

**Review by frant-hartm — APPROVED** [review]

**Review by olukas — APPROVED** [review]

**Comment by kwart** [comment]
Thanks for the reviews.

**Pull request merged**
