### PR TITLE
Remove Beta annotations from MongoDB extension

### PR DESCRIPTION
**Pull request by TomaszGaweda**
As in title, MongoDB extension is going GA.

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

**Review by orcunc — APPROVED** [review]

**Review by frant-hartm — CHANGES_REQUESTED** [review]
What about 

https://github.com/hazelcast/hazelcast/blob/691f4c1392e94febd20a7ed5e9544edbac5b006e/extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/dataconnection/MongoDataConnection.java#L52-L53

?

**Comment by TomaszGaweda** [comment]
@frant-hartm  I kept this, as the JdbcDataConnection is also `@Beta` - so I assumed (probably wrongly) that all DCs are Beta

**Comment by TomaszGaweda** [comment]
Done @frant-hartm

**Comment by TomaszGaweda** [comment]
run-lab-run

**Review by frant-hartm — APPROVED** [review]

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
run-lab-run

**Pull request merged**
