### PR TITLE
Minor ascii cleanup

### PR DESCRIPTION
**Pull request by pveentjer**
Static imports
Removal of redundant initializers
pulled out few methods
Removed author only javadoc
Added/removed some whitelines
Access modifiers added where needed
@Override where needed
Renamed SocketTextReader to TextSocketReader so it is aligned with MessageSocketReader/PacketSocketReader. 
Same for SocketTextWriter.

### CODE REVIEW

**Comment by jerrinot** [comment]
:+1:

**Comment by pveentjer** [comment]
verify

**Comment by Donnerbart** [comment]
verify

**Comment by Donnerbart** [comment]
:+1:

**Pull request merged**
