### PR TITLE
DONT MERGE - Fix/3.x/2981- Provides new event on EntryListener, onMerge.

### PR DESCRIPTION
**Pull request by dbrimley**
Fixed Checkstyle errors from previous pull request.

Provides new event on EntryListener, onMerge.

Previously in a WAN Replication scenario between 2 clusters, a MapEntry would travel to a destination cluster but the EntryListener would not fire there. So there was no way anybody listening in the destination cluster would know a new MapEntry had arrived.

This changes now fires the onMerge event in the EntryListener in the destination cluster.

This is a fix for #2981

### CODE REVIEW

**Comment by mahileeb** [comment]
Which version should we expect this fix in?

**Comment by ahmetmircik** [comment]
@mahileeb it should be in 3.5.

**Comment by mahileeb** [comment]
Is there a roadmap with a date for 3.5?

**Comment by ahmetmircik** [comment]
Scheduled at mid May 2015

**Comment by eminn** [comment]
I am closing this pull request, successor is #5058.

**Pull request closed without merging**
