### PR TITLE
Remove printing the license key while starting instance with overriding config

### PR DESCRIPTION
**Pull request by hasancelik**
Fixes https://github.com/hazelcast/hazelcast-docker/issues/248

Here is the fixed version of related log:
```
Detected external configuration entries in system properties:[hazelcast.clustername=test,hazelcast.licensekey=*********]
```

### CODE REVIEW

**Review by mmedenjak — APPROVED** [review]

**Comment by pivovarit** [comment]
Wouldn't it be a bit more friendly if we masked _almost_ everything? Like they do with credit card numbers?

**Comment by hasancelik** [comment]
@pivovarit good idea, I think we should do it for original key part. Because human-readable part of license key(`ENTERPRISE#10Nodes#`) is garbage actually, it does not keep valuable info for the instance. Here is sample input and output:

`ENTERPRISE#10Nodes#2gn9M....01930`
```
[hazelcast.licensekey=2gn9M*********01930]
```
If it is ok for you, I will update my PRs?

**Comment by pivovarit** [comment]
I don't know much about the structure of license keys, but what you showed looks good to me

**Comment by mmedenjak** [comment]
I'm really fine either way. To be honest, I don't know if showing part of the license brings benefit to anyone, or if we're just making up improvements nobody asked for. Regardless, I don't mind adding it. I'd just check with whomever is generating the licenses (operations? MC team?) on the structure of license keys, and if it's ok to show the beginning, the end, or both, and how long.

**Comment by hasancelik** [comment]
> or if we're just making up improvements nobody asked for

I think the improvement can be even good for us/Hazelcast team who uses multiple licenses at test setups. Giving some hints about current license at instance is user friendly improvement. 

> I'd just check with whomever is generating the licenses (operations? MC team?) on the structure of license keys, and if it's ok to show the beginning, the end, or both, and how long.

As far as I can remember from my old license generator days :), first and last 5 digits should be a problem but I think @erosb can approve it.

**Review by erosb — APPROVED** [review]
The change looks safe for me.
nit: a unittest added would be good.

**Pull request merged**
