### PR TITLE
EndpointSlices support for Kubernetes Discovery Plugin [CN-63]

### LINKED ISSUE #19466: EndpointSlices support
With 1.19 release, `EndpointSlices` is used by default for linux envs. Cluster's control plane mirrors `Endpoints` resources to corresponding `EndpointSlices`:
```
$ kg ep
NAME                      ENDPOINTS                                   AGE
hz-hazelcast   10.128.2.37:5701,10.129.2.246:5701,10.131.0.33:5701   8m14s
$ kg endpointslice
NAME                ADDRESSTYPE   PORTS   ENDPOINTS                              AGE
hz-hazelcast-2rhpc   IPv4          5701    10.129.2.246,10.128.2.37,10.131.0.33   8m34s
```
Its [API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#endpointslice-v1beta1-discovery-k8s-io)(/apis/discovery.k8s.io/v1beta1/) is beta for now, it will be graduated with 1.21 release
Check [EndpointSlices roll-out plan](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/0752-endpointslices#roll-out-plan) for more details.

### PR DESCRIPTION
**Pull request by alparslanavci**
This PR provides EndpointSlices support for k8s discovery plugin. It makes EndpointsSlices API usage default, and the old Endpoints API is not used as a fallback if EndpointSlices are not available. 

Fixes #19466.

### CODE REVIEW

**Review by SeriyBg — APPROVED** [review]
LGTM

**Review by hasancelik — COMMENTED** [review]
@alparslanavci at the first version of your implementation, there was an info log like "endpointslices using for discovery..." or smth like that. Why did we remove it? I think we should add them as `debug`, WDYT?

second thing is, I think we should add config to enable/disable endpointslices based discovery. WDYT?

**Comment by alparslanavci** [comment]
@hasancelik added the debug logs for EndpointSlices API usage.

Regarding the config, I think it would be nice to add a system property to allow usage of former Endpoints API in case of any edge/non-tested scenario. But it is not urgent, we can merge this PR as it is, and we can create a separate issue for the config.

**Comment by hasancelik** [comment]
> Regarding the config, I think it would be nice to add a system property to allow usage of former Endpoints API in case of any edge/non-tested scenario. But it is not urgent, we can merge this PR as it is, and we can create a separate issue for the config.

Could you JIRA ticket for that? Thanks 👍

**Review by hasancelik — APPROVED** [review]

**Pull request merged**
