### PR TITLE
add rbac.yaml file

### PR DESCRIPTION
**Pull request by SeriyBg**
Add `kubernetes-rbac.yaml` file from `hazelcast-kubernetes`
Issue: [CN-113]

Checklist:
- [+] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [+] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [+] Request reviewers if possible
- [+] New public APIs have `@Nonnull/@Nullable` annotations
- [+] New public APIs have `@since` tags in Javadoc
- [+] Send backports/forwardports if fix needs to be applied to past/future releases

[CN-113]: https://hazelcast.atlassian.net/browse/CN-113

### CODE REVIEW

**Comment by SeriyBg** [comment]
run-lab-run

**Review by leszko — APPROVED** [review]
Thanks @SeriyBg for the PR. One question: didn't we want to call the file `k8-rbac.yaml`? I personally don't mind, but thought that it was the idea of @mmedenjak

**Comment by mmedenjak** [comment]
Yeah, or some other way of clarifying what's it for, since the first time I heard about `rbac.yaml` in the root of a github repo, I thought - "Ah, that must be for some github security settings" :)

**Comment by SeriyBg** [comment]
Thanks for the review @leszko. I thought that it's better to use the `kubernetes` instead of the abbreviation `k8s` as it's clearer for the people who are out of context. But I totally ok to change it to `k8s`. @mmedenjak WDYT?

**Pull request merged**
