### PR TITLE
Support update on cleared bitmap indexes

### PR DESCRIPTION
**Pull request by taburet**
Fixes: https://github.com/hazelcast/hazelcast/issues/17342

### CODE REVIEW

**Review by devozerov — APPROVED** [review]

**Review by petrpleshachkov — COMMENTED** [review]
@taburet , have you run the `freeze-x` test to verify the fix?

**Comment by Danny-Hazelcast** [comment]
yes it looks like https://github.com/hazelcast/hazelcast/issues/17342 is fixed

**Review by petrpleshachkov — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2566/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2566/Hazelcast-pr-builder-2566.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MigrationInvocationsSafetyTest.migrationCommit_shouldRollback_whenTargetCrashes:324->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:221->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:225->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253->PartitionCorrectnessTestSupport.access$000:66->PartitionCorrectnessTestSupport.assertSizeAndData:237->PartitionCorrectnessTestSupport.assertPartitionAssignments:179->PartitionCorrectnessTestSupport.assertPartitionAssignments:216 expected:<-1669084290458575971> but was:<8917940183757797572>
[INFO] 
[ERROR] Tests run: 31983, Failures: 1, Errors: 0, Skipped: 978
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by taburet** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2576/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2576/Hazelcast-pr-builder-2576.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MigrationInvocationsSafetyTest.migrationCommit_shouldRollback_whenTargetCrashes:324->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:221->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:225->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253->PartitionCorrectnessTestSupport.access$000:66->PartitionCorrectnessTestSupport.assertSizeAndData:237->PartitionCorrectnessTestSupport.assertPartitionAssignments:179->PartitionCorrectnessTestSupport.assertPartitionAssignments:216 expected:<-1669084290458575971> but was:<8917940183757797572>
[INFO] 
[ERROR] Tests run: 31983, Failures: 1, Errors: 0, Skipped: 978
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by taburet** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2581/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2581/Hazelcast-pr-builder-2581.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MigrationInvocationsSafetyTest.migrationCommit_shouldRollback_whenTargetCrashes:324->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:221->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:225->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253->PartitionCorrectnessTestSupport.access$000:66->PartitionCorrectnessTestSupport.assertSizeAndData:237->PartitionCorrectnessTestSupport.assertPartitionAssignments:179->PartitionCorrectnessTestSupport.assertPartitionAssignments:216 expected:<-1669084290458575971> but was:<8917940183757797572>
[INFO] 
[ERROR] Tests run: 31983, Failures: 1, Errors: 0, Skipped: 978
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by taburet** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2582/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2582/Hazelcast-pr-builder-2582.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MigrationInvocationsSafetyTest.migrationCommit_shouldRollback_whenTargetCrashes:324->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:221->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:225->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253->PartitionCorrectnessTestSupport.access$000:66->PartitionCorrectnessTestSupport.assertSizeAndData:237->PartitionCorrectnessTestSupport.assertPartitionAssignments:179->PartitionCorrectnessTestSupport.assertPartitionAssignments:216 expected:<-1669084290458575971> but was:<8917940183757797572>
[INFO] 
[ERROR] Tests run: 31983, Failures: 1, Errors: 0, Skipped: 978
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by mmedenjak** [comment]
Thank you for the fix and the reviews, everyone!

**Pull request merged**
