### PR TITLE
Repackaged BasicOperationService

### PR DESCRIPTION
**Pull request by pveentjer**

### CODE REVIEW

**Comment by jerrinot** [comment]
:+1:

**Comment by Donnerbart** [comment]
There seems to be a FindBugs issue:
```
[INFO] Total bugs: 1
[INFO] new com.hazelcast.spi.impl.operationservice.impl.operations.Backup(Data, Address, long[], boolean) may expose internal representation by storing an externally mutable object into Backup.replicaVersions ["com.hazelcast.spi.impl.operationservice.impl.operations.Backup"] At Backup.java:[lines 50-188]
```

**Comment by Donnerbart** [comment]
Beside that it looks good to me :+1:

**Comment by pveentjer** [comment]
The array findbugs issue should be easy to solve.

**Comment by pveentjer** [comment]
verify

**Pull request merged**
