### PR TITLE
Added new test to validate spring.schemas

### PR DESCRIPTION
**Pull request by lazydays79**
This fixes issue #14441 

Best regards,
Michael

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by lazydays79** [comment]
Hi,

what I was trying to say in the issue subscription was, that I already signed the HCA, but as "MichaelRisthausAtos".

I hope, this is enough. :-)

Kind regards, 
Michael

**Comment by mmedenjak** [comment]
Ah, sorry about that, missed it. Thanks! I'll double check if that's ok. Thanks again for the contribution.

**Comment by mmedenjak** [comment]
Alternatively, if you cannot rebase it anymore, I will create a PR of my own and rebase it myself so we can include it in the release.

**Comment by kwart** [comment]
I've tried to resolve the conflict in the GitHub GUI, but it doesn't seem it worked :(

**Comment by lazydays79** [comment]
@mmedenjak Thanks for your efforts. I was on a business trip and couldn't answer yet. :)

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
@lazydays79 that was actually quicker than I expected :) thank you for rebasing it, we'll merge it soon.

**Comment by mmedenjak** [comment]
@lazydays79 these two tests are failing, probably because we've already forgotten to add one entry in `spring.schemas`, can you check it out?
```
com.hazelcast.spring.config.SpringSchemasVadilityTest.testPermaLinkIsLatestVersion
com.hazelcast.spring.config.SpringSchemasVadilityTest.testBothHttpAndHttpsAvailable
```

**Comment by mmedenjak** [comment]
@lazydays79 can you take a look at these failing tests?

**Comment by mmedenjak** [comment]
@lazydays79 any updates? We are about to release 4.0 soon. If you can't work on it, I can take over.

**Comment by lazydays79** [comment]
Please take over. I'm in deep... You know how the last days before xmas
holidays are. 🎅

Thanks!

Matko Medenjak <notifications@github.com> schrieb am Di., 17. Dez. 2019,
15:14:

**Comment by mmedenjak** [comment]
Superseded by https://github.com/hazelcast/hazelcast/pull/16293. Thank you for the original PR. We'll include you as the author.

**Pull request closed without merging**
