### PR TITLE
#13938 Remove slash when appended to map key in REST call

### PR DESCRIPTION
**Pull request by ryanlindeborg**
This PR removes the ending slash in the uri when it is appended to a key in a REST API call to put a key-value pair to a map.

Fixes: https://github.com/hazelcast/hazelcast/issues/13938

### CODE REVIEW

**Comment by Holmistr** [comment]
@ryanlindeborg Thanks for the PR! :tada: As discussed here: https://github.com/hazelcast/hazelcast/issues/13938#issuecomment-591833928 , we'll wait with the reviews until you check the other places. Thanks a lot, looking forward to it!

**Comment by ryanlindeborg** [comment]
Thanks for the feedback @kwart ! Should I be updating the hazelcast-reference-manual repository to detail the changes from this ticket?

**Comment by kwart** [comment]
> Thanks for the feedback @kwart ! Should I be updating the hazelcast-reference-manual repository to detail the changes from this ticket?

If you are able to cover the behavior in the reference manual too, it would be great. Thanks.

**Comment by Holmistr** [comment]
@ryanlindeborg Looks great!

Regarding the reference manual, here's the repository: https://github.com/hazelcast/hazelcast-reference-manual . Could you please send a PR to the relevant sections to make sure the documentaiton is inline with your changes?

One last think - before we merge the PR, could I ask you to sign our Contributor's agreement?
https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement

**Comment by ryanlindeborg** [comment]
@Holmistr Submitted my PR to the reference manual repository! And I believe I sent in my Contributor's agreement a few days ago

**Comment by Holmistr** [comment]
@ryanlindeborg You're absolutely right, I'm just blind! In that case there's nothing more to do here, let merge the PR. Welcome to Hazelcast community family :beers:  and thank you very much for your contribution! :tada:

**Pull request merged**
