### PR TITLE
Introduce Code Owners for auto discovery modules

### PR DESCRIPTION
**Pull request by hasancelik**

### CODE REVIEW

**Comment by pveentjer** [comment]
Oops. Didn't mean to close it.

I do have my concerns about this PR. The problem is that often the merging of PR's gets delayed because of mandatory team checks. I have quite a lot of experience with this with client code.

If there is a fundamental change: sure; API team should be involved. But if e.g. a method is renamed or a class is moved, it still leads to a mandatory PR and it just slows down the process.

So I do not believe having such rules is making the end product any better.

**Comment by hasancelik** [comment]
> I do have my concerns about this PR. The problem is that often the merging of PR's gets delayed because of mandatory team checks. I have quite a lot of experience with this with client code.

Your reasoning makes sense for `client` + `serialization` modules because they are active and modified by multiple teams. Our modules are not very active ones so other team members will not be affected so much. 

> If there is a fundamental change: sure; the right team should be involved. But if e.g. a method is renamed or a class is moved, it still leads to a mandatory review and it just slows down the process.

> Therefore I do not believe having such rigid rules makes the product better. I would rather see that people are responsible enough to call in the right people and get rid of such rigid rules completely. Apart from the API team, none of the other teams have such rules btw.

If your changes are just cosmetic, you can follow your own advice easily and leave some messages on a cloud-native channel to call the right people. Your PR is not required proper review, so someone will provide 👍  or approve it directly. I think we can not compare with CN team with others because our main focus is somewhere else most of the time while other teams do active maintenance on this repo.

**Comment by pveentjer** [comment]
>> If your changes are just cosmetic, you can follow your own advice easily and leave some messages on a cloud-native channel to call the right people. 

I tried this with client and it still stalls. This approach doesn't work for me.

**Comment by pveentjer** [comment]
If we allow it for Cloud, where is it going to stop? If every team would do this, then merging PRs is going to be a lot slower. 

Also, it feels like marking territory because you clearly do not trust people to make proper changes/reviews on cloud-related code without the involvement of the cloud team. in Hazelcast we expect engineers to call in the appropriate reviewers for some change because we trust them to make the right choice here. 

There is an argument for clients because of the client protocol and compatibility guarantees.

**Pull request closed without merging**
