### PR TITLE
Fail on invalid EXPLAIN-ordering statement

### PR DESCRIPTION
**Pull request by gierlachg**
Because `EXPLAIN` operates on physical rels, `CreateDagVisitor` methods are never called. Thus, invalid queries must fail during physical optimization phase at latest.

### CODE REVIEW

**Comment by gierlachg** [comment]
run-lab-run

**Comment by gierlachg** [comment]
run-lab-run

**Comment by gierlachg** [comment]
run-lab-run

**Comment by gierlachg** [comment]
run-lab-run

**Review by viliam-durina — APPROVED** [review]

**Review by Fly-Style — APPROVED** [review]
LGTM.

**Comment by gierlachg** [comment]
run-lab-run

**Pull request merged**
