### PR TITLE
Update config.yml for "New Issue" 

### PR DESCRIPTION
**Pull request by burakcelebi**
- Fix misunderstandings regarding "here"
- Add Gitter

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by pivovarit** [comment]
@mmedenjak do we really need to run CI for such changes?

**Comment by mmedenjak** [comment]
@pivovarit no, we didn't :)

**Pull request merged**
