### PR TITLE
revert back the AddMembershipListenerRequest. Added a new class called R...

### PR DESCRIPTION
**Pull request by sancar**
...egisterMEmbershipListenerRequest. Leaving old one as is until other clients are refactored

### CODE REVIEW

**Comment by mdogan** [comment]
I guess these all will change when client protocol comes in place...

**Comment by sancar** [comment]
I am hoping that we can build on top of these changes.

**Comment by sancar** [comment]
Requests not be removed completely but we will transform them to something more useful.

**Comment by mdogan** [comment]
:100:

**Comment by asimarslan** [comment]
look good

**Pull request merged**
