### PR TITLE
InvocationContext inner class and fields final

### PR DESCRIPTION
**Pull request by pveentjer**
To prevent the InvocationContext being abused for other purposes than Invocation, it has been made a static inner class of the Invocation and renamed to Context.

Also the Context fields are now finally and we get truly amazing test construction of the context.

### CODE REVIEW

**Comment by tombujok** [comment]
👍

**Comment by pveentjer** [comment]
run-lab-run

**Comment by jerrinot** [comment]
:+1: on green
in 3.8 we should remove `Node` from the `InvocationContext`

**Comment by pveentjer** [comment]
Probably we can get rid of operationservice as well.

**Comment by Donnerbart** [comment]
:+1: (once green)

**Pull request merged**
