### PR TITLE
Increased replicated map test coverage

### PR DESCRIPTION
**Pull request by eminn**

### CODE REVIEW

**Comment by hasancelik** [comment]
run-lab-run

**Comment by pveentjer** [comment]
@eminn what should be done with this PR?

**Comment by eminn** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
The removed serialization code is reasonable. `ReplicatedRecord` is not serialized anymore and the `ReplicatedMapMergePolicy` classes have no fields, so the change to `Serializable` should have no impact on performance. So this PR removes a lot of noisy code which hurts the code coverage. Also new tests are added. Looks good to me regarding missing code coverage for the replicated map.

:+1: (once green)

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
verify

**Comment by metanet** [comment]
:+1:

**Pull request merged**
