### PR TITLE
Added nodeEngine.isRunning() check to method getPartitionOwnerOrWait

### PR DESCRIPTION
**Pull request by ahmetmircik**
closes https://github.com/hazelcast/hazelcast/issues/6538

Details are in the issue.

### CODE REVIEW

**Comment by jerrinot** [comment]
isn't it still racy?

**Comment by metanet** [comment]
:+1:

**Comment by jerrinot** [comment]
:+1:

**Comment by mdogan** [comment]
@jerrinot: where do you think race is?

**Comment by jerrinot** [comment]
@mdogan: I no longer think there is a race. See my EDIT..

**Comment by mdogan** [comment]
:+1:

**Comment by ahmetmircik** [comment]
Do we need EA port? @jerrinot @mdogan @metanet WDYT?

**Pull request merged**
