### PR TITLE
Correct Javadoc on CacheConfiguration.setManagementEnabled(boolean)

### PR DESCRIPTION
**Pull request by jxblum**
Please see #22574.

### CODE REVIEW

**Comment by TomaszGaweda** [comment]
Hi! Thanks for the correction, I've triggered builds for this PR. Please fill the PR description according to our template @jxblum

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by jxblum** [comment]
Can you please provide a reference to your PR template?

Also, does this simple documentation (Javadoc) change really require an extensive checklist? 1) I filed an [Issue ticket](https://github.com/hazelcast/hazelcast/issues/22574) for this PR  and 2) I also filed a similar [Issue](https://github.com/hazelcast/hazelcast/issues/22572)/[PR](https://github.com/hazelcast/hazelcast/pull/22573) for another Javadoc issue, which has already been merged.

I am happy to comply if necessary, but would appreciate a link to the template. Thanks.

**Review by pveentjer — APPROVED** [review]

**Comment by pveentjer** [comment]
PR description is fine; we are talking about a 1 word change here.

**Pull request merged**
