### PR TITLE
Adds javadoc to TimedMemberStateFactory

### PR DESCRIPTION
**Pull request by emrahkocaman**

### CODE REVIEW

**Comment by eminn** [comment]
There are checkstyle issues

**Comment by emrahkocaman** [comment]
Thanks @eminn

**Comment by eminn** [comment]
Looks good to merge, will be merged when the pull request builder is green. :)

**Comment by emrahkocaman** [comment]
This was a test PR for our HUGI meetup. No need to merge.

**Comment by serkan-ozal** [comment]
@emrahkocaman @eminn what was a lovely PR. I am very sad about closing it :( 
BTW it was really hard to review because of its complicated changes

**Pull request closed without merging**
