### PR TITLE
Removes extra serialization when coalescing mode is on

### PR DESCRIPTION
**Pull request by ahmetmircik**
backport of https://github.com/hazelcast/hazelcast/pull/7058

### CODE REVIEW

**Comment by ahmetmircik** [comment]
verify

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
verify

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
verify

**Pull request merged**
