### PR TITLE
ClientTxnMapProxy.values() should return List instead of Set

### PR DESCRIPTION
**Pull request by cangencer**
When returning the values `ClientTxnMapProxy.values()`should use List instead of Set

### CODE REVIEW

**Comment by sancar** [comment]
@cangencer Could you add test to make sure we don`t break this again ?

**Comment by pveentjer** [comment]
@cangencer can you have a look at this pr? Once the test is added, imho the code is good to go.

**Comment by cangencer** [comment]
@pveentjer @sancar There was an issue on the server as well with the values being returned as a set when a predicate is supplied. I have fixed this as well and added a test for both.

**Comment by sancar** [comment]
@cangencer ClientTxnMapProxy for old client also needs to be updated. Can you fix and add the same test in old client package ? 
And we are gonna need to have backport for maintenance-3.x

**Comment by sancar** [comment]
verify

**Comment by cangencer** [comment]
verify

**Comment by pveentjer** [comment]
Can you squash the commits? After that it is a :+1:  from me

**Comment by sancar** [comment]
:+1:

**Pull request merged**
