### PR TITLE
New option on map that allows to configure if wants a defensive copy of object contained

### PR DESCRIPTION
**Pull request by angel9484**
This enhacement is really cool with paths where the speed is critical over data integrity.
This modification is only for map.
It add's a new option on mapConfig: 
The option let choose if a map can retrieve the object without serialize and deserialize (a defensive copy).
The RecordStore has been enhaced and the readBackupData has been refactored: now exists a new method readBackup that contais all the code in the old readBackupData except the "toData method call". The readBackupData now calls to readBackup and then call to the toData method on mapServiceContext.
Then the MapProxySupport does this:
if true, hazelcast will work as ever.
If false, and in memory type is not Object, hazelcast will work as ever.
If false and in memory type is Object and isReadBackupData is active: it will use the readBackup and retrieve the object as is. With 35KB serialized value, and a bit of bussiness logic, the response time was around 200ms. Now without this defensive copy, the response time is around 30ms

### CODE REVIEW

**Comment by pveentjer** [comment]
Hi @angel9484, thanks you for your PR.

We are currently at feature freeze and this feature needs to wait till 3.6 has been released.

@ahmetmircik @asimarslan can you have a look at this PR?

**Comment by angel9484** [comment]
Aww! Ok! Sorry for the inconvenience! I will try to do this PR on the 3.6-snapshot branch!
Actually we can't work with non stable releases. Do you have an ETA for 3.6?.
Do you have the style code format in some place? if you have it to eclipse or intellij it would be great!

Thanks!

**Comment by Donnerbart** [comment]
To get this eventually merged you have to base it on the master branch, which is the base for the upcoming releases. We don't merge new features into other branches than master (and of course not during feature freeze).

For the code style we have CheckStyle which you can run via Maven, e.g. by executing `mvn clean compile -Pcheckstyle`. That should cover most style issues. We don't have an up to date code formatter, but the out-of-the-box formatter of InetlliJ 15 works quite well for Hazelcast.

**Comment by angel9484** [comment]
Ok @Donnerbart Thanks! now is the new PR on master: #7013 
In spain is holidays today and tomorrow, I will sign the contribution agreement on wednesday utc zone.
Regards!

**Pull request closed without merging**
