### PR TITLE
Upgrade the Surefire plugin to resolve Java 11 parallel test runs with modulepath

### LINKED ISSUE #17726: modulepath-tests causing CorrettoJDK11 build to report failure
- Fails on `CorrettoJDK11`
- Sample [run](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-CorrettoJDK11/83/consoleFull)
- Reactor report logs good except `modulepath-tests`
```
....
00:45:25.597 [INFO] hazelcast-all ...................................... SUCCESS [ 16.887 s]
00:45:25.597 [INFO] hazelcast-distribution ............................. SUCCESS [  1.658 s]
00:45:25.597 [INFO] modulepath-tests ................................... FAILURE [  1.143 s]
```
- Test logs 
```
00:45:24.882 [INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ modulepath-tests ---
00:45:25.022 [2663.208s][info   ][gc] GC(187) Pause Young (Prepare Mixed) (G1 Evacuation Pause) 1049M->187M(2048M) 7.468ms
00:45:25.591 [INFO] 
00:45:25.591 [INFO] -------------------------------------------------------
00:45:25.591 [INFO]  T E S T S
00:45:25.591 [INFO] -------------------------------------------------------
00:45:25.595 [INFO] 
00:45:25.595 [INFO] Results:
00:45:25.595 [INFO] 
00:45:25.595 [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
00:45:25.595 [INFO] 
00:45:25.596 [INFO] ------------------------------------------------------------------------
```
- Kindly check

### PR DESCRIPTION
**Pull request by kwart**
Fixes #17726 

EE: https://github.com/hazelcast/hazelcast-enterprise/pull/3832

### CODE REVIEW

**Review by Holmistr — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2702/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2702/Hazelcast-pr-builder-2702.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   QueueAdvancedTest.testTakeInterruption:620->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253 Thread Thread-811 is still alive
[ERROR]   QueueAdvancedTest.testTakeInterruption:620->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253 Thread Thread-733 is still alive
[ERROR]   PipeliningTest.testInterrupt:75->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253 Thread Thread-3010 is still alive
[INFO] 
[ERROR] Tests run: 32073, Failures: 3, Errors: 0, Skipped: 979
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by kwart** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2707/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2707/Hazelcast-pr-builder-2707.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CacheExpirationTest.test_whenEntryIsRemovedBackupIsCleaned:310 Expected to remove entry 0 but entry was not present. Expired entry count: 1
[ERROR]   QueueAdvancedTest.testTakeInterruption:620->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253 Thread Thread-944 is still alive
[ERROR]   PipeliningTest.testInterrupt:75->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253 Thread Thread-4377 is still alive
[INFO] 
[ERROR] Tests run: 32074, Failures: 3, Errors: 0, Skipped: 979
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Review by mmedenjak — APPROVED** [review]

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
I see multiple tests in both builds failing with `java.lang.AssertionError: Thread Thread-... is still alive`. Is it because of the dependency upgrade?

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2710/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2710/Hazelcast-pr-builder-2710.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   QueueAdvancedTest.testTakeInterruption:620->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253 Thread Thread-845 is still alive
[ERROR] Errors: 
[ERROR]   CacheClientListenerTest>CacheListenerTest.testReplaceIfSameWithSyncListener_whenValueIsNotSame:167->getCachingProvider:63 ? TestTimedOut
[INFO] 
[ERROR] Tests run: 32074, Failures: 1, Errors: 1, Skipped: 979
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by kwart** [comment]
> I see multiple tests in both builds failing with `java.lang.AssertionError: Thread Thread-... is still alive`. Is it because of the dependency upgrade?

It seems to be related. I don't see the problem when I run the failing test classes locally. I will try to find what's causing it.

**Review by lazerion — APPROVED** [review]

**Review by ahmetmircik — APPROVED** [review]

**Comment by kwart** [comment]
It seems the surefire version 3.0.0-M5 is a problematic one and we were hitting https://issues.apache.org/jira/browse/SUREFIRE-1815. Let's get a step back to M4 until the M6 is out.

**Pull request merged**
