### PR TITLE
isAsync takes precedence over OperationHostileThread

### LINKED ISSUE #24712: Response thread "cannot make remote call"
**Describe the bug**
We are facing an issue with map usage after upgrading from Hazelcast 3.12.6 to 5.3.0. When we perform an asynchronous map operation (e.g. setAsync), wrap the future using CompletableFuture.allOf(...) and trigger another asynchronous map operation from the callback, Hazelcast fails with "Thread[hz._hzInstance_1_MyApplication.response-1,5,main] cannot make remote call".

I think the requirement is that the first map invocation contacts another node. As far as I understand, the problem is that the callback is served by Hazelcast response thread which is marked with OperationHostileThread - but I don't get the motivation for this behaviour. Note that it works fine if we don't use CompletableFuture.allOf(...), because a different thread serves the callback when chaining using a single future .

**Expected behavior**
After the map update finishes, the callback should trigger another map update and it should succeed.

**To Reproduce**

        IMap<Integer, Integer> myMap = hazelcastInstance.getMap("my_map");

        List<CompletableFuture<Void>> futures = new ArrayList<>();
        futures.add(myMap.setAsync(10, 20).toCompletableFuture());

        CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]))
                .thenCompose(x -> {
                    log.debug("Callback");
                    return myMap.setAsync(30, 40).toCompletableFuture();
                })
                .exceptionally(e -> {
                    log.error("Error", e); //!!!
                    return null;
                });

**Additional context**

Exception stacktrace:
2023-06-05 14:09:11.300 ERROR 24732 --- [tion.response-1] c.c.a.r.m.c.c.m.AccountController          : Error

java.util.concurrent.CompletionException: java.lang.IllegalThreadStateException: Thread[hz._hzInstance_1_Application.response-1,5,main] cannot make remote call: com.hazelcast.map.impl.operation.SetOperation{serviceName='hz:impl:mapService', identityHash=1034817135, partitionId=66, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 00:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=my_map}
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[na:na]
	at com.hazelcast.spi.impl.DelegatingCompletableFuture.completeSuper(DelegatingCompletableFuture.java:499) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.DelegatingCompletableFuture.lambda$new$0(DelegatingCompletableFuture.java:103) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1570) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.internal.util.ConcurrencyUtil$1.execute(ConcurrencyUtil.java:39) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.execute(AbstractInvocationFuture.java:1568) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockOtherNode(AbstractInvocationFuture.java:802) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockAll(AbstractInvocationFuture.java:760) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockAll(AbstractInvocationFuture.java:757) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1241) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1225) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.complete(Invocation.java:690) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.BaseInvocation.completeWithPendingResponse(BaseInvocation.java:161) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.BaseInvocation.notifyBackupComplete(BaseInvocation.java:82) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.InboundResponseHandler.notifyBackupComplete(InboundResponseHandler.java:127) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.InboundResponseHandler.accept(InboundResponseHandler.java:94) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.InboundResponseHandlerSupplier$ResponseThread.doRun(InboundResponseHandlerSupplier.java:297) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.InboundResponseHandlerSupplier$ResponseThread.executeRun(InboundResponseHandlerSupplier.java:284) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) ~[hazelcast-5.3.0.jar:5.3.0]
Caused by: java.lang.IllegalThreadStateException: Thread[hz._hzInstance_1_MyApplication.response-1,5,main] cannot make remote call: com.hazelcast.map.impl.operation.SetOperation{serviceName='hz:impl:mapService', identityHash=1034817135, partitionId=66, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 00:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=my_map}
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:556) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeAsync(Invocation.java:246) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:70) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperationAsync(MapProxySupport.java:539) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperationAsync(MapProxySupport.java:556) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.map.impl.proxy.MapProxySupport.setAsyncInternal(MapProxySupport.java:576) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.setAsync(MapProxyImpl.java:434) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.setAsync(MapProxyImpl.java:422) ~[hazelcast-5.3.0.jar:5.3.0]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.setAsync(MapProxyImpl.java:112) ~[hazelcast-5.3.0.jar:5.3.0]
	at my.AccountController.lambda$test$0(AccountController.java:92) ~[classes/:na]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[na:na]
	... 20 common frames omitted

### PR DESCRIPTION
**Pull request by lukasherman**
Fixes #24712
OperationExecutor allows async invocation of OperationHostileThread.

### CODE REVIEW

**Comment by TomaszGaweda** [comment]
@vbekiaris can you please take a look?

**Review by TomaszGaweda — APPROVED** [review]

**Comment by JamesHazelcast** [comment]
Thanks for submitting this contribution. I don't see any obvious downsides to this change, but the interface `OperationHostileThread` suggests that these threads should **never** be used to run Operations, in which case it makes sense to disallow running Operations on these threads, even if called async.

As I'm not familiar with `OperationHostileThread` and its exact usage, I'll call in the expert @pveentjer for his review of this change.

**Comment by pveentjer** [comment]
The purpose of OperationHostileThread is to prevent any operation running on that thread. For partition-specific operations it is obvious that you need to run on a partition-thread, but there are also operations that do not require a partition thread to run on. And we need to make sure that such operations don't get executed on such a OperationHostileThread (e.g. an IO-thread).

**Comment by pveentjer** [comment]
The change is fine since with 'async' the actual operation execution will always be offloaded to the right thread and will never be executed on an OperationHostileThread.

**Review by pveentjer — APPROVED** [review]

**Review by JamesHazelcast — APPROVED** [review]
Thanks for the contribution @lukasherman, we appreciate it!

**Comment by zjedi** [comment]
any chance for backporting the fix to 5.3 branch?

**Comment by JamesHazelcast** [comment]
> [CLA assistant check](https://cla.hazelcast.org:443/hazelcast/hazelcast?pullRequest=26227) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.hazelcast.org:443/hazelcast/hazelcast?pullRequest=26227) before we can accept your contribution.
> 
> **Lukáš Herman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org:443/check/hazelcast/hazelcast?pullRequest=26227) it.

Please sign the CLA so we can proceed @lukasherman.

**Comment by lukasherman** [comment]
> Please sign the CLA so we can proceed @lukasherman.

I have signed it several times already, please check.

**Comment by JamesHazelcast** [comment]
> any chance for backporting the fix to 5.3 branch?

This will be backported to our `5.3.z` branch, yes 👍

**Pull request closed without merging**
