### PR TITLE
Rename hot restart home-dir to base-dir

### PR DESCRIPTION
**Pull request by mdogan**

### CODE REVIEW

**Comment by mdogan** [comment]
> Slave went offline during the build
11:04:46 ERROR: Connection was broken: java.nio.channels.AsynchronousCloseException
11:04:46 	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:205)
11:04:46 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:407)
11:04:46 	at hudson.remoting.SocketChannelStream$1.read(SocketChannelStream.java:35)
11:04:46 	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
11:04:46 	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
11:04:46 	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
11:04:46 	at java.io.InputStream.read(InputStream.java:101)
11:04:46 	at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:114)
11:04:46 	at javax.crypto.CipherInputStream.read(CipherInputStream.java:239)
11:04:46 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
11:04:46 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
11:04:46 	at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:82)
11:04:46 	at hudson.remoting.ChunkedInputStream.readHeader(ChunkedInputStream.java:72)
11:04:46 	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:103)
11:04:46 	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
11:04:46 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
11:04:46 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

**Comment by mdogan** [comment]
run-lab-run

**Comment by mdogan** [comment]
Failed spring tests:
```
11:42:25 testCacheNames(com.hazelcast.spring.cache.TestCacheManager)  Time elapsed: 123.393 sec  <<< FAILURE!
11:42:25 java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
11:42:25 	at org.junit.Assert.fail(Assert.java:88)
11:42:25 	at org.junit.Assert.assertTrue(Assert.java:41)
11:42:25 	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:756)
11:42:25 	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:749)
11:42:25 	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:741)
11:42:25 	at com.hazelcast.spring.cache.TestCacheManager.testCacheNames(TestCacheManager.java:121)
11:42:25 
11:42:25 test(com.hazelcast.spring.cache.TestCacheManager)  Time elapsed: 122.964 sec  <<< ERROR!
11:42:25 com.hazelcast.spi.exception.CallerNotMemberException: Not Member! caller:Address[127.0.0.1]:5701, partitionId: 11, operation: com.hazelcast.map.impl.operation.GetOperation, service: hz:impl:mapService
11:42:25 	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureValidMember(OperationRunnerImpl.java:426)
11:42:25 	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:386)
11:42:25 	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184)
11:42:25 	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137)
11:42:25 	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
11:42:25 	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
11:42:25 	at ------ End remote and begin local stack-trace ------.(Unknown Source)
11:42:25 	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:385)
11:42:25 	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:335)
11:42:25 	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:223)
11:42:25 	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
11:42:25 	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:317)
11:42:25 	at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:247)
11:42:25 	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:91)
11:42:25 	at com.hazelcast.spring.cache.HazelcastCache.get(HazelcastCache.java:56)
11:42:25 	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:297)
11:42:25 	at org.springframework.cache.interceptor.CacheAspectSupport.findInAnyCaches(CacheAspectSupport.java:287)
11:42:25 	at org.springframework.cache.interceptor.CacheAspectSupport.collectPutRequests(CacheAspectSupport.java:266)
11:42:25 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:199)
11:42:25 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:178)
11:42:25 	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:60)
11:42:25 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
11:42:25 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
11:42:25 	at com.sun.proxy.$Proxy32.getName(Unknown Source)
11:42:25 	at com.hazelcast.spring.cache.TestCacheManager.test(TestCacheManager.java:65)
```

**Comment by mdogan** [comment]
run-lab-run

**Comment by mtopolnik** [comment]
:+1:

**Pull request merged**
