### PR TITLE
Changes for hot-restart work

### PR DESCRIPTION
**Pull request by mdogan**
- Added some hook methods to NodeExtension to intercept beforeJoin and register additional services.
- Exposed partition replica change listener to outside of partition package
- Improved cluster state handling

### CODE REVIEW

**Comment by mtopolnik** [comment]
Failed due to internal Jenkins error.

**Comment by mtopolnik** [comment]
verify

**Comment by pveentjer** [comment]
*reviewing*

**Comment by mtopolnik** [comment]
:+1:

**Comment by metanet** [comment]
:+1:

**Pull request merged**
