### PR TITLE
Exist key operation.

### PR DESCRIPTION
**Pull request by angel9484**
This operation is equal than containsKey but this doesn't trigger the mapLoader.
Useful when you know you are on the owner node and need to fast-query if the value is loaded into the local map instead of iterate over all localKeySet.

### CODE REVIEW

**Comment by jerrinot** [comment]
Hello @angel9484,
thank you for your PR. I can see usefulness of this, but I am not sure whether this should be exposed via its own method. 

I am a bit worried about API-creep. As in theory you can add a new method which by-pass MapLoader for many existing methods. One option how to prevent this could be adding a method `IMap bypassMapLoader()` (or similar) to the `IMap` interface . It would return another instance of IMap where all calls would bypass configured MapLoader. 

What do you think about this approach?

**Comment by ahmetmircik** [comment]
Instead of `existKey`, as a workaround, `IMap#getEntryView` can be used. It only checks existing in-memory data, doesn't try to load value via map-loader.

**Comment by enesakar** [comment]
Thanks for contribution. My remarks:
`existKey` will create a confusion with `containsKey` in the IMap API.
To bypass mapstore in read operations, you can simply return null from `V load(K key);`
Right?

**Comment by noctarius** [comment]
@enesakar I think the use case is different here. I guess he wants to figure out if a Key was actually loaded into Hazelcast without loading it if not. Your solution would render it to be never loaded at all.

Anyhow I think the method would be better named like `isKeyLoaded(Key)` since I certainly agree that `existKey` is not a good self-explanatory name :)

**Pull request closed without merging**
