### PR TITLE
iam role default support added

### PR DESCRIPTION
**Pull request by bilalyasar**
you can find explanation here https://github.com/hazelcast/hazelcast/issues/7087
fixes https://github.com/hazelcast/hazelcast/issues/7087

### CODE REVIEW

**Comment by pveentjer** [comment]
How is this tested? Did you try it on amazon? I know that adding a unit test for it will be a difficult problem.

**Comment by bilalyasar** [comment]
@pveentjer yes, i tried in amazon manually. After merging, we can also ask the user for trying.

**Comment by pveentjer** [comment]
:+1:

**Comment by mesutcelik** [comment]
@bilalyasar Can you please forward port?

**Pull request merged**
