### PR TITLE
Unsafe disabled on platforms where unaligned access to memory is not allowed

### LINKED ISSUE #5518: Getting instance of sun.misc.Unsafe class does not work on HPUX operation system
See [error report](https://gist.github.com/basovnik/a1c0bb364930d9374e28)

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #5518

I appreciate any advice how to test it. Static initializers are tricky beasts. I could imagine some classloader magic, but it could cause more harm than good.

### CODE REVIEW

**Comment by serkan-ozal** [comment]
@jerrinot 

As far as I see, the only way is custom classloader for this kind of static initializers. 

Besides that I prefer moving the logic inside static initiazer to a static method on another helper class such as `UnsafeChecker` then `UnsafeHelper` uses this one. Then unit test can be written to this static method not `UnsafeHelper`

**Comment by pveentjer** [comment]
@jerrinot what should we do with this pr?

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
There are 2 checkstyle issues:

```
12:15:28 /scratch/jenkins/workspace/Hazelcast-3.x-pr-builder/hazelcast/src/main/java/com/hazelcast/nio/UnsafeHelper.java:62: Line is longer than 130 characters (found 136).
12:15:28 /scratch/jenkins/workspace/Hazelcast-3.x-pr-builder/hazelcast/src/main/java/com/hazelcast/nio/UnsafeHelper.java:65: Line is longer than 130 characters (found 132).
```

**Comment by serkan-ozal** [comment]
Besides that it is OK :+1:

**Comment by serkan-ozal** [comment]
Where should we document new property `hazelcast.unsafe.disable`?

**Comment by serkan-ozal** [comment]
ping @jerrinot

**Comment by jerrinot** [comment]
verify

**Comment by jerrinot** [comment]
@serkan-ozal: I pushed an update. Now you can disable it, but you can also enforce it on platforms where it's disabled by default.

**Comment by jerrinot** [comment]
I'll prepare a backport once it's merged into a mster.

**Comment by jerrinot** [comment]
@Serdaro: This PR introduces a new system property. There should be no need to set it unless auto-detection fails - it's possible when running on exotic platforms. Any idea where/how to document it? 

See this for details: https://github.com/hazelcast/hazelcast/issues/5518#issuecomment-129521827

**Comment by serkan-ozal** [comment]
:+1:

**Comment by pveentjer** [comment]
:+1:

**Pull request merged**
