### PR TITLE
`HttpsRestTest` test failure - `java.net.http.HttpClient` misconfiguration

### PR DESCRIPTION
**Pull request by JackPGreen**
In #25418, Apache's HttpClient was replaced with the java.net one.

This has caused a test failure.

Specifically:
- `com.hazelcast.internal.ascii.HTTPCommunicator.doPost(String, String...)` is doing `HttpClient.newHttpClient()`, not `newClient()`, so SSL configuration is not being used. This is obviously an easy fix.

- The `SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER` configuration has been removed and not replaced. Resolved by moving this configuration to the `HttpsRestTest` EE test instead, as already done in `EnterpriseInvalidEndpointTest` (and done in such a way it's shared).

Breaking changes (list specific methods/types/messages):
* `com.hazelcast.internal.ascii.HTTPCommunicator` (this is a **`test`** class) no longer allows certificates with mismatched hostnames, although this behaviour [was never documented](https://github.com/hazelcast/hazelcast/pull/25434#issuecomment-1718264532).

EE PR: [#6486](https://github.com/hazelcast/hazelcast-enterprise/pull/6486)

Fixes [#6485 (EE)](https://github.com/hazelcast/hazelcast-enterprise/issues/6485)

### CODE REVIEW

**Review by orcunc — APPROVED** [review]

**Comment by orcunc** [comment]
There are two solutions like you have mentioned to disable host name verification. 
1. Setting system property or 
2. Using a X509ExtendedTrustManager that trusts everything.

This PR is using the second solution and I think this solution is better than the first one.

I had another PR https://github.com/hazelcast/hazelcast/pull/25435 but I am going to close it

**Comment by kwart** [comment]
We don't want to trust everything. We want to just disable the hostname verification. If the #25435 resolves those issues, we should merge that one.

**Comment by JackPGreen** [comment]
> After checking the behavior in the second PR (and its concurrency problems), I think the proper way will be to fix it on the EE side. I.e use the system property on the test-class level as we already have it in the `EnterpriseInvalidEndpointTest` class.

That would be a better fix - but is this not a change in behaviour?

Currently anyone using the functionality - even outside of tests - has the `ALLOW_ALL_HOSTNAME_VERIFIER` behaviour.

Seems safer to me, though.

**Comment by kwart** [comment]
The `HTTPCommunicator` JavaDoc is silent about this implementation detail. So no contract change, just fixing the behavior :)

**Comment by JackPGreen** [comment]
> The `HTTPCommunicator` JavaDoc is silent about this implementation detail. So no contract change, just fixing the behavior :)

I didn't realise it was only in `test` scope, apologies.

**Comment by JackPGreen** [comment]
> After checking the behavior in the second PR (and its concurrency problems), I think the proper way will be to fix it on the EE side. I.e use the system property on the test-class level as we already have it in the `EnterpriseInvalidEndpointTest` class.

b2050e26d1453e0c029ce7901ae7ba4e63efb003

**Comment by JackPGreen** [comment]
run-with-ee

**Comment by JackPGreen** [comment]
run-with-os

**Comment by JackPGreen** [comment]
run-with-ee

**Review by orcunc — APPROVED** [review]

**Comment by orcunc** [comment]
run-lab-run

**Pull request merged**
