### PR TITLE
Added wait-for-safe-state in queue tests involving migrations

### PR DESCRIPTION
**Pull request by mmedenjak**
Some tests would fail with error messages where the data was
inconsistent. This is because the environment is slow and the node is
 not able to migrate all partitions before being terminated. The
 error message is not clear though and it is much better if we wait
 for the safe state (all migrations have finished) before asserting
 the data consistency. Next time the environment is slow the
 wait-for-safe-state will first fail.

Also lowered partition count to 10 to speed up test and have less
 interference of slow environment on migrations

 Fixes : https://github.com/hazelcast/hazelcast/issues/10287

### CODE REVIEW

**Comment by mmedenjak** [comment]
@jerrinot it's a common scenario : 
- start instance 1
- mutate data
- start instance 2
- call safe shutdown on instance 1, migrations start
- slow environment causes 2 minutes to pass before all partitions have been migrated
- instance 1 is forcefully shut down (`Graceful shutdown could not be completed in 120 seconds!`)
- you get a lot of `partitionId=xxx is completely lost!` and data consistency assertions fail

I think we can even lower the number of partitions for these kind of simple tests since it is irrelevant that we have 271. In total, we could perhaps even speed up the PR builder and it would fail less (since there would be less partition migrations)

**Comment by mmedenjak** [comment]
@mdogan lowered partition count for these tests to 10 because it definitely speeds up the test and there is less problems with a slow environment. The test does not rely on the default partition count anyway. I think if we decrease partition count for other tests like this we can speed up the PR builder.
Is partition count of 10 too low? What would be your recommendation?

**Comment by mdogan** [comment]
@mmedenjak: We set lower partition count for some tests. It depends on what you are testing. For most of the tests, I think a very low partition count should be fine.

**Comment by mmedenjak** [comment]
Since it's mostly test improvements, I'm merging this one

**Pull request merged**
