### PR TITLE
Removed extra delay from write-behind, delaying is already handled by…

### PR DESCRIPTION
**Pull request by ahmetmircik**
… store-worker class

forward port of https://github.com/hazelcast/hazelcast/pull/8190

### CODE REVIEW

**Comment by ahmetmircik** [comment]
verify

**Comment by ahmetmircik** [comment]
verify

**Comment by jerrinot** [comment]
:+1:

**Comment by gurbuzali** [comment]
👍

**Comment by ahmetmircik** [comment]
passed here: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/18058/

**Pull request merged**
