### PR TITLE
refactor client to client-legacy

### PR DESCRIPTION
**Pull request by asimarslan**
This is the first step of renaming clients.

### CODE REVIEW

**Comment by pveentjer** [comment]
images

**Comment by pveentjer** [comment]
images

**Comment by pveentjer** [comment]
@asimarslan can you rebase? We should get this PR merged ASAP so it doesn't suffer from conflicts.

**Comment by asimarslan** [comment]
Two commits in single PR, will do the same trick.

**Comment by pveentjer** [comment]
Now we are back to the original problem. The commit history is messed up. Can you rollback the 'client-new to client rename' and do a rebase of the'client to client legacy' rename?

**Comment by asimarslan** [comment]
@pveentjer we checked it locally, git history just work fine.

**Comment by mdogan** [comment]
@asimarslan: will you do the same renaming on EE?

**Pull request merged**
