### PR TITLE
[Forward Port] Increment stats on async map operations

### LINKED ISSUE #6731: putAsync does not affect LocalMapStats.getPutOperationCount()
I am using Hazelcast 3.5.3. It seems that putAsync does not affect LocalMapStats.getPutOperationCount(). Is it possible to add all async operations to the Put or Get or Delete OperationsCounts in LocalMapStats?

### PR DESCRIPTION
**Pull request by metanet**
Fixes #6731

### CODE REVIEW

**Comment by metanet** [comment]
verify

**Comment by pveentjer** [comment]
See this pr for comments:

https://github.com/hazelcast/hazelcast/pull/6767

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run

**Comment by hasancelik** [comment]
run-lab

**Comment by hasancelik** [comment]
run-lab

**Pull request merged**
