### PR TITLE
Responsehandler remoteinvocation singleton

### PR DESCRIPTION
**Pull request by pveentjer**
The responsehandler provides a flexible design, but the current implementation causes quite some object litter (2 objects per remote invocation). This PR cleans up the API by making the RemoteResponseHandler a singleton. To provide access to the Operation-context, the operation is passed into the handleResponse method.

This pr depends on the following pr to get merged first:
https://github.com/hazelcast/hazelcast/pull/4485

This pr is the basis for some additional cleanup. One of the things that is the OperationService.sendResponse methods:
- get rid of the response; needed for removing the response-thread
- pass in connection to the sendResponse method so that you don't send in the address and then lookup the connection, if the connection already is at hand.

This is an API breaking method; but to get rid of the response-thread, modifications need to be done anyway to the response-handler.

### CODE REVIEW

**Comment by pveentjer** [comment]
verify

**Comment by ahmetmircik** [comment]
Test failure: __testGetFutureAfterCancel__
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client/11579/testReport/junit/com.hazelcast.client.executor/ClientExecutorServiceTest/testGetFutureAfterCancel/

**Comment by ahmetmircik** [comment]
verify

**Comment by pveentjer** [comment]
verify

**Comment by gurbuzali** [comment]
needs rebase

**Comment by bwzhang2011** [comment]
@gurbuzali , any update with such issue ?

**Comment by pveentjer** [comment]
I'll have another look at it in 3.6.

**Pull request closed without merging**
