### PR TITLE
Fix typo in Python client protocol ID

### PR DESCRIPTION
**Pull request by cangencer**

### CODE REVIEW

**Comment by jerrinot** [comment]
:+1: 
why are the client ids important? is it for debugging? what's a difference from let's say python client and cpp client? they both use the same protocol, don't they?

**Comment by noctarius** [comment]
The more important question, what happens to clients that are thrid-party made?

**Comment by cangencer** [comment]
I believe they get marked as "Other", if they send some other 3 byte string. I don't think it serves any purpose other than some metric information. @sancar or @asimarslan , can you confirm?

**Comment by asimarslan** [comment]
This id is used for statistics in man. center etc.

**Comment by asimarslan** [comment]
:+1:

**Pull request merged**
