### PR TITLE
Size hash based collections

### PR DESCRIPTION
**Pull request by bokken**
The sizing portion of
https://github.com/hazelcast/hazelcast/pull/9446
split out on request of @jerrinot

### CODE REVIEW

**Comment by jerrinot** [comment]
run-lab-run

**Comment by jerrinot** [comment]
hi @bokken,

thanks for splitting this. There appears to be checkstyle issue. 
You can run checkstyle manually via `mvn clean install -Pcheckstyle -DskipTests`

Also it would help if you could remove the changes in import ordering - it makes the path unnecessary longer and harder to review. Cheers!

**Comment by tombujok** [comment]
@bokken `mvn clean verify -Pcheckstyle -DskipTests` is enough to run checkstyle (it's faster than install)

**Comment by bokken** [comment]
My attempts to re-order the imports appears to make git angry. It changes to dif basically the entire file, rather than the small set of actual changes.

**Comment by bokken** [comment]
@jerrinot There appear to be a thousands of checkstyle issues, with nearly all being unrelated to the changes I made. I am guessing some might be related to my changes, but I see no way to identify them. Am I missing something?

**Comment by jerrinot** [comment]
these are the checkstyle issues I can see:
```
[...]
[INFO] Deleting /home/jara/devel/oss/hazelcast/hazelcast/target
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:checkstyle (default) @ hazelcast ---
[INFO] Starting audit...
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferService.java:110:89: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/query/impl/SingleResultSet.java:51: Line has trailing spaces.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/query/impl/OrResultSet.java:58:62: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/query/impl/OrResultSet.java:58:90: '4' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/query/impl/DuplicateDetectingMultiResult.java:58: Line has trailing spaces.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/query/impl/FastMultiResultSet.java:54:56: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/query/impl/FastMultiResultSet.java:54:67: '8' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheProxyBase.java:226:79: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/collection/impl/collection/AbstractCollectionProxyImpl.java:131: Line is longer than 130 characters (found 142).
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/collection/impl/collection/CollectionService.java:125: Line is longer than 130 characters (found 154).
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceProxy.java:291: Line has trailing spaces.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceService.java:98:69: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/util/AddressUtil.java:285:29: Inner assignments should be avoided.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/ClientEngineImpl.java:0: File does not end with a newline.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java:374:56: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java:374:76: '4' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java:384:58: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java:384:78: '4' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java:394:52: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java:394:72: '4' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java:405:73: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java:405:93: '4' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/cardinality/impl/CardinalityEstimatorService.java:104:90: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/mapreduce/impl/task/JobSupervisor.java:499:88: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/mapreduce/impl/task/JobSupervisor.java:499:109: '4' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/security/permission/ActionConstants.java:70:5: Executable statement count is 21 (max allowed is 20).
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/multimap/impl/ObjectMultiMapProxy.java:171:72: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/multimap/impl/ObjectMultiMapProxy.java:171:89: '4' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapProxySupport.java:114:63: '16' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapProxySupport.java:114:84: '4' is a magic number.
/home/jara/devel/oss/hazelcast/hazelcast/src/main/java/com/hazelcast/map/impl/operation/MultipleEntryOperation.java:33:8: Unused import - java.util.HashSet.
Audit done.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[...]
```

Please try to fix the Git issues. It's a prerequisite to get the PR merged - we cannot afford to lose so much of a history. I'd recommend to send a smaller PR - no need to fix it everywhere at once. If that's fine then you can send a bigger PR.

**Comment by bokken** [comment]
Replaced with https://github.com/hazelcast/hazelcast/pull/9597, which has line ending and import order issues resolved. I apologize for the difficulties here.

**Pull request closed without merging**
