### PR TITLE
Attempt at adding GCE support for cluster joining configuration

### PR DESCRIPTION
**Pull request by pires**
Implemented jclouds-based mechanism for discovering potential nodes for a cluster.
Replaced AWS join configuration with aforementioned mechanism.
Implemented Google Compute Engine support, as well.
Refs #2312

### CODE REVIEW

**Comment by pires** [comment]
@sancar you bet it demotivated me. Actually, it's sad that they've closed something that would work but kept #2485 open, which no one seems to care about.

I'm still interested in having this merged - and add discovery support for [Kubernetes](http://kubernetes.io) as well, but I want to be sure it's not going to be closed once again just because.

**Comment by mesutcelik** [comment]
Hi @pires ,

I am going to take care of it. No worries...

More cloud support is definitely in our radar but it is a matter of planning... This is not in our 3.5 release roadmap to include JClouds support but we will check what we can do for 3.6

keep in touch :+1:

**Comment by pires** [comment]
@mesutcelik so just to be sure, I can forget about having this sorted and merged in favor of an in-house implementation?

**Comment by saturnism** [comment]
quick q on the status of this? it seems stale for a while..

**Comment by noctarius** [comment]
Hi @pires ,

We thought about how to handle cloud discovery. We just started an Hazelcast Incubator system. Since we want to make adding new cloud providers easier we want to have a clean SPI to integrate those. I added you to the new repo and I would love to see you help on the SPI design.

Sorry for closing this PR for now but I hope you understand the reasoning. Please do not yet delete the branch on your side, we will come back to the integration for the new SPI!

Chris

**Comment by pires** [comment]
Makes sense. It would probably be a good call to add @saturnism as well, since he implemented Kubernetes discovery.

Thanks

**Comment by noctarius** [comment]
I already did :) See twitter as well! :D

**Pull request closed without merging**
