### PR TITLE
Print exception in MulticastDiscoveryStrategyDeserializationTest

### PR DESCRIPTION
**Pull request by ramizdundar**
This PR prints exception properly if the test fails. The new failure
seems different from the older one. My guess is `joinGroup()` throws
`SocketException: Can't assign requested address` if there is an issue
with sockets availability. I would wrap this area and retry a few times,
but I wanted to be sure that the issue is there. I will mark that issue 
as `waiting-for-next-failure`.

Related https://github.com/hazelcast/hazelcast/issues/20823

### CODE REVIEW

**Review by arodionov — APPROVED** [review]

**Comment by ramizdundar** [comment]
Failed with a know issue, reported here: https://github.com/hazelcast/hazelcast/issues/22564#issuecomment-1319872018

**Comment by kwart** [comment]
This is the exception on AWS MacOS machines:

```
[ERROR] com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategyDeserializationTest.testSafeSerialization  Time elapsed: 0.958 s  <<< ERROR!
com.hazelcast.core.HazelcastException: java.net.SocketException: Can't assign requested address
	at com.hazelcast.internal.util.ExceptionUtil.lambda$static$0(ExceptionUtil.java:48)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:126)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:69)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:131)
	at com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy.initializeMulticastSocket(MulticastDiscoveryStrategy.java:106)
	at com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy.start(MulticastDiscoveryStrategy.java:112)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.start(DefaultDiscoveryService.java:64)
	at com.hazelcast.instance.impl.Node.start(Node.java:493)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:134)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:61)
	at com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategyDeserializationTest.testSafeSerialization(MulticastDiscoveryStrategyDeserializationTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Can't assign requested address
	at java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy.initializeMulticastSocket(MulticastDiscoveryStrategy.java:97)
	... 21 more
```

The solution for the issue is to ask for IPv4 stack explicitly: `-DextraVmArgs="-Djava.net.preferIPv4Stack=true"`

@olukas already reconfigured Jenkins jobs to use the system property.

We can still merge this PR so if some other problem occurs we have better position for the investigation.

**Review by kwart — APPROVED** [review]

**Comment by kwart** [comment]
run-lab-run

**Comment by ramizdundar** [comment]
run-lab-run

**Pull request merged**
