### PR TITLE
tiny refactoring

### PR DESCRIPTION
**Pull request by bilalyasar**

### CODE REVIEW

**Comment by bilalyasar** [comment]
verify

**Comment by bilalyasar** [comment]
verify

**Comment by bilalyasar** [comment]
run-parallel

**Comment by bilalyasar** [comment]
@mesutcelik @serkan-ozal it is green, if you OK, can we merge this PR?

**Comment by mesutcelik** [comment]
:+1:  I remember this was already discussed on some other PR

**Pull request merged**
