### PR TITLE
XA Transactions end/rollback fix

### LINKED ISSUE #5400: XAResource.end should not need to check for threadId
please see comment https://github.com/hazelcast/hazelcast/pull/5390#issuecomment-106075294

### LINKED ISSUE #5401: XAResource.rollback should not need the transaction to be in prepared state if called from another member/client
please see comment https://github.com/hazelcast/hazelcast/pull/5390#issuecomment-106268872

### PR DESCRIPTION
**Pull request by gurbuzali**
remove thread check while ending an xa transaction
removed rollback when 'end' method called with fail flag
fixed finalizing tranasctions remotely 
refactored some backup operations to get rid off an unnecessary serilailization

fixes #5400 
fixes #5401

### CODE REVIEW

**Comment by gurbuzali** [comment]
verify

**Comment by juanavelez** [comment]
Hi @gurbuzali. Thanks a lot for the fixes. 

I have been testing the latest HZ Code and I can see now that commits, rollbacks, timeouts all work fine. Nevertheless, I am seeing several warning messages after the transactions have finished. I don't know if these messages are a symptom of something worse

```
08:04:13,658 INFO  |  | [com.hazelcast.spi.OperationService] (hz._hzInstance_1_dev.InspectInvocationsThread) | [172.16.83.52]:5701 [dev] [3.6-SNAPSHOT] Handled 1 invocation timeouts and 0 backupTimeouts
08:04:13,658 WARNING |  | [com.hazelcast.spi.impl.operationservice.impl.Invocation] (cached1) | [172.16.83.52]:5701 [dev] [3.6-SNAPSHOT] Asking if operation execution has been started: com.hazelcast.spi.impl.operationservice.impl.IsStillRunningService$InvokeIsStillRunningOperationRunnable@3908dc6
08:04:13,660 WARNING |  | [com.hazelcast.spi.impl.operationservice.impl.Invocation] (hz._hzInstance_1_dev.async.thread-1) | [172.16.83.52]:5701 [dev] [3.6-SNAPSHOT] 'is-executing': false -> Invocation{ serviceName='hz:impl:xaService', op=com.hazelcast.transaction.impl.xa.ClearRemoteTransactionOperation{serviceName='null', partitionId=234, callId=10001, invocationTime=1433948533237, waitTimeout=-1, callTimeout=60000}, partitionId=234, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[172.16.83.52]:5701, backupsExpected=0, backupsCompleted=0}
08:04:15,667 INFO  |  | [com.hazelcast.spi.OperationService] (hz._hzInstance_1_dev.InspectInvocationsThread) | [172.16.83.52]:5701 [dev] [3.6-SNAPSHOT] Handled 1 invocation timeouts and 0 backupTimeouts
08:04:15,667 WARNING |  | [com.hazelcast.spi.impl.operationservice.impl.Invocation] (cached1) | [172.16.83.52]:5701 [dev] [3.6-SNAPSHOT] Asking if operation execution has been started: com.hazelcast.spi.impl.operationservice.impl.IsStillRunningService$InvokeIsStillRunningOperationRunnable@1ce9c13b
08:04:15,668 WARNING |  | [com.hazelcast.spi.impl.operationservice.impl.Invocation] (hz._hzInstance_1_dev.async.thread-2) | [172.16.83.52]:5701 [dev] [3.6-SNAPSHOT] 'is-executing': false -> Invocation{ serviceName='hz:impl:xaService', op=com.hazelcast.transaction.impl.xa.ClearRemoteTransactionOperation{serviceName='null', partitionId=25, callId=30003, invocationTime=1433948534694, waitTimeout=-1, callTimeout=60000}, partitionId=25, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[172.16.83.52]:5701, backupsExpected=0, backupsCompleted=0}
```
My execution environment is JBoss EAP 6.4.0 with the latest hazelcast code (3.6-SNAPSHOT)

This is my test class
```
////////////////////////////////////////////////////////////////////////////////
//
// %created_by: jvelez %
//  
// Copyright (c) 2000-2015 AccessLine Communications Corporation
// All rights reserved.  This file is proprietary and confidential.
//
////////////////////////////////////////////////////////////////////////////////
package com.acc.kr.service.app.hp.svc.v3;

import javax.annotation.Resource;
import javax.ejb.Stateless;
import javax.resource.ResourceException;
import javax.ejb.SessionContext;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.resource.cci.ConnectionFactory;

import org.apache.log4j.Logger;
import org.jboss.ejb3.annotation.TransactionTimeout;

import com.hazelcast.core.TransactionalMap;
import com.hazelcast.jca.HazelcastConnection;

@Stateless( name = "TestHazelcast", mappedName = "TestHazelcast" )
@TransactionAttribute( TransactionAttributeType.REQUIRES_NEW )
public class TestHazelcastImpl implements TestHazelcast
{
   private final static Logger LOG = Logger.getLogger( TestHazelcastImpl.class );

   @Resource(mappedName = "java:/HazelcastCF")
   protected ConnectionFactory connectionFactory;

   @Resource
   protected SessionContext context;

   @Override
   @TransactionTimeout( 15 )
   public void doTest( Long wait )
   {
      HazelcastConnection hzConn = null;
      try
      {
         hzConn = getConnection();
         TransactionalMap<Integer,String> txmap = hzConn.getTransactionalMap("txmap");
         for ( int i=0; i<10000; i++ )
         txmap.put( Integer.valueOf( i ), Integer.valueOf( i ).toString() );
         if ( wait != null )
         {
            try
            {
               Thread.sleep( wait );
            }
            catch ( InterruptedException e )
            {
               e.printStackTrace();
            }
         }
         
      }
      finally {
         closeConnection(hzConn);
      }
      
      try
      {
         context.getBusinessObject( TestHazelcast.class ).doTestDifferentTx( 4000L );
      }
      catch( Exception e )
      {
         LOG.warn( "Caught error while executing testHazelcast.doTestDifferentTx()" , e );
      }
   }

   @Override
   @TransactionAttribute( TransactionAttributeType.REQUIRES_NEW )
   @TransactionTimeout( 3 )
   public void doTestDifferentTx( Long wait )
   {
      HazelcastConnection hzConn = null;
      try
      {
         hzConn = getConnection();
         TransactionalMap<Integer,String> txmap = hzConn.getTransactionalMap("txmap");
         for ( int i=10000; i<20000; i++ )
         txmap.put( Integer.valueOf( i ), Integer.valueOf( i ).toString() );
         if ( wait != null )
            try
            {
               Thread.sleep( wait );
            }
            catch ( InterruptedException e )
            {
               e.printStackTrace();
            }
      }
      finally {
         closeConnection(hzConn);
      }
   }

   private HazelcastConnection getConnection()
   {
      try
      {
         return (HazelcastConnection) connectionFactory.getConnection();
      }
      catch ( ResourceException e )
      {
         throw new RuntimeException(
            "Error while getting Hazelcast connection" , e );
      }
   }

   private void closeConnection( HazelcastConnection hzConn )
   {
      if ( hzConn != null )
      {
         try
         {
            hzConn.close();
         }
         catch ( ResourceException e )
         {
            LOG.warn( "Error while closing Hazelcast connection." , e );
         }
      }
   }
}
```
Would you mind taking a look? Again thanks for the fixes.

Juan

**Comment by gurbuzali** [comment]
yes they are symptom of an issue but it should not affect the work of the transactions.
thank you again for your findings

**Comment by juanavelez** [comment]
@gurbuzali : Is there a date for the actual release of 3.5? A ball park figure is fine. Thanks for the great work!

**Comment by gurbuzali** [comment]
@juanavelez we are in the testing phase, it takes 2-3 days at best.

**Pull request merged**
