### PR TITLE
Extend reflective extractors with the possibility to return null for non existing properties

### PR DESCRIPTION
**Pull request by gierlachg**
To support polymorphic maps and to get similar behavior to how Portable & Json payloads treat non existing fields.

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1896/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1896/Hazelcast-pr-builder-1896.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TransactionQueueTest.testIssue859And863_WhenInQueueOnSecondInstance_OutQueueOnFirstInstance:379->testIssue859And863:412->HazelcastTestSupport.assertTrueEventually:1344->HazelcastTestSupport.assertTrueEventually:1242 expected:<3000> but was:<2999>
[INFO] 
[ERROR] Tests run: 31175, Failures: 1, Errors: 0, Skipped: 1000
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by gierlachg** [comment]
run-lab-run

**Review by taburet — APPROVED** [review]

**Comment by devozerov** [comment]
The code itself looks good to me. But what is the design rationale for this change? If we ignore missing fields for SQL, then we may create any DDL schema on top of any map, and it will just work, returning `null`-s for missing fields. 
1. Why do we think that it is better than throwing errors on missing fields?
1. Could you please provide a couple of use cases when the proposed behavior will be useful?

**Comment by gierlachg** [comment]
Reading non-existing fields for Portable or Json (if one uses HZ `JsonObject`) objects already yields `null`, having consistent behavior across different serialization formats feels to me like a good idea.

Specific use case I wanted to support is a polymorphic `IMap`; i.e. one having objects either of `Person(String name)` or `Employee(String name, int id)`. I know IMDG does not (want to) support such use cases but in Jet it might be a thing.

**Comment by devozerov** [comment]
Do we have specific cases in mind or known user requests that make this behavior desirable? Users often benefit from early error reporting. This change will hide a lot of errors from users when DML/DDL is introduced, and I am not sure why we should do that always. Some users will benefit from this flexibility, others will suffer. Can we make this behavior optional?

Regarding consistency with JSON/Portable - here we deal not with the desired behavior, but with peculiarities of specific formats. JSON is schemaless, so any question around field existence doesn't make much sense here. Portable have a schema, and it could be used to throw exceptions similarly to object format. AFAIK future serialization engine will also have a schema.

Therefore, ignoring schema issues by default in the product where most formats indeed have schemas, doesn't seem a good option to me.

**Comment by gierlachg** [comment]
By no means table schema is ignored here. Schema is not even a thing on this level. Imagine `CREATE EXTERNAL TABLE map (name VARCHAR)`. Obviously, it does not mean that you can suddenly `SELECT id FROM map` - the query will be rejected way before we reach this code - but if you declare `id` in the table schema and you happen to have polymorphic map, returning `null` for `Person` feels to me better than throwing an error, otherwise the map is pretty much unusable.

**Comment by viliam-durina** [comment]
Case in point: even if we have DDL, one will not be required to use it. If he does, he will not be required to specify columns. Only when he does the above situation can happen.

**Comment by devozerov** [comment]
@gierlachg @viliam-durina I got your points, thank you.

**Review by devozerov — APPROVED** [review]

**Pull request merged**
