### PR TITLE
ObjectDataInputStream and ObjectDataOutputStream unit tests

### PR DESCRIPTION
**Pull request by asimarslan**
unit tests and some minor fixes

### CODE REVIEW

**Comment by pveentjer** [comment]
:+1:

**Comment by pveentjer** [comment]
There are some test failures:

```
	Test Result (11 failures / +10)

    com.hazelcast.internal.serialization.impl.ObjectDataInputStreamTest.testReadUnsignedShort
    com.hazelcast.internal.serialization.impl.ObjectDataInputStreamTest.testReadByte
    com.hazelcast.internal.serialization.impl.ObjectDataInputStreamTest.testReadBoolean
    com.hazelcast.internal.serialization.impl.ObjectDataInputStreamTest.testReadB
    com.hazelcast.internal.serialization.impl.ObjectDataInputStreamTest.testReadUnsignedByte
    com.hazelcast.internal.serialization.impl.ObjectDataInputStreamTest.testRead
    com.hazelcast.internal.serialization.impl.ObjectDataInputStreamTest.testReadLine
    com.hazelcast.internal.serialization.impl.ObjectDataInputStreamTest.testSkipBytes
    com.hazelcast.internal.serialization.impl.ObjectDataInputStreamTest.testReadForBOffLen
    com.hazelcast.internal.serialization.impl.ObjectDataInputStreamTest.testReadFullyB
```

**Comment by asimarslan** [comment]
Mockito cannot mock final methods, I should find some other solution :(

**Comment by cangencer** [comment]
@asimarslan you can try [Powermock](https://code.google.com/p/powermock/) maybe?

**Comment by cangencer** [comment]
Also what is the purpose of ObjectDataInputStream and ObjectDataOutputStream?  They don't seem to be used outside some simple tests. Maybe they should be moved to test code?

**Comment by asimarslan** [comment]
Hot restart need these so we cannot remove

**Comment by asimarslan** [comment]
run-lab-run

**Comment by asimarslan** [comment]
run-lab-run

**Pull request merged**
