### PR TITLE
Fix metric units (#16796)

### PR DESCRIPTION
**Pull request by zalintyre**
Feel free to leave feedback :)

### CODE REVIEW

**Comment by zalintyre** [comment]
Hello,

can I further assist you with this pull request?

Kind regards
Franz

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Hi @zalintyre ! Thank you for the PR and sorry for the long delay, last two weeks were a bit busy here. I've assigned reviewers and we'll take a look soon. Feel free to ping us here or on community slack if we're unresponsive.

**Comment by zalintyre** [comment]
Hello @mmedenjak ,

sure, no problem :smile: It would be nice if you added the hacktoberfest-accepted label if you are happy with the PR :)

Kind regards
Franz

**Comment by mmedenjak** [comment]
I wasn't aware of the need for that label. Added :)

**Review by blazember — COMMENTED** [review]
@zalintyre thanks for the PR :+1: The change looks good to me, but we need to remove the `.editorconfig` before merging. Could you please do this?

**Comment by zalintyre** [comment]
Hello,

to avoid misunderstandings: The editorconfig is not my personal IDE configuration, it's meant to be understood by a variety of IDEs. I tried to adapt the code style of the hazelcast project, so that new contributors with different IDEs won't mess up the formatting. See the documentation here: https://editorconfig.org/

But if you want, I can remove it, no problem.

Kind regards

**Comment by mmedenjak** [comment]
Hi @zalintyre , yes, please remove the file. @blazember other than that, are there any other necessary changes?

**Comment by blazember** [comment]
Nope, the PR is otherwise good as is.

**Comment by zalintyre** [comment]
Done :)

**Comment by mmedenjak** [comment]
run-lab-run

**Review by blazember — APPROVED** [review]

**Review by mmedenjak — APPROVED** [review]
Feel free to merge if it's backwards compatible.

**Comment by blazember** [comment]
Thanks for the fix @zalintyre :+1:

**Pull request merged**
