### PR TITLE
Fixes 2 invocation future bugs

### LINKED ISSUE #5001: Bug: InvocationFuture.andThen doesn't deal with null response correctly

### PR DESCRIPTION
**Pull request by pveentjer**
Fixes
#5001 
#5002

### CODE REVIEW

**Comment by gurbuzali** [comment]
:+1:

**Comment by jerrinot** [comment]
we should backport this into 3.4.x branch as it makes async API hardly usable.

**Comment by gurbuzali** [comment]
isn't this(https://github.com/hazelcast/hazelcast/pull/5136) the back-port ?

**Comment by jerrinot** [comment]
oh, I missed it was a backport!

**Comment by jerrinot** [comment]
some Simulator tests now leverage async API for a fast initial data load. 
It's failing with v3.4.2 and I can confirm it's running just fine with https://github.com/hazelcast/hazelcast/commit/13a14f3092ea0f0b02b0f5abd157a1f837e10285
:clap:

**Pull request merged**
