### PR TITLE
Add method to easily identify when all replicas of a partition have been lost

### PR DESCRIPTION
**Pull request by acl-oss**
Currently the client is required to check that `PartitionLostEvent.getLostBackupCount() == InternalPartition.MAX_BACKUP_COUNT` which is non-obvious, awkward and leaks implementation details.

### CODE REVIEW

**Comment by acl-oss** [comment]
Do we need to sign the contributors agreement before this change will be considered?

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Holmistr** [comment]
Hi @acl-oss ,

could you please sign the contributor agreement? We really appreciate your effort, so we would like to move on this PR.

**Comment by acl-oss** [comment]
Thanks for your message and apologies for the delay. We have signed this and sent it back to Jaromir.

It looks like we’re still not listed on https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement , perhaps because we asked about a counter signed copy – but I believe this could be progressed now.

Thanks,
Mark

Mark Haslehurst

Aspect Capital Limited
10 Portman Square | London W1H 6AZ
Tel: +44 20 7170 9700 
mark.haslehurst@aspectcapital.com
http://www.aspectcapital.com

This email and any attachments contain CONFIDENTIAL information which may be legally privileged. If this communication constitutes a financial promotion, it is directed only at persons who are professional clients or eligible counterparties (as per UK Financial Conduct Authority rules). The information is provided on a non-reliance basis; and no representation or warranty is made as to its accuracy or completeness. This email is neither an offer to sell nor a solicitation of any offer to buy an interest in any fund or other investment vehicle sponsored or managed by Aspect Capital Limited. Past performance is not necessarily indicative of future returns. Emails are not secure and are not warranted by Aspect to be free of errors, viruses or other defects which may affect a computer system. Aspect Capital Limited (or its service providers) may monitor, review and retain e-communications. By messaging with Aspect Capital Limited you consent to the foregoing. Aspect Capital Limited is authorised and regulated by the Financial Conduct Authority. Registered in England No. 3491169. Registered office: 10 Portman Square, London W1H 6AZ. ASPECT, ASPECT CAPITAL, the ASPECT CAPITAL device and ASPECT CAPITAL: THE SCIENCE OF INVESTMENT are registered trademarks of Aspect Capital Limited. © Aspect Capital Limited 2018. All rights reserved. For more information, go to http://www.aspectcapital.com.

**Comment by Holmistr** [comment]
@jerrinot Can you please confirm?

**Comment by mmedenjak** [comment]
@jerrinot can you check if you have received the signed agreement?

**Comment by Holmistr** [comment]
@mmedenjak Any plans for this PR?

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
@acl-oss apologies for the long delay. We would like to merge this PR in time for Hazelcast 4.0 but there are some compilation issues. Can you address these? Alternatively, I can take over the changes in this PR and fix it in another PR.

**Comment by acl-oss** [comment]
Thanks for not giving up :)
Update pushed.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
All checks have passed, we have a launch! Thank you for the quick response and looking forward to the next PR :)

**Pull request merged**
