### PR TITLE
Remove duplicate methods between `ExceptionUtil` in `com.hazelcast.jet.impl.util` & `com.hazelcast.internal.util`

### PR DESCRIPTION
**Pull request by JackPGreen**
Both classes identically implement the following methods:
- `withTryCatch(ILogger, BiConsumer<T, ? super Throwable>)` 
- `withTryCatch(ILogger, String, BiConsumer<T, ? super Throwable>)`
- `sneakyThrow(Throwable)`

Removed these from `com.hazelcast.jet.impl.util` and updated any reference to suit.

Refactored `com.hazelcast.jet.impl.util.rethrow(Throwable)` to share some logic with the `com.hazelcast.internal.util` equivalent as the behaviour isn't identical

Ensured the `com.hazelcast.jet.impl.util.ExceptionUtil.stackTraceToString(Throwable)` is used consistently across the codebase.

EE PR: [#6403](https://github.com/hazelcast/hazelcast-enterprise/pull/6403)

### CODE REVIEW

**Comment by JackPGreen** [comment]
run-lab-run

**Comment by JackPGreen** [comment]
run-lab-run

**Comment by JackPGreen** [comment]
run-with-ee

**Review by frant-hartm — APPROVED** [review]

**Comment by TomaszGaweda** [comment]
is it possible to merge those two classes into one? Core functionality and intended use is the same

**Comment by JackPGreen** [comment]
> is it possible to merge those two classes into one? Core functionality and intended use is the same

Yes, absolutely. But I thought incremental refactoring would be less invasive.

**Review by TomaszGaweda — APPROVED** [review]

**Pull request merged**
