### PR TITLE
Avoid duplicate connection creation in MockServer

### PR DESCRIPTION
**Pull request by ufukyilmaz**
This PR resolves a duplicate connection creation issue caused by not
double checking for the existence of connection. I noticed that behavior
while checking the logs of this failing test: https://github.com/hazelcast/hazelcast/issues/20553#issuecomment-1027635789 (this test is failing for some other reason). See the logs:

```
01:05:54,225  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockServer] hz.pensive_swartz.generic-operation.thread-1 - [127.0.0.1]:5704 [dev] [5.1-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-8ee4ed3e-79f0-4703-bcc3-4bfef5bd8e26, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5704, uuid=0f815c5d-7841-400f-9a48-19cf7ddeeb4f], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=8ee4ed3e-79f0-4703-bcc3-4bfef5bd8e26], alive=true}
01:05:54,225  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockServer] hz.pensive_swartz.generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.1-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-8ee4ed3e-79f0-4703-bcc3-4bfef5bd8e26, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5704, uuid=0f815c5d-7841-400f-9a48-19cf7ddeeb4f], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=8ee4ed3e-79f0-4703-bcc3-4bfef5bd8e26], alive=true}
```

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

**Comment by ufukyilmaz** [comment]
run-with-ee

**Comment by ufukyilmaz** [comment]
run-lab-run

**Comment by ufukyilmaz** [comment]
run-ee-tests

**Comment by ufukyilmaz** [comment]
run-ee-tests

**Review by ramizdundar — APPROVED** [review]

**Review by vbekiaris — APPROVED** [review]

**Pull request merged**
