### PR TITLE
Moved address to com.hz.cluster

### PR DESCRIPTION
**Pull request by pveentjer**
The nio package is very dirty. Mix of API and internals. And Address
doesn't belong there at all.

### CODE REVIEW

**Comment by pveentjer** [comment]
This PR causes problem with the client code generator.

**Comment by sancar** [comment]
@pveentjer Now you can rebase and make it compile. Client code generator will no longer cause a compile problem. We only need to merge https://github.com/hazelcast/hazelcast-client-protocol/pull/211 
when this pr is ready to keep them consistent.

**Comment by sancar** [comment]
@pveentjer Closing this because I will handle it here
https://github.com/hazelcast/hazelcast/pull/15666

**Comment by sancar** [comment]
Closing it. I will handle it here https://github.com/hazelcast/hazelcast/pull/15666

**Pull request closed without merging**
