### PR TITLE
Upgrade checkstyle to 10.12.1

### PR DESCRIPTION
**Pull request by JackPGreen**
Extension of #24919 with code changes actioned:

- `JavadocMethod` checkstyle configuration updated to use [new access modifier syntax](https://github.com/checkstyle/checkstyle/issues/7417)
- Replace `String ...vargs` with `String... vargs`
- Update to 10.12.1

This is *not* the latest version (10.12.2), it's one behind.
The latest version is in #25128.
The latest version [now identifies inner classes that could/should be final](https://github.com/checkstyle/checkstyle/issues/11338), and as such a lot of classes need to change.
It's probably easier to do all of those separately.

### CODE REVIEW

**Comment by JackPGreen** [comment]
[PR builder is using Java 8 for non-`master` branches](https://hazelcast.slack.com/archives/C0356BG4R/p1692364336607169), target branch modified.

**Review by JamesHazelcast — APPROVED** [review]
Thanks for handling this Jack, LGTM 👍

**Comment by JackPGreen** [comment]
run-lab-run

**Review by vbekiaris — APPROVED** [review]
👍

**Pull request merged**
