### PR TITLE
Remove references to a no-longer-existing InstanceListener interface

### PR DESCRIPTION
**Pull request by pivovarit**
https://docs.hazelcast.org/docs/2.6/javadoc/com/hazelcast/core/InstanceListener.html is no longer present since 3.X, no need to keep it in the examples

### CODE REVIEW

**Comment by vojtechtoman** [comment]
Btw, this may need removing as well in `hazelcast-reference-manual`:
```
src/docs/asciidoc/understanding_configuration.adoc:387:        <listener>com.hazelcast.examples.InstanceListener</listener>
src/docs/asciidoc/understanding_configuration.adoc:403:    - com.hazelcast.examples.InstanceListener
```

**Comment by pivovarit** [comment]
Actually, I figured out that there's some mess around listeners (especially on the client's side) - so I will be hunting these bugs soon as well. Thanks for hints!

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by kwart** [comment]
@pivovarit, It seems, there will be also test update needed. These 2 failed on PR builder:
```
com.hazelcast.client.config.XmlClientConfigBuilderTest.testLeftovers
com.hazelcast.client.config.YamlClientConfigBuilderTest.testLeftovers
```

**Comment by pivovarit** [comment]
I know, working on it now :)

**Pull request merged**
