### PR TITLE
Remove elasticsearch-5 module [HZ-819]

### PR DESCRIPTION
**Pull request by frant-hartm**
Due to Elastic 5 end of life and vulnerabilities identified in #19571 we
are removing and no longer supporting this module.

Breaking changes (list specific methods/types/messages):
* Elastic 5 connector is no longer available

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set

### CODE REVIEW

**Comment by frant-hartm** [comment]
run-lab-run

**Review by ldziedziul — CHANGES_REQUESTED** [review]
Could you remove references to the `elasticsearch-5` module from `docs/jet/api/sources-sinks.md`

**Comment by frant-hartm** [comment]
@ldziedziul See https://github.com/hazelcast/hazelcast/pull/20503

**Review by ldziedziul — APPROVED** [review]

**Comment by frant-hartm** [comment]
run-lab-run

**Pull request merged**
