### PR TITLE
Merge ClientExceptions and ClientExceptionFactory

### PR DESCRIPTION
**Pull request by sancar**
These two classes where seperate because we had client and core
modules before.
Having them seperate causes bugs as one can register an exception
in one and forget in the other class. These two are merged to
prevent such bugs.

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2629/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2629/Hazelcast-pr-builder-2629.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 36 errors reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:212:1: Class Data Abstraction Coupling is 75 (max allowed is 15) classes [AccessControlException, AddressUtil.InvalidAddressException, ArrayStoreException, AssertionError, AuthenticationException, CPGroupDestroyedException, CacheNotExistsException, CallerNotMemberException, CancellationException, CannotReplicateException, ClassCastException, ConcurrentModificationException, ConfigMismatchException, ConsistencyLostException, DistributedObjectDestroyedException, DuplicateTaskException, EOFException, ErrorHolder, HazelcastException, HazelcastInstanceNotActiveException, HazelcastOverloadException, IllegalAccessError, IllegalAccessException, IllegalMonitorStateException, IllegalThreadStateException, InterruptedException, LeaderDemotedException, LocalMemberResetException, LockAcquireLimitReachedException, LockOwnershipLostException, LoginException, MaxMessageSizeExceeded, MemberLeftException, MutationDisallowedException, NegativeArraySizeException, NoClassDefFoundError, NoDataMemberInClusterException, NoSuchElementException, NoSuchFieldError, NoSuchFieldException, NoSuchMethodError, NoSuchMethodException, NodeIdOutOfRangeException, NotLeaderException, NotSerializableException, OperationTimeoutException, OutOfMemoryError, PartitionMigratingException, QueryResultSizeExceededException, ReachedMaxSizeException, ReplicatedMapCantBeCreatedOnLiteMemberException, ResponseAlreadySentException, ServiceNotFoundException, SocketException, SplitBrainProtectionException, StackOverflowError, StackTraceElement, StaleAppendRequestException, StaleSequenceException, StaleTaskException, StaleTaskIdException, TargetDisconnectedException, TargetNotMemberException, TargetNotReplicaException, TimeoutException, TopicOverloadException, TransactionNotActiveException, URISyntaxException, UTFDataFormatException, UndefinedErrorCodeException, UnsupportedCallbackException, VersionMismatchException, WanQueueFullException, WrongTargetException, XAException]. [ClassDataAbstractionCoupling]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:212:1: Class Fan-Out Complexity is 80 (max allowed is 40). [ClassFanOutComplexity]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:222:5: Executable statement count is 101 (max allowed is 20). [ExecutableStatementCount]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:222:5: Method length is 105 lines (max allowed is 60). [MethodLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:231: Line is longer than 130 characters (found 147). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:239: Line is longer than 130 characters (found 147). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:241: Line is longer than 130 characters (found 160). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:245: Line is longer than 130 characters (found 161). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:246: Line is longer than 130 characters (found 132). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:252: Line is longer than 130 characters (found 139). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:254: Line is longer than 130 characters (found 136). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:255: Line is longer than 130 characters (found 131). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:257: Line is longer than 130 characters (found 154). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:260: Line is longer than 130 characters (found 133). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:265: Line is longer than 130 characters (found 135). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:267: Line is longer than 130 characters (found 152). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:268: Line is longer than 130 characters (found 142). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:271: Line is longer than 130 characters (found 139). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:278: Line is longer than 130 characters (found 135). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:283: Line is longer than 130 characters (found 142). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:292: Line is longer than 130 characters (found 144). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:293: Line is longer than 130 characters (found 136). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:294: Line is longer than 130 characters (found 186). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:295: Line is longer than 130 characters (found 131). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:306: Line is longer than 130 characters (found 135). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:307: Line is longer than 130 characters (found 151). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:308: Line is longer than 130 characters (found 140). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:309: Line is longer than 130 characters (found 145). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:310: Line is longer than 130 characters (found 136). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:313: Line is longer than 130 characters (found 162). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:314: Line is longer than 130 characters (found 143). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:315: Line is longer than 130 characters (found 133). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:316: Line is longer than 130 characters (found 133). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:317: Line is longer than 130 characters (found 133). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:318: Line is longer than 130 characters (found 143). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java:320: Line is longer than 130 characters (found 138). [LineLength]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2634/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2634/Hazelcast-pr-builder-2634.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   UnsafeFencedLockMigrationTest.whenLockIsBlocked_thenBackupIsReplicated:138 ? IllegalArgument
[INFO] 
[ERROR] Tests run: 32002, Failures: 0, Errors: 1, Skipped: 979
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by sancar** [comment]
run-lab-run

**Review by puzpuzpuz — APPROVED** [review]

**Review by ihsandemir — APPROVED** [review]
Are we planning to add a test that will check if all codes at ClientProtocolErrorCodes are actually registered?

[Update] After the merge of two exception factories we seem not to need this test.

**Pull request merged**
