### PR TITLE
Cleanup Preconditions/ValidationUtil

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
There was quite a bit of duplicate code in `Preconditions` and `ValidationUtil`. This PR cleans that up.

### CODE REVIEW

**Comment by pveentjer** [comment]
Thanks! 

Can you sign our contributor agreement?

https://hazelcast.atlassian.net/wiki/download/attachments/6357071/Hazelcast%2C%20Inc.%20Individual%20Contrbutor%20License%20Agreement%20v100113.pdf?version=2&modificationDate=1394826512258&api=v2

**Comment by pveentjer** [comment]
@nezihyigitbasi ping!

**Comment by nezihyigitbasi** [comment]
@pveentjer sorry about the delay, just sent the signed contrib. form to @enesakar, we should be good to go. Let me know in the mean time if you have any comments.

**Comment by nezihyigitbasi** [comment]
@pveentjer any comments?

**Comment by pveentjer** [comment]
Thanks for the cleanup!

**Pull request merged**
