### PR TITLE
Adds options for per-socket keep-alive configuration [HZ-1672]

### PR DESCRIPTION
**Pull request by vbekiaris**
Add socket options for per-socket keep-alive configuration.

For OpenJDK-based distros, support for per-socket keep alive configuration is available:
- Since JDK 8u272 on linux & macos
- Since JDK 11

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [x] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

**Comment by vbekiaris** [comment]
run-with-ibm-jdk-8

**Comment by vbekiaris** [comment]
run-windows

**Review by ramizdundar — COMMENTED** [review]
Can you add fullexample configs?

**Comment by vbekiaris** [comment]
> Can you add fullexample configs?

https://github.com/hazelcast/hazelcast/pull/23816/commits/e4a82ebb95aa36f48d2e31e7c294f0ce2d0dba37

**Review by kwart — COMMENTED** [review]
Looks good, I would just suggest small cleanup in the Spring parser.

**Comment by vbekiaris** [comment]
run-windows

**Comment by vbekiaris** [comment]
run-windows

**Comment by vbekiaris** [comment]
run-with-ibm-jdk-8

**Review by ramizdundar — APPROVED** [review]

**Comment by vbekiaris** [comment]
run-windows

**Comment by vbekiaris** [comment]
created #23834 for issues with running tpc-engine tests under IBM JDK 8.

**Comment by vbekiaris** [comment]
windows build is now failing with same issues as reported in https://github.com/hazelcast/hazelcast/issues/23834

**Comment by Patras3** [comment]
run-windows

**Pull request merged**
