### PR TITLE
Simplify HazelcastConnector_RestartTest by removing the MigrationBlockingService

### PR DESCRIPTION
**Pull request by gurbuzali**
[Previous fix attempt ](https://github.com/hazelcast/hazelcast/pull/18524) didn't work because even if we filter out the sink partition from migration blocking service, the blocked partition and the sink partition can share the same partition operation thread.

I've simplified the test so that we don't need a migration blocking service.  I've also removed the additional logging to trace the issue.

Fixes https://github.com/hazelcast/hazelcast/issues/18469

Checklist:
- [x] Labels and Milestone set

### CODE REVIEW

**Comment by viliam-durina** [comment]
The test was introduced as a part to this PR: hazelcast/hazelcast-jet#907. The PR fixed this issue:
>We ignored the HazelcastInstanceNotActiveException in
HazelcastWriters, if the object written to was local. We relied that
the job will restart anyway and writing will work after that. But if the
job completed after such failure, but before a restart, the writing
error was silently ignored.

I don't understand how the test tested this before. I suspect that it would succeed even before that PR. To test that issue, it would have to make sure that the processor completes just after it ignored some failed writes to the IList, but before the execution is terminated. And that's not the case - the `MigrationBlockingService` prevented migration, but didn't prevent the execution from terminating. Even then it doesn't assert the output to check that no item is missing.

So I'm for either removing this confusing test completely, or for replacing it with a stress test that will use a fault-tolerant source and restart many times and assert that no item is missing, there's `SinkStressTestUtil` with which it should be just a couple lines. It will not test the issue fixed by the PR#907, but will be useful to test the IList's guarantee.

**Comment by frant-hartm** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by gurbuzali** [comment]
I've created an issue for stress-test IList connector
https://github.com/hazelcast/hazelcast/issues/18546

I say let's merge this as is to keep the builds clean for now

**Comment by mmedenjak** [comment]
@viliam-durina @frant-hartm can you complete the review?

**Review by viliam-durina — APPROVED** [review]

**Review by frant-hartm — APPROVED** [review]

**Comment by mmedenjak** [comment]
Thank you, all!

**Pull request merged**
