### PR TITLE
Fix 4497 on master

### LINKED ISSUE #4497: IMap.getLocalMapStats() not thread safe and returns wrong values of some properties
If more then one threads invoke getLocalMapStats() on the same IMap, then we have a concurrent modification of some fields of one instance of LocalMapStatsImpl object.

call sequence pseudo code is:

```java
IMapProxyImpl(MapProxySupport).getLocalMapStats();
LocalMapStatsProvider.createLocalMapStats(String mapName) {

    final LocalMapStatsImpl localMapStats = getLocalMapStatsImpl(mapName) {
        return ConcurrencyUtil.getOrPutIfAbsent(statsMap, name, constructorFunction);
    }

    localMapStats.init() {
        ownedEntryCount = 0;
        backupEntryCount = 0;
        ownedEntryMemoryCost = 0;
        backupEntryMemoryCost = 0;
        heapCost = 0;
        lockedEntryCount = 0;
        dirtyEntryCount = 0;
        backupCount = 0;
        hits = 0;
    }    

    addOwnerPartitionStats(localMapStats, mapName, partitionId) {
        localMapStats.incrementOwnedEntryMemoryCost(ownedEntryMemoryCost);
        localMapStats.incrementLockedEntryCount(lockedEntryCount);
        localMapStats.incrementHits(hits);
        localMapStats.incrementDirtyEntryCount(recordStore.getMapDataStore().notFinishedOperationsCount());
        localMapStats.incrementHeapCost(recordStore.getHeapCost());
        localMapStats.incrementOwnedEntryCount(recordStore.size());
    }
}
```

### PR DESCRIPTION
**Pull request by metanet**
Fixes #4497

### CODE REVIEW

**Comment by metanet** [comment]
This one makes PR #4691 obsolete

**Comment by metanet** [comment]
verify

**Comment by gurbuzali** [comment]
verify

**Comment by gurbuzali** [comment]
verify

**Comment by mtopolnik** [comment]
:+1:

**Comment by jerrinot** [comment]
:+1:

**Pull request merged**
