### PR TITLE
Removed unnecessary method getMapEntry from RecordStore

### PR DESCRIPTION
**Pull request by ahmetmircik**
- It is duplicate of `RecordStore#get` method.
- It is creating unnecessary Map.Entry in order to get value of entry.

### CODE REVIEW

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
verify

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by gurbuzali** [comment]
:+1:

**Comment by eminn** [comment]
:+1:

**Pull request merged**
