### PR TITLE
Enable animal-sniffer for test classes too

### PR DESCRIPTION
**Pull request by kwart**
Fixes the animal sniffer plugin execution - to be used also for test classes.
Adds the `MethodHandle` class to ignores due to mojohaus/animal-sniffer#67.

### CODE REVIEW

**Comment by Holmistr** [comment]
@kwart Shouldn't it be enabled for both `compile` and `test-compile`?

**Comment by kwart** [comment]
> @kwart Shouldn't it be enabled for both `compile` and `test-compile`?

Nope, we don't want to double the execution - we want to execute the plugin just once. It should be a point where both - main classes and test classes are compiled.
These are the lifecycle phases for the `jar` packaging:
```
process-resources
compile
process-test-resources
test-compile
test
package
install
deploy
```

The `test-compile` looks as the best fit to me.

**Comment by Holmistr** [comment]
But my point is that this will compile test code only, won't it? Therefore it will find out issues only in the test classes, not the actually production code.
From the Maven lifecycle documentation (https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html):
```
test-compile | compile the test source code into the test destination directory
```

**Comment by kwart** [comment]
When you do the `mvn test`  or `mvn package` or `mvn install` then all the preceding phases are also used. So you won't end up in a state where main sources are not compiled and test sources are compiled.

**Comment by Holmistr** [comment]
There was a confusion on my end. According to @kwart 's explanation, the Animal Sniffer plugin will check all the compiled classes, therefore both production and test classes.
However, if the Animal Sniffer plugin is configured for `compile` phase, the test classes are not yet compiled, therefore not checked. 
Therefore, this PR is a valid fix. Thanks @kwart !

**Comment by Holmistr** [comment]
Merging with only one review as it's quite trivial (after somebody explains it to you :) ).

**Pull request merged**
