### PR TITLE
SingleNodeTest.cancelWhileQueued is fixed

### PR DESCRIPTION
**Pull request by muratayan**
This pull request resolves the test failure issue #4915. For this test' we have an `ExecutorService` with only one thread; we are first submitting a sleep task to it, so the second task we submit consecutively is queued. However, problem was, sometimes, by the time the second task can be submitted, first task finishes. Thus, while we ask for a `CancellationException`, we get an `AssertionError` because the task we expect to be queued is already finished as well.

There is one thing to be considered in my solution, when we repeat the test more than 100 times with `@Repeat()` annotation, `ExecutorService` starts to return `CompletedFuture`  instances, so the test definitely fails. Maybe we could use the submit function with true `preventSync` variable.

### CODE REVIEW

**Comment by bilalyasar** [comment]
Can one of the admins verify this patch?

**Comment by ahmetmircik** [comment]
Seems mergeable to me.

**Comment by mesutcelik** [comment]
verify

**Comment by muratayan** [comment]
@bilalyasar can you verify please?

**Comment by bilalyasar** [comment]
verify

**Pull request merged**
