### PR TITLE
Apply consistency fixes to replicated map

### LINKED ISSUE #6672: ReplicatedMapLoadingTest.testSyncFillup
```
java.lang.AssertionError: expected:<3000> but was:<2999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.replicatedmap.ReplicatedMapLoadingTest.testSyncFillup(ReplicatedMapLoadingTest.java:109)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/717/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapLoadingTest/testSyncFillup/

### LINKED ISSUE #7488: ReplicatedMapLoadingTest.testAsyncFillUp
```
java.lang.AssertionError: map2 should contain 3000 elements expected:<3000> but was:<2999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.replicatedmap.ReplicatedMapLoadingTest.assertMapSize(ReplicatedMapLoadingTest.java:113)
	at com.hazelcast.replicatedmap.ReplicatedMapLoadingTest.access$000(ReplicatedMapLoadingTest.java:37)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/708/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapLoadingTest/testAsyncFillUp/

### LINKED ISSUE #8232: [ZING-JVM] ReplicatedMapMergePolicyTest.testHigherHitsMapMergePolicy
```
org.junit.ComparisonFailure: expected:<[higherHitsV]alue2> but was:<[v]alue2>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.replicatedmap.ReplicatedMapMergePolicyTest.testHigherHitsMapMergePolicy(ReplicatedMapMergePolicyTest.java:136)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/13/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapMergePolicyTest/testHigherHitsMapMergePolicy/

### LINKED ISSUE #8510: ReplicatedMapTest Timeout
```
06:03:15 Running com.hazelcast.replicatedmap.ReplicatedMapTest
08:43:51 Build timed out (after 240 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/969/console

### PR DESCRIPTION
**Pull request by metanet**
* Lets say we have two updates: [ {key1=value1, partitionVersion=1}, {key2=value2, partitionVersion=2} ]. Once they hit the partition owner, they will be replicated to the other nodes. If they are replicated in reverse order, other nodes will ignore {key1=value1, partitionVersion=1} since it has a stale version number as key2 is already applied to the partition. In this case, partition owner contains key1, key2, partitionVersion=2, and other nodes may contain key2, partitionVersion=2 (key1 is missing). In this case, anti-entropy will not converge the replicas since it will see the same version number on owner and replicas. We introduce a "stale" flag to overcome this issue. If an update is missed, stale flag is updated. When anti-entropy is triggered, it also checks the stale flag along with the version numbers.
* Versions are never incremented in non-owner replicas. They are only updated with the versions received via the replications sent from the partition owner.
* WatchedExecutor is deleted and related replicated map tests are simplified.
* Fix setting ClockImpl as system parameter. Referencing to system parameter name is moved to another class to prevent class loading of ClockImpl with default implementation.
* Use non-volatile flag and version variables in InternalReplicatedMapStorage since they are only accessed via partition threads
* Move only partition owner data for migrating replicated maps as there is no notion of backups for replicated maps

Fixes #6672 
Fixes #7488 
Fixes #8232 
Fixes #8510

### CODE REVIEW

**Comment by metanet** [comment]
run-lab-run

**Comment by metanet** [comment]
run-lab-run

**Comment by mdogan** [comment]
run-lab-run

**Comment by metanet** [comment]
unrelated failure on client listeners.

**Comment by metanet** [comment]
run-lab-run

**Comment by jerrinot** [comment]
:+1: good improvements and very good reasoning!

**Comment by mdogan** [comment]
👍

**Pull request merged**
