### PR TITLE
[hazelcast-spring]local schema fetch support in case of https url usage

### LINKED ISSUE #8578: Something wrong with the schema link -  https://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd
Hi,
I am getting the following error for the schema link - 
https://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd

As a result I am not able to start my application in spring. The spring framework Root Context is breaking during tomcat server start up. I think this is due to the SSL Certificate Problem. Anyone help me on this regard?

### PR DESCRIPTION
**Pull request by mesutcelik**
* added local resolution support for https urls defined in xsi:schemaLocation
* added hazelcast-all to default module list

fixes #8578

### CODE REVIEW

**Comment by jerrinot** [comment]
:+1: on green

**Comment by mesutcelik** [comment]
Does anyone know what does `PlaceHolder` do? Apparently, nothing...
https://github.com/hazelcast/hazelcast/blob/master/hazelcast-all/src/main/java/com/hazelcast/PlaceHolder.java

I don't see any reference in the codebase. Are we safe to remove it?

**Comment by jerrinot** [comment]
@mesutcelik: If think you need at least 1 Java file. Otherwise Maven will not create the JAR.

**Comment by mesutcelik** [comment]
I just deleted whole package and see the uber-jar created.

**Comment by jerrinot** [comment]
@mesutcelik: are you sending a backport?

**Comment by mesutcelik** [comment]
here it is @jerrinot https://github.com/hazelcast/hazelcast/pull/8604

**Pull request merged**
