### PR TITLE
Add IOUtil.rename()

### PR DESCRIPTION
**Pull request by mtopolnik**
Needed in Hot Restart code.

### CODE REVIEW

**Comment by tombujok** [comment]
👍  once green

**Comment by mdogan** [comment]
👍

**Comment by mtopolnik** [comment]
```
testWriteBehindFlushPersistsAllRecords_afterShutdownAll(com.hazelcast.map.impl.mapstore.writebehind.WriteBehindMapStoreWithEvictionsTest)  Time elapsed: 4.187 sec  <<< FAILURE!
12:55:40 java.lang.AssertionError: expected:<1000> but was:<1011>
12:55:40 	at org.junit.Assert.fail(Assert.java:88)
12:55:40 	at org.junit.Assert.failNotEquals(Assert.java:834)
12:55:40 	at org.junit.Assert.assertEquals(Assert.java:645)
12:55:40 	at org.junit.Assert.assertEquals(Assert.java:631)
12:55:40 	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindMapStoreWithEvictionsTest.testWriteBehindFlushPersistsAllRecords_afterShutdownAll(WriteBehindMapStoreWithEvictionsTest.java:186)
```

**Comment by mtopolnik** [comment]
run-lab-run

**Pull request merged**
