### PR TITLE
Added labels to ClientEndpoint#toString() method

### PR DESCRIPTION
**Pull request by the-thing**
Fixes https://github.com/hazelcast/hazelcast/issues/17178

### CODE REVIEW

**Comment by sancar** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1433/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1433/Hazelcast-pr-builder-1433.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by mmedenjak** [comment]
Failed with unrelated test failure (https://github.com/hazelcast/hazelcast/issues/17015), merging. Thank you for the contribution @the-thing ! cc @Holmistr

**Pull request merged**
