### PR TITLE
Fix formatting of the auto-generated codecs

### PR DESCRIPTION
**Pull request by mdumandag**
There were a trailing new-line (and two trailing new-lines,
when there is no decodeResponse method) on some codecs. This
PR gets rid of that.

Also, there were some new-lines missing in between responseParameters
and encodeResponse, which are added here.

Also, adds the final modifier to `clientMessages` defined in the
compatibility tests.

Protocol PR: https://github.com/hazelcast/hazelcast-client-protocol/pull/383

### CODE REVIEW

**Review by yuce — APPROVED** [review]
Are the values of "Generated" attribute used anywhere?

**Comment by mdumandag** [comment]
@yuce yes there is a test for it to verify that these codecs are not modified by hand. It is used there

**Comment by mdumandag** [comment]
unrelated test failure, reported on #19025

**Comment by mdumandag** [comment]
verify

**Comment by mdumandag** [comment]
run-lab-run

**Review by ihsandemir — APPROVED** [review]
I assume that all the changes are generated from the related protocol PR, I approve.

**Pull request merged**
