### PR TITLE
Upgrade checkstyle to 10.12.2

### PR DESCRIPTION
**Pull request by JackPGreen**
`FinalClass` warning suppressed.

EE PR: [#6368](https://github.com/hazelcast/hazelcast-enterprise/pull/6368)

### CODE REVIEW

**Comment by TomaszGaweda** [comment]
See https://github.com/hazelcast/hazelcast/pull/25200 :)

**Comment by JackPGreen** [comment]
> See #25200 :)

I raise you #25253

**Comment by JackPGreen** [comment]
I can't reproduce the compilation issue locally, but I can with `mvn clean install -U -B -DskipTests` - to be investigated.

**Comment by JackPGreen** [comment]
OS & EE were branched off different commits. Rebased onto `master`.

**Review by TomaszGaweda — APPROVED** [review]

**Pull request merged**
