### PR TITLE
upgrade kubernetes plugin version to 1.5.2

### PR DESCRIPTION
**Pull request by hasancelik**

### CODE REVIEW

**Comment by leszko** [comment]
@hasancelik Is Hazelcast Kubernetes `1.5.2` released? I don't see it in the official Maven listing: https://mvnrepository.com/artifact/com.hazelcast/hazelcast-kubernetes

**Comment by hasancelik** [comment]
@leszko it is very strange, the release is already listed at https://repo1.maven.org/maven2/com/hazelcast/hazelcast-kubernetes/1.5.2/

**Comment by leszko** [comment]
ok, maybe they'll refresh it later.

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
I could not merge the PR due to some authorization issue so @degerhz helped out. Thanks for the merge Değer 👍

**Pull request merged**
