### PR TITLE
Created predefined FIFO-eviction-policy (#18075)

### PR DESCRIPTION
**Pull request by dominikrebhan**
Hi,
after my Git-Settings were all little mess, I hope it should work now. But first, a draft to test it.

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/eviction/impl/comparator/FIFOEvictionPolicyComparator.java:2: Line does not match expected header line of ' * Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.'. [Header]
--------------------------
</pre>
</details>

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
@dominikrebhan Current test is ok but it is not with public api. Could you please add tests for IMap and ICache separately by using public api?

**Comment by dominikrebhan** [comment]
@ahmetmircik Hi, I'm currently trying to add an extensive test for this. But due the way the eviction works (random samples) it may be very difficult to create a deterministic test case. I also found, that the other test cases (e. g. testEvictionLFU2) also don't work very well. They add only the amount of values that fit in the map itself, so nothing would be evicted anyway. 

`EvictionConfig evictionConfig = mapConfig.getEvictionConfig();
        evictionConfig
                .setEvictionPolicy(EvictionPolicy.LFU)
                .setMaxSizePolicy(MaxSizePolicy.PER_NODE)
                .setSize(size);`

`for (int i = 0; i < size; i++) {
            map.put(i, i);
            //...
}`

While writing this and after a little while of thinking, I'm not sure anymore if this strategy is meaningful. When I'm using FIFO I'm expecting to work like this, that the oldest entries are evicted first. But the way how eviction works, it cannot be guaranteed. The only way to make this work like expected would be to make the sample as big as the dataset, but this would be a huge performance issue I think.

What do you think about this?

**Comment by ahmetmircik** [comment]
Hi @dominikrebhan, to perform evictions in constant time we use sampling method. Sampling is an approximation method and it doesn't have same guarantees with an exact implementation. All Hazelcast LRU, LFU implementations are working in this manner. If you expect exact accuracy from FIFO, yes this approximation algorithm will not give it and OTOH sampling of a bigger set will have performance effects. So, given these, if this kind of FIFO implementation meets with your expectations, you can carry on with this PR.

**Comment by dominikrebhan** [comment]
@ahmetmircik Ok, yeah, I just wanted to verify my thoughts. I added the tests with the public api.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
@dominikrebhan these tests failed with your PR:
```
com.hazelcast.spring.TestFullApplicationContext.testMapConfig
com.hazelcast.cache.eviction.CacheEvictionPolicyComparatorTest.test_evictionPolicyComparator_with_fifo_when_maxSizePolicy_is_entryCount
com.hazelcast.client.cache.eviction.ClientCacheEvictionPolicyComparatorTest.test_evictionPolicyComparator_with_fifo_when_maxSizePolicy_is_entryCount
```

Perhaps some are not related to your changes but can you check each one and verify?

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by dominikrebhan** [comment]
Hi @ahmetmircik, Am I allowed to run "run-lab-run" the command by myself? Regards

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
>Hi @ahmetmircik, Am I allowed to run "run-lab-run" the command by myself? Regards

Hi @dominikrebhan, not sure about it, but possibly, you are not allowed or you can just try to see what will happen.

**Comment by mmedenjak** [comment]
@dominikrebhan because of security policies, unfortunately you are not allowed to start the PR build (in other words `run-lab-run` will not do anything).

**Pull request closed without merging**
