### PR TITLE
Handle family-less Calcite SQL types while converting to HZ SQL types

### PR DESCRIPTION
**Pull request by gierlachg**
Fixes failing generator tests as well.

### CODE REVIEW

**Comment by gierlachg** [comment]
run-lab-run

**Review by viliam-durina — APPROVED** [review]

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by gierlachg** [comment]
run-lab-run

**Review by frant-hartm — APPROVED** [review]

**Comment by gierlachg** [comment]
run-lab-run

**Pull request merged**
