### PR TITLE
NullPointerException error

### PR DESCRIPTION
**Pull request by onderaycicek**
NullPointerException error occurs at line 375 and than REST service stoped.

### CODE REVIEW

**Comment by hasancelik** [comment]
verify

**Comment by pveentjer** [comment]
I doubt if catching the NPE is the right way to solve the problem. Can you send the NPE stacktrace so we can fix the cause instead of the symptom?

**Comment by pveentjer** [comment]
@onderaycicek do you have the original stacktrace?

**Comment by mesutcelik** [comment]
why was this PR sent to `3.4-gem` branch?

**Comment by sancar** [comment]
Hi @onderaycicek , 
I am closing the issue. If you have more insights about to issue, please reopen the pr. To take action on pr we are gonna need more info from you.

**Pull request closed without merging**
