### PR TITLE
Decrease a unit test's memory demand

### LINKED ISSUE #7922: Long2LongMapHsaTest.testMemoryLeak
```
java.lang.OutOfMemoryError: Java heap space
	at com.hazelcast.internal.memory.impl.HeapMemoryManager.<init>(HeapMemoryManager.java:51)
	at com.hazelcast.internal.util.collection.Long2LongMapHsaTest.setUp(Long2LongMapHsaTest.java:47)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2473/testReport/junit/com.hazelcast.internal.util.collection/Long2LongMapHsaTest/testMemoryLeak/

```
java.lang.NullPointerException: null
	at com.hazelcast.internal.util.collection.Long2LongMapHsaTest.tearDown(Long2LongMapHsaTest.java:53)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2473/testReport/junit/com.hazelcast.internal.util.collection/Long2LongMapHsaTest/testMemoryLeak_2/

### PR DESCRIPTION
**Pull request by mtopolnik**
Fixes #7922.

### CODE REVIEW

**Comment by jerrinot** [comment]
:+1:

**Comment by Donnerbart** [comment]
:+1:

**Comment by mtopolnik** [comment]
Four tests failed, unrelated to each other and unrelated to this PR.

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2480/testReport/

**Comment by mtopolnik** [comment]
run-lab-run

**Comment by mtopolnik** [comment]
verify

**Pull request merged**
