### PR TITLE
Make instance name XML-configurable

### PR DESCRIPTION
**Pull request by mdogan**

### CODE REVIEW

**Comment by mtopolnik** [comment]
:+1: 

Let's merge this one as soon as possible because I have a much larger commit with cleanup of the same test file. I want to rebase locally so there are no merge conflicts.

**Comment by pveentjer** [comment]
:+1:

**Comment by mdogan** [comment]
Build stuck at `Running com.hazelcast.client.ClientServiceTest`.

**Comment by mdogan** [comment]
verify

**Comment by juanavelez** [comment]
Excellent addition

**Comment by bilalyasar** [comment]
:+1: 
```
17:51:27 Running com.hazelcast.client.ClientServiceTest
19:13:56 Build timed out (after 180 minutes). Marking the build as aborted.
```
again stuck in CLientServiceTest
@devOpsHazelcast  verify please

**Comment by bilalyasar** [comment]
verify

**Comment by mtopolnik** [comment]
Failed test: `MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode` (test timed out after 60000 milliseconds).

**Comment by mtopolnik** [comment]
verify

**Comment by mtopolnik** [comment]
For reference, this PR should fix #426 as well.

**Comment by pveentjer** [comment]
verify

**Comment by mtopolnik** [comment]
Latest failures:

- `MapNearCacheInvalidationFromClientTest.testUpdate` (assertion at line 184 got a null value);
- `ClientMapNearCacheTest.testServerMapExpiration_doesNotInvalidateClientNearCache` got 0 instead of 1 at line 544

**Comment by mdogan** [comment]
This is insane :) This is just a xml config change and not passing since yesterday...

**Pull request merged**
