### PR TITLE
Apply multiple Connection fixes

### LINKED ISSUE #8253: LiteMemberJoinTest.test_liteMemberReconnects_multicast
```
java.lang.IllegalStateException: ConnectionManager is already shutdown. Cannot start!
	at com.hazelcast.nio.tcp.TcpIpConnectionManager.start(TcpIpConnectionManager.java:454)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:111)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:302)
	at com.hazelcast.cluster.LiteMemberJoinTest.reconnect(LiteMemberJoinTest.java:162)
	at com.hazelcast.cluster.LiteMemberJoinTest.test_liteMemberReconnects(LiteMemberJoinTest.java:148)
	at com.hazelcast.cluster.LiteMemberJoinTest.test_liteMemberReconnects_multicast(LiteMemberJoinTest.java:136)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/815/testReport/junit/com.hazelcast.cluster/LiteMemberJoinTest/test_liteMemberReconnects_multicast/

### PR DESCRIPTION
**Pull request by metanet**
See commit messages for details

Fixes #8253

### CODE REVIEW

**Comment by mdogan** [comment]
👍

**Comment by metanet** [comment]
run-lab-run

**Comment by jerrinot** [comment]
:+1: on green

**Comment by metanet** [comment]
run-lab-run

**Comment by metanet** [comment]
run-lab-run

**Comment by metanet** [comment]
run-lab-run

**Comment by serkan-ozal** [comment]
`Test PASSed` hayırlı olsun @metanet

**Pull request merged**
