### PR TITLE
Sizing hash collections take 3

### PR DESCRIPTION
**Pull request by bokken**
This is a replacement for https://github.com/hazelcast/hazelcast/pull/9582 which finally has white space issues and import order resolved.

Fixes : https://github.com/hazelcast/hazelcast/issues/9445

### CODE REVIEW

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
Thanks @bokken for the PR, there are still a few checkstyle issues (mostly lines longer than 130 characters, unused imports magic numbers).

**Comment by bokken** [comment]
@vbekiaris, I believe I have the checkstyle issues addressed.

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
Please use CheckStyle locally to ensure you have addressed all issues: `mvn clean verify -Pcheckstyle`

```
16:20:39 /home/jenkins/jenkins/workspace/new-lab-fast-pr@8/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheProxyBase.java:260: Line has trailing spaces.
16:20:39 /home/jenkins/jenkins/workspace/new-lab-fast-pr@8/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheProxyBase.java:260:78: '/' should be on a new line.
16:20:39 /home/jenkins/jenkins/workspace/new-lab-fast-pr@8/hazelcast/src/main/java/com/hazelcast/client/impl/ClientEngineImpl.java:98:1: Class Data Abstraction Coupling is 16 (max allowed is 15) classes [Address, AtomicLong, ClientDisconnectionOperation, ClientEndpointManagerImpl, ClientEvent, ClientExceptionFactory, ClientHeartbeatMonitor, CompositeMessageTaskFactory, ConcurrentHashMap, ConnectionListenerImpl, ConstructorFunction, DestroyEndpointTask, EnumMap, GetConnectedClientsOperation, PostJoinClientOperation, PriorityPartitionSpecificRunnable].
16:20:39 /home/jenkins/jenkins/workspace/new-lab-fast-pr@8/hazelcast/src/main/java/com/hazelcast/collection/impl/collection/AbstractCollectionProxyImpl.java:131: Line has trailing spaces.
16:20:39 /home/jenkins/jenkins/workspace/new-lab-fast-pr@8/hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueContainer.java:43:8: Unused import - java.util.LinkedHashMap.
16:20:39 /home/jenkins/jenkins/workspace/new-lab-fast-pr@8/hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueContainer.java:704:32: Name '_itemQueue' must match pattern '^[a-z][a-zA-Z0-9]*$'.
16:20:39 /home/jenkins/jenkins/workspace/new-lab-fast-pr@8/hazelcast/src/main/java/com/hazelcast/internal/jmx/NodeMBean.java:24:8: Unused import - java.util.Hashtable.
```

**Comment by bokken** [comment]
@Donnerbart, when I run that locally I get thousands of issues reported:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 6699 errors reported by Checkstyle 6.1.1 with C:\Users\bo8979\git\hazelcast/checkstyle/checkstyle.xml ruleset. -> [Help 1]

**Comment by bokken** [comment]
@vbekiaris, @Donnerbart, I have addressed everything listed except:

ClientEngineImpl.java:98:1: Class Data Abstraction Coupling is 16 (max allowed is 15) classes [Address, AtomicLong, ClientDisconnectionOperation, ClientEndpointManagerImpl, ClientEvent, ClientExceptionFactory, ClientHeartbeatMonitor, CompositeMessageTaskFactory, ConcurrentHashMap, ConnectionListenerImpl, ConstructorFunction, DestroyEndpointTask, EnumMap, GetConnectedClientsOperation, PostJoinClientOperation, PriorityPartitionSpecificRunnable].

As best I can tell, I did not impact the level of coupling and have no idea how/if this should be addressed.

**Comment by Donnerbart** [comment]
I think our CheckStyle configuration wasn't picked up in your local run. Did you run the Maven command from the root folder of the project? This is definitely working, we use it all the time (and also our build machines do).

Regarding `ClientEngineImpl`: You removed one import and added three new ones. This pushed the number of classes for the `Class Data Abstraction Coupling` check over the limit. You can suppress this by adding this on the class level: `@SuppressWarnings("checkstyle:classdataabstractioncoupling")`

**Comment by bokken** [comment]
I have tried executing from both root of project and the hazelcast child project, both provide same result.

I have added the warning suppression and updated PR.

I apologize for the issues on checkstyle. I am down to 6698 issues after adding the suppression, so hopefully that is everything.

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
There is nothing to apologize for. It's just that we need that check to pass, otherwise the PR builder won't execute, the tests are not started and we cannot merge a PR (general rule to get something into the master branch).

**Comment by LoneRifle** [comment]
If you are using Windows for your dev, you have to make edits to the suppressions file so that they account for Windows path separators and not Unix ones. I might have one lying around in my local stash; I'll create a diff patch that you can apply to yours if you want (but _be very careful not to commit this into hazelcast itself!_ )

**Comment by LoneRifle** [comment]
@bokken - Gist containing my Windows-specific suppressions file can be found in my previous (edited) comment.

**Comment by LoneRifle** [comment]
What shall we do with this PR? If it has been abandoned, I would be happy to have a look and rebase/rewrite parts of it, giving credit where due.

**Comment by bokken** [comment]
It was not my intention to abandon, but it appeared to have been ignored. Given the broad set of classes touched with this PR, it is more work than I have time for to constantly keep updated.
If you are wanting to accept this, I can look to update in the next week or so.

**Comment by mmedenjak** [comment]
Closing in favour of https://github.com/hazelcast/hazelcast/pull/10943

**Pull request closed without merging**
