### PR TITLE
Smart clients default to 3+3 io threads

### PR DESCRIPTION
**Pull request by pveentjer**
So instead of having only 1(+1) io thread for smart clients,
they now default to 3. Just as with the members.

This is done to increase performance.

Mileage may vary. But the below table is from a simple AtomicLong.get test using 6 members, 3 clients and 32 threads per client. 

image

The throughput increase is 14%

### CODE REVIEW

**Comment by tkountis** [comment]
@pveentjer does it affect latency?

**Comment by pveentjer** [comment]
I send you the full performance report so you can have a look. It isn't obvious from the general latency distribution because the difference isn't that big. But if you look at e.g. 90% interval plot, you will see difference in favor of 3+3 threads

**Comment by pveentjer** [comment]
Don't merge yet. The issue is that there are some regressions on ec2

**Comment by pveentjer** [comment]
run-lab-run

**Comment by pveentjer** [comment]
verify

**Comment by pveentjer** [comment]
run-lab-run

**Pull request merged**
