### PR TITLE
Fixes possible NPE case for removeFirstOccurence method

### PR DESCRIPTION
**Pull request by ahmetmircik**
This bug is introduced via https://github.com/hazelcast/hazelcast/pull/7058

### CODE REVIEW

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by eminn** [comment]
:+1:

**Comment by ahmetmircik** [comment]
this needs for simulator runs merging it.

**Pull request merged**
