### PR TITLE
non blocking socket reader idle time probe now on info instead of debug

### PR DESCRIPTION
**Pull request by pveentjer**

### CODE REVIEW

**Comment by jerrinot** [comment]
:+1:

**Comment by pveentjer** [comment]
run-lab-run

**Comment by pveentjer** [comment]
run-lab-run

**Comment by pveentjer** [comment]
run-lab-run

**Comment by pveentjer** [comment]
run-lab-run

**Comment by pveentjer** [comment]
run-lab-run

**Comment by pveentjer** [comment]
roll the dice again!!

**Pull request merged**
