### PR TITLE
Added map.delete method for console app

### PR DESCRIPTION
**Pull request by mumukiller**
Added m.delete method for console app
Added test

However i have doubts regarding ClientConsoleApp class which also does not have such method

#12274

### CODE REVIEW

**Comment by eminn** [comment]
Hi @mumukiller,

Thanks for your contribution. Can you please sign the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement) if you haven't signed yet ?

Could you please also add same changes to the ClientConsoleApp?

**Comment by mumukiller** [comment]
I signed it and sent to jaromir@hazelcast.com. Still waiting for confirmation :(
Regarding ClientConsoleApp, i haven't found any tests related to ClientConsoleApp. Are there any for this class?

**Comment by eminn** [comment]
Good spot,There is no test for that class at the moment, I let the clients team know about it and created an issue -> https://github.com/hazelcast/hazelcast/issues/12298.

You can add the `delete()` method over there and the tests will be written for that class as soon as possible.

**Comment by eminn** [comment]
I've just confirmed that we got your signed agreement. Thanks for your patience.

If you update the PR with the client counterparts of the console application we can proceed to merge your PR.

**Comment by mumukiller** [comment]
Sure i'll update it

**Comment by mumukiller** [comment]
Done!

**Comment by eminn** [comment]
Thanks for the update. After the review from other guys we are happy to merge your PR.

**Comment by pveentjer** [comment]
@mumukiller thanks for your contribution!

**Pull request merged**
