### PR TITLE
Tiny cleanup OperationRunnerImpl.handleResponse

### PR DESCRIPTION
**Pull request by pveentjer**

### CODE REVIEW

**Comment by pveentjer** [comment]
run-lab-run

**Comment by pveentjer** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
What is with operations which have backups, but no response? Those backups won't be made after this change, won't they? And for me it's not obvious that this is an "illegal" combination.

A little explanation why this is a valid optimization would be nice :)

**Comment by pveentjer** [comment]
Good spotting. Apparently I had sh*t in my eyes. I read is at the number of backups.. so a simple 'getter'; but a lot more logic is going on

**Pull request closed without merging**
