### PR TITLE
Replicated map clear operations changed to run on partition threads

### LINKED ISSUE #6871: DummyClientReplicatedMapTest.testClear
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.replicatedmap.DummyClientReplicatedMapTest$7.run(DummyClientReplicatedMapTest.java:222)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:849)
	at com.hazelcast.client.replicatedmap.DummyClientReplicatedMapTest.testClear(DummyClientReplicatedMapTest.java:219)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client/17103/testReport/junit/com.hazelcast.client.replicatedmap/DummyClientReplicatedMapTest/testClear/

### PR DESCRIPTION
**Pull request by eminn**
Fixes #6871

### CODE REVIEW

**Comment by sancar** [comment]
:+1:

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
run-lab-run

**Comment by eminn** [comment]
run-lab-run

**Comment by metanet** [comment]
:+1:

**Pull request merged**
