### PR TITLE
Added type checking unittests to meet the Javadocs exception requirement...

### PR DESCRIPTION
**Pull request by noctarius**
...s on javax.cache.Cache interface, added more unittests in general, especially concurrency

@gurbuzali:
New PR for #4032

### CODE REVIEW

**Comment by noctarius** [comment]
verify

**Comment by noctarius** [comment]
*ping*

**Comment by jerrinot** [comment]
this is really large and hard to review PR. 
You could send 1 PR with the concurrency tests and other with the stricter type checking(?) or whatever the functional change is doing.

**Comment by noctarius** [comment]
This PR is pending now for a very long time, I already re-implemented it again... I have no time to split it up again at the moment ... This was already pending before release of 3.4

**Comment by noctarius** [comment]
To not have this merged for 3.4.20, there you go, 4 "small" PRs ;)

#4582 
#4583 
#4585 
#4586 

Closing this one

**Comment by serkan-ozal** [comment]
@noctarius Ok, I will look them ASAP after finishing JCache infinite retry problem (if there is) :) Still looking at it to reproduce case.

**Pull request closed without merging**
