### PR TITLE
Removed RedundantThrows & JUnitTestCase from checkstyle config 

### PR DESCRIPTION
**Pull request by ahmetmircik**
See:
https://github.com/checkstyle/checkstyle/issues/473
https://github.com/jshiell/checkstyle-idea

### CODE REVIEW

**Comment by pveentjer** [comment]
What is the reason this needs to be changed?

**Comment by ahmetmircik** [comment]
Not working with new plugin versions. And as stated in the checkstyle issue, those checks are also buggy.

**Comment by pveentjer** [comment]
Can you post some links? And which version are you referring too? checkstyle? Maven plugin? IDEA?

**Comment by ahmetmircik** [comment]
plugin 4.14.2 is using CheckStyle 6.5.
You can read the provided links in the issue comment for further info.

**Comment by pveentjer** [comment]
I'm not using this plugin (I find it it a big pita) so I alway use the CLI. But what are consequences of the bugs?

**Comment by ahmetmircik** [comment]
Since it is removed from checkstyle, checkstyle integration is giving error and not working, this is the first important thing for me. Secondly, you can find the other consequences in checkstyle issues one is https://github.com/checkstyle/checkstyle/issues/74

**Pull request merged**
