### PR TITLE
Check value of key if it is null or not while iterating on cache since entry might be removed or evicted.

### LINKED ISSUE #6234: [TEST-FAILURE]  com.hazelcast.client.cache.CacheBasicClientTest.testIteratorDuringInsertion
```
Tests run: 29, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.03 sec <<< FAILURE! - in com.hazelcast.client.cache.CacheBasicClientTest
testIteratorDuringInsertion(com.hazelcast.client.cache.CacheBasicClientTest)  Time elapsed: 0.188 sec  <<< ERROR!
java.lang.NullPointerException: null
    at com.hazelcast.cache.CacheBasicAbstractTest.testIteratorDuringInsertion(CacheBasicAbstractTest.java:338)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:134)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:47)
    at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:144)
    at java.lang.Thread.run(Thread.java:744)
```

Reported by @dbrimley

### PR DESCRIPTION
**Pull request by serkan-ozal**
Fixes #6234

### CODE REVIEW

**Comment by metanet** [comment]
:+1: once green

**Comment by ahmetmircik** [comment]
:+1:

**Comment by emrahkocaman** [comment]
:+1:

**Comment by serkan-ozal** [comment]
verify

**Comment by kobalski** [comment]
:+1: Cannot resist.

**Comment by metanet** [comment]
:+1:

**Comment by serkan-ozal** [comment]
good job Serkan :+1:

**Pull request merged**
