### PR TITLE
Allow to use JDK8 JavaScript scripting engine in OSGi platforms

### PR DESCRIPTION
**Pull request by adessaigne**
This patch allows to use the JavaScript scripting engine of JDK8 (named _Nashorn_). It is still capable of using the one of JDK7 (named _Rhino_).

Without this patch, the following log is displayed when running in JDK8
```
2015-05-12 16:48:06,805 [FelixStartLevel] WARN com.hazelcast.osgi.OSGiScriptEngineManager - Found ScriptEngineFactory candidate for com.sun.script.javascript.RhinoScriptEngineFactory, but cannot load class! -> java.lang.ClassNotFoundException: com.sun.script.javascript.RhinoScriptEngineFactory not found by com.hazelcast [156]
```

### CODE REVIEW

**Comment by adessaigne** [comment]
verify

**Comment by bilalyasar** [comment]
verify

**Comment by adessaigne** [comment]
Do this test failure related to my pull-request ? I failing at finding a connection between the error and my pull-request.

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
@adessaigne Thanks for your work. Could you please sign [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement)

**Comment by adessaigne** [comment]
@serkan-ozal I've just sent the email with a scan of my signed Hazelcast Contributor Agreement.

**Comment by pveentjer** [comment]
verify

**Comment by ajermakovics** [comment]
Seems like ClassLoaderUtil could be used here instead of custom methods

**Comment by adessaigne** [comment]
Yes, I thought that too, but the ```ClassLoaderUtil``` is located in ```com.hazelcast.nio``` and not in ```com.hazelcast.util```. Also its ```loadClass``` method doesn't have the fallback mechanism from one class loader to another when there is a ```ClassNotFoundException```.

**Comment by ajermakovics** [comment]
If the existing method isn't suitable then I think a new one can be added to ClassLoaderUtil. Having these methods in one place is makes it easier to discover them. The existing one seems to have some fallback though I don't know it works in this case

verify

**Comment by adessaigne** [comment]
If I update the code, the ```com.hazelcast.internal.osgi``` package will have a dependency towards ```com.hazelcast.nio```. I found it a bit odd, are you ok with that ?

As of today, the dependencies of ```com.hazelcast.internal.osgi``` are : ```com.hazelcast.core.```, ```com.hazelcast.logging``` and ```com.hazelcast.internal.management```

**Comment by ajermakovics** [comment]
nio may not be the best place for ClassLoaderUtil anymore and eventually we should move it to util but that's probably out of scope of this pr. Other than that it's a +1 from me, not sure what others think

**Comment by mesutcelik** [comment]
:+1:  for moving methods to `ClassLoaderUtil` only.

**Comment by adessaigne** [comment]
OK then, I'll move ```tryLoadClass``` and ```isClassDefined``` into ```ClassLoaderUtil```.
How should I rename my ```tryLoadClass``` method because there already is a method named that way in ```ClassLoaderUtil``` ?

**Comment by adessaigne** [comment]
What should I do in order to help you integrate this PR into the code base ?

**Comment by ajermakovics** [comment]
Any reason the existing loadClass method can't be used? It also does fallback. It'd be better if we didn't have two methods doing very similar things. 
If it can't be used then moving the methods should be enough. Doesn't need renaming since signatures are different.

**Comment by adessaigne** [comment]
The ```loadClass``` method is indeed different from my ```tryLoadClass``` method. My first attempt is with ```Class.loadClass(className)``` which is the last statement of the ```loadClass``` method but it's never called due to logic above.

**Comment by ajermakovics** [comment]
verify

**Comment by mesutcelik** [comment]
verify

**Comment by adessaigne** [comment]
Hi everyone ? Is everything ok ? Did I forget to do something to help you integrate this PR ?

**Comment by pveentjer** [comment]
@ajermakovics @mesutcelik what should we do with this one?

**Comment by adessaigne** [comment]
Thanks a lot !

**Comment by mesutcelik** [comment]
Thanks goes to you for the contribution @adessaigne !

**Pull request merged**
