### PR TITLE
Implemented AWS v4 signer

### LINKED ISSUE #3963: TcpIpJoinerOverAWS fails with signature v4
Recently, AWS launched eu-central-1. The API for that region requires v4 signatures. Older versions return a 401 error : 

2014-10-31 21:59:52,005 WARN  com.hazelcast.cluster.TcpIpJoinerOverAWS ~ [10.10.1.242]:5701 [dev-frankfurt] [3.3.2] Server returned HTTP response code: 401 for URL: https://ec2.eu-central-1.amazonaws.com/?Action=DescribeInstances&SignatureMethod=HmacSHA256&AWSAccessKeyId=secret&SignatureVersion=2&Version=2011-05-15&Signature=H%2BOojfBnp96dqcuadwEJ%2BLmTGQ6QuCSrxvbrH2ECWkI%3D&Timestamp=2014-10-31T21%3A59%3A51.507Z

This prevents the AWS joiner from working. The newer signature requirements are mandatory in eu-central-1, and also on the China region.

### PR DESCRIPTION
**Pull request by igmar**
This replace the AWS v2 signer by a version that does v4 signing. I've removed the old V2 signer : There is no reason to keep it in, since all regions support V4, and for some regions (eu-central-1, China) it is mandatory.

For more info:
http://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html
http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html

Fixes #3963

### CODE REVIEW

**Comment by igmar** [comment]
Just pushed the latest version.

**Comment by mdogan** [comment]
verify

**Comment by mdogan** [comment]
@igmar, there are 1 checkstyle error and 4 findbugs issues. Please check these with 
`mvn clean compile -P checkstyle,findbugs`

Checkstyle:
```
hazelcast-cloud/src/main/java/com/hazelcast/aws/impl/DescribeInstances.java:33:15: Unused import - com.hazelcast.aws.impl.Constants.SIGNATURE_METHOD_V4.
```

Findbugs:
```
INFO] Total bugs: 4
[INFO] Unread field: com.hazelcast.aws.AWSClient.endpoint ["com.hazelcast.aws.AWSClient"] At AWSClient.java:[lines 30-55]
[INFO] Found reliance on default encoding in com.hazelcast.aws.security.EC2RequestSigner.createSignature(String, byte[]): String.getBytes() ["com.hazelcast.aws.security.EC2RequestSigner"] At EC2RequestSigner.java:[lines 51-228]
[INFO] Found reliance on default encoding in com.hazelcast.aws.security.EC2RequestSigner.deriveSigningKey(): String.getBytes() ["com.hazelcast.aws.security.EC2RequestSigner"] At EC2RequestSigner.java:[lines 51-228]
[INFO] Format string should use %n rather than \n in com.hazelcast.aws.security.EC2RequestSigner.getCanonicalHeaders() ["com.hazelcast.aws.security.EC2RequestSigner"] At EC2RequestSigner.java:[lines 51-228]
```

**Comment by igmar** [comment]
On it.

**Comment by mesutcelik** [comment]
@igmar ,
When can we finalize this?

**Comment by igmar** [comment]
Committed.

**Comment by mesutcelik** [comment]
verify

**Comment by mesutcelik** [comment]
looks good to me. @mdogan , can you have another look?

**Comment by mdogan** [comment]
good for me too.

**Pull request merged**
