### PR TITLE
[#10885] Fix ClientStateListenerTest.testClientReconnecModeOffDisconn…

### PR DESCRIPTION
**Pull request by Holmistr**
…ected

Trying to fix: https://github.com/hazelcast/hazelcast/issues/10885

### CODE REVIEW

**Comment by Holmistr** [comment]
run-lab-run

**Comment by sancar** [comment]
It seems test failed because  `assertFalse(listener.isStarted());` queried before shutdown actually happened. If that is the case, this test still can fail. 

I am not really sure what `isStarted` should return when client shutdown. Logically if client shutdown you can say it is started. But current implementation returns false if client shutdown.  

I think we should change the implementation of `isStarted`. if `STARTED` event seen once, it should never return false from that point on. 
@ihsandemir what do you think?

**Comment by ihsandemir** [comment]
@sancar issStarted meaning: The client is NOT shutdown. It returns false only if client is shutdown (or STARTING state which you will not usually catch). Hence, the test checks if client shutdown happened and client state became SHUTDOWN. I examined the log at https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/865/testReport/junit/com.hazelcast.client.util/ClientStateListenerTest/testClientReconnecModeOffDisconnected/# 

I see this in the log:

CLIENT_DISCONNECTED is printed and then no other client logs and the new server start log only exist. Here is a possible scenario:

1. CLIENT_DISCONNECTED is printed and the client shutdown is offloaded to an external thread. 
2. The external shutdown thread is late executing and hence when the check is done the client shutdown did not happen yet.

It can be fixed within the test code like this:

```
index 75f976633d..74e7ac7cff 100644
--- a/hazelcast-client/src/test/java/com/hazelcast/client/util/ClientStateListenerTest.java
+++ b/hazelcast-client/src/test/java/com/hazelcast/client/util/ClientStateListenerTest.java
@@ -224,8 +224,6 @@ public class ClientStateListenerTest extends ClientTestSupport{
 
         assertFalse(listener.isConnected());
 
-        assertFalse(listener.isStarted());
-
         assertTrueEventually(new AssertTask() {
             @Override
             public void run()
@@ -233,6 +231,8 @@ public class ClientStateListenerTest extends ClientTestSupport{
                 assertEquals(SHUTDOWN, listener.getCurrentState());
             }
         });
+
+        assertFalse(listener.isStarted());
     }
```
Fix is: Do the check after the state is SHUTDOWN.

**Comment by Holmistr** [comment]
@sancar Or how about we added assertEventually to make sure that the shutdown really happened? I think it's quite obvious that this is an unlucky timing issue, something later than expected, so we might solve it by "blocking" wait. WDYT?

**Comment by Holmistr** [comment]
@ihsandemir Hehe, exactly what I had it mind, you were faster :) Ok, I will update the PR soon.

**Comment by sancar** [comment]
I still think that meaning of `isStarted` not straightforward.  I don't think it should mean `The client is NOT shutdown.`  The name of the method is not a good fit. And we already have `isShutdown` method.

**Comment by Holmistr** [comment]
@sancar @ihsandemir I have update the PR with suggested fix.

**Comment by Holmistr** [comment]
@sancar @ihsandemir Have you reached any decision? Could we merge this PR to see if it fixes the spurious failure? I'm trying to get rid of those pesky failures :)

**Comment by sancar** [comment]
Yes, we can merge this one. We decided to not change the behaviour of the method.

**Pull request merged**
