### PR TITLE
Regression test which does have to use real network moved into own class

### PR DESCRIPTION
**Pull request by jerrinot**
This is the only test from the ClientRegressionTest which does rely on real network.

### CODE REVIEW

**Comment by Donnerbart** [comment]
Does it have to be a `SlowTest` (so moved out of PR-builder if I'm right) or is it enough to use the real network again?

**Comment by jerrinot** [comment]
This very test is not particularly slow on its own. If you have better idea how to structure it then I'm open to suggestions!

**Comment by Donnerbart** [comment]
My main criterias would be:
* importance of the test, as in:
  * importance of the component the test is testing
  * probability of breaking something which the tests is testing
* runtime of the test

Some tests may be important, but are nevertheless too slow/expensive for the PR-builder. Those would be candidates to move to `SlowTest`s to keep the PR-builder fast.

For this test I have no idea about the importance. I hope the client team can help out with their opinion and give advice where we should put this test in (PR-builder or daily run).

**Comment by jerrinot** [comment]
@sancar: May I kindly ask you for a suggestion here? Thanks!

**Comment by sancar** [comment]
It seems this test is written to prove an issue is fixed, hence it is important. Since it is fast, I would like to see this test in pr builder.

**Comment by jerrinot** [comment]
@sancar: I pushed a new version where both test classes are in the QuickTest category. Feel free to suggest better names!

**Comment by Donnerbart** [comment]
The names may not be beautiful, but they are very clear in their meaning.

:+1:

**Comment by pveentjer** [comment]
verify

**Comment by pveentjer** [comment]
:+1:

**Pull request merged**
