### PR TITLE
Remove legacy Semaphore

### PR DESCRIPTION
**Pull request by mdogan**
Removed legacy Semaphore implementation and HazelcastInstance.getSemaphore(..) method. Instead we provide unsafe mode for all CP data structures (See #15184).

EE: https://github.com/hazelcast/hazelcast-enterprise/pull/3156

See TDD: https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1749057609/Concurrency+API+Clean-up+Design

Protocol change: https://github.com/hazelcast/hazelcast-client-protocol/pull/226

### CODE REVIEW

**Comment by asimarslan** [comment]
@mdogan Can you send the client protocol changes to protocol repo too?

**Comment by mdogan** [comment]
@asimarslan: See https://github.com/hazelcast/hazelcast/pull/15538#issuecomment-532083462

**Comment by mdogan** [comment]
See https://github.com/hazelcast/hazelcast-client-protocol/pull/222

**Comment by mmedenjak** [comment]
Minor: we'll have to update the references to removed methods in javadoc, e.g. `{@link HazelcastInstance#getSemaphore(String)}`

**Pull request merged**
