### PR TITLE
Don't fire quorum events until quorum is met for the first time

### LINKED ISSUE #17038: QuorumListener is triggered during member startup but before it has joined a cluster
**Describe the bug**
Tested on 3.12.2 which is customer's version.
In a cluster with Quorum defined, without touching any maps, just calling `Hazelcast.newHazelcastInstance();` causes `QuorumListener` to be triggered, before the member joins anyone and forms the cluster initially. 

**Expected behavior**
We shouldn’t fire any quorum listener events after a member starts until quorum is met initially.

**To Reproduce**

1. Define a quorum of 3 with a listener attached 
```
    <quorum enabled="true" name="myquorum">
        <quorum-size>3</quorum-size>
        <quorum-listeners>
            <quorum-listener>MyQuoLis</quorum-listener>
        </quorum-listeners>
    </quorum>
```
2. Start one member
3. Observe how member logs a quorum event before join:
```
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Hazelcast 3.12.2 (20190802 - e34b163) starting at [127.0.0.1]:5701
Jun 01, 2020 4:22:40 PM com.hazelcast.system
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
Jun 01, 2020 4:22:40 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Backpressure is disabled
Jun 01, 2020 4:22:40 PM com.hazelcast.instance.Node
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Creating TcpIpJoiner
Jun 01, 2020 4:22:40 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Starting 8 partition threads and 5 generic threads (1 dedicated for priority tasks)
Jun 01, 2020 4:22:40 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Jun 01, 2020 4:22:40 PM com.hazelcast.core.LifecycleService
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] [127.0.0.1]:5701 is STARTING
Listener triggered: QuorumEvent{threshold=3, currentMembers=com.hazelcast.internal.cluster.impl.MemberSelectingCollection@1d30e322, presence=false}
Jun 01, 2020 4:22:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Connecting to /127.0.0.1:5703, timeout: 10000, bind-any: true
Jun 01, 2020 4:22:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Connecting to /127.0.0.1:5702, timeout: 10000, bind-any: true
Jun 01, 2020 4:22:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Could not connect to: /127.0.0.1:5702. Reason: SocketException[Connection refused to address /127.0.0.1:5702]
Jun 01, 2020 4:22:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] Could not connect to: /127.0.0.1:5703. Reason: SocketException[Connection refused to address /127.0.0.1:5703]
Jun 01, 2020 4:22:40 PM com.hazelcast.cluster.impl.TcpIpJoiner
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] [127.0.0.1]:5703 is added to the blacklist.
Jun 01, 2020 4:22:40 PM com.hazelcast.cluster.impl.TcpIpJoiner
INFO: [127.0.0.1]:5701 [sertug] [3.12.2] [127.0.0.1]:5702 is added to the blacklist.
Jun 01, 2020 4:22:41 PM com.hazelcast.internal.cluster.ClusterService
INFO: [127.0.0.1]:5701 [sertug] [3.12.2]

Members {size:1, ver:1} [
Member [127.0.0.1]:5701 - 3a89efeb-9da0-4a08-8b54-f6f7632387d5 this
]
```

### PR DESCRIPTION
**Pull request by mdogan**
Note: Removed data-structure quorum-listeners tests. Quorum events
are not bound to a specific data-structure.

Fixes #17038

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1098/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1098/Hazelcast-pr-builder-1098.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:testCompile (default-testCompile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[51,20] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/quorum/QuorumListenerTest.java:[61,32] error: local variable listener is accessed from within inner class; needs to be declared final
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/quorum/QuorumListenerTest.java:[71,32] error: local variable listener is accessed from within inner class; needs to be declared final
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[51,20] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/quorum/QuorumListenerTest.java:[61,32] error: local variable listener is accessed from within inner class; needs to be declared final
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/quorum/QuorumListenerTest.java:[71,32] error: local variable listener is accessed from within inner class; needs to be declared final
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1099/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1099/Hazelcast-pr-builder-1099.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 6.1.1 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1100/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1100/Hazelcast-pr-builder-1100.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   QuorumTest.com.hazelcast.quorum.QuorumTest ? IllegalState Instances haven't be...
[ERROR]   QuorumTest.testCustomQuorumFunctionFailsThenSuccess:304 ? Quorum Split brain p...
[INFO] 
[ERROR] Tests run: 14870, Failures: 0, Errors: 2, Skipped: 648
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1101/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1101/Hazelcast-pr-builder-1101.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CPMemberAutoRemoveTest.when_missingCPNodeJoins_then_itIsNotAutomaticallyRemoved:108->HazelcastTestSupport.assertTrueEventually:1420->HazelcastTestSupport.assertTrueEventually:1318 
Expected: an empty collection
     but: <[CPMember{uuid=1eb9a9c2-9c9f-4547-a711-a86f3d7e38b0, address=[127.0.0.1]:5701}, CPMember{uuid=3a1a002f-1f30-46bb-9498-27a43ba9aacb, address=[127.0.0.1]:5702}]>
[ERROR] Errors: 
[ERROR]   CPMemberAddRemoveTest.when_newCPMemberIsAddedToTheMetadataGroupAfterRestartAndSnapshot_newMemberInstallsSnapshot ? Execution
[INFO] 
[ERROR] Tests run: 14869, Failures: 1, Errors: 1, Skipped: 648
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1102/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1102/Hazelcast-pr-builder-1102.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CPMemberAutoRemoveTest.when_missingCPNodeJoins_then_itIsNotAutomaticallyRemoved:108->HazelcastTestSupport.assertTrueEventually:1420->HazelcastTestSupport.assertTrueEventually:1318 
Expected: an empty collection
     but: <[CPMember{uuid=c2e3228b-ecca-4583-8756-494994fa8772, address=[127.0.0.1]:5702}, CPMember{uuid=789382e1-9e8f-4219-9c61-6a720bbc605d, address=[127.0.0.1]:5701}]>
[ERROR] Errors: 
[ERROR]   CPMemberAddRemoveTest.when_newCPMemberIsAddedToTheMetadataGroupAfterRestart_newMemberCommitsMetadataGroupLogEntries ? Execution
[INFO] 
[ERROR] Tests run: 14869, Failures: 1, Errors: 1, Skipped: 648
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by mdogan** [comment]
Failures in the last two runs, `CPMemberAutoRemoveTest` and `CPMemberAddRemoveTest`,  are not related to this PR. I checked and tested on `3.12.z` branch and they are not failing.

**Comment by mdogan** [comment]
run-lab-run

**Pull request merged**
