### PR TITLE
Decrease log level for ExecutionNotFoundException

### LINKED ISSUE #19840: SnapshotPhase2Operation exception on 5.0.1-SNAPSHOT
Using Hazelcast Platform 5.0.1-SNAPSHOT (20211022 - aafdf51)

I get
```
16:31:08.499 WARN  hz.naughty_cartwright.cached.thread-6 c.h.jet.impl.MasterSnapshotContext - [10.172.3.5]:5701 [grid] [5.0.1-SNAPSHOT] SnapshotPhase2Operation for snapshot 28 in job 'SlackSQLJob', execution 06fe-73a2-78c8-0001 failed on member: MemberInfo{address=[10.172.0.5]:5701, uuid=54de9756-8659-402c-b745-b8e628b2535d, liteMember=false, memberListJoinVersion=2}=com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fe-73a2-78c4-0001, execution 06fe-73a2-78c8-0001 not found for coordinator [10.172.3.5]:5701 for 'SnapshotPhase2Operation' 
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fe-73a2-78c4-0001, execution 06fe-73a2-78c8-0001 not found for coordinator [10.172.3.5]:5701 for 'SnapshotPhase2Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:441)
	at com.hazelcast.jet.impl.operation.SnapshotPhase2Operation.doRun(SnapshotPhase2Operation.java:54)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

I have a (huge!) reproducer project. DM me for details

### PR DESCRIPTION
**Pull request by viliam-durina**
The `ExecutionNotFoundException` after phase2 is normal and can be
ignored, let's decrease its log level to FINE, log other exceptions on
WARNING level.

Fixes #19840

### CODE REVIEW

**Review by ramizdundar — APPROVED** [review]

**Comment by ufukyilmaz** [comment]
These logs are still being thrown at the severe level at the operation level here:
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/jet/impl/operation/AsyncOperation.java#L56

Example log:
```
14:48:20,584 ERROR || - [SnapshotPhase1Operation] hz.silly_lichterman.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] job 0758-52ac-8740-0001, execution 0758-52ac-8741-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase1Operation'
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 0758-52ac-8740-0001, execution 0758-52ac-8741-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase1Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:495) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.SnapshotPhase1Operation.doRun(SnapshotPhase1Operation.java:65) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
	
```
Do we want to decrease the level of these logs too?

**Comment by viliam-durina** [comment]
@ufukyilmaz Might be nice, but the logging is in shared code. And not in all cases the exception is harmless. But on the other hand, in this specific case it's the logging at the callee end. And it's a problem for the caller, not for the callee. Therefore I decided to change this exception to SilentException.

The previous commit reduced the logging level on caller side, the second commit reduces it on callee end.

**Review by ufukyilmaz — APPROVED** [review]
Thanks for the PR. It looks good to me.

**Comment by ufukyilmaz** [comment]
run-lab-run

**Pull request merged**
