### PR TITLE
Include JSON parser in the project instead of shading and relocating

### PR DESCRIPTION
**Pull request by kwart**
This PR adds classes from eclipse-source minimal-json project (version 0.9.5) into the hazelcast's new package `com.hazelcast.internal.json`. This PR is related to (replaces) the #13403. 

Advantages:
* zero dependency policy applies
* no shading
* no relocation
* Java 9 friendly (the package just in core)

Disadvantages:
* we will have to maintain fixes in the JSON code ourselves

### CODE REVIEW

**Comment by Donnerbart** [comment]
Technically the PR looks very good to me. The replacement of the imports is fine. The PR also includes the tests. I also think that this the best solution for the issue.

The only missing thing is feedback from legal, regarding the licence compatibility. Josef already reached out to Nadine, but I think there is no answer yet.

**Comment by mmedenjak** [comment]
@kwart can we merge this? Do we have some info from Nadine?

**Comment by kwart** [comment]
There are still running some internal checks, but it looks promising.

**Comment by Donnerbart** [comment]
I think we also need to adapt the `ReflectionsHelper`:
```java
        subtypesScanner.setResultFilter(new FilterBuilder().exclude("java\\.lang\\.(Object|Enum)")
                .exclude("com\\.hazelcast\\.com\\.eclipsesource.*"));
```

**Comment by kwart** [comment]
NIce catch, David. The class `ReflectionsHelper` is updated now.

**Comment by kwart** [comment]
I've updated the `NOTICE` file with the information about `com.hazelcast.internal.json`. It should be the last necessary step. Once the tests are green I'll merge.

**Comment by kwart** [comment]
Thanks guys for all the reviews. Merged.

**Pull request merged**
