### PR TITLE
`SystemPropertiesPluginTest` - add `Java.vm.args` test case (HZ-3157)

### LINKED ISSUE #11610: java.vm.args doesn't work under windows [HZ-3157]
So we don't see the JVM args under windows in the diagnostics file.

### PR DESCRIPTION
**Pull request by JackPGreen**
Add test case to cover scenario in #11610

Fixes #11610

### CODE REVIEW

**Comment by JackPGreen** [comment]
run-windows

**Comment by olukas** [comment]
run-windows

**Comment by olukas** [comment]
run-windows

**Comment by JackPGreen** [comment]
run-windows

**Review by pveentjer — APPROVED** [review]

**Pull request merged**
