### PR TITLE
exporting eclipsesource package in MANIFEST.MF

### LINKED ISSUE #10994: NoClassDefFoundError: com/hazelcast/com/eclipsesource/json/JsonObject when using Payara Server and hazelcast-aws
Hazelcast comes bundled with Payara which is an OSGI environment. The `com.hazelcast.com.eclipsesource.json.JsonObject` class is not exported in the OSGI metadata in the MANIFEST of the Hazelcast.jar. Therefore cannot be loaded by classes in the hazelcast-aws-2.0.1.jar.  Because of this, when we use the hazelcast-aws-2.0.1.jar and the Discovery SPI strategy with `iam-role`  we get `NoClassDefFoundError: com/hazelcast/com/eclipsesource/json/JsonObject `.    The discovery works fine when we provide the proper `access-key` and `secret-key` but fails with `iam-role`.  

I raised an issue with the Payara team (https://github.com/payara/Payara/issues/1806) regarding this.  The suggested workaround was to manually edit the hazelcast.jar  MANIFEST file and add `com.hazelcast.com.eclipsesource.json;version="3.7.4"` to the Export-Package section.  This resolved our issue. 

Contents of hazelcast-config.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.7.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>group-name</name>
        <password>group-pass</password>
    </group>
  <properties>
     <property name="hazelcast.discovery.enabled">true</property>
  </properties>
   <network>
        <port auto-increment="false">5700</port>
        <outbound-ports>
            <ports>0</ports>
        </outbound-ports>
        <join>
            <multicast enabled="false" />
            <tcp-ip enabled="false" />
            <aws enabled="false" />
           <discovery-strategies>
              <discovery-strategy  enabled="true" class="com.hazelcast.aws.AwsDiscoveryStrategy">
                <properties>
                   <property name="access-key">my-access-key</property>
                   <property name="secret-key">my-secret-key</property>
                   <property name="iam-role">IAM_ROLE</property>
                   <property name="region">us-west-1</property>
                   <property name="tag-key">TagName</property>
                   <property name="tag-value">TagValue</property>
                   <property name="hz-port">5700</property>
                </properties>
              </discovery-strategy>
            </discovery-strategies>
        </join>
      </network>
</hazelcast>
```

## Environment ##
* **Payara Version**: 4.1.1.171.1
* **Hazelcast Version**: 3.7.4
* **JDK Version**: 8 u131 - OpenJDK
* **Operating System**: Linux - Amazon Linux

### PR DESCRIPTION
**Pull request by mesutcelik**
fixes #10994 

The problem in #10994  is that BundlePlugin generates MANIFEST.MF export/import packages before maven-shade-plugin relocates eclipsesource classes. That makes `com.hazelcast.com.eclipsesource.json` not visible to OSGI because `Export-Package:` in MANIFEST.MF is already generated. 

Apparently, `hazelcast-aws` is using this package for JSON Parsing and fails in OSGI environment.

There are two solutions to that

1. Remove `com.hazelcast.com.eclipsesource.json` dependency on `hazelcast-aws` and use directly any other JSON Parser
2. Play with the order of maven plugin executions by first creating uber jar,extracting to classes folder, generate MANIFEST.MF and create the jar again.

I have tried to implement 2nd solution but It fails in the last part of creating jar file. I just commented maven-jar-plugin and seems the rest works fine.

@Donnerbart @hasancelik any idea? 
You can simply run `mvn clean package -DskipTests` in this PR and see `com.hazelcast.com.eclipsesource.json` added as Export package.

### CODE REVIEW

**Comment by mesutcelik** [comment]
run-lab-run

**Comment by mesutcelik** [comment]
verify

**Comment by mesutcelik** [comment]
As you see in the https://github.com/hazelcast/hazelcast/pull/11318/commits/e686b4e149315f69f464aec4ab72d2a59618d4cf , I added two executions of jar plugin. Current execution is as follows

1. maven-jar-plugin(id:default-jar) creates an hazelcast.jar with a default MANIFEST.MF
2. maven-shade-plugin creates an uber jar with its two dependencies
3. maven-dependency-plugin unpacks uber jar for maven-bundle-plugin
4. maven-bundle-plugin generates MANIFEST.MF
5. maven-jar-plugin(id:latest-artifact) creates the jar file with latest MANIFEST.MF and classes

**Comment by mesutcelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by mesutcelik** [comment]
run-lab-run

**Comment by mesutcelik** [comment]
@noctarius or @jerrinot Can you guys have a look at this when you have time?

**Comment by mesutcelik** [comment]
please see https://github.com/hazelcast/hazelcast/issues/10994

**Pull request closed without merging**
