### PR TITLE
Remove unused constants

### PR DESCRIPTION
**Pull request by mmedenjak**

### CODE REVIEW

**Comment by asimarslan** [comment]
@mmedenjak What about renumbering these factoryId's when we chance in 4.0?

**Comment by mmedenjak** [comment]
Renumbering how?

**Comment by asimarslan** [comment]
`public static final int MAP_DS_FACTORY_ID = -10;`
jumps to -10. we can continue with -4 instead. 
`public static final int QUEUE_DS_FACTORY_ID = -11;` can be -5 and so on.

**Comment by mmedenjak** [comment]
@asimarslan done.

**Comment by Holmistr** [comment]
run-lab-run

**Comment by Holmistr** [comment]
run-lab-run

**Comment by Holmistr** [comment]
run-lab-run

**Comment by Holmistr** [comment]
run-lab-run

**Comment by Holmistr** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
As agreed with Sancar, closing in favour of https://github.com/hazelcast/hazelcast/pull/16028. Thank you for the review @vojtechtoman anyway :)

**Pull request closed without merging**
