### PR TITLE
Removed deprecated Properties

### PR DESCRIPTION
**Pull request by pveentjer**
Since these classes have moved to internal, we don't need to offer the public
ones anymore.

No enterprise PR required.

### CODE REVIEW

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by pveentjer** [comment]
run-lab-run

**Comment by jerrinot** [comment]
@pveentjer, @Donnerbart: guys, did you check other modules/plugins?

**Comment by Donnerbart** [comment]
I'm quite sure that I ported everything to the new classes before the plugins got ripped out. I'm also not sure if any of the plugins is at 3.8-SNAPSHOT yet. But I'll check them out (I think I should have all of them locally due to the CheckStyle alignments).

As I stated above, the code samples could have a left over, but I'll check that as well.

**Comment by Donnerbart** [comment]
I've checked all relevant repos and they are all fine.

**Pull request merged**
