### PR TITLE
Moves accessors out of HazelcastTestSupport

### PR DESCRIPTION
**Pull request by vbekiaris**
`HazelcastTestSupport` currently serves both as
common superclass of several tests and as a
utility class for public static accessors to
Hazelcast internals. The latter results in
`HazelcastTestSupport` referencing too many classes
which need to be loaded as the first test class
is being loaded. This is an issue for compatibility
tests execution which rely on dynamically
attaching an agent, resulting in too many classes
having been already loaded before the agent
is attached. Moving the accessors to a separate
class resolves the issue, by deferring important
classes loading to a time after the agent is
attached.

This PR includes only the `Accessors` class creation
and the result of refactor move action, no manual
changes were done.

An EE-side PR is required.

### CODE REVIEW

**Comment by tkountis** [comment]
Can't we statically import the `Accessors` to avoid the line changes ... nit-picking

**Comment by vbekiaris** [comment]
> Can't we statically import the Accessors to avoid the line changes

I would gladly do that if there is a way to do it in bulk in IntelliJ, but I don't know if it is possible.

**Comment by vojtechtoman** [comment]
One way to use only static imports for `Accessors` might be to add `import static` for each `Accessors` method to all test files (might be possible with a single search & replace of `import com.hazelcast.test.Accessors` over all test files; otherwise I would use `sed`) and then do "Optimize imports" on all tests.

**Comment by vbekiaris** [comment]
@vojtechtoman @tkountis thanks for your suggestions, optimize imports + a bit of regex-fu did the trick. PR looks a lot cleaner now.

**Comment by vbekiaris** [comment]
@vojtechtoman @sancar @tkountis thanks for the reviews

**Pull request merged**
