### PR TITLE
Minor invocation cleanup

### PR DESCRIPTION
**Pull request by pveentjer**

### CODE REVIEW

**Comment by Donnerbart** [comment]
Had some test failures which seem to be unrelated: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2032/

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by pveentjer** [comment]
run-lab-run

**Comment by jerrinot** [comment]
:+1:

**Comment by Donnerbart** [comment]
:+1:

**Pull request merged**
