### PR TITLE
Respect `migrating` flag while computing member state

### PR DESCRIPTION
**Pull request by taburet**
Before this change, member state was considered safe once all migrations
are committed. Technically, after that point a member can safely execute
queries. But some queries might be executed using full scans (instead of
index scans) since global indexes are populated during the migration
finalization phase which goes after the migration commit phase.

Tests verifying indexing behavior expect indexes to be fully populated
once member state reported as safe. There was an attempt to fix that:
https://github.com/hazelcast/hazelcast/pull/17738, but apparently it
introduced some race condition in migration management leading to
assertion and test failures.

This fix also considers a member to be safe only after the finalization
phase is finished on it, but does it in a different way without changing
the migration logic.

Fixes: https://github.com/hazelcast/hazelcast/issues/17805

### CODE REVIEW

**Comment by vbekiaris** [comment]
The fix looks good. I am wondering whether the original fix in #17738 is actually needed.

The change introduced in #17738 changed the definition of "safe state" from "Safe state means; all backups of partitions currently owned by local member are in sync when this method is called." to also include "and indexes are populated".

The test failure in [`PartitionIndexingTest`](https://github.com/hazelcast/hazelcast/issues/17724) that was fixed by #17738 was not an issue of incorrect query results; it was rather an issue of the test (erroneously) expecting that achieving safe state implies that indexes are populated. Even if indexes are not populated, query results will be correctly returned due to falling back to partition scan.

If my understanding is correct, then probably we should revert the change of "safe state" definition introduced in #17738? Reasoning is that it can prolong the time it takes to reach safe state and does not provide better correctness guarantee than what was already provided. Instead we should fix the `PartitionIndexingTest` to assert eventual index population. 

wdyt @taburet @petrpleshachkov ?

**Comment by taburet** [comment]
@vbekiaris my reasoning was to keep the extended safe state definition since the safe state check is mostly used by tests and status reporting in the tooling, nothing critical depends on it. But probably that creates too clean environment for the tests not relying on indexes being populated.

**Review by petrpleshachkov — APPROVED** [review]

**Comment by petrpleshachkov** [comment]
I'd aslo keep the extended SAFE semantics including indexes being populated.

**Review by vbekiaris — APPROVED** [review]

**Comment by vbekiaris** [comment]
@taburet thanks for the investigation & fix, @petrpleshachkov thanks for the review

**Comment by ahmetmircik** [comment]
This also seems to prolong waiting times for hot-restart service: [waitPartitionReplicaSyncOnCluster](https://github.com/hazelcast/hazelcast-enterprise/blob/1764c5001a862ccaa9bd9e7ff2ea78cb1c4f9eef/hazelcast-enterprise/src/main/java/com/hazelcast/internal/hotrestart/HotRestartIntegrationService.java#L1052)

**Comment by vbekiaris** [comment]
@taburet can you backport the fix to `4.1.z` and `4.0.z`?

**Pull request merged**
