### PR TITLE
Updated Mockito version to 5.3.1 after JDK update

### PR DESCRIPTION
**Pull request by arodionov**
EE PR: https://github.com/hazelcast/hazelcast-enterprise/pull/6048

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

**Comment by arodionov** [comment]
run-lab-run

**Comment by arodionov** [comment]
run-nightly-tests

**Comment by arodionov** [comment]
run-nightly-tests

**Comment by arodionov** [comment]
run-nightly-tests

**Review by TomaszGaweda — APPROVED** [review]

**Comment by TomaszGaweda** [comment]
run-nightly-tests

**Comment by TomaszGaweda** [comment]
run-nightly-tests

**Comment by TomaszGaweda** [comment]
run-nightly-tests

**Comment by TomaszGaweda** [comment]
run-nightly-tests

**Comment by arodionov** [comment]
run-nightly-tests

**Comment by arodionov** [comment]
Merging, since failed `Hazelcast-pr-nightly-tests` tests are not related to the current PR.

**Pull request merged**
