### PR TITLE
priorityPendingCount returns scheduleQueue.prioritySize()

### LINKED ISSUE #6318: Possible issue in OperationThread
It looks like ```OperationThread.priorityPendingCount()``` should be returning ```scheduleQueue.prioritySize()``` instead of ```scheduleQueue.normalSize()```

```
    @Probe
    int priorityPendingCount() {
        return scheduleQueue.normalSize();
    }

    @Probe
    int normalPendingCount() {
        return scheduleQueue.normalSize();
    }

```

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #6318 

Thanks to @juanavelez for reporting this!

### CODE REVIEW

**Comment by pveentjer** [comment]
:+1:

**Comment by pveentjer** [comment]
Probably needs to be backported to 3.5

**Comment by jerrinot** [comment]
For the record: Probes are integrated in 3.6 -> There is nothing to backport.

**Comment by pveentjer** [comment]
Doh... and I'm the one responsible for integrating it :)

**Comment by pveentjer** [comment]
https://s-media-cache-ak0.pinimg.com/736x/92/55/ea/9255ea271f96d03bd1774ccb771d7ec9.jpg

**Comment by pveentjer** [comment]
9255ea271f96d03bd1774ccb771d7ec9

**Pull request merged**
