### PR TITLE
Cleanup warnings for deprecated readUTF() and writeUTF() calls [HZ-2381]

### PR DESCRIPTION
**Pull request by orcunc**
Jira : https://hazelcast.atlassian.net/browse/HZ-2381 

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [x] Request reviewers if possible

### CODE REVIEW

**Review by TomaszGaweda — APPROVED** [review]

**Comment by JackPGreen** [comment]
@orcunc this is a draft - are there further changes expected? I can still see more usages of `writeUTF`.

**Comment by orcunc** [comment]
> @orcunc this is a draft - are there further changes expected? I can still see more usages of `writeUTF`.

It is ready for review. I forgot to make it ready

**Comment by JackPGreen** [comment]
> > @orcunc this is a draft - are there further changes expected? I can still see more usages of `writeUTF`.
> 
> It is ready for review. I forgot to make it ready. The remaining writeUTF() calls are coming from java.io.DataOutput interface.

Ok thanks - I can still see some usages of `writeUTF`, e.g. used in `CPMemberInfo` and declared in `ObjectOutputStream`.

Are we expecting all references to be removed in this PR?

**Comment by orcunc** [comment]
> Ok thanks - I can still see some usages of `writeUTF`, e.g. used in `CPMemberInfo` and declared in `ObjectOutputStream`.
> 
> Are we expecting all references to be removed in this PR?

ObjectOutputStream is JDK class. It has only writeUTF() method. Somebody in Hazelcast decided to deprecate overriden writeUTF () method and use writeString() instead. The compiler is giving warnings. So I am fixing them for a clean output. Otherwise deprecation did not make sense in my opinion back then.  Why on earth would somebody deprecate overriden JDK method in a mystery

**Comment by JackPGreen** [comment]
> > Ok thanks - I can still see some usages of `writeUTF`, e.g. used in `CPMemberInfo` and declared in `ObjectOutputStream`.
> > Are we expecting all references to be removed in this PR?
> 
> ObjectOutputStream is JDK class. It has only writeUTF() method. Somebody in Hazelcast decided to deprecate overriden writeUTF () method and use writeString() instead. The compiler is giving warnings. So I am fixing them for a clean output. Otherwise deprecation did not make sense in my opinion back then. Why on earth would somebody deprecate overriden JDK method in a mystery

Thanks for the clarification, I got mixed up with `ObjectOutputStream` - what I meant was that `PortableWriter` still declares the `writeUTF` method for example.

**Comment by orcunc** [comment]
> > > Ok thanks - I can still see some usages of `writeUTF`, e.g. used in `CPMemberInfo` and declared in `ObjectOutputStream`.
> > > Are we expecting all references to be removed in this PR?
> > 
> > 
> > ObjectOutputStream is JDK class. It has only writeUTF() method. Somebody in Hazelcast decided to deprecate overriden writeUTF () method and use writeString() instead. The compiler is giving warnings. So I am fixing them for a clean output. Otherwise deprecation did not make sense in my opinion back then. Why on earth would somebody deprecate overriden JDK method in a mystery
> 
> Thanks for the clarification, I got mixed up with `ObjectOutputStream` - what I meant was that `PortableWriter` still declares the `writeUTF` method for example.

Changing PortableWriter would break backward compatibility. We can do it later

**Comment by JackPGreen** [comment]
> Changing PortableWriter would break backward compatibility. We can do it later

Do you have a specific example where this might happen? Just want to be sure we don't introduce the same problem with this change.

**Comment by orcunc** [comment]
> > Changing PortableWriter would break backward compatibility. We can do it later
> 
> Do you have a specific example where this might happen? Just want to be sure we don't introduce the same problem with this change.

If customer has code like this it will break
```java
public class Foo implements Portable {
  ...

  @Override
  public void writePortable(PortableWriter writer) throws IOException {
    writer.writeUTF(...);
  }

} 
```

**Review by JackPGreen — APPROVED** [review]

**Pull request merged**
