### PR TITLE
Get rid of ResponseParameters for single response

### PR DESCRIPTION
**Pull request by sancar**
ClientCodec returns the parameters on a different object.
This is necessary for a multivariable response but for single
types it is an unnecessary object.

I haven’t touched the requests since it is not common to have 
a single type request. And they are not critical ones. 

Protocol pr: https://github.com/hazelcast/hazelcast-client-protocol/pull/328

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1293/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1293/Hazelcast-pr-builder-1293.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.12:check (default) on project hazelcast: failed with 220 bugs and 0 errors -> [Help 1]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1302/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1302/Hazelcast-pr-builder-1302.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/main/java/com/hazelcast/internal/diagnostics/Diagnostics.java:223: Line has trailing spaces. [RegexpSingleline]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1308/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1308/Hazelcast-pr-builder-1308.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/main/java/com/hazelcast/internal/diagnostics/Diagnostics.java:223: Line has trailing spaces. [RegexpSingleline]
--------------------------
</details>
</pre>

**Comment by sancar** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1311/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1311/Hazelcast-pr-builder-1311.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ScheduledExecutorServiceBasicTest.scheduleOnMember_testMemberLostEvent:1112->HazelcastTestSupport.assertTrueEventually:1344->HazelcastTestSupport.assertTrueEventually:1242->lambda$scheduleOnMember_testMemberLostEvent$2:1114 ? NullPointer
[INFO] 
[ERROR] Tests run: 31085, Failures: 0, Errors: 1, Skipped: 1001
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by sancar** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1318/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1318/Hazelcast-pr-builder-1318.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientReliableTopicOnClusterRestartTest.shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant:185->lambda$shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant$5:187
[INFO] 
[ERROR] Tests run: 31085, Failures: 1, Errors: 0, Skipped: 1001
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by sancar** [comment]
Failed by an unrelated test failure. Reported here https://github.com/hazelcast/hazelcast/issues/17015

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1322/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1322/Hazelcast-pr-builder-1322.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR] com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.clientSmokeTest(com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest)
[ERROR]   Run 1: AdvancedNetworkClientIntegrationTest.setup:77 Cluster size is not correct. Expected: 3, actual: 15, instance index: 0
[ERROR]   Run 2: AdvancedNetworkClientIntegrationTest.tearDown:82 NullPointer
[INFO] 
[ERROR]   AdvancedNetworkClientIntegrationTest.com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest ? IllegalState
[ERROR] com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testClientMembersList(com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest)
[ERROR]   Run 1: AdvancedNetworkClientIntegrationTest.setup:77 Cluster size is not correct. Expected: 3, actual: 6, instance index: 0
[ERROR]   Run 2: AdvancedNetworkClientIntegrationTest.tearDown:82 NullPointer
[INFO] 
[ERROR] com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testClientMembershipEvent(com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest)
[ERROR]   Run 1: AdvancedNetworkClientIntegrationTest.setup:77 Cluster size is not correct. Expected: 3, actual: 9, instance index: 0
[ERROR]   Run 2: AdvancedNetworkClientIntegrationTest.tearDown:82 NullPointer
[INFO] 
[ERROR] com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testClientViewOfAddressMap(com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest)
[ERROR]   Run 1: AdvancedNetworkClientIntegrationTest.testClientViewOfAddressMap:116 ? IllegalState
[ERROR]   Run 2: AdvancedNetworkClientIntegrationTest.tearDown:82 NullPointer
[INFO] 
[ERROR] com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testGetScheduledFutures(com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest)
[ERROR]   Run 1: AdvancedNetworkClientIntegrationTest.setup:77 Cluster size is not correct. Expected: 3, actual: 18, instance index: 0
[ERROR]   Run 2: AdvancedNetworkClientIntegrationTest.tearDown:82 NullPointer
[INFO] 
[ERROR] com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testPartitions(com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest)
[ERROR]   Run 1: AdvancedNetworkClientIntegrationTest.setup:77 Cluster size is not correct. Expected: 3, actual: 12, instance index: 0
[ERROR]   Run 2: AdvancedNetworkClientIntegrationTest.tearDown:82 NullPointer
[INFO] 
[ERROR] com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testScheduleOnMember(com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest)
[ERROR]   Run 1: AdvancedNetworkClientIntegrationTest.setup:77 Cluster size is not correct. Expected: 3, actual: 21, instance index: 0
[ERROR]   Run 2: AdvancedNetworkClientIntegrationTest.tearDown:82 NullPointer
[INFO] 
[INFO] 
[ERROR] Tests run: 3858, Failures: 0, Errors: 8, Skipped: 14
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1333/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1333/Hazelcast-pr-builder-1333.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TransactionQueueTest.testIssue859And863_WhenInQueueOnSecondInstance_OutQueueOnFirstInstance:379->testIssue859And863:412->HazelcastTestSupport.assertTrueEventually:1344->HazelcastTestSupport.assertTrueEventually:1242 expected:<3000> but was:<2998>
[INFO] 
[ERROR] Tests run: 31114, Failures: 1, Errors: 0, Skipped: 1001
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Pull request merged**
