### PR TITLE
Moved ResultSet class to util package

### PR DESCRIPTION
**Pull request by ahmetmircik**
__Reasoning__:
This is not a class only used by replicated map also query-engine uses it.

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by pveentjer** [comment]
Is this a public class or a private class? If private, we should consider moving it to com.hazelcast.internal.util.

**Comment by ahmetmircik** [comment]
@pveentjer done

**Pull request merged**
