### PR TITLE
Feature: Improve batching in write-behind processor [5.3.z]

### PR DESCRIPTION
**Pull request by lukasblu**
Back-port of [PR 24672](https://github.com/hazelcast/hazelcast/pull/24672)

### CODE REVIEW

**Comment by ahmetmircik** [comment]
run-lab-run

**Review by ahmetmircik — APPROVED** [review]

**Comment by lukasblu** [comment]
Hi @vbekiaris ,
as mentioned on https://github.com/hazelcast/hazelcast/pull/24672 , I also changed the test here to SlowTest.

**Comment by vbekiaris** [comment]
run-lab-run

**Review by vbekiaris — APPROVED** [review]

**Comment by vbekiaris** [comment]
run-lab-run

**Pull request merged**
