### PR TITLE
Race in MapReduce fixed

### PR DESCRIPTION
**Pull request by jerrinot**
See commit messages for details.

I believe this race was responsible for hanging Map/Reduce tests. 
I'm re-enabling them and let's see.

### CODE REVIEW

**Comment by jerrinot** [comment]
verify

**Comment by jerrinot** [comment]
verify

**Comment by noctarius** [comment]
:+1: looks good, I like the extraction of the scheduler part

**Comment by toktarev** [comment]
:+1: looks good

**Comment by sancar** [comment]
I have bad news. Todays failures seem related:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/659/#showFailuresLink
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/675/#showFailuresLink

**Comment by jerrinot** [comment]
@sancar :(
from the other hand - there seems to be quite a few non-M/R test failures. Can we enable verbose GC on the build server? @bilalyasar ?

**Comment by sancar** [comment]
@jerrinot Other test failures in client looks like caused by not closed instances. 
And there is another test that failed in both links
which already have an opened issue
https://github.com/hazelcast/hazelcast/issues/6055

**Pull request merged**
