### PR TITLE
[CP] Client protocol client side improvemets and JCache tasks

### PR DESCRIPTION
**Pull request by asimarslan**

### CODE REVIEW

**Comment by asimarslan** [comment]
This PR, is the last one before replacing hazelcast-client module with hazelcast-client-new module and delete all *Request and related classes. A huge clean-up PR will follow this PR.

**Comment by asimarslan** [comment]
Please note that, If we delete the requests in this PR, it becomes so big that github cannot even display it for reviewing so we just keep the requests as dead code to be removed in the next PR

**Comment by sancar** [comment]
:+1:

**Comment by asimarslan** [comment]
This PR is quite big. It will be followed by  a clean up PR. So I will merge it. Please comment on this PR. we will resolve them in the following PR.

**Comment by mdogan** [comment]
First of all, can you squash the last commits, some of them don't mean anything.. *fix pom*.. etc

**Pull request merged**
