### PR TITLE
Update stream-to-stream join TDD for fault-tolerance

### PR DESCRIPTION
**Pull request by viliam-durina**

### CODE REVIEW

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by viliam-durina** [comment]
run-lab-run

**Review by Fly-Style — APPROVED** [review]

**Comment by Fly-Style** [comment]
run-sql-only

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by viliam-durina** [comment]
run-lab-run

**Pull request merged**
