### PR TITLE
When using InMemoryFormat.OBJECT Ability to mark data as immutable to remove seralisation cost on local operations

### PR DESCRIPTION
**Pull request by shiv-sivaram**
This is our attempt at addressing https://github.com/hazelcast/hazelcast/issues/21198

Creating a draft PR to get your feedback on the approach that we have taken.

- We have created a marker interface `com.hazelcast.map.Immutable` to identify Immutable Objects
-  Changed the `Data` type to `Object` as needed (in `put`, `putIfAbsent`, `get` and a few more) to connect the operation to storage
- Moved serialisation to the points where it is needed.

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

**Comment by vbekiaris** [comment]
@ahmetmircik can you please have a look at the changes and see if you think these are in the right direction? See also the discussion on #21198

**Comment by ahmetmircik** [comment]
@vbekiaris please see: https://github.com/hazelcast/hazelcast/issues/21198#issuecomment-1143565294

**Comment by ashley-taylor** [comment]
@ahmetmircik any feedback for this PR?

**Comment by vbekiaris** [comment]
As feature freeze for 5.2 beta is quite close, this PR will be considered for inclusion in 5.3.

**Comment by vibhuti-phocas** [comment]
Hello @ahmetmircik, we have opened this PR to get your feedback on the approach we have taken. We will greatly appreciate a feedback from you as that will help us complete the remaining work. Thanks

**Comment by ahmetmircik** [comment]
Hi @vibhuti-phocas, i was busy with something else, i will try to review this PR in next week hopefully.

**Comment by ahmetmircik** [comment]
Hi @vibhuti-phocas,

Please let me know,  in my recap, if something is missing from my understanding of this work:

- You are using hazelcat in embedded mode, so not reaching hazelcast-server instances over hazelcast-client. 
- You are trying to eliminate serde(serialization-deserialization) penalty for local put/putIfAbsent/get, calls on remote nodes will still have this penalty.
- You have no backups, so maps are configured with 0 backup.
- You have large objects like 5MB in size.

**Comment by ashley-taylor** [comment]
@ahmetmircik 
yip trying to remove the penalty.
Run with no backups objects are easily rebuilt. 
All stored objects are immutable.
Heavily use execute on key to manipulate large objects. Also, use it to perform analysis which also incurs the penalty.
This creates a new immutable object. 
Objects range in size from 5MB to 100's MB

**Comment by ahmetmircik** [comment]
@ashley-taylor thanks for the confirmation.

Let me share what i think with you, having immutability makes sense but how should we introduce it in a simple and maintainable form without increasing complexity, this is the question in my mind. Additionally we have enterprise code base working based on open-source operations, backward compatibility guarantees, all have to be taken into consideration. Scope seems large.

Given the change has a potential to impact related/unrelated all use cases, for now what seems plausible to me is using as much as existing functionality to address your use case.

I think our mental model for the solution should be based on entry-processors(EP) usage, for example, local `puts` can be done by using EP without ser/de penalty. Just make your large object a field of EP and put it into `OBJECT` formatted map, this eliminates local ser/de cost. `gets` can also be implemented in this way. 

Otherwise it seems we cannot manage to address this in next 5.3 release.

**Pull request closed without merging**
