### PR TITLE
Protocol tests for 1.1 and 1.2 added

### PR DESCRIPTION
**Pull request by mustafaiman**
I generated binary files and tests for 1.1 and 1.2 from client protocol repo.
`1.2.protocol.errorCodec.compatibility.binary` is 0 bytes and `throwables_1_2` is empty because there is no new error added in 1.2.

### CODE REVIEW

**Comment by ihsandemir** [comment]
Can you do auto-format in IDE for the committed tests?

**Comment by mustafaiman** [comment]
@ihsandemir done

**Comment by mustafaiman** [comment]
run-lab-run

**Comment by mustafaiman** [comment]
run-lab-run

**Comment by ihsandemir** [comment]
👍

**Pull request merged**
