### PR TITLE
Workaround for "Illegal character" issue (#3752)

### PR DESCRIPTION
**Pull request by idf3d**
This is small workaround for issue #3752, it shouldn't provide any regression but resolves issue. I'm not sure is it will be good idea to undo changes that provided regression, so i'm just applying this solution.

### CODE REVIEW

**Comment by pveentjer** [comment]
@idf3d thanks for the PR. Can you also add some tests to see that if a space ends up the url, the fix works like expected?

@gurbuzali we should get this imho merged.  It doesn't change anything for url's that don't have spaces in them.

**Comment by pveentjer** [comment]
I'm going to close this PR for the time being. After you have added some tests, I would be happy to re-open this ticket and to get it merged.

**Comment by Vampire** [comment]
I'd also like to see this merged. If you have your app server in a location with space or have an application name with space like "applicationName 1.0", you run into the error, this is really bad. :-(

**Comment by jerrinot** [comment]
I'm re-opening the original issue.

**Comment by PeterVanDerVelde** [comment]
Using tomcat 8 with java 8 I run into a similar issue(only not spaces but ^ and !):
```
13-Jul-2017 11:42:25.846 SEVERE [localhost-startStop-1] com.hazelcast.util.ServiceLoader.null Illegal character in opaque part at index 118: jar:war:file:/D:/repositories/server/test-portal-0.1-SNAPSHOT.war^/WEB-INF/lib/hazelcast-3.8.3.jar!/META-INF/services/com.hazelcast.instance.NodeExtension
 java.net.URISyntaxException: Illegal character in opaque part at index 118: jar:war:file:/D:/repositories/server/test-portal-0.1-SNAPSHOT.war^/WEB-INF/lib/hazelcast-3.8.3.jar!/META-INF/services/com.hazelcast.instance.NodeExtension
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at com.hazelcast.util.ServiceLoader.collectFactoryUrls(ServiceLoader.java:117)
	at com.hazelcast.util.ServiceLoader.getServiceDefinitions(ServiceLoader.java:90)
	at com.hazelcast.util.ServiceLoader.classIterator(ServiceLoader.java:81)
	at com.hazelcast.instance.NodeExtensionFactory.create(NodeExtensionFactory.java:38)
	at com.hazelcast.instance.DefaultNodeContext.createNodeExtension(DefaultNodeContext.java:38)
	at com.hazelcast.instance.Node.<init>(Node.java:191)
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:159)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:127)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.anachron.service.hazelcast.HazelcastService.init(HazelcastService.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4797)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5221)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:581)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1685)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ravichappa22** [comment]
This is really a big issue as we see most of the windows OS based application servers deployed under folder "Program Files" which has space and they are not converted to replace with %20, but Mac or Linux based working fine, anyone fix this issue or found a work around please suggest, I am at the same problem  @mmedenjak @Vampire @pveentjer @idf3d

**Pull request closed without merging**
