### PR TITLE
Do not throw NPE when intermediate field is an interface

### PR DESCRIPTION
**Pull request by jerrinot**
and the interface does not contain a requested attribute

The issue was originally reported by @wimdeblauwe
 at #6151 Thanks to @serkan-ozal for analysis!

### CODE REVIEW

**Comment by jerrinot** [comment]
I'll prepare a backport once this is reviewed.

**Comment by jerrinot** [comment]
@serkan-ozal: can you please have a look at this one? thanks!

**Comment by serkan-ozal** [comment]
:+1:

**Comment by serkan-ozal** [comment]
This PR fixes NPE but doesn't cover all issue.

@jerrinot will you work on the other problem that is about finding field on field's dynamic type rather than static field type?

**Comment by jerrinot** [comment]
@serkan-ozal: I know it's not fixing the whole issue. The requested use-case is not supported at the moment. This is just fixing the NPE which is obviously a clear bug.

I have hacked an experiment to add somewhat more dynamic behaviour - the naive implementation is rather simple: See this: https://github.com/jerrinot/hazelcast/commit/7b2811f688e9565ca2243907c8f29ec673f68615

but it's not without side-effects: The getters are cached - so it means it uses the first passed object as q blueprint to get actual (=not just declared) types. However what if another object instance returns a different implementation? It's all solvable, but it won't be easy (without performance regressions)

**Comment by serkan-ozal** [comment]
@jerrinot I am not sure also performance overhead of `method.invoke(...)` like you.
Even though this doesn't solve all issues, I think we may use dynamic type checking only if field type is interface or abstract class. If not (I know, still it may be a non-abstract base class), we can simple skip dynamic type checking and can go as it is.

**Comment by ajermakovics** [comment]
:+1:

**Pull request merged**
