### PR TITLE
Increased code coverage of OperationFactory implementations

### PR DESCRIPTION
**Pull request by Donnerbart**
Fixed code coverage issues of
* `AddDynamicConfigOperationFactory`
* `DeregistrationOperationFactory`
* `RegistrationOperationFactory`

### CODE REVIEW

**Comment by mdogan** [comment]
I was planning to use `com.hazelcast.util.function.Supplier<Operation>` instead of `OperationFactory` in `InvocationUtil.invokeOnStableClusterSerial()`.  We use `OperationFactory` only to create operation via `Operation createOperation()` locally. That's why serialization methods are never called.

**Comment by Donnerbart** [comment]
Ah, right, the `OperationFactory` is normally used over-the-write via `invokeOnAllPartitions()`. So these classes would look like `ReAuthenticationOperationSupplier` in the end`? Sounds good to me.

**Comment by pveentjer** [comment]
So we get more testing for a solution that we should get rid of?

**Comment by mdogan** [comment]
See https://github.com/hazelcast/hazelcast/pull/11579

**Pull request closed without merging**
