### PR TITLE
Remove duplicate MBeans

### PR DESCRIPTION
**Pull request by blazember**
Having the metrics MBean exposed, several MBeans are just duplicates and
can be removed. This commit removes the following MBeans:
- `ClientEngineMBean`
- `EventServiceMBean`
- `NetworkingServiceMBean`
- `OperationServiceMBean`
- `ProxyServiceMBean`

Implements #16265

### CODE REVIEW

**Comment by blazember** [comment]
run-lab-run

**Comment by blazember** [comment]
run-lab-run

**Comment by pveentjer** [comment]
The best kind of code improvement; the one removing superfluous code.

**Comment by blazember** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Unrelated test failures, merging.

**Pull request merged**
