### PR TITLE
Make PagingPredicate generic

### PR DESCRIPTION
**Pull request by LoneRifle**
Follows up on #7840, allowing users who extend this class to likewise take advantage of now-exposed generics

### CODE REVIEW

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by LoneRifle** [comment]
Located checkstyle error with modified suppressions.xml for Windows. Will issue a separate PR for that.

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by pveentjer** [comment]
Seems like an OK change, but I'm not an expert of the paging predicate. @gurbuzali can you have a look at this one.

**Comment by gurbuzali** [comment]
looks fine :+1:

**Comment by pveentjer** [comment]
There is one last concern, backwards compatibility. Just to make sure that we don't run into an unexpected generics incompatibility problems. @mtopolnik @jerrinot WDYT?

**Comment by mtopolnik** [comment]
`Comparator<Map.Entry<K, V>>` is stricter than the previous `Comparator<Map.Entry>>`.

**Comment by LoneRifle** [comment]
That shouldn't be a problem if PagingPredicate is instantiated without type parameters; you can still supply a `Comparator<Map.Entry>`. Or am I mistaken?

**Comment by pveentjer** [comment]
The question is regarding binary compatibility. So can people replace 3.6 by 3.7 without needing to recompile the code.

**Comment by LoneRifle** [comment]
Given generics in Java is implemented using type erasure, I do not foresee any binary compatibility breaks, as type parameters do not affect the binary identity of a method signature.

**Comment by vbekiaris** [comment]
You can always use [sigtest](https://wiki.openjdk.java.net/display/CodeTools/sigtest) to verify binary compatibility. I have already generated a [signature file for Hazelcast 3.6.0 - hazelcast-3.6.sig.zip](https://github.com/hazelcast/hazelcast/files/252394/hazelcast-3.6.sig.zip), you should be able to check for binary compatibility with something like this cmd line:
```bash
$ java -jar sigtestdev.jar Test -Mode bin -B -static -classpath \
$JDK_HOME/jre/lib/rt.jar:$YOUR_PATH_HERE/hazelcast/target/hazelcast-3.7-SNAPSHOT.jar:$HOME/.m2/repository/com/google/code/findbugs/annotations/3.0.0/annotations-3.0.0.jar  \
-filename $YOUR_SIGFILE_PATH_HERE/hazelcast-3.6.sig
```

**Comment by tombujok** [comment]
It's a follow up on the https://github.com/hazelcast/hazelcast/pull/7840
I'll give my thumbs up if the binary compatibility is checked (IMHO it should be fine)

**Comment by LoneRifle** [comment]
Verified at https://gist.github.com/LoneRifle/ae7c883319493f1c86243466cacf873f . Note that two passes had to be done to account for the addition of IMap.setAsync.

**Comment by tombujok** [comment]
👍 
@ahmetmircik could you have a look too?

**Comment by tombujok** [comment]
Actually we have two thumbs-up already. Merging!

**Pull request merged**
