### PR TITLE
fix issue #3752: do not transform a URL with spaces into a URI

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by serkan-ozal** [comment]
Hi @Vampire 

Thanks for your contribution.

Not very important but I would use different service interface rather than `ServiceLoaderTestInterface` since it is already there for another tests and for this reason we assert the size as `2`. Because this behaviour might confuse others at first sight.

**Comment by Vampire** [comment]
As you wish @serkan-ozal, both PRs are adapted accordingly.

**Comment by serkan-ozal** [comment]
:+1:

**Comment by jerrinot** [comment]
:+1:

**Comment by jerrinot** [comment]
@Vampire: hello,

many thanks for your contribution, it's very much appreciated. I apologize for being quite slow to respond.

Could you please sign our contribution agreement: https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

then we'll be able to (finally!) merge your PR.

**Comment by Vampire** [comment]
@jerrinot I just sent the CLA to enes

**Comment by mesutcelik** [comment]
Thanks @Vampire

**Comment by jerrinot** [comment]
:clap:

**Comment by Vampire** [comment]
Great. :-) Any chance this also makes it into 3.6.2 like the milestone of the issue suggests?

**Pull request merged**
