### PR TITLE
Refactored map-store tests

### PR DESCRIPTION
**Pull request by ahmetmircik**

### CODE REVIEW

**Comment by ahmetmircik** [comment]
```
Test Result (2 failures / +2)
com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups
com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario2```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/17023/

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by gurbuzali** [comment]
since these are just test refactoring to be able to extend them on enterprise, I'm merging this

**Pull request merged**
