### PR TITLE
MapMergePolicy mergingEntry.getValue() does not return Value Object

### PR DESCRIPTION
**Pull request by mesutcelik**
**mergingEntry.getValue()** argument is always in a type of SimpleEntryView which does not return real Value Object but **com.hazelcast.nio.serialization.Data**. This is a problem for Developers who want to create their own Custom Merge Policy by manipulating real Value Object... 

Following PR converts EntryView Object into LazyEntryView Object which returns Value Object for Custom Merge Policies when **mergingEntry.getValue()** called...

### CODE REVIEW

**Comment by mesutcelik** [comment]
@ahmetmircik , 
can you have a look when you have time?

**Comment by mesutcelik** [comment]
How are we gonna proceed with that one?

**Comment by ahmetmircik** [comment]
seems mergeable to me

**Comment by ahmetmircik** [comment]
@mesutcelik Can you also please prepare a backporter PR?

**Comment by gurbuzali** [comment]
@mesutcelik we need to update LazyEntryView for other merge policies too
```
    private boolean validMergePolicyForValueNullCheck(MapMergePolicy mergePolicy) {
        return mergePolicy instanceof PutIfAbsentMapMergePolicy
                || mergePolicy instanceof PassThroughMergePolicy;
    }
```
also the name of the method is misleading

**Comment by mesutcelik** [comment]
How is this?

```
    public V getValue() {
        if (returnRawData(mergePolicy)) {
            return value;
        }
        value = serializationService.toObject(value);
        return value;
    }

    private boolean returnRawData(MapMergePolicy mergePolicy) {
        return mergePolicy instanceof PutIfAbsentMapMergePolicy
                || mergePolicy instanceof PassThroughMergePolicy
                || mergePolicy instanceof HigherHitsMapMergePolicy
                || mergePolicy instanceof LatestUpdateMapMergePolicy;
    }
```

**Comment by gurbuzali** [comment]
looks good

**Comment by mesutcelik** [comment]
ok... gonna push the change now

**Comment by mesutcelik** [comment]
*green*

**Pull request merged**
