### PR TITLE
Reverted the incorrectly changed method names back to the original name

### PR DESCRIPTION
**Pull request by ihsandemir**
Fixed the incorrectly changed method names at [merged PR](https://github.com/hazelcast/hazelcast/pull/25020) back to the original name.

Fixes the test failure at [this](https://github.com/hazelcast/hazelcast-enterprise/pull/6548) PR [run](https://jenkins.hazelcast.com/job/Hazelcast-EE-pr-builder/9256/#showFailuresLink).

### CODE REVIEW

**Comment by kwart** [comment]
run-ee-tests

**Comment by kwart** [comment]
run-ee-nightly-tests

**Comment by ihsandemir** [comment]
run-lab-run

**Comment by ihsandemir** [comment]
run-ee-nightly-tests

**Comment by ihsandemir** [comment]
nightly [failed](https://jenkins.hazelcast.com/job/Hazelcast-pr-builder-ee-nightly-tests/9/testReport/junit/com.hazelcast.it.sql.data.connection.jdbc/SqlJDBCDataConnectionTest/test_getDDLFailsInSecureCluster_dbRuleName_h2__isShared_true_/) due to [this](https://github.com/hazelcast/hazelcast-enterprise/issues/6538) issue.

**Review by emreyigit — APPROVED** [review]

**Pull request merged**
