### PR TITLE
Update docker images and ignore not supported tests for arm64 architecture [HZ-1641]

### PR DESCRIPTION
**Pull request by Patras3**
Update docker images to version which supports arm64
Ignore tests with MSSQL server for arm64

Checklist:
- [X] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [X] Label `Add to Release Notes` or `Not Release Notes content` set
- [X] Request reviewers if possible

### CODE REVIEW

**Comment by Patras3** [comment]
run-arm64

**Comment by Patras3** [comment]
run-arm64

**Comment by Patras3** [comment]
run-arm64

**Review by sumnerib — APPROVED** [review]

**Review by kwart — APPROVED** [review]

**Comment by Patras3** [comment]
fyi: arm64 pr failed with known failures

**Pull request merged**
