### PR TITLE
implementing TransactionalQueue retainAll method

### PR DESCRIPTION
**Pull request by alex-dukhno**
`TransactionalQueue#retainAll` method implementation
client protocol PR https://github.com/hazelcast/hazelcast-client-protocol/pull/298

### CODE REVIEW

**Comment by hz-highfive** [comment]
Thanks for the pull request, and welcome! The Hazelcast team is excited to review your changes, and you should hear from @Holmistr or @mmedenjak (or someone else) soon.In the meantime, make sure that you signed the CLAas described [here](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)

**Comment by Holmistr** [comment]
Hi @alex-dukhno , great to see another PR of yours :-P ... Is the PR ready, so we can run the PR builder or are you going to make some other changes?

**Comment by alex-dukhno** [comment]
Hi @Holmistr,
I need to:
 * implement `REMOVE` queue element event publishing in the `TxnRetainAllOperation` 
 * and address the question https://github.com/hazelcast/hazelcast/pull/16129#discussion_r368655578 if it is relevant ¯\\\_(ツ)\_/¯

**Comment by alex-dukhno** [comment]
@Holmistr, PR is ready to go 😃

**Comment by Holmistr** [comment]
run-lab-run

**Comment by pveentjer** [comment]
Closing PR due to lack of progress and we should not add new functionality to our TX system.

**Pull request closed without merging**
