### PR TITLE
Apply join fixes

### LINKED ISSUE #6688: ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join
```
java.lang.AssertionError: the size of the collection is not correct: found-content:[Member [127.0.0.1]:9806, Member [127.0.0.1]:9808 this, Member [127.0.0.1]:9810] expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.test.HazelcastTestSupport$6.run(HazelcastTestSupport.java:643)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:825)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:640)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:636)
	at com.hazelcast.cluster.ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join(ClusterInfoTest.java:102)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/234/testReport/junit/com.hazelcast.cluster/ClusterInfoTest/all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join/

### LINKED ISSUE #8097: ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_cluster_id
```
java.lang.AssertionError: expected:<1462416052225> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cluster.ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_cluster_id(ClusterInfoTest.java:72)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/899/testReport/junit/com.hazelcast.cluster/ClusterInfoTest/all_nodes_should_have_the_same_cluster_start_time_and_cluster_id/

### LINKED ISSUE #8273: JoinStressTest.testJoinWhenMemberClosedInBetween
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.internal.cluster.impl.MulticastJoiner.joinMaster(MulticastJoiner.java:94)
	at com.hazelcast.internal.cluster.impl.MulticastJoiner.doJoin(MulticastJoiner.java:72)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:118)
	at com.hazelcast.instance.Node.join(Node.java:650)
	at com.hazelcast.instance.Node.start(Node.java:362)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:133)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.hazelcast.cluster.JoinStressTest.testJoinWhenMemberClosedInBetween(JoinStressTest.java:342)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/967/testReport/junit/com.hazelcast.cluster/JoinStressTest/testJoinWhenMemberClosedInBetween/

### PR DESCRIPTION
**Pull request by metanet**
See commit messages for details

Fixes #6688 
Fixes #8097 
Fixes #8273

### CODE REVIEW

**Comment by metanet** [comment]
run-lab-run

**Comment by metanet** [comment]
unrelated test failure

**Comment by metanet** [comment]
run-lab-run

**Comment by mdogan** [comment]
👍

**Comment by gurbuzali** [comment]
👍

**Pull request merged**
