### PR TITLE
Fixes null logger problem in LoadFinishedFuture  

### PR DESCRIPTION
**Pull request by ahmetmircik**
NPE can be seen here https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java#L342

### CODE REVIEW

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
:+1:

**Comment by eminn** [comment]
:+1:

**Pull request merged**
