### PR TITLE
Made reading of InMemoryFormat value from XML similar to server nodes - ...

### PR DESCRIPTION
**Pull request by noctarius**
...convert to uppercase first

### CODE REVIEW

**Comment by serkan-ozal** [comment]
@noctarius can it be problem for different locales such as TR locale? For example, AFAIK when I made uppercase 'native_memory', possibly, it will be "NATİVE_MEMORY" since Turkish alphabet, "i" => "İ" (not I)

**Comment by jerrinot** [comment]
128 ASCII characters ought to be enough for everyone!

**Comment by serkan-ozal** [comment]
@noctarius Ok, upper case internal already handles this :)
@jerrinot as you know "i" is valid ASCII character and it exist in "native_memory" word. So I don't mention about non-ASCII character

**Comment by noctarius** [comment]
We would have the same problems on server side :D

**Comment by noctarius** [comment]
verify

**Pull request merged**
