### PR TITLE
Remove unnecessary return.

### PR DESCRIPTION
**Pull request by bmbferreira**

### CODE REVIEW

**Comment by mmedenjak** [comment]
Hi @bmbferreira  !

Thank you for your contribution.
Before we can merge, can you please follow the instructions to sign and send the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)? I know it might seem like a lot of ceremony for a simple fix but it's legally required and once you sign, you can contribute more fixes. 
Alternatively, if you are unable to sign, I may fix it for you and I'll mention you in the commit.

**Comment by bmbferreira** [comment]
Hi @mmedenjak! I just sent the document. Please confirm that you received it. Thanks!

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
PR builder failed with known issue `SelectWithSelectorFix_TcpIpConnection_BasicTest`, merging.

Thanks @bmbferreira for the contribution.

**Pull request merged**
