### PR TITLE
Partition movement detection uses partitionStateVersion instead just comparing owned partitions

### PR DESCRIPTION
**Pull request by jerrinot**
It's faster and more importantly it fixes the situation when there is a partition
movement while Query is running, but the member ends-up owning the same partitions
as in the beginning.

### CODE REVIEW

**Comment by gurbuzali** [comment]
:+1:

**Comment by jerrinot** [comment]
verify

**Comment by ahmetmircik** [comment]
:+1:

**Comment by jerrinot** [comment]
verify

**Pull request merged**
