### PR TITLE
Fix thread leak that kept starting new instances (backport of #20566)

### PR DESCRIPTION
**Pull request by viliam-durina**

### CODE REVIEW

**Review by olukas — APPROVED** [review]
Thanks Vilo.

**Review by Fly-Style — APPROVED** [review]

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by Fly-Style** [comment]
run-lab-run

**Comment by kwart** [comment]
run-lts-compilers

**Comment by kwart** [comment]
run-lts-compilers

**Pull request merged**
