### PR TITLE
Fixes #8876 MapReduceForMultiMapMessageTask should use MultiMapKeyValueSource

### LINKED ISSUE #8876: MapReduce and Aggregation not working on MultiMap
There is a bug in MapReduceForMultiMapMessageTask where simple MapKeyValueStore is being used instead of MultiMapKeyValueStore. This prevents MapReduce and Aggregate from working with MultiMaps.

Fixes #8875

### PR DESCRIPTION
**Pull request by ssi-hu-balint-balku**
this will make MapReduce and Aggregate work for MultiMap as well
fixes #8876

### CODE REVIEW

**Comment by jerrinot** [comment]
@ssi-hu-balint-balku many thanks! Can you also send a PR into the `maintanance-3.x` branch? 

This way the fix will be included in the next patch release. We'll need you to sign [Contributor Agreement](https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement). I hope it's ok with you.

**Comment by LoneRifle** [comment]
If you change the title so that it reads "Fix #8876: MapReduceForMultiMapMessageTask should use MultiMapKeyValueSource", the issue will automatically close when the PR is merged.

**Comment by jerrinot** [comment]
@ssi-hu-balint-balku: one more thing - can you add a test for this?

**Comment by ssi-hu-balint-balku** [comment]
@LoneRifle: renamed it, hope i am using the correct pattern now :)

@jerrinot: i'll ask the legal department of our company if there is anything making me unable to sing the agreement. i'll submit a PR into the other branch soon and will also try to add some test coverage

**Comment by ssi-hu-balint-balku** [comment]
here is the PR into maintanance-3.x branch: https://github.com/hazelcast/hazelcast/pull/8879

**Comment by LoneRifle** [comment]
Sorry, my fault, you should edit the body of the initial post on this PR to say "Fixes #8876"

https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by ssi-hu-balint-balku** [comment]
i've changed the title but looks like it was enough that you mentioned it in your last commit :)

**Comment by LoneRifle** [comment]
Erm, not really - the issue merely reports that it's been referenced from the PR, it's still not linked to close upon merge.

**Comment by ssi-hu-balint-balku** [comment]
looks like it is linked now

**Comment by jerrinot** [comment]
I'm closing this PR in favour of #8990

**Pull request closed without merging**
