### PR TITLE
Demonstrates CP FencedLock failures (supposed to fail until issue is fixed)

### PR DESCRIPTION
**Pull request by lprimak**
This PR adds test to demonstrate #17260 failures

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2439/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2439/Hazelcast-pr-builder-2439.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   UnsafeFencedLockSplitBrainTest>SplitBrainTestSupport.testSplitBrain:195->SplitBrainTestSupport.doIteration:207->onAfterSplitBrainHealed:99 lock should be unlocked
[INFO] 
[ERROR] Tests run: 31896, Failures: 1, Errors: 0, Skipped: 983
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by petrpleshachkov** [comment]
@lprimak , I have managed to reproduce the test failure below. Is this what you've experienced as well? Thanks for the PR, I'll work on the fix.

```
java.lang.AssertionError: lock should be unlocked

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.hazelcast.cp.internal.datastructures.lock.UnsafeFencedLockSplitBrainTest.onAfterSplitBrainHealed(UnsafeFencedLockSplitBrainTest.java:99)
	at com.hazelcast.test.SplitBrainTestSupport.doIteration(SplitBrainTestSupport.java:207)
	at com.hazelcast.test.SplitBrainTestSupport.testSplitBrain(SplitBrainTestSupport.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lprimak** [comment]
Yes. Looks like test failure above exactly

**Comment by plesingr-aeb** [comment]
Hi, we are using hazelcast since some time and this bug caused us very hot moments when some key processes stopped working. Actually, now we are forced to hastily seek workarounds to keep the functionality without using hazelcast. I'd be very happy if the issue gets solved soon. Thanks!

**Comment by lprimak** [comment]
@AyberkSorgun This is still very much an issue with the latest Hazelcast. 5.4-SNAPSHOT
Please bump

**Comment by lprimak** [comment]
Since CP FencedLock doesn't handle crash detection, or split brain by design in Unsafe mode, this works "as expected"
CP needs to be enabled to have split brain and crash detection working

**Pull request closed without merging**
