### PR TITLE
Revert "Implementing IdentifiedDataSerializable in lambdas (#20578)"

### PR DESCRIPTION
**Pull request by krzysztofslusarski**
Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

**Comment by krzysztofslusarski** [comment]
run-lts-compilers

**Comment by krzysztofslusarski** [comment]
run-lab-run

**Comment by krzysztofslusarski** [comment]
run-lab-run

**Comment by krzysztofslusarski** [comment]
run-lab-run

**Review by sancar — APPROVED** [review]

**Review by mdumandag — APPROVED** [review]

**Comment by krzysztofslusarski** [comment]
Sorry for branch in main repository, will remove it after merge.

**Review by viliam-durina — APPROVED** [review]

**Pull request merged**
