### PR TITLE
TriggerLoadIfNeeded should test whether keys loading has finished

### PR DESCRIPTION
**Pull request by vbekiaris**
Backport of fix in #11473

### CODE REVIEW

**Comment by vbekiaris** [comment]
Merging with a single +1 as it is backport of already approved fix.

**Comment by lukasblu** [comment]
@vbekiaris @mmedenjak do you know when 3.8.7 is going to be released?

**Comment by vbekiaris** [comment]
@lukasblu don't have an exact date yet but code freeze should be soon (maybe within next week). Note that after code freeze we need some days to execute our release test suite, so take this with a grain of salt.

**Comment by vbekiaris** [comment]
@lukasblu 3.8.7 is now released (but it may take some hours to show up in maven central). Cheers!

**Comment by lukasblu** [comment]
@vbekiaris super! thanks a lot for letting me know. We are upgrading to this version now.

**Pull request merged**
