### PR TITLE
Ensure `HazelcastInstanceAware` registering instance when listener configured directly on datastructure

### PR DESCRIPTION
**Pull request by JackPGreen**
This was not being done for:
- Set
- List
- Queue
- MultiMap
- Topic

Support added, refactored to use the utility method from `MapProxySupport`, relocated to `AbstractDistributedObject`.

Fixes: https://github.com/hazelcast/hazelcast/issues/26062

### CODE REVIEW

**Comment by JackPGreen** [comment]
> These changes will heavily conflict with the solutions I introduced during the development of UCD on our non-master branch - since there is likely low impact of this issue on current use-cases, I suggest we close this PR and let the UCD feature branch merge handle the resolution.

Have you fixed these same issues in the UCD branch? It would probably be neater to fix pre-existing bugs in a separate PR to additional functionality - do you want to raise a separate PR for those changes instead?

**Comment by JackPGreen** [comment]
Ok - how about I merge the unit tests into the UCD branch instead and we can resolve the issue with that instead?

**Comment by pveentjer** [comment]
What are the memory effects of this method? So do we guarantee any happens-before edge between setting the HZ instance and the user reading the reference? If there is no such guarantee, then there could be a data-race.

**Comment by JackPGreen** [comment]
> What are the memory consistency effects of this functionality? So do we guarantee any happens-before edge between setting the HZ instance and the user reading the reference? If there is no such guarantee, then there could be a data race.

As discussed, the listeners are retried for execution from a  `ConcurrentHashMap`, which provides the required guarantees of memory consistency.

**Comment by JamesHazelcast** [comment]
> Ok - how about I merge the unit tests into the UCD branch instead and we can resolve the issue with that instead?

I'm happy to introduce the unit tests, but we should do so after the UCD branch is merged to prevent breaking builds until then.

**Pull request closed without merging**
