### PR TITLE
Add design document for the instance tracking feature

### PR DESCRIPTION
**Pull request by mmedenjak**
PRD: https://hazelcast.atlassian.net/wiki/spaces/PM/pages/2179432512/Tracking+Hazelcast+Usage

A rendered version for easier reading - https://github.com/mmedenjak/hazelcast/blob/instance-tracking-design-doc/docs/design/instance-tracking/instance-tracking.md.

Reference manual PR - https://github.com/hazelcast/hazelcast-reference-manual/pull/860

### CODE REVIEW

**Comment by sancar** [comment]
@mmedenjak Should we have a more detailed how-to configure programmatically and declaratively part on the design?

**Review by sancar — COMMENTED** [review]
A minor comment. Looks good overall.

**Comment by mmedenjak** [comment]
@sancar sure, I'll add examples.

**Review by blazember — APPROVED** [review]
LGTM :+1: 
One question though: if needed, we plan to extend the `PRODUCT` with Jet, right? The point is, we don't need to change anything in the implementation apart from extending the product list.

**Comment by mmedenjak** [comment]
@blazember yes, it should be fairly straightforward - I'll just need to add something like this to `com.hazelcast.jet.impl.JetNodeExtension`:
```java
    @Override
    protected Map<String, Object> getTrackingFileProperties(BuildInfo buildInfo) {
        Map<String, Object> props = super.getTrackingFileProperties(buildInfo);
        props.put(InstanceTrackingProperties.PRODUCT.getPropertyName(), InstanceProductName.HAZELCAST_JET.getProductName());
        return props;
    }
```

And the same to `com.hazelcast.jet.impl.JetEnterpriseNodeExtension`.

Which reminds me, I better add those two enums to the `InstanceProductName` :)

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by kwart** [comment]
This peaceful document is too nice and honest to be insulted by the treacherous coalition of flaky tests and the Jenkins dinosaur. Merging.

**Comment by mmedenjak** [comment]
:D thanks for the resolute action, oh valiant knight!

**Pull request merged**
