### PR TITLE
Implemented containsValue for TransactionalMap

### PR DESCRIPTION
**Pull request by Andu033**
Create method to check if value is present in TransactionalMap.

Fixes: https://github.com/hazelcast/hazelcast/issues/1027

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Hi @Andu033 ! Finally managed to take a look at your PR. Thank you for submitting it. Unfortunately, there are several things that need to be addressed before merging. Right now, the method checks if the value is contained in one of the entries that were manipulated since the transaction was opened. If that isn't the case, the method will return `false`. But in addition to the `txMap` collection (which only holds entries mutated during the transaction), the entries might also be located on another member. Please take a look at the discussion in the issue, the PR which was opened against the issue a couple of years ago and perhaps how some other method works. For instance, `TransactionalMapProxy#get(java.lang.Object)`.

In addition to this, you will have to implement a similar method on `ClientTxnMapProxy`, which is the equivalent of using a transactional map from a Hazelcast client. Also, you'll need to add tests.

Please let us know if you have additional questions.

**Comment by Holmistr** [comment]
Hey @Andu033 , how is it going? Is there anything we can do to help you make progress? :)

**Comment by Andu033** [comment]
@Holmistr no at this moment. Sorry for being late. I had deadlines. I will try to update this within 2 weeks.

**Comment by Holmistr** [comment]
@Andu033 No need to apologize at all :) We all understand that it's difficult to find some spare time. I was just checking in. Be sure to reach out to us whenever you need any assistance.

**Comment by Andu033** [comment]
@Holmistr I took a look back at the code. I don't quite understand what I need to checkout to see if this map contains a value. I think i have to see if that object is contained in txMap that is wrapped by this class. Also maybe check if transaction state is active . I'm quite new to hazelcast and take a while to understand how the things works. Can you guide me please?

**Comment by Holmistr** [comment]
Hi @Andu033 , sorry for a late response. It was a bit crazy for me these days. Let me circle back with the team and provide you more guidance.

**Comment by mmedenjak** [comment]
Hey @Andu033 ! Yes, you're right, you need to check the transaction map first to determine if the value was added as part of the transaction but after you've done so, you need to also send a partition operation to see if the value has been added previous to this transaction starting. The thing is, when talking about transactions, there are two places where map data may be located - on the partition replicas which contain all map data and in the transaction map which only contains entries added, removed or updated during an ongoing transaction.

For an example see how [`TransactionalMap#get` is implemented](https://github.com/hazelcast/hazelcast/blob/bad1c33db21e2ddb1a301179ac240507620a3e75/hazelcast/src/main/java/com/hazelcast/map/impl/tx/TransactionalMapProxy.java#L109-L120
) and see [another example from another PR which implemented `containsValue`](https://github.com/hazelcast/hazelcast/pull/9971/files#diff-362f92412624f14312bc7f5f13fa0284R79-R90).

**Comment by mmedenjak** [comment]
Hi @Andu033 ! Any updates? Are you able to progress with this task?

**Comment by pveentjer** [comment]
Closing this PR for multiple reasons:

1: we should not add more functionality to tx data-structures
2: This pr seems to be abandoned

**Pull request closed without merging**
