### PR TITLE
to add getAll/putAll methods in TransactionalMap interface; issue #4698

### PR DESCRIPTION
**Pull request by dsukhoroslov**
to explain the changes I did in PR:
- moved method getAll(Set<K> keys) from IMap to it's parent BaseMap interface;
- moved method keySet() from IMap to BaseMap interface;
- moved method keySet(Predicate p) from IMap to BaseMap interface;
- added putAll(Map<K, V> entries) method to BaseMap interface;
- removed method keySet() from TransactionalMap interface (now it is in it's parent BaseMap interface);
- removed method keySet(Predicate p) from TransactionalMap interface;
- implemented getAll/putAll methods in TransactionalMapProxy class;
- implemented getAll/putAll methods in ClientTxnMapProxy class;
- extended MapPortableHook class with two new requests to process getAll/putAll calls;
- implemented getAll/putAll requests in TxnMapRequestWithKeySet/TxnMapRequestWithDataMap classes;
- extended AbstractTxnMapRequest.innerCallInternal method with getAll/putAll request processing;
- added testTxnMapPutGetAll test to ClientTxnMapTest class;

### CODE REVIEW

**Comment by noctarius** [comment]
@gurbuzali thanks for picking this up :) I guess we can merge that into the core, don't we? As far as I remember there is an open issue on that topic and I think I also added it to the ideas list for HEPs, would remove it then.

**Comment by dsukhoroslov** [comment]
rebased PR to master; fixed compilation issue in hazelcast-client-new

**Comment by dsukhoroslov** [comment]
fixed merge conflicts

**Comment by bilalyasar** [comment]
Can one of the admins verify this patch?

**Comment by dsukhoroslov** [comment]
if anyone is going to commit the PR then I'll fix conflicts. so far it looks like noone need it.

**Comment by noctarius** [comment]
@gurbuzali what do you think about this PR, are we going to merge it? I see it is set to 3.5 :)

**Comment by pveentjer** [comment]
@dsukhoroslov can you rebase + squash the commits
@gurbuzali can you check this pr?

**Comment by mtopolnik** [comment]
This is closed in favor of #6705, which takes over the same code and rebases it.

**Pull request closed without merging**
