### PR TITLE
Removes extra serialization when coalescing mode is on

### PR DESCRIPTION
**Pull request by ahmetmircik**
closes https://github.com/hazelcast/hazelcast/issues/7040

### CODE REVIEW

**Comment by ahmetmircik** [comment]
verify

**Comment by eminn** [comment]
:+1:

**Comment by eminn** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
verify

**Comment by gurbuzali** [comment]
:+1:

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Pull request merged**
