### PR TITLE
Fix MapNearCacheInvalidationFromClientTest failures

### LINKED ISSUE #6407: [TEST-FAILURE] MapNearCacheInvalidationFromClientTest Failures
```
java.lang.AssertionError: expected:<DefaultData{type=-7, hashCode=768969306, partitionHash=768969306, totalSize=9, dataSize=4, heapCost=29}> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.map.MapNearCacheInvalidationFromClientTest.testRemove(MapNearCacheInvalidationFromClientTest.java:208)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/lastCompletedBuild/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.map/MapNearCacheInvalidationFromClientTest/testRemove/

### PR DESCRIPTION
**Pull request by metanet**
Fixes #6407

### CODE REVIEW

**Comment by serkan-ozal** [comment]
:+1:

**Comment by metanet** [comment]
verify

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Pull request merged**
