### PR TITLE
Deprecated Local transaction

### PR DESCRIPTION
**Pull request by pveentjer**
Local transaction is very confusing. It is just an ordinary one phase transaction,
so lets give it the right name. Also updated the documentation regarding local
onephase and two phase since it was incorrect.

### CODE REVIEW

**Comment by pveentjer** [comment]
Don't merge this PR before the following PR is merged:
https://github.com/hazelcast/hazelcast/pull/6133

**Comment by gurbuzali** [comment]
:+1:

**Comment by pveentjer** [comment]
verify

**Comment by jerrinot** [comment]
:+1:

**Pull request merged**
