### PR TITLE
#5386 list remove operation should publish REMOVED event

### LINKED ISSUE #5386: list remove operation should publish REMOVED event
Currently it publishes ADDED event.

### PR DESCRIPTION
**Pull request by trohovsky**
Fixes #5386

### CODE REVIEW

**Comment by eminn** [comment]
Thank you for reporting the issue and providing a fix for that. Could  you please sign the Contributor License Agreement ? 

https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by trohovsky** [comment]
I guess it cannot be merged without signing of signing of the CLA, right? I just don't like bureaucracy.

**Comment by eminn** [comment]
Well, me neither but this is needed and this is not up to me :) . This is just one time thing. 

If the fix is urgent for you and you are not willing to sign it, just let me know that  I can apply the fix with a new pull request.

**Comment by trohovsky** [comment]
Signed and send.

**Comment by eminn** [comment]
Thank you.

**Pull request merged**
