### PR TITLE
[DO-NOT-MERGE] New Replicated Map Implementation

### PR DESCRIPTION
**Pull request by eminn**
It was used with intention of automatically solving conflicts but it is proven that approach is not working since vector clocks are not designed for that. Vector clocks were leading to the infinite message loops when they are trying to solve conflicts. That is a performance killer, in a big clusters they are biggest bottleneck to scale.

### CODE REVIEW

**Comment by pveentjer** [comment]
Hi Emin,

what approach did you use so that all members converge to the same map content?

**Comment by pveentjer** [comment]
@eminn ping.

**Comment by eminn** [comment]
run-parallel

**Comment by eminn** [comment]
run-parallel

**Comment by eminn** [comment]
run-parallel

**Comment by eminn** [comment]
run-parallel

**Pull request closed without merging**
