### PR TITLE
Support HazelcastInstanceAware for QuorumFunction

### LINKED ISSUE #7499: Support HazelcastInstanceAware for QuorumFunction
If a `QuorumFunction` implements `HazelcastInstanceAware`, it should have instance injected.

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #7499 

This is a small fix for this very issue to be applied on the maintenance branch only. For master I'm working on a new abstraction to fix this on multiple places.

### CODE REVIEW

**Comment by eminn** [comment]
:+1:

**Comment by pveentjer** [comment]
:+1:

**Comment by nilskp** [comment]
@jerrinot, @eminn, @pveentjer 
I just came across this fix and it's incomplete. It only works for class name based quorum functions, not for provided instances.

**Comment by jerrinot** [comment]
@nilskp: this is expected. When you create an instance then it's your responsibility to set all dependencies. When Hazelcast creates an instance then it will set dependencies. It's the same on other places.

**Comment by gurbuzali** [comment]
@jerrinot @nilskp  `When you create an instance then it's your responsibility to set all dependencies` this is simply wrong, one should set to `QuorumConfig` object and quorumFunction before creating the instance therefore s/he cannot handle dependencies properly.
This logic applies to other places too, please take a look at listeners for example.

**Comment by jerrinot** [comment]
@gurbuzali it makes sense. I was wrong. Thanks!

**Comment by nilskp** [comment]
Exactly. `HazelcastInstance` is the _one_ dependency I cannot set at construction time.

**Pull request merged**
