### PR TITLE
Add an alias for not equals <>

### PR DESCRIPTION
**Pull request by innerverse**
Fixes https://github.com/hazelcast/hazelcast/issues/6195 - Submitting my version in case the extra tests are useful.  Contributor agreement sent this morning.

Very close to the pull request here, although not based on it:
https://github.com/hazelcast/hazelcast/pull/6357

### CODE REVIEW

**Comment by jerrinot** [comment]
:+1:

**Comment by jerrinot** [comment]
@innerverse: Many thanks for your contribution, it's much appreciated!

**Comment by jerrinot** [comment]
I assume @Donnerbart is fine with this as well as it's very similar to #6357 he has already reviewed.

**Comment by Donnerbart** [comment]
:+1:

**Comment by pveentjer** [comment]
:+1:

**Pull request merged**
