### PR TITLE
Update IntelliJ icon with new branding

### PR DESCRIPTION
**Pull request by JackPGreen**

### CODE REVIEW

**Comment by TomaszGaweda** [comment]
Does it work? I think it should be 128x128

**Comment by JackPGreen** [comment]
> Does it work? I think it should be 128x128

@TomaszGaweda yes, it does:
image

I couldn't find any requirements on size etc, the only reference I could find was to the [required paths in their source code](https://github.com/JetBrains/intellij-community/blob/b2295bc87c633200ff49ed0f87eeeb16cf469ad0/platform/platform-impl/src/com/intellij/openapi/wm/impl/welcomeScreen/ChangeProjectIconForm.java#L68-L69), probably because for icons, [PNG is deprecated over SVG](https://youtrack.jetbrains.com/issue/IDEA-268229/Welcome-screen-file-chooser-doesnt-show-PNG-images-when-trying-to-change-project-icon-on-Windows#focus=Comments-27-4864854.0-0).

If I can get an SVG version, I'll update it.

**Review by TomaszGaweda — APPROVED** [review]

**Comment by TomaszGaweda** [comment]
@pawelklasa May have SVG version

**Comment by JackPGreen** [comment]
> If I can get an SVG version, I'll update it.

> @pawelklasa May have SVG version

[SVG version](https://github.com/hazelcast/COM_website/blob/master/wp-content/themes/hazelcast/assets/img/logo_mark.svg) added.

**Review by frant-hartm — APPROVED** [review]

**Pull request merged**
