### PR TITLE
Close leaking streams using try-with-resources in tests [HZ-3351]

### PR DESCRIPTION
**Pull request by orcunc**
Jira : https://hazelcast.atlassian.net/browse/HZ-3351

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

**Review by JackPGreen — APPROVED** [review]
@orcunc thanks for fixing this. Is this the only place it occurs? I think Sonar flags it also.

**Comment by orcunc** [comment]
> @orcunc thanks for fixing this. Is this the only place it occurs? I think Sonar flags it also.

@JackPGreen sonar does not show it. Here is an example to a file that is change in this PR

**Comment by JackPGreen** [comment]
> > @orcunc thanks for fixing this. Is this the only place it occurs? I think Sonar flags it also.
> 
> @JackPGreen sonar does not show it. Here is an example to a file that is change in this PR https://sonarcloud.io/code?id=hazelcast_hazelcast&selected=hazelcast_hazelcast%3Ahazelcast%2Fsrc%2Ftest%2Fjava%2Fcom%2Fhazelcast%2Fjet%2Fimpl%2Futil%2FIOUtilTest.java&line=91
> 
> I am not sure why

Weird - it's definitely flagged this before on a different codebase, but even outside of Sonarcloud it's not for me.

There are several other places that `Files.list` and `Files.walk` are used in the same defective manner - I think we should address all of them at once?

**Comment by orcunc** [comment]
> Weird - it's definitely flagged this before on a different codebase, but even outside of Sonarcloud it's not for me.
> 
> There are several other places that `Files.list` and `Files.walk` are used in the same defective manner - I think we should address all of them at once?

@JackPGreen I did one more push. I think I have covered all of them with the latest commit

**Review by JackPGreen — APPROVED** [review]

**Review by JamesHazelcast — APPROVED** [review]
LGTM!

**Comment by orcunc** [comment]
> > > Weird - it's definitely flagged this before on a different codebase, but even outside of Sonarcloud it's not for me.
> > > There are several other places that `Files.list` and `Files.walk` are used in the same defective manner - I think we should address all of them at once?
> > 
> > 
> > @JackPGreen I did one more push. I think I have covered all of them with the latest commit
> 
> I can `Files.list` in `src/test/java/com/hazelcast/jet/impl/deployment/AbstractDeploymentTest.java` isn't being closed.
> 
> I'd be happy to add a lazy fix (i.e. `stream.collect(Collectors.toList()).stream`) as it's only test code.
> 
> EDIT - Ok, looking further - that is used for a `Traverser` which says it `close`s the stream off anyway. So were good. Thanks!

Yes Traversers.traverseStream closes the stream by itself

**Pull request merged**
