### PR TITLE
Fixes a ClassCastException thrown when ClientMapNearCacheStaleReadTest fails with inconsistencies

### PR DESCRIPTION
**Pull request by vbekiaris**
When `ClientMapNearCacheStaleReadTest` fails with near cache inconsistencies detected, it attempts to flush near cache, however the method only works on member `HazelcastInstance`s and fails with:
```
java.lang.ClassCastException: com.hazelcast.client.impl.HazelcastClientProxy cannot be cast to com.hazelcast.instance.HazelcastInstanceProxy

	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheStaleReadTest.flushMemberNearCache(ClientMapNearCacheStaleReadTest.java:164)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheStaleReadTest.testNoLostInvalidations(ClientMapNearCacheStaleReadTest.java:111)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheStaleReadTest.testNoLostInvalidationsEventually(ClientMapNearCacheStaleReadTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:695)
```

Introduces a separate method to clear a `NearCachedClientMapProxy`'s near cache.

### CODE REVIEW

**Comment by jerrinot** [comment]
:+1:

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
Unrelated test failure `com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest.testSlowRunnableOnPartitionOperationThread`

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
:+1:

**Pull request merged**
