### PR TITLE
Fix fluent API for config classes

### PR DESCRIPTION
**Pull request by mmedenjak**
Setters and other modification methods should try to return the same
instance for a fluent API.

Fixes: https://github.com/hazelcast/hazelcast/issues/11669
EE: https://github.com/hazelcast/hazelcast-enterprise/pull/3116

### CODE REVIEW

**Comment by vojtechtoman** [comment]
What about:
- `EntryListenerConfig#setHazelcastInstance(HazelcastInstance hazelcastInstance)`
- `CacheConfig#setTenantControl(TenantControl tenantControl)`
- `DynamicConfigurationAwareConfig#setConfigurationService(ConfigurationService configurationService)`

These still return `void`.

**Comment by mmedenjak** [comment]
@vojtechtoman 
- `EntryListenerConfig#setHazelcastInstance(HazelcastInstance hazelcastInstance)` is inherited from the `HazelcastInstanceAware` interface
- looks like `CacheConfig#setTenantControl(TenantControl tenantControl)` and `DynamicConfigurationAwareConfig#setConfigurationService(ConfigurationService configurationService)` are meant only for internal use. The first one is more obvious as it's not public and the other one is a bit odd but I'm sure it's not meant for end-user use.

**Comment by ihsandemir** [comment]
This class seems to be missing: `XmlClientFailoverConfigBuilder`
See `XmlClientFailoverConfigBuilder.setProperties`

**Comment by mmedenjak** [comment]
@ihsandemir addressed review comments in a separate commit. Can you take a look?

**Comment by mmedenjak** [comment]
Thank you for the reviews, guys!

**Pull request merged**
