### PR TITLE
[BACKPORT] Interpret duration time `0` as eternal for cache entry expiration

### PR DESCRIPTION
**Pull request by serkan-ozal**
Backport of https://github.com/hazelcast/hazelcast/pull/8206

### CODE REVIEW

**Comment by emrahkocaman** [comment]
Nice one. 👍

**Comment by jerrinot** [comment]
:+1:

**Comment by jerrinot** [comment]
again, it's something for release notes. CC @Serdaro

**Comment by serkan-ozal** [comment]
verify

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by serkan-ozal** [comment]
verify

**Pull request merged**
