### PR TITLE
Send prejoin ops from joining to master

### PR DESCRIPTION
**Pull request by sancar**
fix attempt for https://github.com/hazelcast/hazelcast/issues/18381

Especially see following comments from this issue. 
https://github.com/hazelcast/hazelcast/issues/18381#issuecomment-952843577 https://github.com/hazelcast/hazelcast/issues/18381#issuecomment-952644607

- [x] update javadoc of `PreJoinAwareService`  if we decide to continue with this fix.

### CODE REVIEW

**Review by vbekiaris — CHANGES_REQUESTED** [review]
Thanks for the fix @sancar . I think there are still a few open issues about RU compatibility.

Additionally, in order to minimize the risk of potential regressions, I would add a check in existing prejoin-aware services (`AbstractCacheService`, `ClusterWideConfigurationService` etc) to only send a pre-join op if they are current master (except event service, as required by  this fix).

**Comment by ahmetmircik** [comment]
@sancar https://github.com/hazelcast/hazelcast/issues/18381 is for 5.2 but your fix is targeting 5.1. Which one is correct? This is to know urgency of fix.

**Comment by AyberkSorgun** [comment]
@ahmetmircik went through this today with @vbekiaris. We thought about moving it. Since the issue is already moved, this can be treated as non-urgent

**Review by ahmetmircik — COMMENTED** [review]
Can you please rephrase the issue in this PR's description?

**Comment by arodionov** [comment]
This PR has been updated and reimplemented at PR https://github.com/hazelcast/hazelcast/pull/22942

**Pull request closed without merging**
