### PR TITLE
[PLAT-305] Pretty print cluster connect timeout in logs

### PR DESCRIPTION
**Pull request by mdumandag**
The default value for the cluster connect timeout is infinite,
so it is represented with `Long.MAX_VALUE`. When we try to log
this as it is, we output something like below.

```
... cluster connect timeout: 9223372036854775807 ms, ...
```

To make this more clear, we will replace this with the
output below.

```
... cluster connect timeout: INFINITE, ...
```

If the user has provided some other timeout value (such as 999 ms),
the output will still be as it is now.

```
... cluster connect timeout: 999 ms, ...
```

### CODE REVIEW

**Review by sancar — APPROVED** [review]

**Comment by srknzl** [comment]
run-lab-run

**Comment by mdumandag** [comment]
unrelated test failure reported on #18644

**Comment by mdumandag** [comment]
run-lab-run

**Review by ihsandemir — APPROVED** [review]

**Comment by mdumandag** [comment]
One more unrelated test failure that is already reported #18626

**Comment by mdumandag** [comment]
run-lab-run

**Review by srknzl — APPROVED** [review]

**Pull request merged**
