### PR TITLE
OperationTimeoutException: includes the first invocation time

### PR DESCRIPTION
**Pull request by pveentjer**

### CODE REVIEW

**Comment by pveentjer** [comment]
verify

**Comment by jerrinot** [comment]
@pveentjer: there is some rubbish included in the commit (`performance-client-0-1458240759009-000.log`)

**Comment by mdogan** [comment]
@pveentjer: can you please remove `performance-client-*.log` files from the commit?

**Comment by pveentjer** [comment]
run-lab-run

**Comment by pveentjer** [comment]
Since it is a error message failure, there is no need to play the 'will the build succeed this time' lottery. So I'm going to merge it.

**Pull request merged**
