### PR TITLE
Use specified instance if instance name is given regardless from URI is specified or not

### LINKED ISSUE #6454: HazelcastCachingProvider does not use specified instance when instance-name not specified
Both `HazelcastServerCachingProvider` and `HazelcastClientCachingProvider` does not use the instance specified by in object when `uri` is not null and `instance-name` not specified in Properties. They try to start a new instance instead.

### PR DESCRIPTION
**Pull request by serkan-ozal**
Fixes #6454

### CODE REVIEW

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
verify

**Comment by sancar** [comment]
:+1:

**Comment by mustafaiman** [comment]
:+1:

**Pull request merged**
