### PR TITLE
Add automated NOTICE file generation

### PR DESCRIPTION
**Pull request by gurbuzali**

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/636/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/636/Hazelcast-pr-builder-636.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:1.19:add-third-party (default) on project hazelcast-build-utils: There are some forbidden licenses used, please check your dependencies. -> [Help 1]
--------------------------
</details>
</pre>

**Comment by cangencer** [comment]
> Could you explain what is the desired result of these changes? Is there a related issue or PRD?
> 
> IMO, if we want to generate the `NOTICE` files, we should add them into released artifacts (jars and source jars) under `META-INF/NOTICE`.
> 
> Some comments related to the current implementation:
> 
> * I don't like generating resources back to the source folder. The generated output should go to `target` directory
> * Why the template contains the full text of the supported licenses?

Not sure if there's a better way to include the full text. It's typically not present in the maven artifact, must be added manually.

> * Did you consider using the plugin on the root project?

The root project doesn't have any dependencies, so wouldn't generate anything.

> * The newly defined dependencies in hazelcast-all just for sake of proper listing is not good option for maintenance. Maybe the additional transformer `ApacheNoticeResourceTransformer` configured in the `maven-shade-plugin` would be a safer choice.

That only merges NOTICE/LICENSE from inside the maven artifact. This is typically not present in almost all of the dependencies, so wouldn't be very useful by itself. I've only seen in it in a few apache dependencies.

> * I'm missing tests verifying the desired results;

**Comment by jerrinot** [comment]
It's good enough. The only missing bit: The PR should contain the `NOTICE` file. Otherwise other developers are going to be confused. 

The file generation is deterministic so normally there should no be any issues. It actually helps to detect cases when a dependency is included by accident.

**Comment by kwart** [comment]
What issue is this PR fixing? Does it resolve any existing problem? If I read correctly the plugin description, it serves rather to generating a third-party licenses file than gathering content of the  `NOTICE` file. Point 4 in Apache license says:

> If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places:
> ...
> You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License.

**Comment by jerrinot** [comment]
@gurbuzali I tried to merge this PR into the 4.1-BETA-1 branch and I've got this error:
```
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:1.19:add-third-party (default) on project hazelcast-all: could not execute goal AddThirdPartyMojo for reason : Template "/home/jara/devel/oss/hazelcast/hazelcast-all/src/main/resources/ThirdParty.txt.ftl" not found. -> [Help 1]
[ERROR] 
```

**Comment by gurbuzali** [comment]
fixed the naming and rebased to latest master

**Review by jerrinot — APPROVED** [review]

**Review by jerrinot — CHANGES_REQUESTED** [review]
I played a bit more with this. when executed on 4.1-BETA-1 it's including this in the report:
```
GNU General Public License, version 2 (GPL2), with the classpath exception
  Checker Qual:2.0.0
```
I am not sure where is this coming from. it's most likely the `org.checkerframework:checker-compat-qual:jar:2.0.0:compile` which is a compile-time Guava dependency. We don't shade this library into our artifact and we don't distribute it in any way.

**Review by cangencer — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2510/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2510/Hazelcast-pr-builder-2510.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   QueueSplitBrainTest>SplitBrainTestSupport.testSplitBrain:195->SplitBrainTestSupport.doIteration:207->onAfterSplitBrainHealed:157 ? ConcurrentModification
[INFO] 
[ERROR] Tests run: 31940, Failures: 0, Errors: 1, Skipped: 978
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by gurbuzali** [comment]
verify

**Comment by mmedenjak** [comment]
run-lab-run

**Pull request closed without merging**
