### PR TITLE
[Possible fix of #4911] Assert local executor stats eventually

### LINKED ISSUE #4911: Test of getLocalExecutorStats() is failing spuriously
The commit bd9bb627bb9dceae1c2971ea0e4f0abae097d893 has commented out a test of `getLocalExecutorStats()` because it is failing spuriously. After fixing this issue the test should be enabled.

This is probably related to issue #4677.

### PR DESCRIPTION
**Pull request by metanet**
* As far as I understand, this issue is not related to #4677, since the test fails before asserting the task cancellation. The cause of the rare fails is scheduling the task to another thread. I have run the test 100K times and it hasn't failed.

Fixes #4911

### CODE REVIEW

**Comment by serkan-ozal** [comment]
:+1:

**Comment by mdogan** [comment]
> The cause of the rare fails is scheduling the task to another thread.

I did not understand, which task is scheduled to another thread?

**Comment by metanet** [comment]
SingleNodeTest:347 submits the task to another thread. Therefore, SingleNodeTest:338 fails occasionally.

**Comment by mdogan** [comment]
Still, not understand. 

First `k` executions are guaranteed to be completed, after `assertOpenEventually(LatchRunnable.latch)`.
```java
final LatchRunnable r = new LatchRunnable();
        for (int i = 0; i < k; i++) {
            executor.execute(r);
        }
assertOpenEventually(LatchRunnable.latch);
```
And `executor.submit(new SleepingTask(10))` is guaranteed to be completed after `f.get();`. 

So, where is the race window here?

**Comment by metanet** [comment]
Sorry for not telling it clearly. 

As you say, first k operations are guaranteed to be executed. 
The next task is the SleepingTask which is k + 1 and it is submitted and eventually started. After that, cancel() invocation cancels it before completion. Therefore, f.get() throws a CancellationException.

**Comment by mdogan** [comment]
ok, I got your point now. thanks.

**Comment by mdogan** [comment]
:+1:

**Pull request merged**
