### PR TITLE
Add selectionKey null check in NioOutboundPipeline.executePipeline to prevent NPE

### LINKED ISSUE #16754: NullPointerException executePipeline(NioOutboundPipeline.java:244)
http://jenkins.hazelcast.com/view/hot-restart/job/hot-shutdown/45/console
/disk1/jenkins/workspace/hot-shutdown/4.1-SNAPSHOT/2020_02_25-03_41_33/shutdown
http://54.147.27.51/~jenkins/workspace/hot-shutdown/4.1-SNAPSHOT/2020_02_25-03_41_33/shutdown/

I do not think there is anything specific to the above test which should provoke this issue
lots of other test are doing the same style of operations under the same conditions.  It looks like this exception is very rare and very difficult to reproduce and or specific to the commited version of the code.

version
HazelcastClient 4.1-SNAPSHOT (20200224 - b7e578f, b19167a)

```
java.lang.NullPointerException
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.executePipeline(NioOutboundPipeline.java:244)
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.write(NioOutboundPipeline.java:215)
	at com.hazelcast.internal.networking.nio.NioChannel.write(NioChannel.java:79)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection.write(TcpIpConnection.java:185)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.sendClientMessage(AbstractMessageTask.java:251)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.sendResponse(AbstractMessageTask.java:239)
	at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.sendResponseOrHandleFailure(AbstractAsyncMessageTask.java:79)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at com.hazelcast.internal.util.ConcurrencyUtil$1.execute(ConcurrencyUtil.java:39)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:751)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:781)
	at java.util.concurrent.CompletableFuture.whenCompleteAsync(CompletableFuture.java:2150)
	at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.processMessage(AbstractAsyncMessageTask.java:73)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:145)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:108)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:172)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:140)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)
```

### PR DESCRIPTION
**Pull request by kwart**
Fixes #16754

The `selectionKey` can be `null` in two cases - either before the `initSelectionKey()` is called or after the `startMigration()` is called.
Other places handling with the `selectionKey` field already have the null-check implemented.

### CODE REVIEW

**Review by mmedenjak — APPROVED** [review]

**Comment by pveentjer** [comment]
I'm currently looking at the code. The code is complex unfortunately; especially due to the write through.

The issue is that the OutboundPipeline should have the SCHEDULED flag set during migration and during migration the selectionkey is null.

The exception shows that a write through was done and since the selectionkey is null, it must have been done during a migration. So appearently the SCHEDULED flag is not set otherwise the write through would not have been possible.

**Comment by pveentjer** [comment]
Some more insights. I marked the line where the NPE was thrown based on the commit hash Danny posted in the original ticket.

```
  private void executePipeline() {
         if (writeThroughEnabled && !concurrencyDetection.isDetected()) {
            // we are allowed to do a write through, so lets process the request on the calling thread
            try {
                process();
            } catch (Throwable t) {
                onError(t);
            }
        } else {
            if (selectionKeyWakeupEnabled) {
                registerOp(OP_WRITE);
                selectionKey.selector().wakeup();   <-----
            } else {
                owner.addTaskAndWakeup(this);
            }
        }
    }
```
If selectionKey would be null before the executePipeline is called, then the registerOp(OP_WRITE) would have triggered the NPE as well.

```
    final void registerOp(int operation) {
        selectionKey.interestOps(selectionKey.interestOps() | operation);
    }
```
So either the selectionKey was set to null just after returning from registerOp(OP_WRITE) or the selectionKey.selector() returns null (which is not possible).

**Comment by hz-highfive** [comment]
The job `no-jenkins` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
just-test
</pre>
</details>

**Comment by kwart** [comment]
The thing is the `NioOutboundPipeline.executePipeline()` can be called from many different threads. If the pipeline processing is migrated between IO threads in the meantime, then the `selectionKey` can be `null`. The migration works in 2 steps - first runs on the old `NioThread` and the second on the new one:
* the `NioPipeline.startMigration()` is called on the original thread and it cancels the `selectionKey` and sets it to `null`. Then the migration task is registered on the new thread;
* when the new thread picks the migration task and proceeds with it, it restores the delayed tasks and as the (nearly) last step it initializes the `selectionKey` again.

So there is a space where the `selectionKey` is `null`.

**Here are thread names (from a sample test run) calling the `executePipeline` with their stack traces:**

```
hz.stupefied_driscoll.IO.thread-in-1
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.executePipeline(NioOutboundPipeline.java:236)
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.write(NioOutboundPipeline.java:216)
	at com.hazelcast.internal.networking.nio.NioChannel.write(NioChannel.java:78)
	at com.hazelcast.internal.server.tcp.TcpServerConnection.write(TcpServerConnection.java:197)
	at com.hazelcast.internal.server.tcp.SendMemberHandshakeTask.run(SendMemberHandshakeTask.java:80)
	at com.hazelcast.internal.server.tcp.TcpServerControl.process0(TcpServerControl.java:165)
	at com.hazelcast.internal.server.tcp.TcpServerControl.process(TcpServerControl.java:127)
	at com.hazelcast.internal.server.tcp.TcpServerControl.process(TcpServerControl.java:85)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionManager.accept(TcpServerConnectionManager.java:106)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionManager.accept(TcpServerConnectionManager.java:1)
	at com.hazelcast.spi.impl.PacketDispatcher.accept(PacketDispatcher.java:81)
	at com.hazelcast.spi.impl.PacketDispatcher.accept(PacketDispatcher.java:1)
	at com.hazelcast.internal.server.tcp.PacketDecoder.onPacketComplete(PacketDecoder.java:84)
	at com.hazelcast.internal.server.tcp.PacketDecoder.onRead(PacketDecoder.java:66)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:137)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

```
hz.jolly_driscoll.TcpServer.thread-1
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.executePipeline(NioOutboundPipeline.java:236)
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.write(NioOutboundPipeline.java:216)
	at com.hazelcast.internal.networking.nio.NioChannel.write(NioChannel.java:78)
	at com.hazelcast.internal.server.tcp.TcpServerConnection.write(TcpServerConnection.java:197)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionManagerBase.send(TcpServerConnectionManagerBase.java:220)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionManagerBase$SendTask.run(TcpServerConnectionManagerBase.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
hz.stupefied_driscoll.generic-operation.thread-1
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.executePipeline(NioOutboundPipeline.java:236)
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.write(NioOutboundPipeline.java:216)
	at com.hazelcast.internal.networking.nio.NioChannel.write(NioChannel.java:78)
	at com.hazelcast.internal.server.tcp.TcpServerConnection.write(TcpServerConnection.java:197)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionManagerBase.send(TcpServerConnectionManagerBase.java:220)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionManager.transmit(TcpServerConnectionManager.java:216)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.send(OutboundOperationHandler.java:54)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.send(OperationServiceImpl.java:460)
	at com.hazelcast.internal.cluster.impl.ClusterJoinManager.sendMasterAnswer(ClusterJoinManager.java:634)
	at com.hazelcast.internal.cluster.impl.ClusterJoinManager.startJoinRequest(ClusterJoinManager.java:445)
	at com.hazelcast.internal.cluster.impl.ClusterJoinManager.executeJoinRequest(ClusterJoinManager.java:267)
	at com.hazelcast.internal.cluster.impl.ClusterJoinManager.handleJoinRequest(ClusterJoinManager.java:179)
	at com.hazelcast.internal.cluster.impl.operations.JoinRequestOp.run(JoinRequestOp.java:41)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

```
hz.jolly_driscoll.priority-generic-operation.thread-0
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.executePipeline(NioOutboundPipeline.java:236)
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.write(NioOutboundPipeline.java:216)
	at com.hazelcast.internal.networking.nio.NioChannel.write(NioChannel.java:78)
	at com.hazelcast.internal.server.tcp.TcpServerConnection.write(TcpServerConnection.java:197)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionManagerBase.send(TcpServerConnectionManagerBase.java:220)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionManager.transmit(TcpServerConnectionManager.java:216)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.send(OutboundOperationHandler.java:54)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.send(OperationServiceImpl.java:460)
	at com.hazelcast.internal.cluster.impl.ClusterJoinManager.sendJoinRequest(ClusterJoinManager.java:470)
	at com.hazelcast.internal.cluster.impl.ClusterJoinManager.setMasterAndJoin(ClusterJoinManager.java:562)
	at com.hazelcast.internal.cluster.impl.ClusterJoinManager.handleMasterResponse(ClusterJoinManager.java:531)
	at com.hazelcast.internal.cluster.impl.operations.MasterResponseOp.run(MasterResponseOp.java:42)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Comment by kwart** [comment]
Nightly tests run for this PR: http://jenkins.hazelcast.com/job/tmp-josef-nightly/1/

**Review by vbekiaris — APPROVED** [review]

**Comment by kwart** [comment]
Thanks for reviews, Matko & Vassilis.

**Comment by cnlzhang** [comment]
Hi kwart,
Is there any possiable that this multi thread problem can happen to owner?

**Pull request merged**
