### PR TITLE
Add min/max aggregation to map/reduce framework.

### PR DESCRIPTION
**Pull request by wesleypeck**
Adds a min/max aggregation to the map/reduce framework that computes both the minimum and maximum value in one pass.

### CODE REVIEW

**Comment by bwzhang2011** [comment]
@noctarius , how about such issue going on ? min or max aggregation is much wanted during map-reduce computation, so such feature would be nice and appreciated of.

**Comment by noctarius** [comment]
We want to extend the aggregations with a ComposerAggregation that is meant to be composed from multiple Aggregators but I guess no timeline yet. Min and Max are both available they just need to be composed to run at once.

This is the proposed API:
```
Aggregation<String, BigInteger, BigInteger> minAggregation = Aggregations.bigIntegerMin();
Aggregation<String, BigInteger, BigInteger> maxAggregation = Aggregations.bigIntegerMax();
 
Aggregation<String, BigInteger, BigInteger[]> compositeAggregation = Aggregations
    .composeArray(minAggregation, maxAggregation);
 
Supplier<String, BigInteger, BigInteger> supplier = Supplier.all(...);
BigInteger[] result = map.aggregate(supplier, compositeAggregation);
```

or

```
// Non type safe array
Aggregation<String, BigInteger, Collection<Object>> compositeAggregation = Aggregations
    .compose(aggregation1, aggregation2);
 
// Possibly defined result tuple type
TupleProducer<ResultType> resultTypeTupleProducer = new ...;
Aggregation<String, BigInteger, ResultType> compositeAggregation = Aggregations
    .compose(ResultType.class, resultTypeTupleProducer, aggregation1, aggregation2);
```

But as I said, no timeline yet, haven't made it into a release yet :(

**Comment by bwzhang2011** [comment]
thanks for feed back. we're looking into simple map-reduce solution and hz map-reduce provides such with great efforts and easy to use. 
and as you know, the original from hz team for similar functions like min/max or else as the database provides are much needed and hope
hz team could provide more supports for map-reduce enhancement. what's the more, we also face up with the data pumping problem while there
were no default out of box solution or tool for large data import (e.g you need to write the application to connect different datasource for
computing). so we also care about the real experiences for large data processing in hz map-reduce (leave us more detail around this)

**Comment by bwzhang2011** [comment]
by the way, it's a pity that such has not been in timeline yet. @noctarius, hope more functions  taken into the side of hz team could be support as large data computing support is much needed and appreciated of. hope you could push that we're looking forward to.

**Comment by bilalyasar** [comment]
Can one of the admins verify this patch?

**Comment by pveentjer** [comment]
I'm going to close this one due to inactivity. Feel free to re-open it.

**Pull request closed without merging**
