### PR TITLE
variable replacement and xml config import docs added

### PR DESCRIPTION
**Pull request by bilalyasar**

### CODE REVIEW

**Comment by mesutcelik** [comment]
not-related failure

```
com.hazelcast.queue.TransactionQueueTest.testIssue859And863
```

**Comment by mesutcelik** [comment]
@Serdaro ,
can you please review?

**Comment by Serdaro** [comment]
Can I merge this? (your entry `not related failure` was about this?)

**Comment by mesutcelik** [comment]
yes you can.

**Pull request merged**
