### PR TITLE
Handling mancenter REST requests

### PR DESCRIPTION
**Pull request by emrahkocaman**
- Prevent processing of REST requests when REST is disabled.
- Allow mancenter requests to be processed when REST is disabled

### CODE REVIEW

**Comment by pveentjer** [comment]
Can the commits be squashed?

**Comment by pveentjer** [comment]
I don't know if any tests exists for the rest functionality. But it sound important to have at least this new functionality covered.

**Comment by sancar** [comment]
:+1:

**Comment by emrahkocaman** [comment]
Commits are squashed. There are already tests both in management center and hz for rest.

**Comment by pveentjer** [comment]
Your changes are not tested. So please add a test for it.

**Comment by emrahkocaman** [comment]
Test added for hz.
Already tested in mancenter https://github.com/hazelcast/management-center/blob/master/src/test/java/com/hazelcast/webmonitor/integration/DataServiceIntegrationTest.java#L897

**Comment by bilalyasar** [comment]
:+1:

**Comment by pveentjer** [comment]
:+1:

**Pull request merged**
