### PR TITLE
Remove SQL core tests re-run from Jet SQL module

### PR DESCRIPTION
**Pull request by gierlachg**

### CODE REVIEW

**Comment by gurbuzali** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Review by viliam-durina — APPROVED** [review]

**Comment by gierlachg** [comment]
run-lab-run

**Review by vbekiaris — APPROVED** [review]

**Comment by gierlachg** [comment]
run-lab-run

**Pull request merged**
