### PR TITLE
Replace `Preconditions.checkNotNull` implementation with `Objects.requireNonNull`

### PR DESCRIPTION
**Pull request by JackPGreen**
`Preconditions.checkNotNull` duplicates [`Objects.requireNonNull`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Objects.html#requireNonNull(T)) - it's implementation should delegate to that instead.

### CODE REVIEW

**Comment by JamesHazelcast** [comment]
Is there any point in us keeping this utility method when we could just be calling `Objects.requireNonNull` directly?

**Comment by JamesHazelcast** [comment]
> `checkNotNull` has over 1,000 usages and changing that many would just cause other open PRs to be a pain to merge.

That's a fair point - not sure there's anything to be gained here then, the original method is extremely simple and never going to require changes in the future to maintain functionality, this change seems superfluous.

**Comment by JackPGreen** [comment]
> > not sure there's anything to be gained here then, the original method is extremely simple and never going to require changes in the future to maintain functionality, this change seems superfluous.

That's fair too - there's not a massive benefit.
Maybe that's justification for changing it and deprecating it instead?

**Comment by orcunc** [comment]
> > > not sure there's anything to be gained here then, the original method is extremely simple and never going to require changes in the future to maintain functionality, this change seems superfluous.
> 
> That's fair too - there's not a massive benefit. Maybe that's justification for changing it and deprecating it instead?

You can just replace the usage in tests in this PR. 
Then gradually we can get rid of this method with smaller PRs

**Comment by JackPGreen** [comment]
> > > > not sure there's anything to be gained here then, the original method is extremely simple and never going to require changes in the future to maintain functionality, this change seems superfluous.
> > 
> > 
> > That's fair too - there's not a massive benefit. Maybe that's justification for changing it and deprecating it instead?
> 
> You can just replace the usage in tests in this PR. Then gradually we can get rid of this method with smaller PRs

That would suggest this should be `@Deprecated` as well then.

**Comment by JackPGreen** [comment]
@orcunc @JamesHazelcast sounds like this PR was a swing and a miss.

Alternatives:
- `@Deprecate` the method and document the `Objects.requireNonNull` as an alternative
- leave it alone

Thoughts?

**Comment by JamesHazelcast** [comment]
> You can just replace the usage in tests in this PR.
> Then gradually we can get rid of this method with smaller PRs

@orcunc's suggestion makes sense to me - we can deprecate, replace in tests, and leave it there for this PR.

**Review by orcunc — APPROVED** [review]

**Pull request merged**
