### PR TITLE
Demonstrates multi-homed cluster connection failures (supposed to fail until issue is fixed)

### PR DESCRIPTION
**Pull request by lprimak**
This test demonstrates failure to establish cluster on a multi-homed machine
when multiple addresses are used to connect to the cluster.
The connection should either fail or succeed, but it hangs and never connects.

Related issues:
#17834 #17466 #16358

### CODE REVIEW

**Comment by mmedenjak** [comment]
Thank you for the test. I'm positively overloaded still, but added it to my queue. I'll see if someone else can take a look at the issue as well.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2911/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2911/Hazelcast-pr-builder-2911.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MultiHomedJoinerTest.checkMultiHomed:111->HazelcastTestSupport.assertGreaterOrEquals:1401 Expected 'Not Multi-Homed' to be greater than or equal to 2, but was 1
[ERROR]   TransactionContextImpl_backupLogsTest.list_backupLogCreationForced:74->assertBackupLogCreationForced:96
[ERROR]   TransactionContextImpl_backupLogsTest.queue_backupLogCreationForced:84->assertBackupLogCreationForced:96
[ERROR]   TransactionContextImpl_backupLogsTest.set_backupLogCreationForced:79->assertBackupLogCreationForced:96
[ERROR] Errors: 
[ERROR]   MultiHomedJoinerTest.simulateMultiHomedWithLocalHost:127 ? TestTimedOut test t...
[ERROR]   TransactionImpl_TwoPhaseIntegrationTest.commit_whenMultipleItemsAndDurabilityOne_thenBackupLog:203->commit_whenMultipleItemsAndDurabilityOne_thenBackupLog:203 ? HazelcastInstanceNotActive
[ERROR]   TransactionImpl_TwoPhaseIntegrationTest.commit_whenSingleItemAndDurabilityOne_thenNoBackupLog:183->HazelcastTestSupport.shutdownNodeFactory:179 ? HazelcastInstanceNotActive
[ERROR]   TransactionImpl_TwoPhaseIntegrationTest.prepare_whenMultipleItemsAndDurabilityOne_thenBackupLog:127->HazelcastTestSupport.shutdownNodeFactory:179 ? HazelcastInstanceNotActive
[ERROR]   TransactionImpl_TwoPhaseIntegrationTest.prepare_whenMultipleItemsAndDurabilityZero_thenNoBackupLog:147->HazelcastTestSupport.shutdownNodeFactory:179 ? HazelcastInstanceNotActive
[ERROR]   TransactionImpl_TwoPhaseIntegrationTest.prepare_whenSingleItemAndDurabilityOne_thenNoBackupLog:105->HazelcastTestSupport.shutdownNodeFactory:179 ? HazelcastInstanceNotActive
[INFO] 
[ERROR] Tests run: 3599, Failures: 4, Errors: 6, Skipped: 15
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by kwart** [comment]
@ufukyilmaz Could you check this PR? The original issue should be fixed now (by your 5.1 hostnames fixes).

If we need to extend the test coverage in this area, maybe it would be safer to add the scenario(s) to the Docker-based integration testsuite in the hazelcast-enterprise repo.

This PR would need some clean-up if we decide to merge it - e.g. removal of the `checkMultiHomed` test; add proper handling of the `HAZELCAST_TEST_USE_NETWORK`; proper check if any non-loopback interface is available at all, ...

**Comment by lprimak** [comment]
Any update on this issue?
Thanks

**Comment by kwart** [comment]
I don't think we need this test anymore as new tests were added to cover changes in 5.1 and 5.2 networking. @ufukyilmaz WDYT?

The current form of the test class also has several issues:
* it uses `TestHazelcastInstanceFactory` together with the `HAZELCAST_TEST_USE_NETWORK` - i.e. it can't run in parallel with other tests;
* property `HAZELCAST_TEST_USE_NETWORK` is not cleaned up;
* the `checkMultiHomed()` is still present - i.e. failing;
* the "big condition" in `init()` method seems fragile to me;
* the cluster size assertions could fail, we usually check the size with `assertClusterSizeEventually` method;
* the checkstyle fails on the file header check.

**Comment by ufukyilmaz** [comment]
@kwart, I agree with your thoughts. Most of the mentioned issues in this PR can be fixed but we don't have a way to properly provide a multihomed environment for our junit test suite. Also, after 5.1-5.2 changes, we already test the setups with multiple network interfaces in our docker-based integration test suite. So, I am also favor of closing this PR.

**Comment by kwart** [comment]
Thanks for the comments, Ufuk.

@lprimak I'm closing this PR as already covered by other tests. Thank you for sharing the reproducer for the issues you reported. It helped to prepare networking fixes in the new Hazelcast versions.

**Comment by lprimak** [comment]
ok, assuming this is fixed in 5.x

**Pull request closed without merging**
