### PR TITLE
Limit active operation count during merge

### PR DESCRIPTION
**Pull request by ahmetmircik**

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2107/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2107/Hazelcast-pr-builder-2107.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientQueryCacheRecreationTest.query_cache_recreates_itself_after_server_restart:112->HazelcastTestSupport.assertTrueEventually:1350->HazelcastTestSupport.assertTrueEventually:1248->lambda$query_cache_recreates_itself_after_server_restart$0:114 expected:<200> but was:<191>
[INFO] 
[ERROR] Tests run: 31283, Failures: 1, Errors: 0, Skipped: 976
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by kwart** [comment]
run-lab-run

**Comment by kwart** [comment]
run-lab-run

**Comment by kwart** [comment]
run-lab-run

**Pull request closed without merging**
