### PR TITLE
Avoid volatile writes from Atomics default values

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this PR avoids volatile writes by removing the default parameters from `Atomic...` classes.

Cheers,
Christoph

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

**Comment by JackPGreen** [comment]
run-lab-run

**Review by srknzl — APPROVED** [review]

**Comment by JackPGreen** [comment]
Thanks for your contribution - I think this is a positive change.

I'm concerned about the number and scope of changes that might cause conflicts with other open branches.

Is it possible to focus these changes on any critical paths of the code to get the best improvement on a smaller scale?

**Comment by dreis2211** [comment]
Most of these are insight tests. I can't tell what the "critical paths" are for you and what might conflict with other branches. You have a better overview of that.

**Comment by dreis2211** [comment]
This is still relevant.

**Comment by JackPGreen** [comment]
When benchmarking, on average they initialise ~10% values when using implicit (over explicit) defaults.

**Comment by dreis2211** [comment]
This is still relevant. Please reopen this

**Pull request closed without merging**
