### PR TITLE
[PLAT-286 PLAT-81] Generate third-party notice file

### PR DESCRIPTION
**Pull request by gurbuzali**

### CODE REVIEW

**Comment by Holmistr** [comment]
As agreed with our layer, we don't need the "third-party.txt" but rather have it as content of the notice file. (= delete the old notice file and replace it with the stuff that is generated by this PR)

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
@kwart @gurbuzali is this PR superseded by https://github.com/hazelcast/hazelcast/pull/18573?

**Comment by kwart** [comment]
> is this PR superseded by #18573?

I think it is.

**Comment by gurbuzali** [comment]
yes, closing this one

**Pull request closed without merging**
