### PR TITLE
Rename DelegatingMigrationAwareService to match its function

### PR DESCRIPTION
**Pull request by vbekiaris**
Rename DelegatingMigrationAwareService to CountingMigrationAwareService

### CODE REVIEW

**Comment by vbekiaris** [comment]
Requires an EE counterpart after merging.

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
:+1:

**Comment by Donnerbart** [comment]
Vassilis was the original author of the class and it's just a rename. Should be fine to merge with a single review.

**Comment by jerrinot** [comment]
:+1:

**Pull request merged**
