### PR TITLE
Check status of "ICompletableFuture" while waiting for completion latch

### PR DESCRIPTION
**Pull request by serkan-ozal**
Fix for #4335

### CODE REVIEW

**Comment by jerrinot** [comment]
Could you please elaborate mechanics of the fix? What was wrong and how you fixed that? 
The #4335 raises a few points, is this fix addressing all of them?

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
Hi @jerrinot,

Currently if invoked cache operation fails (such as operation timeout) before completion latch, completion latch waits as redundant. 

https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/AbstractClientInternalCacheProxy.java#L194

With this PR, `awaitLatch` checks status of `InvocationFuture`. If it finishes with error (`isDone` is `true` and response is a kind of error), caller doesn't wait completion latches and returns.

As we talked with @mdogan, this cover 2nd and 3rd issues are covered. However, for 1st issue, we keep the current implementation.

**Comment by metanet** [comment]
:+1:

**Comment by kobalski** [comment]
:+1:

**Pull request merged**
