### PR TITLE
Heap-based MemoryManager for LongSetHsa

### PR DESCRIPTION
**Pull request by mtopolnik**
`LongSetHsa` will be needed in Hot Restart. This PR contributes a heap-based memory allocator for it.

### CODE REVIEW

**Comment by mtopolnik** [comment]
run-lab-run

**Comment by mtopolnik** [comment]
run-lab-run

**Comment by pveentjer** [comment]
I think you will get problems with the test coverage of this class even though many methods are Unsupported. Eventually all newly added code needs to follow minimal test coverage and you will get @Donnerbart on your roof with him creating those spreadsheets during the last phase of the release.

**Comment by Donnerbart** [comment]
The newly added class `LongSetHsa` is already failing with 80.8% coverage (87.5% would be required).

**Comment by mtopolnik** [comment]
Unit test is in the making.

**Comment by mtopolnik** [comment]
Unit test is committed.

**Comment by serkan-ozal** [comment]
👍

**Comment by pveentjer** [comment]
:+1:

**Pull request merged**
