### PR TITLE
added warning log for host name configuration

### PR DESCRIPTION
**Pull request by bilalyasar**

### CODE REVIEW

**Comment by mesutcelik** [comment]
verify

**Comment by pveentjer** [comment]
Using a hostname in HZ is not recommended at all. It is fragile because at some points the ip address is used and other hostname which can lead to strange behavior in a cluster. At least that is what I remember.

**Comment by bilalyasar** [comment]
run-parallel

**Comment by bilalyasar** [comment]
run-parallel

**Comment by bilalyasar** [comment]
verify

**Comment by bilalyasar** [comment]
verify

**Pull request merged**
