### PR TITLE
[DONT MERGE] Performance: Caller Runs Optimization

### PR DESCRIPTION
**Pull request by pveentjer**
Instead of offloading partition specific operations to partition thread, try to do it yourself.

Very naive benchmark where a single thread calls IAtomicLong.get. 

disabled:
Throughput: 102.234 ops/second
enabled:
Throughput: 1.484.428 op/second

The smaller the cluster, the more impact this optimization will have. Once this one is done, we need to crack  https://github.com/hazelcast/hazelcast/issues/1194 for cheap local access in IMap.

This is an older much more complex approach:
hazelcast/pull/4513

### CODE REVIEW

**Comment by pveentjer** [comment]
The same implementation last year did 17.6M ops/second. After reverting simulator to that version, the new implementation using the same test/environment does:

INFO  09:34:22 Performance: 28,846,455.56 ops/s

**Comment by pveentjer** [comment]
Implementation of last year did 17.6M ops/second. Current implementation is at 50M op/second. I hope there will not be too much regression when it is finished.

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue ? could be merged into 3.8 branch ?

**Comment by marsbible** [comment]
any update with such issue ? could be merged into 3.8 branch ?

**Comment by mmedenjak** [comment]
I'm going to put this in 3.10 so we merge/close it then

**Comment by Holmistr** [comment]
Closing for inactivity. Please reopen if necessary.

**Pull request closed without merging**
