### PR TITLE
update SerializerConfig typeClass when typeClassName is set

### PR DESCRIPTION
**Pull request by alex-dukhno**
Fix for #16047 

@neilstevenson, @mmedenjak could you guys have a look?

### CODE REVIEW

**Comment by sancar** [comment]
@alex-dukhno Thanks for fix, again. 

We expect to get what you set from setTypeClass from getTypeClass. And it is also same for getTypeClassName and setTypeClassName methods. 
The preferred way is to make the conversion after reading from this methods. 
A similar usage can be found here:
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/spi/ProxyManager.java#L183

Can you update the solution accordingly ?

**Comment by alex-dukhno** [comment]
@sancar done

**Comment by sancar** [comment]
Sorry for the misguiding earlier. I found time to look into the issue. 
It seems that member side usage is correct. Can you fix the client side same ?
See https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/ConfigXmlGenerator.java#L459

To give it more detail, SerializerConfig should not change. Only its usage is wrong. ClientConfigXmlGenerator should use  a method like `classNameOrClass` instead of `classNameOrImplClass`

**Comment by alex-dukhno** [comment]
I am not sure that `SerializerConfig` shouldn't be changed.
When it serialized/deserialized into/from xml/yaml config parser can't say if `"type-class"` attribute was set from `typeClass` or `typeClassName` field.
If we don't care about that then `SerializerConfig #equals` method should be changed to something like
```java
return Objects.equals(className, that.className)
    && Objects.equals(implementation, that.implementation)
    && (Objects.equals(typeClass, that.typeClass)||Objects.equals(typeClassName, that.typeClassName))
```
otherwise added [tests](https://github.com/hazelcast/hazelcast/pull/16097/files#diff-e552779497fd0c1c2dc00fa1362f04ffR349) will fail with the following error:
```
java.lang.AssertionError: Collection [
SerializerConfig{className='com.hazelcast.client.config.ClientConfigXmlGeneratorTest$TestSerializer',
implementation=null,
typeClass=class com.hazelcast.client.config.ClientConfigXmlGeneratorTest$TestType,
typeClassName='com.hazelcast.client.config.ClientConfigXmlGeneratorTest$TestType'}
] (1)
didn't contain expected [
SerializerConfig{className='com.hazelcast.client.config.ClientConfigXmlGeneratorTest$TestSerializer',
implementation=null,
typeClass=class com.hazelcast.client.config.ClientConfigXmlGeneratorTest$TestType,
typeClassName='null'}
] (1)
```

**Comment by sancar** [comment]
We have the same equality problem with any config class that having both implementation/class and name as the configuration. Their tests are only with class name. 
Other example classes with same problem, `PartitioningStrategyConfig` , `ListenerConfig` , `ProxyFactoryConfig` ... etc.
Even tough objects are not equal, a new member/client will work correctly when created with generated xml. May be we should not do an equality check, but expect correct class name always.
@alex-dukhno How about this ? Lets create another issue for this equality problem so that when 
we fix it, we will address all classes with same problem. 

For this fix, we can modify the test to expect correct class name when class provided.

**Comment by alex-dukhno** [comment]
@sancar I updated code and squashed as you suggested in the last comment.

Thank you

**Comment by mmedenjak** [comment]
Ah, yes, true, the issue with the inconsistency between implementation/class name/class type is another problem in itself and affects many other config classes. I don't see it as a major defect, more like a surprising behaviour.

I agree we should first merge this as it's a completely unrelated issue and then try to address this problem on different config classes as a separate PR, so feel free to open an issue @sancar or @alex-dukhno . As I mentioned, this is not a major issue but I also believe fixing it is breaking behaviour so the only chance we have for fixing it is in 4.0.

Merging this PR, thank you for another contribution @alex-dukhno . We'll have to send you some cake once we release! :)

**Pull request merged**
