### PR TITLE
Add support for evictAll through MBean

### PR DESCRIPTION
**Pull request by kuseman**
Add support for evictAll through MBean

### CODE REVIEW

**Comment by jerrinot** [comment]
hi @kuseman, thanks for this contribution. can you please sign the [Hazelcast Contribution Agreement](https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement)

This is a prerequisite to get this PR merged.

**Comment by mesutcelik** [comment]
Hi @kuseman ,
It would be great if you add a test too after signing the Hazelcast Contribution Agreement.

Example test implementation as below.
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/internal/jmx/MapMBeanTest.java

**Comment by pveentjer** [comment]
I just checked the code. It looks fine to be merged. @kuseman can you check the Contribution Agreement?

**Comment by pveentjer** [comment]
Closing due to inactivity.

**Pull request closed without merging**
