### PR TITLE
deleted hazelcast-cloud module

### PR DESCRIPTION
**Pull request by bilalyasar**

### CODE REVIEW

**Comment by bilalyasar** [comment]
verify

**Comment by pveentjer** [comment]
```
14:41:36 [ERROR] Failed to execute goal on project hazelcast-client: Could not resolve dependencies for project com.hazelcast:hazelcast-client:jar:3.7-SNAPSHOT: Could not find artifact com.hazelcast:hazelcast-cloud:jar:3.7-SNAPSHOT in cloudbees-private-snapshot-repository (https://repository-hazelcast-l337.forge.cloudbees.com/snapshot) -> [Help 1]
```

**Comment by emrahkocaman** [comment]
:+1:

**Comment by mesutcelik** [comment]
:+1:

**Pull request merged**
