### PR TITLE
Added new tests for Executor future cancel. The tests are ignored for now

### PR DESCRIPTION
**Pull request by sancar**
Related issue #4677 . And there are some cleanups in  ExecutorService test .

### CODE REVIEW

**Comment by sancar** [comment]
unrelated test failed
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/12463/testReport/junit/com.hazelcast.collection.impl.queue/QueueSplitBrainTest/testQueueSplitBrain/

**Comment by sancar** [comment]
verify

**Comment by mtopolnik** [comment]
testQueueSplitBrain was failing spuriously for me too.

**Comment by mesutcelik** [comment]
I think https://github.com/hazelcast/hazelcast/issues/4876 is failing with the same reason as well.  
@gurbuzali , anyone working on #4876 ?

**Pull request merged**
