### PR TITLE
Fixed ommited timeToLiveSeconds value

### PR DESCRIPTION
**Pull request by mumukiller**
Added missed timeToLiveSeconds value
Related test was fixed

https://github.com/hazelcast/hazelcast/issues/12273

### CODE REVIEW

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
@mumukiller before we merge your fix, can you please sign the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement) and send it to the email listed on the web page?

**Comment by vbekiaris** [comment]
Also, can you backport the change to `maintenance-3.x` branch so the fix will be merged for an upcoming 3.9.4 release?

**Comment by mumukiller** [comment]
@vbekiaris agreement was sent

**Comment by mumukiller** [comment]
@vbekiaris are there any docs related to backporting process?

**Comment by vbekiaris** [comment]
@mumukiller you just need to create a new branch in your local git repos off of `maintenance-3.x`, then apply the same changes in this PR (maybe you will be able to cherry pick your commit, I think these classes haven't changed much). Then, while creating the new pull request, select `hazelcast:maintenance-3.x` as the target branch to merge to.

**Comment by mumukiller** [comment]
Backport is done! https://github.com/hazelcast/hazelcast/pull/12292

**Pull request merged**
