### PR TITLE
[BACKPORT] added GetCacheEntryRequest for MC cache browser

### PR DESCRIPTION
**Pull request by hasancelik**
backport of https://github.com/hazelcast/hazelcast/pull/9959

this PR includes also fix for jcache jar problem. --> https://github.com/hazelcast/hazelcast/pull/9974

### CODE REVIEW

**Comment by ahmetmircik** [comment]
@hasancelik is this change compatible with 3.8?

**Comment by mesutcelik** [comment]
run-lab-run

**Comment by mesutcelik** [comment]
```
12:59:10 /home/jenkins/jenkins/workspace/new-lab-fast-pr-7696/hazelcast/src/main/java/com/hazelcast/internal/management/request/GetCacheEntryRequest.java:2: Line does not match expected header line of ' * Copyright (c) 2008-2017, Hazelcast, Inc. All Rights Reserved.'.
```

**Comment by mesutcelik** [comment]
👍

**Pull request merged**
