### PR TITLE
Add overall timeout to ClientServiceTests to detect stuck test

### PR DESCRIPTION
**Pull request by cangencer**
Also, added assertions to removeClientListener tests

See issue #6580

### CODE REVIEW

**Comment by cangencer** [comment]
verify

**Comment by sancar** [comment]
:+1:

**Comment by hasancelik** [comment]
:+1:

**Comment by pveentjer** [comment]
:+1: 

But we need to change this mechanism. Any tests that is not configured to have longer timeout, should by default have a system imposed timeout. So it should be an opt out feature instead of an opt in feature.

**Pull request merged**
