### PR TITLE
Do not shade test jars

### PR DESCRIPTION
**Pull request by TomaszGaweda**
Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

### CODE REVIEW

**Comment by k-jamroz** [comment]
run-ee-tests

**Review by vbekiaris — APPROVED** [review]
`shadeTestJar` was introduced in #9278 to allow for EE-side tests using the `minimal-json` library (which was shaded on OS side). The dependency was removed in #13405 which imported the sources under `com.hazelcast.internal.json` package, so it looks like shading can be safely removed (at last :-) ).

**Comment by vbekiaris** [comment]
hm... but apparently there are other EE-side tests that are failing with other dependencies' shading

**Comment by TomaszGaweda** [comment]
run-ee-tests

**Pull request closed without merging**
