### PR TITLE
Repackages map.impl.query

### PR DESCRIPTION
**Pull request by pveentjer**
All the query related stuff has been moved into map.impl.queries.
And MapContextQuerySupport has been renamed to QueryEngine.

### CODE REVIEW

**Comment by jerrinot** [comment]
@pveentjer: can you move test classes too? eg. QueryOperationTest.

**Comment by pveentjer** [comment]
Done.

**Comment by jerrinot** [comment]
:+1:

**Comment by ahmetmircik** [comment]
:+1:

**Comment by ahmetmircik** [comment]
@pveentjer Please also check enterprise part for possible side-effects.

**Comment by pveentjer** [comment]
Enterprise PR:
https://github.com/hazelcast/hazelcast-enterprise/pull/370

**Comment by pveentjer** [comment]
verify

**Comment by jerrinot** [comment]
apparently this test is broken due this changeset: 

https://github.com/jerrinot/hazelcast-stabilizer/blob/6dd931de7eb712e538ed84d113ce615950edd7a9/tests/src/main/java/com/hazelcast/simulator/tests/map/queryresultsize/AbstractMapTest.java#L69-69

**Pull request merged**
