### PR TITLE
Add UTC zone to formatter

### PR DESCRIPTION
**Pull request by hakanmemisoglu**
Adds UTC zone to DateTimeFormatter

Alternatively, we can also change it to use system default time zone.

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [x] Request reviewers if possible

Fixes: https://github.com/hazelcast/hazelcast-jet/issues/3043

### CODE REVIEW

**Comment by hakanmemisoglu** [comment]
hazelcast/hazelcast-jet#3043

**Comment by mmedenjak** [comment]
@hakanmemisoglu does this PR fix the issue?

**Comment by hakanmemisoglu** [comment]
Yes it does. The test in the PR fails with the same problem in the issue before the code change.

**Comment by mmedenjak** [comment]
Thanks, I'll link the two then.

**Review by viliam-durina — APPROVED** [review]

**Pull request merged**
