### PR TITLE
Improved TargetDisconnectException

### PR DESCRIPTION
**Pull request by pveentjer**
Improved TargetDisconnectException to include the String representation of the connection being closed. This will help with quicker spotting the source of the problem.

### CODE REVIEW

**Comment by jerrinot** [comment]
:+1:

**Comment by vbekiaris** [comment]
👍

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by pveentjer** [comment]
run-lab-run

**Comment by tombujok** [comment]
run-lab-run

**Pull request merged**
