### PR TITLE
Renamed EventPacket to EventEnvelope

### PR DESCRIPTION
**Pull request by pveentjer**
EventPacket is not a correct name since it isn't a type of a Packet.
Envelope is more clear since it is placed around an arbitrary event
object and some meta-data is added.

### CODE REVIEW

**Comment by mtopolnik** [comment]
:+1:

**Comment by Donnerbart** [comment]
:+1: (if we have consensus on the name change, the rest of the cleanup looks good)

**Comment by toktarev** [comment]
:+1:

**Comment by pveentjer** [comment]
verify

**Pull request merged**
