### PR TITLE
Mock network fixes and parallel test improvements

### LINKED ISSUE #6383: AdvancedClusterStateTest failures
**changeClusterState_shouldFail_whenInitiatorDies_beforePrepare**
**changeClusterState_shouldFail_withoutBackup_whenInitiatorDies_afterPrepare**
**changeClusterState_shouldFail_withoutBackup_whenInitiatorDies_beforePrepare**

```
com.hazelcast.transaction.TransactionException: Transaction is timed-out!
    at com.hazelcast.transaction.impl.TransactionImpl.checkTimeout(TransactionImpl.java:287)
    at com.hazelcast.transaction.impl.TransactionImpl.prepare(TransactionImpl.java:211)
    at com.hazelcast.cluster.AdvancedClusterStateTest$DelegatingTransaction.prepare(AdvancedClusterStateTest.java:584)
    at com.hazelcast.cluster.AdvancedClusterStateTest$TransactionAnswer$1.prepare(AdvancedClusterStateTest.java:505)
    at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:210)
    at com.hazelcast.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:794)
    at com.hazelcast.cluster.AdvancedClusterStateTest.changeClusterState_shouldFail_whenInitiatorDies_beforePrepare(AdvancedClusterStateTest.java:160)
```

**invocationShouldComplete_whenMemberReJoins_inFrozenState**
**partitionTable_shouldBeFrozen_whenMemberLeaves_inFrozenState**

```
ava.lang.IllegalStateException: Still have pending migration/replication tasks, cannot lock cluster state! New state: FROZEN, current state: ACTIVE
    at com.hazelcast.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:124)
    at com.hazelcast.cluster.impl.operations.LockClusterStateOperation.run(LockClusterStateOperation.java:68)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/685/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/681/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/684/

### LINKED ISSUE #6974: ClusterRollingRestartTest.test_rollingRestart[clusterState:PASSIVE,partitionAssignmentType:NEVER]
```
com.hazelcast.core.HazelcastException: java.util.concurrent.TimeoutException: Call Invocation{serviceName='hz:core:clusterService', op=com.hazelcast.cluster.impl.operations.LockClusterStateOperation{serviceName='hz:core:clusterService', partitionId=-1, replicaIndex=0, callId=4, invocationTime=1449113838589 (Thu Dec 03 05:37:18 EET 2015), waitTimeout=-1, callTimeout=60000}, partitionId=-1, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[127.0.0.1]:8180, backupsExpected=0, backupsCompleted=0, connection=MockConnection{localEndpoint=Address[127.0.0.1]:8178, remoteEndpoint=Address[127.0.0.1]:8180}} encountered a timeout
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:367)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:335)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:223)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:275)
	at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:249)
	at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:228)
	at com.hazelcast.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:821)
	at com.hazelcast.cluster.impl.AdvancedClusterStateTest.changeClusterStateEventually(AdvancedClusterStateTest.java:641)
	at com.hazelcast.cluster.impl.ClusterRollingRestartTest.test_rollingRestart(ClusterRollingRestartTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/317/testReport/junit/com.hazelcast.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_PASSIVE_partitionAssignmentType_NEVER_/

### LINKED ISSUE #7004: BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_PASSIVE
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
    at java.lang.Thread.sleep(Native Method)
    at com.hazelcast.test.TestNodeRegistry$MockJoiner.doJoin(TestNodeRegistry.java:221)
    at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:103)
    at com.hazelcast.instance.Node.join(Node.java:581)
    at com.hazelcast.instance.Node.start(Node.java:339)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:130)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:117)
    at com.hazelcast.cluster.impl.BasicClusterStateTest.testNoMigrationWhenNodeLeaves(BasicClusterStateTest.java:366)
    at com.hazelcast.cluster.impl.BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_PASSIVE(BasicClusterStateTest.java:346)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/641/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_PASSIVE/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/746/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_PASSIVE/

### PR DESCRIPTION
**Pull request by mdogan**
- MockConnectionManager.getConnection() should not create a connection for an already
shutdown instance.
- MockClientConnection.write() should check if server is running
- Refactor TestNodeRegistry inner classes to their own package
- Append junit test name to each log line

Possibly
fixes #6974
fixes #7004 
fixes #6383

### CODE REVIEW

**Comment by eminn** [comment]
Fixes #6371

**Comment by mdogan** [comment]
run-lab-run

**Comment by metanet** [comment]
:+1:

**Comment by mdogan** [comment]
Build slave went offline after successful build:
```
16:07:01 [INFO] ------------------------------------------------------------------------
16:07:01 [INFO] Reactor Summary:
16:07:01 [INFO] 
16:07:01 [INFO] Hazelcast Root .................................... SUCCESS [  0.410 s]
16:07:01 [INFO] hazelcast-code-generator .......................... SUCCESS [  1.261 s]
16:07:01 [INFO] hazelcast ......................................... SUCCESS [14:16 min]
16:07:01 [INFO] hazelcast-cloud ................................... SUCCESS [  2.096 s]
16:07:01 [INFO] hazelcast-client .................................. SUCCESS [04:29 min]
16:07:01 [INFO] hazelcast-client-legacy ........................... SUCCESS [04:22 min]
16:07:01 [INFO] hazelcast-hibernate ............................... SUCCESS [  0.238 s]
16:07:01 [INFO] hazelcast-hibernate3 .............................. SUCCESS [ 10.376 s]
16:07:01 [INFO] hazelcast-hibernate4 .............................. SUCCESS [  8.155 s]
16:07:01 [INFO] hazelcast-wm ...................................... SUCCESS [01:12 min]
16:07:01 [INFO] hazelcast-spring .................................. SUCCESS [ 36.603 s]
16:07:01 [INFO] hazelcast-ra ...................................... SUCCESS [  0.015 s]
16:07:01 [INFO] hazelcast-jca ..................................... SUCCESS [  3.515 s]
16:07:01 [INFO] hazelcast-jca-rar ................................. SUCCESS [  0.021 s]
16:07:01 [INFO] hazelcast-build-utils ............................. SUCCESS [  0.699 s]
16:07:01 [INFO] hazelcast-jclouds ................................. SUCCESS [01:36 min]
16:07:01 [INFO] ------------------------------------------------------------------------
16:07:01 [INFO] BUILD SUCCESS
16:07:01 [INFO] ------------------------------------------------------------------------
16:07:01 [INFO] Total time: 27:01 min
16:07:01 [INFO] Finished at: 2015-12-07T14:07:01+00:00
16:07:01 [INFO] Final Memory: 435M/5335M
16:07:01 [INFO] ------------------------------------------------------------------------
16:07:02 Stopping Docker container after build completion
16:07:09 Run condition [Always] enabling perform for step [[Archive the artifacts]]
16:07:09 Archiving artifacts
16:08:10 Recording test results
16:18:24 Slave went offline during the build
16:18:24 ERROR: Node is being removed
16:18:24 Build step 'Publish JUnit test result report' marked build as failure
16:18:24 [BFA] Scanning build for known causes...
16:18:24 [BFA] No failure causes found
16:18:24 [BFA] Done. 0s
16:18:24 Setting status of 7c596193d8f6a6a71cda5125a5d036650ae2cf3a to FAILURE with url https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/392/ and message: ' No test results found.'
16:18:24 Finished: FAILURE
```

**Comment by mdogan** [comment]
run-lab-run

**Comment by mdogan** [comment]
went offline again after successful build: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/397/console

```
17:39:19 [INFO] ------------------------------------------------------------------------
17:39:19 [INFO] Reactor Summary:
17:39:19 [INFO] 
17:39:19 [INFO] Hazelcast Root .................................... SUCCESS [  0.418 s]
17:39:19 [INFO] hazelcast-code-generator .......................... SUCCESS [  1.288 s]
17:39:19 [INFO] hazelcast ......................................... SUCCESS [14:04 min]
17:39:19 [INFO] hazelcast-cloud ................................... SUCCESS [  4.158 s]
17:39:19 [INFO] hazelcast-client .................................. SUCCESS [04:47 min]
17:39:19 [INFO] hazelcast-client-legacy ........................... SUCCESS [04:40 min]
17:39:19 [INFO] hazelcast-hibernate ............................... SUCCESS [  0.257 s]
17:39:19 [INFO] hazelcast-hibernate3 .............................. SUCCESS [ 10.791 s]
17:39:19 [INFO] hazelcast-hibernate4 .............................. SUCCESS [  8.142 s]
17:39:19 [INFO] hazelcast-wm ...................................... SUCCESS [01:12 min]
17:39:19 [INFO] hazelcast-spring .................................. SUCCESS [ 37.443 s]
17:39:19 [INFO] hazelcast-ra ...................................... SUCCESS [  0.015 s]
17:39:19 [INFO] hazelcast-jca ..................................... SUCCESS [  3.430 s]
17:39:19 [INFO] hazelcast-jca-rar ................................. SUCCESS [  0.021 s]
17:39:19 [INFO] hazelcast-build-utils ............................. SUCCESS [  0.695 s]
17:39:19 [INFO] hazelcast-jclouds ................................. SUCCESS [01:35 min]
17:39:19 [INFO] ------------------------------------------------------------------------
17:39:19 [INFO] BUILD SUCCESS
17:39:19 [INFO] ------------------------------------------------------------------------
17:39:19 [INFO] Total time: 27:28 min
17:39:19 [INFO] Finished at: 2015-12-07T15:38:58+00:00
17:39:19 [INFO] Final Memory: 476M/5490M
17:39:19 [INFO] ------------------------------------------------------------------------
17:39:41 Stopping Docker container after build completion
17:40:19 Run condition [Always] enabling perform for step [[Archive the artifacts]]
17:40:19 Archiving artifacts
17:41:38 Recording test results
17:55:05 Slave went offline during the build
17:55:05 ERROR: Node is being removed
17:55:05 Build step 'Publish JUnit test result report' marked build as failure
17:55:05 [BFA] Scanning build for known causes...
17:55:05 [BFA] No failure causes found
17:55:05 [BFA] Done. 0s
17:55:05 Setting status of b73753cbd5638c22a78087ae820a338031a74ec1 to FAILURE with url https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/397/ and message: ' No test results found.'
17:55:05 Finished: FAILURE
```

**Comment by serkan-ozal** [comment]
no need to wait and another pr builder run

**Pull request merged**
