### PR TITLE
Litter optimization MPSCQueue

### PR DESCRIPTION
**Pull request by pveentjer**
In case of a single item on the queue, the item isn't wrapped in a Node
instance.

Also if there are N items on the queue, it will only take N-1 Node
instances.

### CODE REVIEW

**Comment by pveentjer** [comment]
verify

**Comment by pveentjer** [comment]
run-lab-run

**Comment by mdogan** [comment]
How much gain is this change going to provide? Do you have any measurements?

**Comment by Holmistr** [comment]
Closing for inactivity. Please reopen if necessary.

**Pull request closed without merging**
