### PR TITLE
Adding data structure config at runtime should not fail unless equal …

### LINKED ISSUE #13158: Adding data structure config at runtime fails when same config exists as static config
When adding a dynamic data structure configuration then we fail-fast when the same structure is already configured statically. even when both configs are equal.
The expected outcome would be to silently ignore the submitted dynamic config when it is equal to an existing static config, or fail with a `ConfigurationException` when a conflicting static config already exists. The same behavior (ignore when equal, fail on conflict) is already in place when checking a submitted config against existing dynamic configs.

Kudos @jerrinot for raising this issue

### PR DESCRIPTION
**Pull request by webashutosh**
Adding data structure config at runtime should not fail unless equal config exists as static config 
Fixes #13158

### CODE REVIEW

**Comment by webashutosh** [comment]
Hello @vbekiaris @jerrinot ... could you please review this PR? It is to address Issue #13158

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by mdogan** [comment]
Isn't this change the opposite of what issue #13158 describes?

**Comment by webashutosh** [comment]
@mdogan you are right! My bad. Inserted a commit to correct the code. Note that ideally, when we see that the same config exists as static config, we do NOT need to broadcast the new config. I did not make this change as am not sure if its worth it. Do you think we should make that change-well? Thanks so much for the review :)

**Comment by mdogan** [comment]
@webashutosh: I agree that, we should prevent redundant broadcasting when the same config exist in static configuration.

**Comment by webashutosh** [comment]
@mdogan thanks! I pushed a commit to make required changes ... can you please have a look?

**Comment by mdogan** [comment]
@webashutosh: Looks good to me. Can you please rebase/squash into single commit?

**Comment by webashutosh** [comment]
@mdogan I made multiple attempts to squash all my commits into a single commit - with no success. I believe its happening as I had to bring-in upstream changes in between my commits. Can you please consider squashing when this PR is merged into master?

**Pull request merged**
