### PR TITLE
Serialization classes package refactoring

### PR DESCRIPTION
**Pull request by sancar**
Main motivation is to categorize implementation to analyze better,
before starting new serialization format.

Moving portable implementations into `portable` package
Moving serializers that for primitives and java classes to
`defaultserializers` package

Serialization related tests were under two different directory.
test/java/com/hazelcast/nio/serialization/ is merged to
test/java/com/hazelcast/internal/serialization/impl/

Enterprise part: https://github.com/hazelcast/hazelcast-enterprise/pull/3592

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/566/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/566/Hazelcast-pr-builder-566.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 14 errors reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/portable/DefaultPortableReader.java:44: Total number of methods is 59 (max allowed is 30). [MethodCount]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/portable/DefaultPortableWriter.java:54:28: '4' is a magic number. [MagicNumber]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/portable/DefaultPortableWriter.java:222:38: '4' is a magic number. [MagicNumber]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compatibility/ReferenceObjects.java:66:16: Name 'PORTABLE_FACTORY_ID' must match pattern '^[a-z][a-zA-Z0-9]*$'. [StaticVariableName]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compatibility/ReferenceObjects.java:67:16: Name 'PORTABLE_CLASS_ID' must match pattern '^[a-z][a-zA-Z0-9]*$'. [StaticVariableName]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compatibility/ReferenceObjects.java:68:16: Name 'INNER_PORTABLE_CLASS_ID' must match pattern '^[a-z][a-zA-Z0-9]*$'. [StaticVariableName]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compatibility/ReferenceObjects.java:73:16: Name 'IDENTIFIED_DATA_SERIALIZABLE_FACTORY_ID' must match pattern '^[a-z][a-zA-Z0-9]*$'. [StaticVariableName]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compatibility/ReferenceObjects.java:74:16: Name 'DATA_SERIALIZABLE_CLASS_ID' must match pattern '^[a-z][a-zA-Z0-9]*$'. [StaticVariableName]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compatibility/ReferenceObjects.java:79:16: Name 'CUSTOM_STREAM_SERIALIZABLE_ID' must match pattern '^[a-z][a-zA-Z0-9]*$'. [StaticVariableName]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compatibility/ReferenceObjects.java:80:16: Name 'CUSTOM_BYTE_ARRAY_SERIALIZABLE_ID' must match pattern '^[a-z][a-zA-Z0-9]*$'. [StaticVariableName]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/portable/PortablePathCursorTest.java:19:1: Redundant import from the same package - com.hazelcast.internal.serialization.impl.portable.PortablePathCursor. [RedundantImport]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/portable/PortablePositionFactoryTest.java:19:1: Redundant import from the same package - com.hazelcast.internal.serialization.impl.portable.FieldDefinitionImpl. [RedundantImport]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/portable/PortablePositionFactoryTest.java:20:1: Redundant import from the same package - com.hazelcast.internal.serialization.impl.portable.PortablePosition. [RedundantImport]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/portable/PortablePositionFactoryTest.java:21:1: Redundant import from the same package - com.hazelcast.internal.serialization.impl.portable.PortablePositionFactory. [RedundantImport]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/568/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/568/Hazelcast-pr-builder-568.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientCacheEventJournalBasicTest>AbstractEventJournalBasicTest.allowReadingWithFutureSeq:512->HazelcastTestSupport.assertOpenEventually:1108->HazelcastTestSupport.assertOpenEventually:1123 CountDownLatch failed to complete within 30 seconds, count left: 1
[ERROR] Errors: 
[ERROR]   SerializerHookLoaderTest.testLoad_withDefaultConstructor:54 ? HazelcastSerialization
[ERROR]   SerializerHookLoaderTest.testLoad_withParametrizedConstructor:68 ? HazelcastSerialization
[ERROR]   SerializerHookLoaderTest.testLoad_withParametrizedConstructorAndCompatibilitySwitchOn:89 ? HazelcastSerialization
[INFO] 
[ERROR] Tests run: 27737, Failures: 1, Errors: 3, Skipped: 1001
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/569/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/569/Hazelcast-pr-builder-569.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization Pro...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization Pro...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization Fai...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization Fai...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization Fai...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization Fai...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization Pro...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization Pro...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[ERROR]   BinaryCompatibilityTest.readAndVerifyBinaries:123 ? HazelcastSerialization jav...
[INFO] 
[ERROR] Tests run: 3855, Failures: 0, Errors: 56, Skipped: 14
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/572/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/572/Hazelcast-pr-builder-572.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientCacheEventJournalBasicTest>AbstractEventJournalBasicTest.allowReadingWithFutureSeq:512->HazelcastTestSupport.assertOpenEventually:1108->HazelcastTestSupport.assertOpenEventually:1123 CountDownLatch failed to complete within 30 seconds, count left: 1
[INFO] 
[ERROR] Tests run: 27737, Failures: 1, Errors: 0, Skipped: 1001
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by sancar** [comment]
Unrelated test failure `ClientCacheEventJournalBasicTest ` reported here https://github.com/hazelcast/hazelcast/issues/16964

**Comment by sancar** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/584/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/584/Hazelcast-pr-builder-584.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   TestClientApplicationContext.testAwsClientConfig ? IllegalState Failed to load...
[ERROR]   TestClientApplicationContext.testBackupAckToClient ? IllegalState Failed to lo...
[ERROR]   TestClientApplicationContext.testClient ? IllegalState Failed to load Applicat...
[ERROR]   TestClientApplicationContext.testClientConnectionStrategyConfig ? IllegalState
[ERROR]   TestClientApplicationContext.testClientIcmpConfig ? IllegalState Failed to loa...
[ERROR]   TestClientApplicationContext.testClientNearCacheEvictionPolicies ? IllegalState
[ERROR]   TestClientApplicationContext.testCloudConfig ? IllegalState Failed to load App...
[ERROR]   TestClientApplicationContext.testConnectionRetry ? IllegalState Failed to load...
[ERROR]   TestClientApplicationContext.testDefaultSerializationConfig ? IllegalState Fai...
[ERROR]   TestClientApplicationContext.testFlakeIdGeneratorConfig ? IllegalState Failed ...
[ERROR]   TestClientApplicationContext.testFullQueryCacheConfig ? IllegalState Failed to...
[ERROR]   TestClientApplicationContext.testHazelcastInstances ? IllegalState Failed to l...
[ERROR]   TestClientApplicationContext.testInstanceNameConfig ? IllegalState Failed to l...
[ERROR]   TestClientApplicationContext.testLabelsConfig ? IllegalState Failed to load Ap...
[ERROR]   TestClientApplicationContext.testMetrics ? IllegalState Failed to load Applica...
[ERROR]   TestClientApplicationContext.testNearCachePreloader ? IllegalState Failed to l...
[ERROR]   TestClientApplicationContext.testReliableTopicConfig ? IllegalState Failed to ...
[ERROR]   TestClientApplicationContext.testSecurityRealms ? IllegalState Failed to load ...
[ERROR]   TestClientApplicationContext.testUnlimitedConnectionAttempt ? IllegalState Fai...
[ERROR]   TestClientApplicationContext.testUserCodeDeploymentConfig ? IllegalState Faile...
[ERROR]   TestClientNetworkConfig.smokeAwsConfig ? IllegalState Failed to load Applicati...
[ERROR]   TestClientNetworkConfig.smokeAzureConfig ? IllegalState Failed to load Applica...
[ERROR]   TestClientNetworkConfig.smokeEurekaConfig ? IllegalState Failed to load Applic...
[ERROR]   TestClientNetworkConfig.smokeGcpConfig ? IllegalState Failed to load Applicati...
[ERROR]   TestClientNetworkConfig.smokeKubernetesConfig ? IllegalState Failed to load Ap...
[ERROR]   TestClientNetworkConfig.smokeMember ? IllegalState Failed to load ApplicationC...
[ERROR]   TestClientNetworkConfig.smokeOutboundPorts ? IllegalState Failed to load Appli...
[ERROR]   TestClientNetworkConfig.smokeSSLConfig ? IllegalState Failed to load Applicati...
[ERROR]   TestClientNetworkConfig.smokeSocketInterceptor ? IllegalState Failed to load A...
[ERROR]   TestClientNetworkConfig.smokeSocketOptions ? IllegalState Failed to load Appli...
[INFO] 
[ERROR] Tests run: 188, Failures: 0, Errors: 30, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/586/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/586/Hazelcast-pr-builder-586.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientCacheEventJournalBasicTest>AbstractEventJournalBasicTest.allowReadingWithFutureSeq:512->HazelcastTestSupport.assertOpenEventually:1108->HazelcastTestSupport.assertOpenEventually:1123 CountDownLatch failed to complete within 30 seconds, count left: 1
[INFO] 
[ERROR] Tests run: 27737, Failures: 1, Errors: 0, Skipped: 1001
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Pull request merged**
