### PR TITLE
Add namespace declaration for XmlClientConfig tests which test invalid configuration

### PR DESCRIPTION
**Pull request by cangencer**
Additionally, add a test for missing namespace declaration. Fixes issue #6633

### CODE REVIEW

**Comment by cangencer** [comment]
verify

**Comment by pveentjer** [comment]
It looks good to me on a quick glance. @mtopolnik can you have a look?

**Comment by bilalyasar** [comment]
:+1:

**Comment by mtopolnik** [comment]
:+1: This follows the same approach as done in HZ core for the equivalent tests.

**Pull request merged**
