### PR TITLE
lazy deserialization of event to map,multimap,queue,topic,list,set,re…

### LINKED ISSUE #6582: Lazy Deserialization required on events processing
If 2 clients are listening on entryEvicted of EntryEvictedListener only, a map.put on one client results in a callback ClientMapProxy$ClientMapEventHandler.creteEntryEvent() on other clients, which further leads to deserialisation of the entry on those clients. This causes GC and excess CPU issues on the clients which are not even actively making map calls. 

It requires lazy deserialization on clients when the event arrives. This will prevent excess CPU and memory usage spikes.

### PR DESCRIPTION
**Pull request by sancar**
…plicated map

fixes #6582

### CODE REVIEW

**Comment by pveentjer** [comment]
Can ItemEvent.getItem be called concurrently? getItem isn't threadsafe; and I'm not pointing at a potential double deserialization.

**Comment by pveentjer** [comment]
And can we rename DataAwareItemEvent to e.g. LazyDeserializingItemEvent. The name DataAware is very confusing to me.

**Comment by sancar** [comment]
@pveentjer 
We are passing new DataAwareItemEvent to every listener. They are not shared, so concurrency should not be a problem.

Lets do renaming later. We need these asap. And we dont want to wait for tests to pass again.

**Comment by pveentjer** [comment]
:+1:

**Comment by pveentjer** [comment]
One problem. There are not tests. Is it possible to write tests for this behavior?

**Pull request merged**
