### PR TITLE
Avoid opening java.net module on JDK17 HZ-687

### PR DESCRIPTION
**Pull request by ldziedziul**
Introduced abstraction over `NetworkInterface` and system DNS resolving to provide testability without opening `java.net` module on JDK17

Related issue: 
- https://hazelcast.atlassian.net/browse/HZ-687
- https://github.com/hazelcast/hazelcast/pull/19896

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

**Review by slavagithub — APPROVED** [review]

**Comment by ldziedziul** [comment]
@slavagithub I've added one more commit with fixes regarding `java.net` module. They were hidden behind problems with `java.util` module

**Review by ramizdundar — APPROVED** [review]
1. I would comment what is only used for testing.
2. I would add ParralelJVMTest and QuickTest category to all of them.

WDYT? Other than these LGTM.

**Review by slavagithub — APPROVED** [review]
Looks good, thank you!

**Comment by ramizdundar** [comment]
run-lab-run

**Comment by ldziedziul** [comment]
run-lab-run

**Pull request merged**
