### PR TITLE
[DO NOT MERGE] Friendly PR bot

### PR DESCRIPTION
**Pull request by Holmistr**

### CODE REVIEW

**Comment by Holmistr** [comment]
highfive

**Comment by Holmistr** [comment]
highfive

**Comment by Holmistr** [comment]
highfive

**Comment by Holmistr** [comment]
highfive

**Comment by Holmistr** [comment]
highfive

**Comment by hz-highfive** [comment]
Test comment

**Comment by hz-highfive** [comment]
Test comment

**Comment by hz-highfive** [comment]
Test comment

**Comment by hz-highfive** [comment]
Test comment

**Comment by hz-highfive** [comment]
Test comment

**Comment by hz-highfive** [comment]
Test comment

**Comment by hz-highfive** [comment]
http://www.seznam.cz

**Comment by mmedenjak** [comment]
https://media2.giphy.com/media/xUOwGhxclbHAqMgggw/source.gif

**Comment by Holmistr** [comment]
Stop stalking us @mmedenjak ! :-D

**Comment by Holmistr** [comment]
highfive

**Comment by hz-highfive** [comment]
The job `hazelcast-pr-builder` of your PR failed ([log](${S3_BUCKET_URL}/${JOB_NAME}/${BUILD_NUMBER}/build_log.txt), [artifacts](${S3_BUCKET_URL}/${JOB_NAME}/${BUILD_NUMBER}/${JOB_NAME}-${BUILD_NUMBER}.zip)). 
        Through arcane magic we have determined that the following fragments from the build log may contain 
        information about the problem.
        <details>
        <summary>Click to expand the log file</summary>
        ```
        Here are some details
        ```
        </details>

**Comment by Holmistr** [comment]
highfive

**Comment by Holmistr** [comment]
highfive

**Comment by hz-highfive** [comment]
The job `hazelcast-pr-builder` of your PR failed ([log](https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder-high-five/18/build_log.txt), [artifacts](https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder-high-five/18/Hazelcast-pr-builder-high-five-18.zip)). 
        Through arcane magic we have determined that the following fragments from the build log may contain 
        information about the problem.
        <details>
        <summary>Click to expand the log file</summary>
        ```
        Here are some details
        ```
        </details>

**Comment by hz-highfive** [comment]
The job `hazelcast-pr-builder` of your PR failed ([log](https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder-high-five/20/build_log.txt), [artifacts](https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder-high-five/20/Hazelcast-pr-builder-high-five-20.zip)). 
        Through arcane magic we have determined that the following fragments from the build log may contain 
        information about the problem.
        <details>
        <summary>Click to expand the log file</summary>
        ```
        Here are some details
        ```
        </details>

**Comment by Holmistr** [comment]
highfive

**Comment by hz-highfive** [comment]
The job `hazelcast` of your PR failed ([log](sss), [artifacts](aaa)). 
Through arcane magic we have determined that the following fragments from the build log may contain 
information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
bbb
</details>
</pre>

**Pull request closed without merging**
