### PR TITLE
fixes #4750. Membership events are ordered via client uuid used as key. 

### LINKED ISSUE #4750: [TEST-FAILURE] ClientRegressionTest.testIssue1181
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/540/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client/ClientRegressionTest/testIssue1181/

### PR DESCRIPTION
**Pull request by sancar**
Initial member list is waited at startup to make the behaviour consistent.

### CODE REVIEW

**Comment by sancar** [comment]
also fixes https://github.com/hazelcast/hazelcast/issues/4766

**Comment by sancar** [comment]
also a possible fix for #4771

**Comment by gurbuzali** [comment]
verify

**Comment by gurbuzali** [comment]
:+1:

**Pull request merged**
