### PR TITLE
[FORWARD-PORT] Publish WAN events in CacheMergeOperation

### PR DESCRIPTION
**Pull request by mmedenjak**
Fixes: https://github.com/hazelcast/hazelcast/issues/12186
Test in EE PR: https://github.com/hazelcast/hazelcast-enterprise/pull/1896

Forward port of: https://github.com/hazelcast/hazelcast/pull/12226
(cherry picked from commit 6ea7b4272773ce15f5907401c7ff488888f0a8b4)

### CODE REVIEW

**Comment by ahmetmircik** [comment]
@mmedenjak In master, we have `CacheMergeOperation` and `CacheLegacyMergeOperation` which are not inline with maintenance counterparts any more.

**Comment by mmedenjak** [comment]
@ahmetmircik fixed, please check

**Comment by Donnerbart** [comment]
`CacheLegacyMergeOperation` in master should be the same as `CacheMergeOperation` in maintenance. I think I didn't change anything import there beside the name + type id name.

**Comment by ahmetmircik** [comment]
@mmedenjak do we also need to fix same issue inside new `CacheMergeOperation`?

**Comment by Donnerbart** [comment]
I think I need to fix the `WanReplicationRef` etc. first, before the new merge policies will work for map and cache replication.

**Comment by mmedenjak** [comment]
@ahmetmircik seems the `CacheMergeOperation` [is already publishing the WAN event](https://github.com/hazelcast/hazelcast/blob/cb1d225b7a84fb671abdce9fb48d01abe9b32604/hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheMergeOperation.java#L98-L106). 
@Donnerbart I see the logic there assumes if the `backupRecord` is `null`, the record was removed and we should send a WAN remove event. Is this correct?

**Comment by Donnerbart** [comment]
This `null` means remove logic is still a little PITA for me, since it's not implemented everywhere. I'm not sure if I should remove it entirely, since it's quite complex to integrate with batching for all data structure, if you have the need for mixed add/update/remove backup batch operations.

**Comment by mmedenjak** [comment]
@Donnerbart I'm not sure what should be the decision but I noticed that the `CacheMergeOperation`, `CacheLegacyMergeOperation`, `LegacyMergeOperation` take different approaches. I guess you may open an issue so we take a closer look.

**Comment by Donnerbart** [comment]
I've already started to fix the implementation (for map + cache). The problem is tracked in my split-brain overview issue.

**Pull request merged**
