### PR TITLE
Introduced com.hz.util.function.Function interface

### PR DESCRIPTION
**Pull request by pveentjer**
Needed for the IO-pipeline

### CODE REVIEW

**Comment by mdogan** [comment]
What about `com.hazelcast.core.IFunction`:

```java
public interface IFunction<T, R> extends Serializable {

    R apply(T input);
}
```

**Comment by pveentjer** [comment]
The java.util.Function is not serializable, IFunction is. IFunctions should therefor always be able to be serialized. My main implementation of the Function will certainly not be serializable since it relies on all kinds of HZ resources. Apart from that; having a function that isn't in com.hazelcast.util.function like the rest of the Java classes like Consumer, Supplier etc isn't very intuitive (hence I didn't find IFunction)

**Comment by mmedenjak** [comment]
@pveentjer is this PR still valid?

**Comment by Holmistr** [comment]
Closing for inactivity. Please reopen if necessary.

**Pull request closed without merging**
