### PR TITLE
Near cache consistency improvements

### PR DESCRIPTION
**Pull request by ahmetmircik**
- Removed stale read probability during near cache updates.
- Removed `KeyStateMarker` and introduced record states. A record can have 3 states now UPDATE_STARTED, REMOVE_REQUESTED, READ_PERMITTED. This new approach will help to utilize near cache more effectively compared to existing approach. Because in existing approach, only one thread can operate on a partition, if other threads want to put some other keys belonging to that partition, they can't do it because partition is already locked by first thread. 
- fixes https://github.com/hazelcast/hazelcast/issues/9403
- Implemented `computeIfPresent` and `merge` for `IConcurrentMap` and introduced `IBiFunction`

PS: EE part will be introduced upon end of this PRs' review.

### CODE REVIEW

**Comment by jerrinot** [comment]
@ahmetmircik: what's preventing to have this merged?

**Comment by ahmetmircik** [comment]
@jerrinot ee counterpart is not ready yet.

**Comment by Donnerbart** [comment]
Fixes https://github.com/hazelcast/hazelcast/issues/9536

**Comment by ahmetmircik** [comment]
@vbekiaris fixed

**Pull request merged**
