### PR TITLE
Introduce ManageableClock

### PR DESCRIPTION
**Pull request by blazember**
Many tests use `sleep`s and rely on that certain actions happen within
the time bounds defined by the test. These time bounds are measured against
the system time. This is both time consuming, since the test occupies a
slot for testing while actually not making any progress (due to sleep) and
is also sensitive to high load on the testing system.

With this change we make an attempt to manage the time in the test cases
where it is needed and applicable so that no sleep is needed and since
the time is measured against a virtual clock, the hiccups caused by the
scheduler pressure are not present anymore, since elapsing the time
doesn't contain these hiccups anymore.

On the technical ground the idea is to perform this without a single
line of prod code change. There is already the `Clock` abstraction that we
can extend in the test scope with the manageability features. This is
done by extending `Clock.ClockImpl` in the test scope by `ManageableClock`.
The `ManageableClock` has three operational modes:
- `SYSTEM` (default): we use the system time
- `MANAGED`: we take a snapshot of the system time and return that until
the time is advanced programmatically
- `SYNCHRONIZED`: the current clock returns the time of another clock

Beyond the above, we can assign a dedicated clock to every
`HazelcastInstance` created (default) or use a common clock for all. This
is done by using a `Clock.ClockImpl` implementation that uses an
`InheritableThreadLocal<ManageableClock>` under the hood always returns
the time from this thread-local instance. When an instance is created,
all of its threads inherit the clock set for the test's thread at time
of instance creation, therefore the multiple instances will end up having
multiple, instance-dedicated clocks.

For easy support of this `ManageableClockRule` is added to
`HazelcastTestSupport`. That serves multiple purposes. First, it makes sure
the thread-local `Clock.ClockImpl` is used in the test. It does it in all
tests, which is safe given the default behavior of the `ManageableClock`
is returning the system time, which is effectively no change. Second, it
makes sure the thread-local clock of the test resets before and after
every test execution. Third, if the rule is assigned to the
`TestHazelcastInstanceFactory` used by the test, it maintains the
`HazelcastInstance->ManageableClock` mapping, which makes it
straightforward to work with an instance's clock by calling
`clockOf(instance)`.

`TestHazelcastInstanceFactory` is modified that it assigns a dedicated
clock for every created HazelcastInstance, unless there is one set for
the test's thread, in which case the test's clock will be inherited by
the HazelcastInstance's threads.

All tests extending `HazelcastTestSupport` get all this for free and
without any ceremony can start tweaking the time individually on
per-HazelcastInstance or per-cluster (if the cluster members' clocks are
synchronized) basis.

Known issues

This idea with the clocks doesn't play nicely with some client tests that
create static instances and test against the very same instances from every
test cases in parallel. The test cases in these tests relying on time should
ideally be extracted to a test class that creates the instances per test case.

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2805/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2805/Hazelcast-pr-builder-2805.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java:1701:116: '+' should be on a new line. [OperatorWrap]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/test/TestHazelcastInstanceFactory.java:242:31: '{' is not preceded with whitespace. [WhitespaceAround]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2806/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2806/Hazelcast-pr-builder-2806.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClockTest.testCreateClock_withClockOffset:70->HazelcastTestSupport.assertInstanceOf:926 com.hazelcast.test.ThreadLocalManageableClock@4c28e6c9 is not an instanceof com.hazelcast.internal.util.Clock$SystemOffsetClock
[ERROR]   ClockTest.testCreateClock_withDefaults:52->HazelcastTestSupport.assertInstanceOf:926 com.hazelcast.test.ThreadLocalManageableClock@17a82342 is not an instanceof com.hazelcast.internal.util.Clock$SystemClock
[ERROR]   ProbabilisticSplitBrainProtectionFunctionTest.testSplitBrainProtectionAbsent_whenHeartbeatsLate:69
[ERROR]   RecentlyActiveSplitBrainProtectionFunctionTest.testSplitBrainProtectionAbsent_whenHeartbeatsReceivedBeforeToleratedWindow:72
[INFO] 
[ERROR] Tests run: 3767, Failures: 4, Errors: 0, Skipped: 14
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by blazember** [comment]
run-lab-run

**Comment by jerrinot** [comment]
Is there a chance to have this reliable? even if we make our our code to use exclusively the managed clock then the moment we delegate e.g. to JDK classes then this will use the unmanaged clocks. Code which uses `System.nano()` to measure elapsed time will not respect this. What am I missing anything?

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2809/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2809/Hazelcast-pr-builder-2809.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ManageableClockTest.testCallingUnsyncThrowsInSystemMode:131 expected java.lang.AssertionError to be thrown, but nothing was thrown
[INFO] 
[ERROR] Tests run: 31990, Failures: 1, Errors: 0, Skipped: 979
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by blazember** [comment]
@jerrinot So you'd like to see even the JDK time to be managed? That's a tricky thing. We would need to make sure `System.currentTimeMillis()` returns different time for different callers. Specifically, some need to get the real system time (logging, probably executors, some backoff logic too, etc), while for others we can tweak the time as we need for our testing approach. This all may want to see different times on the same thread. The idea behind this `ManageableClock` attempt is that we can use the `Clock` abstraction (either ours or JDK's, since we are on Java8) for this differentiation. Where we need to get the system time always, we can still use the low-level JDK method (which is intrinsic btw).

**Comment by jerrinot** [comment]
I know it's a tricky thing. Hence I am questioning the feasibility of this overall approach. 

This is my understanding of the idea behind this PR: 
We have an expiration test. It stores an entry with TTL set to 5 seconds. Then the test sleeps 1s and then checks the entry is still there. There is an obvious issue: A system hiccup may cause the test to sleep more than 1s. When it sleeps 5+ seconds then it won't find the entry and the test fails. 

Now with this PR you would not sleep at all. You would just shift the ManagedClock to 1s. and if all components uses exclusively the ManagedClock for everything time-related then the test will still pass. No matter how the actual/real time passes. 

Am I getting the idea right? If that's the case then I would argue you are testing implementation details. The test relies on the fact no other component uses any other source of time. That's probably OK for unit-tests. For example when testing the scheduler in isolation. However I am not sure about using this in Integration tests (=most of problematic cases).

**Comment by blazember** [comment]
Closing as this idea didn't take off and is quite outdated.

**Pull request closed without merging**
