### PR TITLE
Mark commons logging package as optional import in OSGi metadata

### PR DESCRIPTION
**Pull request by netudima**
https://github.com/hazelcast/hazelcast/issues/10770

### CODE REVIEW

**Comment by mdogan** [comment]
run-lab-run

**Comment by mdogan** [comment]
@netudima:

Could you please send us signed copy of the Hazelcast Contributor Agreement? This is our formal merge procedure for community contributions. Thanks.
https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by netudima** [comment]
@mdogan: 
> Could you please send us signed copy of the Hazelcast Contributor Agreement?
yes, will do it today/tomorrow

**Comment by netudima** [comment]
@mdogan: 
> Could you please send us signed copy of the Hazelcast Contributor Agreement?

done - https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Pull request merged**
