### PR TITLE
Fix issue #4315 and #2431

### PR DESCRIPTION
**Pull request by Donnerbart**
Should fix issue #4315 and #2431 by adding an interface `ConfigPatternMatcher` to provide different and user configurable matching algorithms for Hazelcast instance and client.

### CODE REVIEW

**Comment by gurbuzali** [comment]
@Donnerbart can you comment on mehmet's inputs and update the PR accordingly if you see fit

**Comment by gurbuzali** [comment]
@Donnerbart ?

**Comment by Donnerbart** [comment]
Sorry, finished higher prio tasks first. Now I'm on the way to a wedding, so out of office for the rest of the day.

**Comment by Donnerbart** [comment]
I changed the default matcher for clienter and server to the new `MatchingPointConfigPatternMatcher`. I added a log warning if no configuration is found by a matcher. I also added a new `ConfigurationException` which is thrown by all new matchers if more than one configuration is found. The exception logs the itemName and both configuration names. The legacy matchers won't throw that exception to be 100% backward compatible. I changed the documentation accordingly to the new behavior and added tests to check for the exception.

I hope with the latest changes we don't surprise our customers with the API change, since the configuration matching should not fail silently anymore.

**Comment by mdogan** [comment]
After a quick scan, changes seem fine to me.

**Comment by mdogan** [comment]
One minor issue I saw today, when `default` config is requested, following warning is printed:

```
11:22:07,003  WARN [Config] - No configuration found for default, using default config!
```

**Comment by Donnerbart** [comment]
Can I submit a fix to this PR or should I make a new one?

**Comment by gurbuzali** [comment]
a new one I guess

**Pull request merged**
