### PR TITLE
Added missing https URLs for all xsds since 3.8

### PR DESCRIPTION
**Pull request by MichaelRisthausAtos**
This fixes issue #14398

### CODE REVIEW

**Comment by kwart** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Hi @MichaelRisthausAtos !

Before we can merge, can you please follow the instructions to sign and send the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)?

**Comment by MichaelRisthausAtos** [comment]
Hi!

Sure! :) But not until tomorrow… today I’m in home office and don’t have a scanner to use near me.

Regards,
Michael

**Comment by MichaelRisthausAtos** [comment]
Done: PR #14407

**Comment by MichaelRisthausAtos** [comment]
> Hi @MichaelRisthausAtos !
> 
> Before we can merge, can you please follow the instructions to sign and send the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)?

I've just sendet the document to 'cla@hazelcast.com'.

Regards,
Michael

**Comment by kwart** [comment]
Thanks for the CLA, the wiki is updated.

**Comment by kwart** [comment]
run-lab-run

**Comment by kwart** [comment]
run-lab-run

**Comment by kwart** [comment]
run-lab-run

**Pull request merged**
