### PR TITLE
Remove extra new line after message body in HTTP response for the REST API

### PR DESCRIPTION
**Pull request by cangencer**
Fixes issue #6144

### CODE REVIEW

**Comment by pveentjer** [comment]
Can you add a test for this?

**Comment by cangencer** [comment]
No new tests but I've updated the tests so that they don't use readLine() to read the response. This way they fail with the extra line new line at the end of the reponse body.

**Comment by Donnerbart** [comment]
:+1: Looks good for new, but would appreciate another pair of eyes :)

If we need an explicit test we could use the REST client code from the code samples as base (which is not working due to #6144 at the moment).

**Comment by cangencer** [comment]
I did test it against the sample code, and it works from there as well. Some more useful info here:

http://stackoverflow.com/questions/13821263/should-newline-be-included-in-http-response-content-length/30677511#30677511

**Comment by pveentjer** [comment]
:+1:

**Pull request merged**
