### PR TITLE
adding the exception to the log warning in ClientCacheMetaDataFetcher

### PR DESCRIPTION
**Pull request by StefanLiebenberg**
This PR adds additional exception information to log warning.

### CODE REVIEW

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
@StefanLiebenberg thanks for your contribution, before we can review & merge can you follow the instructions to sign and send the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)?

There's a checkstyle issue in the PR:
```
/hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/nearcache/invalidation/ClientCacheMetaDataFetcher.java:75: Line is longer than 130 characters (found 133).
```

You can ensure there are no such issues by running locally:
```
mvn -Pcheckstyle,findbugs clean install
```
under `hazelcast` root.

**Comment by Holmistr** [comment]
Hi @StefanLiebenberg  ,

could you please sign the contributor agreement? We really appreciate your effort, so we would like to move on this PR.

**Comment by pveentjer** [comment]
@StefanLiebenberg could you sign the Hazelcast Contributor Agreement? Otherwise we can't merge your work.

**Comment by StefanLiebenberg** [comment]
Why is there not a online, easier way to sign this agreement? For me, having this PR accepted is not worth the effort of trying to find a printer/scanner. I won't mind if you discard the PR.

**Comment by Holmistr** [comment]
@StefanLiebenberg I have double checked with our legal department. This is a law thing and the problem is that some jurisdictions don’t accept electronic signatures so we would need to know what laws will govern the contribution agreement. And this is indeed complicated, because anybody from all around the world might contribute, hence the only option is to have it the way we have that :(
I totally share your pain, but there's nothing we can do about it. Wouldn't you reconsider signing the agreement? I promise you will be in a hall of same :)

**Comment by StefanLiebenberg** [comment]
I don't have access to either a printer or a scanner, perhaps the legal department would be willing to mail the agreement to me?

**Comment by mmedenjak** [comment]
@StefanLiebenberg if it's a big issue for you, I will create my own PR with your changes. That way, we get the changes fixed but you will need to sign and send us the agreement next time. Does that work for you?

**Comment by StefanLiebenberg** [comment]
You can include this change in a PR of your own, sure. Or you can discard it. It’s all the same to me.

**Comment by mmedenjak** [comment]
Closing in favour of https://github.com/hazelcast/hazelcast/pull/12579

**Pull request closed without merging**
