### PR TITLE
Refactor client partition lost listener invocation tests

### LINKED ISSUE #6142: [TEST-FAILURE] map.ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest$1.run(ClientMapPartitionLostListenerTest.java:97)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:737)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:751)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest.assertMapPartitionLostEventEventually(ClientMapPartitionLostListenerTest.java:91)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode(ClientMapPartitionLostListenerTest.java:124)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.6/com.hazelcast$hazelcast-client-new/285/testReport/junit/com.hazelcast.client.map/ClientMapPartitionLostListenerTest/test_mapPartitionLostListener_invoked_fromOtherNode/

### PR DESCRIPTION
**Pull request by metanet**
Fixes #6142

### CODE REVIEW

**Comment by serkan-ozal** [comment]
:+1:

**Comment by kobalski** [comment]
:+1:

**Comment by serkan-ozal** [comment]
@metanet Could you please squash your commits?

**Comment by metanet** [comment]
No

**Comment by serkan-ozal** [comment]
ah, sorry there is only one commit :)

**Comment by metanet** [comment]
verify

**Pull request merged**
