### PR TITLE
Gives lowest priority to latest added entry when selecting candidate entry for eviction

### PR DESCRIPTION
**Pull request by ahmetmircik**
closes https://github.com/hazelcast/hazelcast/issues/4334
closes https://github.com/hazelcast/hazelcast/issues/7634

### CODE REVIEW

**Comment by serkan-ozal** [comment]
👍

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
verify

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by gurbuzali** [comment]
👍

**Pull request merged**
