### PR TITLE
Correct request should be used when removing item listeners

### PR DESCRIPTION
**Pull request by cangencer**

### CODE REVIEW

**Comment by sancar** [comment]
run-lab-run

**Comment by sancar** [comment]
Can you also include the ClientQueueProxy in this fix. It looks like I made the same mistake also there.

**Comment by cangencer** [comment]
done, there was the same problem in TopicProxy as well.

**Comment by pveentjer** [comment]
Can you create a test which demonstrates that the original problem existed and verifies that the problem is now resolved?

**Comment by cangencer** [comment]
@pveentjer There are tests in enterprise repo, where this problem originated in the first place. See hazelcast/hazelcast-enterprise#493

**Comment by sancar** [comment]
:+1:

**Comment by pveentjer** [comment]
If this functionality is used on HZ OS, we should have test for HZ OS.

**Comment by cangencer** [comment]
As all remove listener requests are very similar (they just pass a topic name + registration id), the only way to test them is using SecurityInterceptors which can intercept the actual method name. Those are available only on Enterprise.

**Comment by hasancelik** [comment]
run-lab-run

**Pull request merged**
