### PR TITLE
Map/reduce type variance improvements

### PR DESCRIPTION
**Pull request by Leperous**
You should be able to pass a more variantly-typed reducer, combiner and predicate to a mapping job. The job does not mutate any data so this is a well defined operation.

The same also holds for the KeyValueSource factory methods.

### CODE REVIEW

**Comment by pveentjer** [comment]
@noctarius can you have a look since you created the map reduce api.

**Comment by noctarius** [comment]
Since it just adds extends / super for producer and consumers it should be fine. I guess all test are still running tho :)

**Comment by pveentjer** [comment]
@noctarius what are we going to do with this pr?

**Comment by noctarius** [comment]
I guess we can merge it but I'm not module owner anymore, I suppose :)

**Comment by bilalyasar** [comment]
Can one of the admins verify this patch?

**Comment by pveentjer** [comment]
verify

**Comment by mtopolnik** [comment]
This PR has become stale and was revived as #6693

**Pull request closed without merging**
