### PR TITLE
[WIP] [HZ-203] Adds explicit auto/manual rebalance modes

### PR DESCRIPTION
**Pull request by vbekiaris**
Also adds configurable partition rebalance
delay when member leaves cluster
unexpectedly.

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
Superseded by #19013

**Pull request closed without merging**
