### PR TITLE
add explicit null checks for password in UsernamePasswordCredentials

### LINKED ISSUE #11767: Coverity - dereference null return value - ClientConnectionManagerImpl.encodeAuthenticationRequest()
The call `cr.getPassword()` may return `null` value in the `com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.encodeAuthenticationRequest(boolean, SerializationService, ClientPrincipal)` method. The value is then dereferenced without a `null` check in `ClientAuthenticationCodec.encodeRequest` call:

```java
ClientAuthenticationCodec.encodeRequest(cr.getUsername(), cr.getPassword(), uuid, ownerUuid, asOwner, ClientTypes.JAVA,
    serializationVersion, BuildInfoProvider.getBuildInfo().getVersion());
```

The `encodeRequest()` calls `ParameterUtil.calculateDataSize(String string)` in which `string.length()` is called.

https://scan4.coverity.com/reports.htm#v32322/p13030/fileInstanceId=29225738&defectInstanceId=5757169&mergedDefectId=202151

### PR DESCRIPTION
**Pull request by sancar**
fixes #11767

### CODE REVIEW

**Comment by ihsandemir** [comment]
@kwart The null checks are at GroupConfig.setName and GroupConfig.setPassword.(Also XmlClientConfigBuilder.handleGroup for the xml config handles null name)

**Comment by sancar** [comment]
run-lab-run

**Comment by sancar** [comment]
run-lab-run

**Comment by sancar** [comment]
run-lab-run

**Pull request merged**
