### PR TITLE
Client message internal buffer created with correct size for decode

### PR DESCRIPTION
**Pull request by asimarslan**

### CODE REVIEW

**Comment by pveentjer** [comment]
Looks good. Is there sufficient testing, e.g. when insufficient data available to read out the frame length?

**Comment by asimarslan** [comment]
Yes there are tests in `com.hazelcast.client.protocol.ClientMessageAccumulatorTest`

**Comment by pveentjer** [comment]
+1 This is going to be backported to 3.6 maintenance?

**Comment by asimarslan** [comment]
I'll backport if this one succeed.

**Comment by sancar** [comment]
:+1:

**Comment by ihsandemir** [comment]
:+1:

**Pull request merged**
