### PR TITLE
Avoid unnecessary HashSets in ClientMapProxy.convertKeysToData and MapGetAllMessageTask

### PR DESCRIPTION
**Pull request by LoneRifle**
@cangencer noted on [gitter](https://gitter.im/hazelcast/hazelcast?at=56825e120199d70069e00edf) that ClientMapProxy.convertKeysToData should return an ArrayList instead of a HashSet, to avoid unneeded hashing. Further, MapGetAllMessageTask had an unnecessary HashSet which should be removed.

This PR ratifies this.

### CODE REVIEW

**Comment by sancar** [comment]
verify

**Comment by sancar** [comment]
Hi @LoneRifle 
Your pull request failed with following errors

```09:59:15 /scratch/jenkins/workspace/Hazelcast-3.x-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapGetAllMessageTask.java:27:8: Unused import - com.hazelcast.nio.serialization.Data.
09:59:15 /scratch/jenkins/workspace/Hazelcast-3.x-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapGetAllMessageTask.java:33:8: Unused import - java.util.HashSet.
09:59:15 /scratch/jenkins/workspace/Hazelcast-3.x-pr-builder/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapGetAllMessageTask.java:34:8: Unused import - java.util.Map.```

**Comment by LoneRifle** [comment]
Have already cleared those on being notified - verify by inspecting the
file changes

**Comment by sancar** [comment]
verify

**Comment by sancar** [comment]
@LoneRifle 
One more checkstyle error
`16:18:34 /scratch/jenkins/workspace/Hazelcast-3.x-pr-builder/hazelcast-client/src/main/java/com/hazelcast/client/proxy/NearCachedClientMapProxy.java:47:8: Unused import - java.util.Set.`

**Comment by LoneRifle** [comment]
Corrected and rebased. Sorry for the trouble.

**Comment by sancar** [comment]
verify

**Comment by sancar** [comment]
@LoneRifle No problem. Thanks for the pr.

**Pull request merged**
