### PR TITLE
Add support for returning nested fields without deserializing them

### PR DESCRIPTION
**Pull request by sancar**
This will enable Portable users to use client/server usecases
without touching the server side.

fixes https://github.com/hazelcast/hazelcast/issues/18595

### CODE REVIEW

**Comment by sancar** [comment]
I had to touch too many files. Leaving here some guidelines so that we may simplify the PRD. 

I had to add a parameter to Row.get() to be able to determine if I need to return the nested field as Data or as Object. Only place where the `asDataIfPossible` is set `AbstractMapScanExec#prepareRow` method. Note that on the same method `filter.evalTop(row, ctx)` also reads a field but as Object to be able compare. 

`asDataIfPossible` this one is used only for Portable and nested Portable fields. 

I have added two tests in SqlClientServerUseCaseTest. The common inportant part is the server does not have any Portable configuration and can not deserialize to users class. 

`testNestedPortableOnTheQuery`
One is to test if accessing a field of nested Portable is working. This is not addressed in this pr. It should already work according to sql team. It is failing but I am waiting for sql team's input for that. If we found out that it is not working I will remove the test from the pr and address the problem in a seperate pr. 

`testNestedPortableAsColumn`
This is the test which is addressed in this pr.

**Comment by gierlachg** [comment]
TBH if I have top-level `GenericRecord` I would expect it's children to be `GenericRecord`s as well.
Moreover, Isn't top-level `Portable` read as `GenericRecord` in case of missing factory? Could not we do the same for children?

**Comment by gierlachg** [comment]
Looks much, much simpler. I definitely prefer  #18922

**Comment by sancar** [comment]
Closing this in favor of https://github.com/hazelcast/hazelcast/pull/18922

**Pull request closed without merging**
