### PR TITLE
Fix #5900: call GZIPOutputStream.finish at end of serializer.write if gzipEnabled

### LINKED ISSUE #5900: Serialization compression is broken due to unfinished GZIPOutputStreams
When compression is enabled, the serializers for Serializables and Externalizables will put a GZIPOutputStream between ObjectOutputStream and target OutputStream when serializer.write is called. This usually results in the following HazelcastSerializationException on reading:

    Problem while reading Externalizable class : 
    com.hazelcast.nio.serialization.SerializationTest$ExternalizableString, exception:
    java.io.EOFException: Unexpected end of ZLIB input stream

GZIPOutputStream.finish() should hence be called to ensure everything gets written to the target OutputStream.

A related issue can be found here - https://groups.google.com/forum/#!topic/hazelcast/CRAXXbberek

### PR DESCRIPTION
**Pull request by LoneRifle**
* Create two tests that demonstrate compression in ObjectSerializer and Externalizer. The tests will serialize an object, deserialize the resulting Data, and compare the original object with the deserialized one to ensure no loss of fidelity.

* Ensure that GZIPOutputStream.finish is called at the end of serializer.write if gzipEnabled, to ensure that everything in the gzip buffer gets flushed out.

Fixes #5900

### CODE REVIEW

**Comment by pveentjer** [comment]
Thanks for you bug report + fix!

Can you sign our contributor agreement so we can merge your PR?
https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by LoneRifle** [comment]
Agreement signed and sent.

**Comment by pveentjer** [comment]
Looks good to me. What about it @gurbuzali or @mdogan

**Comment by jerrinot** [comment]
:+1:

**Comment by jerrinot** [comment]
@LoneRifle Thanks for your contribution, it's much appreciated! 

It'd be nice to have a backport to a maintenance branch (https://github.com/hazelcast/hazelcast/tree/maintenance-3.x) so we could include it in the `3.5.2` release. Could you please send a new PR with the backport? No worries if you are busy, I can backport it myself. Just let me know. Thanks!

**Comment by LoneRifle** [comment]
I'll try my best, but you might beat me to it since I am indeed busy at the moment.

**Pull request merged**
