### PR TITLE
Adds support for HazelcastJsonValue over Rest

### PR DESCRIPTION
**Pull request by mustafaiman**
When a HazelcastJsonValue is requested over Rest API, we return UTF8 encoded json value. Response has the json string in payload and "Content-Type" header is set to application/json. This is a very small change. Rest of the PR is about refactoring to test classes.

### CODE REVIEW

**Comment by mustafaiman** [comment]
run-lab-run

**Comment by mustafaiman** [comment]
Thanks for the reviews!

**Comment by jszap** [comment]
Will a json POST create a  HazelcastJsonValue? 
For example...
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"username":"xyz","password":"xyz"}' \
  http://1localhost:5701/hazelcast/rest/maps/myUserMap/key-xyz

**Comment by jszap** [comment]
Nope, still RestValue :(

**Comment by mmedenjak** [comment]
@jszap can you create a new issue for this? I see it as an enhancement but I'm not sure we can introduce it before the next major version.

**Pull request merged**
