### PR TITLE
Changed naming of SortLimitTest to PagingPredicateTest

### PR DESCRIPTION
**Pull request by ahmetmircik**

### CODE REVIEW

**Comment by gurbuzali** [comment]
👍

**Comment by gurbuzali** [comment]
just a naming change for the test, merging

**Comment by mdogan** [comment]
what about `com.hazelcast.map.impl.query.HDSortLimitTest` in EE?

```java
public class HDSortLimitTest extends SortLimitTest {
...
```

**Comment by ahmetmircik** [comment]
Thanks @mdogan. Fixed here https://github.com/hazelcast/hazelcast-enterprise/commit/4e4b9ae7f13d5e0c654e4c03ff2d14f075beac00

**Pull request merged**
