### PR TITLE
Set updatePolicy for release repositories to never

### PR DESCRIPTION
**Pull request by frant-hartm**
This avoids re-downloading maven metadata every day.

### CODE REVIEW

**Review by kwart — COMMENTED** [review]
Do you know how does it work in cases when the artifact (GAV) is not present locally and it's not found in the repository (yet)? Is it retried next time?

If it's not retried for missing artifacts, then we shouldn't proceed with this change.

I saw this old blog post, but I'm not sure if it's still valid for newer Maven versions.
https://blog.saddey.net/2010/02/07/maven-never-say-never-in-an-updatepolicy/

**Comment by frant-hartm** [comment]
It also provides this message:

```
[ERROR] Failed to execute goal on project hazelcast-root: Could not resolve dependencies for project com.hazelcast:hazelcast-root:pom:5.1-SNAPSHOT: Failure to find com.hazelcast:dummy:jar:1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

**Comment by frant-hartm** [comment]
Another option is to use `interval:x` where x is in minutes, e.g. `interval:10080` for one week.

**Comment by ramizdundar** [comment]
I am not an expert in this area but with what @frant-hartm said, this looks good as it is to me.

**Comment by kwart** [comment]
I think the `interval` (configured for 1 or 2 weeks) would be a safer choice.
Imagine a user trying to fix vulnerable dependency by updating the version number. If the version is not yet in the repository (404 returned) then IIUC the retrieval fails together with all subsequent ones. Unless the `-U` is specified.

**Comment by ramizdundar** [comment]
I'll ping this to bring forward because it's a QOL change I look forward to. Can we agree on some conclusion? My personal opinion would be go with never and if it causes some problems we can change to 1-2 weeks or find some other solution.

**Comment by kwart** [comment]
> I'll ping this to bring forward because it's a QOL change I look forward to. Can we agree on some conclusion? My personal opinion would be go with never and if it causes some problems we can change to 1-2 weeks or find some other solution.

OK, let's give it a try. We can revert later if we see issues with the approach.

**Review by kwart — APPROVED** [review]

**Review by ramizdundar — APPROVED** [review]

**Pull request merged**
