### PR TITLE
Change missing mapping error message

### PR DESCRIPTION
**Pull request by gierlachg**
Changed missing mapping error message so it mentions `CREATE MAPPING`.

If I'm reading Calcite sources correctly [ObjectNotFound](https://github.com/apache/calcite/blob/12a484a5c364c36e9551e59f4dc33bfb219ecf07/core/src/main/java/org/apache/calcite/sql/validate/IdentifierNamespace.java#L183) can be thrown only if we fail to [resolveTable](https://github.com/apache/calcite/blob/12a484a5c364c36e9551e59f4dc33bfb219ecf07/core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorScope.java#L202). `If the "table" is defined in a WITH clause it may be a query, not a table after all.`. However, we don't support `WITH` (yet?).

### CODE REVIEW

**Comment by utkukaratas** [comment]
@emre-aydin this is just what we talked about. sql team is already on it. godspeed @gierlachg; the old error message ("map not found" really left me confused for some time.)

**Comment by Holmistr** [comment]
If I understand the PR correctly, it doesn't distinguish between two cases:
* The map is not existing
* The map exists but mapping was not created yet.

@gierlachg Is that correct? If so, would be it possible to distinguish between those cases?

**Comment by gierlachg** [comment]
The exception is thrown from deep inside Calcite guts. We would have to start catching exceptions and parsing their exceptions... very brittle. Calcite does not have an extension point for such a case, at least I didn't find one.

**Review by Holmistr — APPROVED** [review]

**Review by Holmistr — APPROVED** [review]
Approving the error message format.

**Review by viliam-durina — APPROVED** [review]

**Pull request merged**
