### PR TITLE
Centralise `os.name` calls

### PR DESCRIPTION
**Pull request by JackPGreen**
There are two utility classes that abstract operating system detection:

- `com.hazelcast.internal.tpcengine.util.OS`
- `com.hazelcast.internal.util.OsHelper`

Both duplicate sections of each other, and other parts of the system use neither and roll their own.

Consolidated all implementations to:

- Use a utility class where possible
- Merge `OsHelper` into `OS`
- Remove `OsHelper`
- Tidy `OS` Javadoc

EE PR: https://github.com/hazelcast/hazelcast-enterprise/pull/6746

### CODE REVIEW

**Comment by JackPGreen** [comment]
run-with-os

**Comment by JackPGreen** [comment]
run-with-ee

**Review by vbekiaris — CHANGES_REQUESTED** [review]
Both `OsHelper` and `OS` classes are utility classes (`final` class, `private` constructor & only `static` methods). There is no reason to keep both around or make a class hierarchy out of them, let's just consolidate all `static` methods in `OS` class.

**Comment by JackPGreen** [comment]
> Both `OsHelper` and `OS` classes are utility classes (`final` class, `private` constructor & only `static` methods). There is no reason to keep both around or make a class hierarchy out of them, let's just consolidate all `static` methods in `OS` class.

Done, was trying to avoid changing lots of places but actually wasn't as bad as I thought.

**Comment by JackPGreen** [comment]
run-lab-run

**Comment by JackPGreen** [comment]
run-lab-run

**Comment by JackPGreen** [comment]
run-lab-run

**Review by pveentjer — APPROVED** [review]

**Comment by pveentjer** [comment]
Ideally we would have a commons utility maven module. I guess this will be one of the first things that needs to be done when we start to modularize the codebase.

**Review by vbekiaris — APPROVED** [review]

**Pull request merged**
