### PR TITLE
Revert changes to MemoryStats

### PR DESCRIPTION
**Pull request by mtopolnik**
The attempt to introduce an abstract notion of statistics for a MemoryManager failed because statistics are tightly coupled to the actual implementation and the abstract notions are of questionable value.

Therefore the `getStatistics` methods was removed from the general `MemoryManager` and the `MemoryStats` interface was reverted to prior state. The only change is the removal of the redundant `Memory` word from `getXNativeMemory` methods.

### CODE REVIEW

**Comment by mtopolnik** [comment]
Merging now as these changes are urgent to make the EE side build again.

**Comment by toktarev** [comment]
Could you please explain motivation of this change in details ?
MemoryStats is public API ?

**Comment by mtopolnik** [comment]
This is the undoing of the previous change. MemoryStats wasn't public API before, therefore isn't now, either. In the future maybe we'll manage to properly generalize MemoryStats.

**Comment by toktarev** [comment]
If MemoryStats wasn't public API before, why we can't modify it ?
The change was really valuable and decoupled MemoryStats from memory implementation

**Comment by mtopolnik** [comment]
The immediate concern is insufficient work on a sensible implementation in
HZ memory manager. The API itself will need work to accommodate that. To
make EE buildable again this had to be removed.

**Pull request merged**
