### PR TITLE
Remove unneeded offload

### PR DESCRIPTION
**Pull request by ahmetmircik**

### CODE REVIEW

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Please assign the PR to a milestone.

**Review by vbekiaris — APPROVED** [review]
@Danny-Hazelcast it would be great if you could run your hot-restart tests with Merkle trees enabled once this PR is merged

**Comment by ahmetmircik** [comment]
@vbekiaris thanks for the review.

**Pull request merged**
