### PR TITLE
[DONT MERGE] Initial work on pulling on HZ API module

### PR DESCRIPTION
**Pull request by pveentjer**

### CODE REVIEW

**Comment by pveentjer** [comment]
@gurbuzali @mdogan @asimarslan can you have a look. More work is needed, e.g. I need to move Hazelcast/HazelcastInstance and all classes depending on these. But a lot of work has been done.

**Comment by asimarslan** [comment]
@pveentjer Can you combine your multiple commits into one. Git cannot display this PR as it's too big. I'll check it out and try it with my serialization module branch.

**Comment by pveentjer** [comment]
Sure. I do the changes in small steps so I can roll back when I pull in to many changes in 1 go.

**Comment by gregrluck** [comment]
Do you have a doc that explains what you are doing with this change?

**Comment by pveentjer** [comment]
Doc: moving all interfaces/classes that are part of the public API into a seperate maven module.

**Pull request closed without merging**
