### PR TITLE
configurationURL inconsistencies fixed

### LINKED ISSUE #6061: XmlBuilder does not set URL in the config it parses
I am integrating Hazelcast in Spring Boot and I found what I think is an inconsistency. If I create the `HazelcastInstance` with the _default_ `newHazelcastInstance` static method then I get an `HazelcastInstance` whose `Config` has a valid `configurationUrl` property.

However, the following code gives me a null `configurationUrl`:

```
Config cfg = new XmlConfigBuilder(url).build();
```

Looking at `XmlConfigBuilder` it doesn't do anything with the parameter (except initializing the input stream). How about specifying the `configurationUrl` as well?

### PR DESCRIPTION
**Pull request by mesutcelik**
closes #6061

### CODE REVIEW

**Comment by bilalyasar** [comment]
https://github.com/hazelcast/hazelcast/pull/6077/files#diff-3dffd84a99122128d983e9c2491c4668R118 
Do we need to set `configurationFile` here?

**Comment by mesutcelik** [comment]
@bilalyasar ,
updated the PR.

**Comment by bilalyasar** [comment]
:+1:  looks good to merge.

**Comment by pveentjer** [comment]
:+1:

**Comment by pveentjer** [comment]
Do we need a backport?

**Pull request merged**
