### PR TITLE
Compensate backup in case  on replica loss

### PR DESCRIPTION
**Pull request by pveentjer**
If a member fails that isn't the primary, the number of
acked backups is increased by 1 to compensate for the failed member.

### CODE REVIEW

**Comment by pveentjer** [comment]
verify

**Comment by pveentjer** [comment]
verify

**Comment by mdogan** [comment]
Following test fails:
```
java.lang.AssertionError: Future has not completed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport$8.run(HazelcastTestSupport.java:902)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1158)
	at com.hazelcast.test.HazelcastTestSupport.assertCompletesEventually(HazelcastTestSupport.java:899)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_OnBackupLeftTest.whenPrimaryResponseAlreadyReceived(Invocation_OnBackupLeftTest.java:103)
```

Reason is, local partition table might be updated already after member left. So, backup replica owner check (`leftMember.getAddress().equals(partition.getReplicaAddress(k + 1))`) fails and invocation still waits for backup ack.

**Comment by pveentjer** [comment]
I just figured that out myself :) 

I saw that the replica address was still null.. so the desired member wasn't found and the test fails. I can add a null check like this:

```
  for (int k = 0; k < backupsAcksExpected; k++) {
                    Address replicaAddress = partition.getReplicaAddress(k + 1);
                    System.out.println("replica address:"+replicaAddress+" leftmember address:"+leftMember.getAddress());
                    if (replicaAddress == null || leftMember.getAddress().equals(replicaAddress)) {
                        invocation.notifyBackupComplete();
                        found= true;
                        break;
                    }
                }
```

**Comment by pveentjer** [comment]
verify

**Comment by pveentjer** [comment]
verify

**Pull request merged**
