### PR TITLE
Update Platform logo in member console

### LINKED ISSUE #25788: Enhancement: logo
Using 5.4.0-SNAPSHOT 
```
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o    
```

Doesn't match branding

### PR DESCRIPTION
**Pull request by kwart**
New platform console/log-files logo suggestion:

```
@@   @@@    @@@    @@@@@@@@   @@@@@@@  @@      @@@@@@@    @@@    @@@@@@  @@@@@@@
@@   @@@   \@@@@       @@@             @@     @@         \@@@@   @@        @@   
@@@@@@@@  \ \ @@      @@@   @@@@@@@@@  @@    @@@        \ \ @@    @@@@@    @@   
@@   @@@  0\   @@    @@                @@     @@        0\   @@      @@@   @@   
@@   @@@ 000   @@@ @@@@@@@@   @@@@@@@  @@@@@@ @@@@@@@@ 000   @@@ @@@@@@@   @@
```
image

Fixes #25788

### CODE REVIEW

**Review by vbekiaris — COMMENTED** [review]
Nice one! I tried some minor tweaks:

- A few tweaks in the "S" to fix some inconsistencies (top & bottom row now both have 5 `@`s)
- All Z diagonal line rows have 3 `@`s 
- replace `@` with space in bottom-left corner of C to make it consistent with upper curve

code:
```
    private static final String PLATFORM_LOGO
            = "\t@@   @@@    @@@    @@@@@@@@   @@@@@@@  @@      @@@@@@@    @@@     @@@@@  @@@@@@@\n"
            + "\t@@   @@@   \\@@@@       @@@             @@     @@         \\@@@@   @@        @@   \n"
            + "\t@@@@@@@@  \\ \\ @@      @@@   @@@@@@@@@  @@    @@@        \\ \\ @@    @@@@@    @@   \n"
            + "\t@@   @@@  0\\   @@    @@@               @@     @@        0\\   @@       @@   @@   \n"
            + "\t@@   @@@ 000   @@@ @@@@@@@@   @@@@@@@  @@@@@@  @@@@@@@ 000   @@@  @@@@@    @@   ";
```

looks like this:
 
Screenshot_20230925_090013

wdyt?

**Review by vbekiaris — APPROVED** [review]

**Review by frant-hartm — COMMENTED** [review]
TBH I don't like this fat style and IMO it doesn't look anything like the new logo :-/

My counter-proposal would be to use the current design without the logo with couple of minor adjustments:

```
o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
|    |    / \       /         |     /         / \    |         |   
o----o       o     o   o----o |    o             o   o----o    |   
|    |  *     \   /           |     \       *     \       |    |   
o    o *       o o---o   o--o o----o o---o *       o o----o    o   
```

**Comment by kwart** [comment]
Reopening, we don't want to use the old logo.

**Comment by kwart** [comment]
Closing - replaced by https://github.com/hazelcast/hazelcast-mono/pull/536

**Pull request closed without merging**
