### PR TITLE
Make TextReadHandler command buffer expandable

### LINKED ISSUE #9355: TextReadHandler(Rest and Memcache) commands has a size restriction
Large responses can not be handled at the moment. There is a hardcoded buffer size in TextReadHandler. This should be converted to dynamic so that it can handle any size response.
A complaint related to this issue is reported here https://github.com/hazelcast/hazelcast/pull/8536

### PR DESCRIPTION
**Pull request by mdogan**
TextReadHandler command buffer had a fixed capacity of 500 bytes.
When
- REST request is sent with a URL longer than that
- Memcached request is sent with a very long key
- Memcached bulk read request is sent with a many keys

this buffer can overflow and requests fail.

This buffer is made on-demand expandable up to 65536 bytes.

Improved REST and Memcached integration tests.

Fixes #9355

### CODE REVIEW

**Comment by mdogan** [comment]
> ERROR: [GitHub Commit Status Setter] - Cannot retrieve Git metadata for the build, setting build result to FAILURE

**Comment by mdogan** [comment]
run-lab-run

**Comment by pveentjer** [comment]
👍

**Comment by mdogan** [comment]
@pveentjer: Backport -> https://github.com/hazelcast/hazelcast/pull/9629

**Pull request merged**
