### PR TITLE
Cleanup of CheckStyle suppressions for DebugUtil

### PR DESCRIPTION
**Pull request by Donnerbart**
Not much to say, was close to directly commit this.

### CODE REVIEW

**Comment by pveentjer** [comment]
Just remove the class. I can get back when I need to.

**Comment by Donnerbart** [comment]
I added another commit to delete the file. But I kept the previous one, so we have a CheckStyle compliant version in the history for restore.

**Comment by pveentjer** [comment]
:+1:

**Comment by jerrinot** [comment]
:+1:

**Pull request merged**
