### PR TITLE
	Retry uses -execute- rather than -schedule- to be able to catch RejectedExecutionException ...

### PR DESCRIPTION
**Pull request by sancar**
...ExecutionException which is thrown when client shutdown. related to #4592

### CODE REVIEW

**Comment by sancar** [comment]
NearCacheTest/testNearCacheInvalidationWithLFU just failed. We are already working on it.

**Comment by sancar** [comment]
verify

**Comment by sancar** [comment]
Failed test.
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK7/com.hazelcast%24hazelcast/142/testReport/junit/com.hazelcast.queue/TransactionQueueTest/testIssue859And863/

**Comment by sancar** [comment]
verify

**Comment by sancar** [comment]
verify

**Comment by sancar** [comment]
```
Put operations should not hang, failed to complete within 120 seconds , count left: 1
Stacktrace

java.lang.AssertionError: Put operations should not hang, failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:456)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:442)
	at com.hazelcast.client.ClientRegressionTest.testClusterShutdown_thenCheckOperationsNotHanging(ClientRegressionTest.java:824)
```

This failure related to pr itself.

**Comment by gurbuzali** [comment]
:+1:

**Pull request merged**
