### PR TITLE
Prevent updates on the near cache if the new value was invalidated in th...

### PR DESCRIPTION
**Pull request by lukasblu**
...e meantime.

Hi @serkan-ozal ,

here is the fix for #4671 which seams to work for me.

Could you have a look and run your complete test suite against it?

Thanks and best,
Lukas

### CODE REVIEW

**Comment by pveentjer** [comment]
@serkan-ozal since the JCache is now your baby, can you have a look at this PR?

**Comment by serkan-ozal** [comment]
@pveentjer I had looked at the PR but I think, solution in this PR may creates unnecessary objects even while invalidating. On the other hand, since this near-cache issue is for IMap, maybe @ahmetmircik can also look at this PR.

**Comment by lukasblu** [comment]
Hi @serkan-ozal ,

yes, that is true, my solution above does indeed keep objects to remember which value are no longer valid. However, since the actual value is not retained, the overhead is really small. We are already using the PR in real life solutions and see no overhead what so ever.

Maybe an option to improve this even further would be to keep those invalidation objects only if caching of local entries is enabled and/or to only keep those objects for a very short period of time.

Best,
Lukas

**Comment by ahmetmircik** [comment]
Hi @lukasblu, 

It seems to me this may also be an alternative solution: (btw it needs more tests and not a finished work)
https://github.com/hazelcast/hazelcast/compare/master...ahmetmircik:fix/3.5/nearcacheStalenessMaybeFix?expand=1

_Summary of that work:_
Only keeping an array of counters and increasing values of two random indexes according to pre-calculated hashes and checking whether or not the sum of those indexes has changed, by comparing that sum before and after `put-near-cache` we can easily guess the staleness of the value in near-cache, there should be a very low false positive rate that means we can also remove a not-stale value with a very low probability, like 1 in every 100 put. Also we don't create any object for every invalidation.

**Comment by bilalyasar** [comment]
Can one of the admins verify this patch?

**Comment by lukasblu** [comment]
Hi @ahmetmircik ,

I had a look at your solution and - without having tested it yet - it feels good.

Did you have a chance to do more testing? And did you already run my two tests from #4671 (TestLocalNearCache6 and TestLocalNearCache7)? I'm not sure if have time to run my tests against your branch today, but I could do more testing on Monday or Tuesday next week.

Thanks and best,
Lukas

Ps. @bilalyasar depending on the test results on Ahmet's solution, my PR would become obsolete...

**Comment by ahmetmircik** [comment]
Hi @lukasblu, 

We have fixed this issue with this PR https://github.com/hazelcast/hazelcast/pull/8091. We will also apply that fix to current 3.6 and 3.7. Now, i am closing this PR. 

Thanks for pointing this issue.

**Pull request closed without merging**
