### PR TITLE
[HZ-1383] Fix watermark key assignment for self-join, UNION

### PR DESCRIPTION
**Pull request by Fly-Style**

### CODE REVIEW

**Comment by Fly-Style** [comment]
run-lab-run

**Comment by Fly-Style** [comment]
run-lab-run

**Comment by Fly-Style** [comment]
run-lab-run

**Comment by Fly-Style** [comment]
run-lab-run

**Comment by Fly-Style** [comment]
run-lab-run

**Comment by Fly-Style** [comment]
run-ee-compile

**Comment by Fly-Style** [comment]
run-ee-compile

**Review by viliam-durina — APPROVED** [review]

**Review by krzysztofslusarski — APPROVED** [review]

**Comment by Fly-Style** [comment]
run-lab-run

**Pull request merged**
