### PR TITLE
[DONT MERGE] Removed patched Maven Surefire dependency

### PR DESCRIPTION
**Pull request by Donnerbart**

### CODE REVIEW

**Comment by mmedenjak** [comment]
https://github.com/hazelcast/hazelcast/pull/11492

**Comment by Donnerbart** [comment]
Hmm, wasn't the memory leak in 2.20 and fixed in 2.20.1?

**Comment by mmedenjak** [comment]
Possibly. That is an additional issue we haven't encountered. We have encountered many spurious PR builder failures: https://hazelcast.slack.com/archives/C034W6YHK/p1506949198000286

**Comment by Donnerbart** [comment]
Hmm, the problem is that jitpack is not working anymore with older JDKs. Let me think what we can do as alternative.

**Comment by Donnerbart** [comment]
Looks like the jitpack failure is gone. I'm just trying how 2.19.1 works with the PR now.

The last run was 31 minutes (without Matko's other improvements). That's faster than the current average of ~34 minutes:
> This run spent:
> 5.2 sec waiting in the queue;
> 31 min building on an executor;
> 31 min total from scheduled to completion.

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
This run spent:
> 5.4 sec waiting in the queue;
> 31 min building on an executor;
> 32 min total from scheduled to completion.
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13946/

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (singlejvm) on project hazelcast: Execution singlejvm of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
23:26:11 [ERROR] Command was /bin/sh -c cd /home/jenkins/jenkins/workspace/new-lab-fast-pr-13961/hazelcast && /usr/lib/jvm/java-8-oracle/jre/bin/java -Xms512m -Xmx2G -XX:MaxPermSize=1024M -Dhazelcast.phone.home.enabled=false -Dhazelcast.mancenter.enabled=false -Dhazelcast.logging.type=none -Dhazelcast.test.use.network=false -Dlog4j.configurationFile=log4j2-info.xml -jar /home/jenkins/jenkins/workspace/new-lab-fast-pr-13961/hazelcast/target/surefire/surefirebooter7066472865785291408.jar /home/jenkins/jenkins/workspace/new-lab-fast-pr-13961/hazelcast/target/surefire/surefire331560052455925231tmp /home/jenkins/jenkins/workspace/new-lab-fast-pr-13961/hazelcast/target/surefire/surefire_722175918334672264247tmp

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (singlejvm) on project hazelcast: Execution singlejvm of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
02:24:12 [ERROR] Command was /bin/sh -c cd /home/jenkins/jenkins/workspace/new-lab-fast-pr-13965/hazelcast && /usr/lib/jvm/java-8-oracle/jre/bin/java -Xms512m -Xmx2G -XX:MaxPermSize=1024M -Dhazelcast.phone.home.enabled=false -Dhazelcast.mancenter.enabled=false -Dhazelcast.logging.type=none -Dhazelcast.test.use.network=false -Dlog4j.configurationFile=log4j2-info.xml -jar /home/jenkins/jenkins/workspace/new-lab-fast-pr-13965/hazelcast/target/surefire/surefirebooter8977805439628583020.jar /home/jenkins/jenkins/workspace/new-lab-fast-pr-13965/hazelcast/target/surefire/surefire2359748719716264520tmp /home/jenkins/jenkins/workspace/new-lab-fast-pr-13965/hazelcast/target/surefire/surefire_723873692308055384720tmp

**Pull request closed without merging**
