### PR TITLE
[WIP] Changed default configuration in HazelcastTestSupport

### PR DESCRIPTION
**Pull request by Donnerbart**
This is just a test how the PR builder will perform. The changed config is used by a bunch of tests.

### CODE REVIEW

**Comment by mmedenjak** [comment]
Whoops :)

**Comment by Donnerbart** [comment]
As expected some tests failed, since they probably rely on the default partition count or so.

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
Another run:
> This run spent:
> 5.8 sec waiting in the queue;
> 48 min building on an executor;
> 48 min total from scheduled to completion.

**Comment by mmedenjak** [comment]
Not sure if we will actually speed up the build (maybe by just a minor amount) but we should definitely be using less resources and (hopefully) have stabler builds.

**Comment by Donnerbart** [comment]
The only risk I see is to silently render tests useless, which depend on the full partition count. We had some related test failures, but maybe there are more.

And of course it would be good to have monitoring on the build machine, so we can compare if there is any measurable difference in the utilization.

**Comment by mmedenjak** [comment]
Ran the test suite with JFR, both with and without changes. The thread usage decrease is noticeable.
Without changes:
without-changes

With changes:
with-changes

**Comment by mmedenjak** [comment]
Also, the threads are parked much less because they are utilised more.
Without changes:
without-changes-latency

With changes:
with-changes-latency

**Comment by mmedenjak** [comment]
The CPU usage drop in the middle of the graph seems to be related to the `AbstractNearCacheBasicTest`. The `com.hazelcast.map.impl.nearcache` package takes the most time to run, most notably `MapNearCacheBasicTest`. Probably because of methods that assert something eventually, like `assertNearCacheInvalidations`.

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
I managed to speed it up by increasing the frequency of batch message invalidations. The next issue was on a transactional queue test where it wasted 45 seconds of waiting. You can see the changes here:
https://github.com/hazelcast/hazelcast/compare/master...mmedenjak:jfr-tests?expand=1

It still isn't at 100% the entire duration of the build so there might be more problematic tests. On the bright side, the build with these two test changes took 27 minutes so we might have squeezed an another couple of minutes from the build as well. Here are the builds:
https://hazelcast-l337.ci.cloudbees.com/job/matko-new-lab-fast-pr-with-jfr

**Comment by Donnerbart** [comment]
Cool, I've made two comments there. Please remind me to explain the big pitfall I see in the Near Cache tests, so we can discuss how to tackle that. It'll also make the test setup much less complex, if we can fight the root cause.

**Comment by mmedenjak** [comment]
There were some additional changes in some tests (e.g. `Invocation_TimeoutTest` which is tricky to shorten) and now we are close to 100% CPU utilisation:
screen shot 2018-03-05 at 09 13 10

**Pull request closed without merging**
