### PR TITLE
Exclude log4j-api dependency from the elastic fat jars

### PR DESCRIPTION
**Pull request by frant-hartm**
We already have logj4-api jar in the server distribution, so it is not
needed.
Also log4j-api is a multi-release jar and the shade plugin didn't
repackage the jar correctly, causing the following message to be printed
at startup:

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
```

This commit fixes this issue.

### CODE REVIEW

**Comment by jerrinot** [comment]
how is the elastic5 client logging?

**Comment by frant-hartm** [comment]
I have excluded log4j-api also for elasticsearch 5 module. 

I thought we don't create a fat jar for the module, because some transitive dependency is LGPL licensed - I am not sure if this is ok.

**Comment by frant-hartm** [comment]
run-lab-run

**Comment by jerrinot** [comment]
LGPL library is probably OK as long as you don't shade it. Shading a LGPL library is no-no.

**Review by jerrinot — APPROVED** [review]

**Review by kwart — APPROVED** [review]

**Pull request merged**
