### PR TITLE
[DO NOT MERGE] Highfive test

### PR DESCRIPTION
**Pull request by Holmistr**

### CODE REVIEW

**Comment by Holmistr** [comment]
highfive

**Comment by hz-highfive** [comment]
The job `hazelcast-pr-builder` of your PR failed ([log](https://j-artifacts.s3.amazonaws.com/jiri-yet-another-test/24/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jiri-yet-another-test/24/jiri-yet-another-test-24.zip)). 
        Through arcane magic we have determined that the following fragments from the build log may contain 
        information about the problem.
        <details>
        <summary>Click to expand the log file</summary>
        ```
        --------------------------
-------TEST FAILURE-------
--------------------------
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BasicMapTest.testMapPutAndGet:196 expected:<[Intentional Error]> but was:<[World]>
[INFO] 

[ERROR] Tests run: 54, Failures: 1, Errors: 0, Skipped: 0

[ERROR] 

        ```
        </details>

**Comment by hz-highfive** [comment]
The job `hazelcast-pr-builder` of your PR failed ([log](https://j-artifacts.s3.amazonaws.com/jiri-yet-another-test/27/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jiri-yet-another-test/27/jiri-yet-another-test-27.zip)). 
        Through arcane magic we have determined that the following fragments from the build log may contain 
        information about the problem.
        <details>
        <summary>Click to expand the log file</summary>
        ```
        --------------------------
-------TEST FAILURE-------
--------------------------
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BasicMapTest.testMapPutAndGet:196 expected:<[Intentional Error]> but was:<[World]>
[INFO] 

[ERROR] Tests run: 54, Failures: 1, Errors: 0, Skipped: 0

[ERROR] 

        ```
        </details>

**Comment by hz-highfive** [comment]
The job `hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jiri-yet-another-test/32/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jiri-yet-another-test/32/jiri-yet-another-test-32.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain 
information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------------------------------TESTFAILURE---------------------------------[INFO][INFO]Results:[INFO][ERROR]Failures:[ERROR]BasicMapTest.testMapPutAndGet:196expected:<[IntentionalError]>butwas:<[World]>[INFO][ERROR]Testsrun:54,Failures:1,Errors:0,Skipped:0[ERROR]
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jiri-yet-another-test/33/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jiri-yet-another-test/33/jiri-yet-another-test-33.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain 
information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BasicMapTest.testMapPutAndGet:196 expected:<[Intentional Error]> but was:<[World]>
[INFO] 

[ERROR] Tests run: 54, Failures: 1, Errors: 0, Skipped: 0

[ERROR] 
</details>
</pre>

**Pull request closed without merging**
