### PR TITLE
Small fixes/additions for native

### PR DESCRIPTION
**Pull request by ahmetmircik**

### CODE REVIEW

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/426/
```
Test Result (1 failure / +1)
com.hazelcast.client.ClientServiceTest.testClientListener
```

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by gurbuzali** [comment]
:+1:

**Comment by ahmetmircik** [comment]
tiny changes merging it after this will add additional tests for near-cache invalidator

**Pull request merged**
