### PR TITLE
Upgraded JMH version to a more recent one

### PR DESCRIPTION
**Pull request by pveentjer**
The old one was almost 2 years old

### CODE REVIEW

**Comment by pveentjer** [comment]
Merging this one since we have no tests making use of JMH and the failure is unrelated.

**Comment by mdogan** [comment]
Problem with JMH 1.20 is, it's built for Java 1.7 but Hazelcast is for 1.6. This change breaks my dev environment:

>Error:java: error: Exception thrown while constructing Processor object: org/openjdk/jmh/generators/BenchmarkProcessor : Unsupported major.minor version 51.0


See pom: http://central.maven.org/maven2/org/openjdk/jmh/jmh-core/1.20/jmh-core-1.20.pom

**Comment by ahmetmircik** [comment]
Seems latest 1.6 support is in JMH 1.16 (http://hg.openjdk.java.net/code-tools/jmh/rev/44b01917fb79)

**Comment by pveentjer** [comment]
I wish JDK 6 would just stop working. Would be a better place for all of us.

**Comment by pveentjer** [comment]
https://github.com/hazelcast/hazelcast/pull/12355

**Pull request merged**
