### PR TITLE
Enhance IDE integration

### PR DESCRIPTION
**Pull request by mathieu-pousse**
Until now, when using the hazelcast spring namespace, the IDEs were not able to know what type of beans were created when using <hz:client/>, <hz:map/>, ...

I have added the requiered information in the xsd to seriously enhance the spring integration with IntelliJ for instance.

Before in IntelliJ: 
image
image

Now: 
image

This is more or less the same with all kind of hz objects.

### CODE REVIEW

**Comment by mdogan** [comment]
:+1:

**Comment by pveentjer** [comment]
Thumbs up here as well.

**Comment by noctarius** [comment]
Same from me, pretty cool thing, thanks for the effort! :)

**Comment by mathieu-pousse** [comment]
was a pleasure !

**Pull request merged**
