### PR TITLE
Deregistered listener on queryCache destroy

### LINKED ISSUE #10156: Client oom ClientSmartListenerService,
Hz version 3.8.1

https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x/6/console Failed  

/disk1/jenkins/workspace/stable-x/3.8.1/2017_03_27-17_21_51/create-use-destroy Failed

http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_27-17_21_51/create-use-destroy

http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_27-17_21_51/create-use-destroy/gc.html

http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_27-17_21_51/create-use-destroy/gc.html
client GC
image

hprof
http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_27-17_21_51/create-use-destroy/output/HZ/HzClient1HZ/HzClient1HZ.hprof

output/HZ/HzClient3HZ/HzClient3HZ.hprof
output/HZ/HzClient2HZ/HzClient2HZ.hprof
output/HZ/HzClient1HZ/HzClient1HZ.hprof

screen shot 2017-03-28 at 09 48 18

### PR DESCRIPTION
**Pull request by ahmetmircik**
closes #10156

### CODE REVIEW

**Comment by ahmetmircik** [comment]
```Test Result (1 failure / +1)
DurableRetrieveResultTest.testSingleExecution_WhenMigratedAfterCompletion_WhenOwnerMemberKilled```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/7836/

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by sancar** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Pull request merged**
