### PR TITLE
com.hazelcast.util.ConcurrentMap has been renamed to com.hazelcast.util.IConcurrentMap

### PR DESCRIPTION
**Pull request by toktarev**
com.hazelcast.util.ConcurrentMap has been renamed to com.hazelcast.util.IConcurrentMap

### CODE REVIEW

**Comment by pveentjer** [comment]
Can't we give this interface a different name? Having a class with a name that is well known can be very confusing; especially if you rely on on the fly imports.

**Comment by toktarev** [comment]
Which name do you think is good here ?

**Comment by toktarev** [comment]
IConcurrentMap ?

**Comment by pveentjer** [comment]
I think that is fine since it is a private class anyway. We can always rename it if we come up with a better name.

**Comment by toktarev** [comment]
Done

**Comment by pveentjer** [comment]
:+1: 

Can be merged once the build is green.

**Comment by pveentjer** [comment]
verify

**Pull request merged**
