### PR TITLE
NPE in PartitionRuntimeState fixed

### PR DESCRIPTION
**Pull request by jerrinot**
NPE after deserialization

### CODE REVIEW

**Comment by mdogan** [comment]
👍

**Comment by vbekiaris** [comment]
[`PartitionRuntimeState::writeData`](https://github.com/hazelcast/hazelcast/pull/8300/files#diff-f84ebd51a4ccc6ec495229355f2481d6R183) assumes `addressesToIndexes` will never be null. Isn't it possible to attempt to serialize a `PartitionRuntimeState` that was originally obtained from deserialization and get an NPE?

**Comment by mdogan** [comment]
@vbekiaris: Good point. 
Currently, no, `PartitionRuntimeState` is not sent/serialized again after it's received from master member. But in theory or in future it's possible. We can fix `PartitionRuntimeState::writeData` with the same way too.

**Comment by jerrinot** [comment]
@vbekiaris: very good finding indeed!
I'm going to update this PR.

**Comment by jerrinot** [comment]
PR updated. 
@mdogan: There is also a NPE in `getPartitionTable()` - is it worth fixing too?

**Comment by mdogan** [comment]
@jerrinot: `getPartitionTable()` currently only used after deserialization. But again, someday it can be used without serializing. Good thing is, NPE here will be more visible. It's up to you :)

**Pull request merged**
