### PR TITLE
Prevent the thread of ConsoleTest from leaking

### PR DESCRIPTION
**Pull request by ufukyilmaz**
The `ConsoleApp.main(null)` task created here https://github.com/hazelcast/hazelcast/blob/2b21917d243de30cf1477c2480ca817991721598/hazelcast/src/test/java/com/hazelcast/console/ConsoleTest.java#L88-L96 was getting blocked on https://github.com/hazelcast/hazelcast/blob/2b21917d243de30cf1477c2480ca817991721598/hazelcast/src/main/java/com/hazelcast/console/ConsoleApp.java#L170 and didn't complete although we shutdown the thread pool. This blocking call was stemmed from `BufferReader#readLine` method and it doesn't respond the interrupt calls. At the end of the test, I write
 a line to `Sys.in` where it is listening so that it completes 

Fixes https://github.com/hazelcast/hazelcast/issues/20680

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

**Comment by ufukyilmaz** [comment]
run-windows

**Review by kwart — APPROVED** [review]
LGTM. Thanks for the fix.

**Review by olukas — APPROVED** [review]
Seems that it's cleaned properly:
```
09:48:07 [INFO] Running com.hazelcast.console.ConsoleAppTest
09:48:08 [INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.429 s - in com.hazelcast.console.ConsoleAppTest
09:48:08 [INFO] Running com.hazelcast.console.ConsoleTest
09:48:10 [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.96 s - in com.hazelcast.console.ConsoleTest
09:48:10 [INFO] 
09:48:10 [INFO] Results:
09:48:10 [INFO] 
09:48:10 [INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0
```
Thanks Ufuk!

**Comment by vbekiaris** [comment]
Windows build failed with known issues #20709 & #20617

**Comment by vbekiaris** [comment]
thanks for the fix @ufukyilmaz

**Pull request merged**
