### PR TITLE
Adding configurable thresholds in HealthMonitor

### PR DESCRIPTION
**Pull request by Jorik0**
Possible solution for issue #7391 .

I've only made the thresholds for memory and CPU configurable, as I wanted to add the least amount of new configuration options as possible.

The new system properties are:
hazelcast.health.monitoring.threshold.percentage.memory
hazelcast.health.monitoring.threshold.percentage.cpu

Please tell me if I missed something, as this is the first time I've worked on your project.

### CODE REVIEW

**Comment by jerrinot** [comment]
Hello @Jorik0,
thank you for you contribution, it's always very much appreciated! 

It looks pretty clean, just a small remark: I'd change `hazelcast.health.monitoring.threshold.percentage.memory` to `hazelcast.health.monitoring.threshold.memory.percentage` as we tend to have "units" as a last word of the property name. The same goes for the other property.

**Comment by jerrinot** [comment]
run-lab-run

**Comment by jerrinot** [comment]
verify

**Comment by Donnerbart** [comment]
:+1:

We never established an official naming schema, but I think Jaromir is right about the tendency of putting the "unit" at the end. The rest of the PR looks very good to me.

**Comment by Jorik0** [comment]
Thanks for the advice. I've put the unit at the end this time.

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
verify

**Comment by jerrinot** [comment]
@Jorik0: Many thanks for your useful contribution; I just merged it into a 3.7-SNAPSHOT!

**Pull request merged**
