### PR TITLE
spring support for user defined services

### PR DESCRIPTION
**Pull request by bilalyasar**
fix for #3565

### CODE REVIEW

**Comment by mesutcelik** [comment]
@ahmetmircik @gurbuzali , can one of you have a look ?

it seems ok for me...

**Comment by gurbuzali** [comment]
looks ok, but it would be good to shrink those commits into one

**Comment by ahmetmircik** [comment]
seems mergeable to me.

**Comment by emrahkocaman** [comment]
@gurbuzali, @mesutcelik , @ahmetmircik , @bilalyasar  I've created another PR for a cleaner commit history. I'm closing this one, let's move to https://github.com/hazelcast/hazelcast/pull/4484

**Pull request closed without merging**
