### PR TITLE
Fix HazelcastProperties javadoc #12820

### PR DESCRIPTION
**Pull request by hgvanpariya**
Fixes: https://github.com/hazelcast/hazelcast/issues/12820

### CODE REVIEW

**Comment by hgvanpariya** [comment]
@mmedenjak , please provide your feedback.

**Comment by mmedenjak** [comment]
Hi @hgvanpariya ,

thank you for your contribution. Can you please check other places in `HazelcastProperties` and `HazelcastProperty` where `environmental value` is used? 
And can you please sign the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement), scan and and email it ?

Thanks!

**Comment by hgvanpariya** [comment]
@mmedenjak , updated, `HazelcastProperty` , please provide your comments ...

**Comment by hgvanpariya** [comment]
@mmedenjak , please let me know if any further updates are needed...

**Comment by mmedenjak** [comment]
@jerrinot have you received the signed license agreement?
@hgvanpariya looks good, if you can, please update `system variable` to `system property` as now you are using both.

**Comment by hgvanpariya** [comment]
@mmedenjak : updated the `system variable` to `system property`

**Comment by mmedenjak** [comment]
@hgvanpariya the PR looks good.
@jerrinot have you received the signed agreement?

**Comment by mmedenjak** [comment]
Thank you for your contribution @hgvanpariya ! Happy Hazelcasting!

**Pull request merged**
