### PR TITLE
Moves Json metadata initialization to RecordStoreMutationObserver

### PR DESCRIPTION
**Pull request by mustafaiman**
Groundwork for HDMap json metadata store.

JsonMetadataInitializer is removed from RecordFactory interface.
JsonMetadataRecordStoreMutationObserver is added
 EE: https://github.com/hazelcast/hazelcast-enterprise/pull/2748

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Comment by Holmistr** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mustafaiman** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Pull request merged**
