### PR TITLE
Backport all related fixes from 5.2 to 5.1

### PR DESCRIPTION
**Pull request by ahmetmircik**
closes https://github.com/hazelcast/hazelcast/issues/17460

Based on this request: https://github.com/hazelcast/hazelcast/issues/17460#issuecomment-1127336242

This PR includes cherry-picked backport of all commits separately from 5.2 to 5.1.

### CODE REVIEW

**Comment by ahmetmircik** [comment]
run-ee-tests

**Comment by ahmetmircik** [comment]
run-ee-tests

**Comment by ahmetmircik** [comment]
run-nightly-tests

**Review by vbekiaris — APPROVED** [review]

**Comment by mdumandag** [comment]
@ahmetmircik The https://github.com/hazelcast/hazelcast/pull/22073/commits/108ee43d529331a4058c824e4300362326bfbf65 introduced a race in the `TestHazelcastFactory`, which was fixed in https://github.com/hazelcast/hazelcast/pull/21718. Maybe we can backport this as well. Other than that, looks good to me.

**Comment by ahmetmircik** [comment]
@mdumandag i have just added https://github.com/hazelcast/hazelcast/pull/21718 as a separate commit in this PR. Can you please re-review?

**Review by mdumandag — APPROVED** [review]

**Pull request merged**
