### PR TITLE
[DO NOT MERGE] Fixes #5453

### LINKED ISSUE #5453: MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/558/artifact/hazelcast/target/surefire-reports/com.hazelcast.map.mapstore.MapLoaderTest-output.txt

It is weird that it tries to connect Man Center

```
http://127.0.0.1:8090/mancenter
04:24:25,085 DEBUG [ManagementCenterService] hz._hzInstance_2628_dev.MC.State.Sender - [127.0.0.1]:7675 [dev] [3.5-EA2-SNAPSHOT] Opening collector connection:http://127.0.0.1:8090/mancenter/collector.do
04:24:25,085 DEBUG [ManagementCenterService] hz._hzInstance_2628_dev.MC.Task.Poller - [127.0.0.1]:7675 [dev] [3.5-EA2-SNAPSHOT] Opening getTask connection:http://127.0.0.1:8090/mancenter/getTask.do?member=127.0.0.1:7675&cluster=dev
04:24:25,086 DEBUG [ManagementCenterService] hz._hzInstance_2628_dev.MC.Task.Poller - [127.0.0.1]:7675 [dev] [3.5-EA2-SNAPSHOT] Failed to connect to management center
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
    at com.hazelcast.internal.management.ManagementCenterService$TaskPollThread.openTaskInputStream(ManagementCenterService.java:495)
    at com.hazelcast.internal.management.ManagementCenterService$TaskPollThread.processTask(ManagementCenterService.java:435)
    at com.hazelcast.internal.management.ManagementCenterService$TaskPollThread.run(ManagementCenterService.java:416)
```

### PR DESCRIPTION
**Pull request by tombujok**

### CODE REVIEW

**Comment by tombujok** [comment]
run-lab-run

**Comment by tombujok** [comment]
verify

**Comment by hasancelik** [comment]
verify-ivm

**Comment by hasancelik** [comment]
verify-ibm

**Comment by hasancelik** [comment]
verify-ibm

**Comment by hasancelik** [comment]
verify-ibm

**Comment by hasancelik** [comment]
verify-ibm

**Comment by tombujok** [comment]
verify-ibm

**Comment by tombujok** [comment]
verify-ibm

**Pull request closed without merging**
