### PR TITLE
Try fix RingbufferAddAllReadManyStressTest

### PR DESCRIPTION
**Pull request by mmedenjak**
All of the test failures are because what is supposed to last
about 30 seconds actually lasts more than 5 minutes because of the
load induced by the test and the environment. Here we attempt to
make the test fail less by:
- decreasing the resource usage by the test
- making the test timeout longer

If this test continues to fail, we will have to decrease the load in the
 stress test.

Fixes:
https://github.com/hazelcast/hazelcast/issues/5498

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
@mmedenjak Could you backport these changes to maintenance-3.x branch?

**Pull request merged**
