### PR TITLE
Removal of hibernate module from main repo.

### PR DESCRIPTION
**Pull request by kobalski**
-Removed hibernate module from main repo
-Removed all dependencies from hazelcast-all and readme file
-New repo can be found https://github.com/hazelcast/hazelcast-hibernate

### CODE REVIEW

**Comment by kobalski** [comment]
I have update hibernate-module dependencies of hazelcast-spring module to latest stable hazelcast release(3.6) instead of 3.7-SNAPSHOT to overcome build problems.

**Comment by pveentjer** [comment]
:+1:

**Comment by emrahkocaman** [comment]
:+1:

**Comment by serkan-ozal** [comment]
:+1:

**Pull request merged**
