### PR TITLE
Resolve Sonarlint `S1319 - Declarations should use Java collection interfaces {...} rather than specific implementation classes`

### PR DESCRIPTION
**Pull request by JackPGreen**
EE PR: https://github.com/hazelcast/hazelcast-enterprise/pull/6618

### CODE REVIEW

**Comment by JackPGreen** [comment]
run-with-ee

**Review by orcunc — APPROVED** [review]

**Comment by JackPGreen** [comment]
run-with-ee

**Review by Patras3 — APPROVED** [review]
LGTM, thanks!

**Comment by JackPGreen** [comment]
run-with-os

**Comment by JackPGreen** [comment]
run-with-os

**Comment by JackPGreen** [comment]
run-lab-run

**Comment by JackPGreen** [comment]
run-lab-run

**Comment by JackPGreen** [comment]
run-lab-run

**Pull request merged**
