### PR TITLE
Refactor JSON Test assertions

### PR DESCRIPTION
**Pull request by JackPGreen**
Refactor:
`assertTrue` / `assertFalse` + `equals`

To:
`assertEquals` / `assertNotEquals`

Gives better failure messages, and clears Sonar warnings

### CODE REVIEW

**Comment by JackPGreen** [comment]
run-lab-run

**Review by orcunc — APPROVED** [review]

**Review by frant-hartm — APPROVED** [review]
Hi, I am approving because this is a clear improvement, but I would actually prefer to use the assertj's `assertThat` if we are making changes like this, then it would be even better.

I have two reasons for that
- I find the assertThat style easier to read
- the message is better, especially for more complex types like lists

**Comment by JackPGreen** [comment]
> Hi, I am approving because this is a clear improvement, but I would actually prefer to use the assertj's `assertThat` if we are making changes like this, then it would be even better.
> 
> I have two reasons for that
> 
> * I find the assertThat style easier to read

Do you have an example, please? I don’t think I’ve used it outside of ErrorCollectors.

> * the message is better, especially for more complex types like lists

Again, do you have an example, please? Be interested to see the difference. In the past I’ve JSON-formatted the outputs when complex to aid read/diff-ability.

**Comment by frant-hartm** [comment]
Right, so `assertThat(a).isEqualTo(b)` is clearer to me than `assertEquals(b, a)` (notice the need for reversed order)

Assertj has more expressive asserts, e.g.:
```
    @Test
    public void junit() {
        List<String> result = newArrayList("Frodo", "Bilbo", "Gandalf");

        assertEquals(newArrayList("Frodo", "Sam", "Pippin", "Merry"), result);
    }

    @Test
    public void assertj() {
        List<String> result = newArrayList("Frodo", "Bilbo", "Gandalf");

        assertThat(result).containsExactly("Frodo", "Sam", "Pippin", "Merry");
    }
```

will give you:
```
java.lang.AssertionError: 
Expected :[Frodo, Sam, Pippin, Merry]
Actual   :[Frodo, Bilbo, Gandalf]
```
and you need to figure out the difference yourself (or use IDE when you run locally).

while:


org.opentest4j.AssertionFailedError: 
```
Expecting actual:
  ["Frodo", "Bilbo", "Gandalf"]
to contain exactly (and in same order):
  ["Frodo", "Sam", "Pippin", "Merry"]
but some elements were not found:
  ["Sam", "Pippin", "Merry"]
and others were not expected:
  ["Bilbo", "Gandalf"]

Expected :[Frodo, Sam, Pippin, Merry]
Actual   :[Frodo, Bilbo, Gandalf]
```
Tells you exactly what's wrong. More extreme example would be the following, but with 1000s of elements (we have such tests):


<details><summary>JUnit</summary>

```
java.lang.AssertionError: 
Expected :[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Actual   :[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19]
```

</details>
<details><summary>Assertj</summary>

```
org.opentest4j.AssertionFailedError: 
Expecting actual:
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19]
to contain exactly (and in same order):
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
but could not find the following elements:
  [15]
```
</details>

**Comment by JackPGreen** [comment]
> Right, so `assertThat(a).isEqualTo(b)` is clearer to me than `assertEquals(b, a)` (notice the need for reversed order)
> 
> Assertj has more expressive asserts, e.g.:
> 
> ```
>     @Test
>     public void junit() {
>         List<String> result = newArrayList("Frodo", "Bilbo", "Gandalf");
> 
>         assertEquals(newArrayList("Frodo", "Sam", "Pippin", "Merry"), result);
>     }
> 
>     @Test
>     public void assertj() {
>         List<String> result = newArrayList("Frodo", "Bilbo", "Gandalf");
> 
>         assertThat(result).containsExactly("Frodo", "Sam", "Pippin", "Merry");
>     }
> ```
> 
> will give you:
> 
> ```
> java.lang.AssertionError: 
> Expected :[Frodo, Sam, Pippin, Merry]
> Actual   :[Frodo, Bilbo, Gandalf]
> ```
> 
> and you need to figure out the difference yourself (or use IDE when you run locally).
> 
> while:
> 
> org.opentest4j.AssertionFailedError:
> 
> ```
> Expecting actual:
>   ["Frodo", "Bilbo", "Gandalf"]
> to contain exactly (and in same order):
>   ["Frodo", "Sam", "Pippin", "Merry"]
> but some elements were not found:
>   ["Sam", "Pippin", "Merry"]
> and others were not expected:
>   ["Bilbo", "Gandalf"]
> 
> Expected :[Frodo, Sam, Pippin, Merry]
> Actual   :[Frodo, Bilbo, Gandalf]
> ```
> 
> Tells you exactly what's wrong. More extreme example would be the following, but with 1000s of elements (we have such tests):
> 
> JUnit
> ```
> java.lang.AssertionError: 
> Expected :[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
> Actual   :[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19]
> ```
> 
> Assertj
> ```
> org.opentest4j.AssertionFailedError: 
> Expecting actual:
>   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19]
> to contain exactly (and in same order):
>   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
> but could not find the following elements:
>   [15]
> ```

@frant-hartm thanks, I agree this output is much more readable. I thought JUnit5 had improved things but clearly not.

I've had a look and the `hazelcast` repo has roughly ~3600 classes using JUnit and ~700 using AssertJ.
Based on this I'd rather leave it as it is and use JUnit.

Maybe instead it's worth raising a separate issue to get a consensus on which assertion framework we want to be using, and then consolidate en-masse? AssertJ have a [migration tool](https://plugins.jetbrains.com/plugin/10345-assertions2assertj) if we did go down that route.

**Pull request merged**
