### PR TITLE
Added missing generics to CacheConfig setters

### PR DESCRIPTION
**Pull request by Donnerbart**

### CODE REVIEW

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by pveentjer** [comment]
Could this cause subtle backwards compatibility issues? @mtopolnik @jerrinot @vbekiaris WDYT?

Apart from that it looks fine.

**Comment by mtopolnik** [comment]
I can't think of any problems. Before this change, some methods already had the type params and some didn't.

**Comment by pveentjer** [comment]
I'm no expert, but can there be potential binary incompatibility?

**Comment by Donnerbart** [comment]
I think in the worst case this kind of incompatibility is accepted in minor releases, but not patch releases, right?

**Comment by pveentjer** [comment]
Also not in minor releases; it should be a drop in replacement.

If there is truly no binary compatibility issue; I would be more than happy to give thumbs up.

But my knowledge is lacking here.

**Pull request merged**
