### PR TITLE
Fix parsing of reuse-address in Spring

### PR DESCRIPTION
**Pull request by tkountis**
Fixes https://github.com/hazelcast/hazelcast/issues/14514

There was no parsing for `reuse-address` for Spring, and the test was checking against the defaults for this property. However, the default for Windows was different, see. https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/ServerSocketEndpointConfig.java#L56

### CODE REVIEW

**Comment by Holmistr** [comment]
@tkountis Minor thing, there is a typo in the commit message :) If you could fix it right away before the PR builder starts, that would be great, so we wouldn't waste time :)

**Comment by Holmistr** [comment]
@tkountis Apparently the fix isn't working, since the test failed on this PR builder.

**Comment by tkountis** [comment]
Yes saw it, looks unrelated, but looking into it

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by tkountis** [comment]
run-lab-run

**Comment by Holmistr** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by tkountis** [comment]
Working on fixing the lifecycle on this one

**Pull request merged**
