### PR TITLE
Pulled out ThreadLocalRandom

### PR DESCRIPTION
**Pull request by pveentjer**
There are some other pr's pending that rely on this class to be available as
utility.

### CODE REVIEW

**Comment by jerrinot** [comment]
why don't you model the interface after the ThreadLocalRandom from JDK 1.7? 

`public int nextInt(int bound)` etc. 

That would make transition easier once we upgrade our minimal Java requirements.

**Comment by pveentjer** [comment]
Good point. But apart from that?

**Comment by jerrinot** [comment]
well, the alternative is to directly use Doug's code: http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/jsr166y/ThreadLocalRandom.java?revision=1.17&view=markup

It's a backport to JDK6 released into public domain. It potentially offers a bit higher performance (there is  padding to eliminate false sharing) at the expense of some extra memory (8 longs) :)

**Comment by jerrinot** [comment]
:+1:

**Pull request merged**
