### PR TITLE
Fix ilike Predicate for cyrillic strings

### LINKED ISSUE #15748: Predicates.ilike not working for cyrillic strings
Hazelcast 3.12.2

For example. This code works fine:
`cacheClient.getCollectionFilterByPredicate(clazz, Predicates.ilike("firstName", "alexey"))`
firstName is a String field with value 'Alexey'

But this code does not work at all. It returns zero elements.
`cacheClient.getCollectionFilterByPredicate(clazz, Predicates.ilike("firstName", "алексей"))`
firstName is a String field with value 'Алексей'

Could you fix this? Our business logic relates on this kind of filters.

### PR DESCRIPTION
**Pull request by PokimonZerg**
Add flag to the ilike regex
Fixes #15748

### CODE REVIEW

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
@PokimonZerg are you able to add a test for the fix?

**Comment by PokimonZerg** [comment]
@mmedenjak I will add required tests at the next weekend. Too busy on my primary job.

**Comment by PokimonZerg** [comment]
Looks like there is no any good tests for LikePredicate.

I added some tests for Like and iLike predicates. Including checks for unicode case.

**Comment by petrpleshachkov** [comment]
run-lab-run

**Comment by petrpleshachkov** [comment]
The PR builder failed with not related test https://github.com/hazelcast/hazelcast/issues/16126. 
Aleksey, @PokimonZerg thank you for the PR, I am merging the fix.

**Pull request merged**
