### PR TITLE
Fix for `CachePartitionSegment` clear and close

### PR DESCRIPTION
**Pull request by serkan-ozal**
In `CachePartitionSegment` , `ICacheRecordStore` should not be removed from internal `recordStores` map if it is not destroyed otherwise it causes to memory leak since we lost its reference but its storage memory is not disposed.

Fixes https://github.com/hazelcast/hazelcast-enterprise/issues/340

### CODE REVIEW

**Comment by ahmetmircik** [comment]
Is it testable?

**Comment by serkan-ozal** [comment]
tested at enterprise and fixes hazelcast/hazelcast-enterprise#340

**Comment by ahmetmircik** [comment]
ok

**Comment by ahmetmircik** [comment]
:+1:  good catch. Seems mergeable.

**Comment by ahmetmircik** [comment]
What about porting it to EA? @enesakar  @serkan-ozal WDYT?

**Comment by serkan-ozal** [comment]
I think this should be there

**Comment by enesakar** [comment]
yes please port it to 3.6-EA

**Comment by ahmetmircik** [comment]
i will port

**Comment by ahmetmircik** [comment]
done https://github.com/hazelcast/hazelcast/commit/0bfc9a624c23117a941f53f9c0ddad3bc01df158

**Comment by serkan-ozal** [comment]
Thanks @ahmetmircik

**Pull request merged**
