### PR TITLE
Fix bug in HashSlotArrayBase

### PR DESCRIPTION
**Pull request by mtopolnik**
auxAllocateAndAdjustFields read from a free()'d location

### CODE REVIEW

**Comment by mtopolnik** [comment]
Merging immediately (build reached the test phase) because the code in question is only exercised from EE tests.

**Comment by Donnerbart** [comment]
So the fix is to read `size()` before the `move()` operation. I don't know the details of the methods, but that looks very reasonable :)

:+1:

**Comment by mtopolnik** [comment]
Yes, `size()` reads from the backing native memory block, and `move()` frees the block after copying it somewhere else.

**Comment by Donnerbart** [comment]
Good finding.

**Comment by mtopolnik** [comment]
Jenkins build found it in the form of a segfault dump file :)

**Pull request merged**
