### PR TITLE
Ability to specify multiple partitions in a predicate query.

### PR DESCRIPTION
**Pull request by ashley-taylor**

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
@ashley-taylor there are checkstyle issues on your PR. Can you run `mvn clean install -Pcheckstyle,spotbugs -DskipTests` locally and fix those issues? Also, can you rerun that step each time you add more changes to make sure checkstyle and spotbugs keep passing?

**Comment by viliam-durina** [comment]
This PR uses the broken internal API, see #18240. We don't know yet whether we'll fix or remove it.

**Comment by ashley-taylor** [comment]
@viliam-durina 
I've addressed #18240 in my last commit.
I created a unit test that using a static map and just counts the time it was run and returns that to confirm it only executes ones.

Then I added a new QueryPartitionsOperation that would include the partitions that this query should be run against.

**Comment by ashley-taylor** [comment]
@mmedenjak addressed the checkstyle issue. Forgot to run after merging master back in and the copyright year had change.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Whoops, looks like there's a regression :) Can you take a look?

**Comment by ashley-taylor** [comment]
@mmedenjak regression fixed. Looks like before a partition is assigned would return null. Then within the operation would throw a specific exception that causes a retry.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by ashley-taylor** [comment]
@mmedenjak the checkstyles issue was interesting. How it runs against the latest snap not encapsulated to code in your branch.
Change in master I hand not merged in was causing the checkstyles to break.

I reverted out my implementation to fix #18240 since was addressed in master.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
`com.hazelcast.nio.serialization.compatibility.BinaryCompatibilityTest.readAndVerifyBinaries` is failing. I guess there were some serialisation changes which break compatibility. Haven't reviewed the PR though, but maybe you know which ones I'm referring to.

**Comment by ashley-taylor** [comment]
@mmedenjak I added another another Predicate `PartitionsPredicate` and updated the serialization factory as a result.
I can't recreate the failure locally as I also updated the compatibility binary.
I assumed adding a new option to the end would not break compatibility. Is there a better way I should go about this?

**Review by taburet — COMMENTED** [review]
The approach looks good in general, but there are many places missing the support for the new predicate. For instance, client message handlers don't support it, see `MapExecuteWithPredicateMessageTask.getPartitions`, another example is `MapRemoveAllMessageTask.processMessage`. I think the easiest way to find all such places is just to find all the references to the existing `PartitionPredicate` using IDE.

**Comment by mmedenjak** [comment]
> I assumed adding a new option to the end would not break compatibility. Is there a better way I should go about this?

As for this, there are some rules how we maintain backwards compatibility while allowing changes to classes exchanged between members. Your class first needs to implement `IdentifiedDataSerializable`, which is the basis for any class providing compatibility guarantees. I assume you're already working with some class that satisfies that criteria. Then, if you want to change it by adding or removing fields, you need to add a `Versioned` marker interface after which you can add conditional checks in `writeData` and `readData`, like [here](https://github.com/hazelcast/hazelcast/blob/95ebe66fb647973facc05170ab3ad8faea01a71d/hazelcast/src/main/java/com/hazelcast/config/MapConfig.java#L914-L978).

**Comment by Holmistr** [comment]
Closing as https://github.com/hazelcast/hazelcast/pull/21319 is the successor.

**Pull request closed without merging**
