### PR TITLE
adds partition lost listener for map config to spring

### PR DESCRIPTION
**Pull request by mustafaiman**

### CODE REVIEW

**Comment by bilalyasar** [comment]
:+1:

**Comment by mustafaiman** [comment]
verify

**Comment by mustafaiman** [comment]
verify

**Comment by mustafaiman** [comment]
verify

**Comment by mesutcelik** [comment]
verify

**Comment by mesutcelik** [comment]
:+1: once green.

can you please prepare backport + check if documentation update is required?

**Comment by mustafaiman** [comment]
Sure I will.

**Comment by mesutcelik** [comment]
verify

**Comment by mustafaiman** [comment]
verify

**Comment by mustafaiman** [comment]
verify

**Comment by mustafaiman** [comment]
verify

**Comment by mustafaiman** [comment]
verify

**Comment by mesutcelik** [comment]
verify again.

**Comment by mustafaiman** [comment]
verify

**Comment by bilalyasar** [comment]
run-parallel

**Comment by bilalyasar** [comment]
run-parallel

**Comment by bilalyasar** [comment]
run-parallel

**Comment by bilalyasar** [comment]
run-parallel

**Pull request merged**
