### PR TITLE
[WIP] Fixes #1540 without client side.

### LINKED ISSUE #1540: Distributed Map: Add support for getQuiet operation
Add support for getQuiet operation (http://ehcache.org/apidocs/net/sf/ehcache/Cache.html#getQuiet(java.lang.Object))?

The idea is to be able to get an entry without touching it, meaning that it will not update the last accessed time stamp.

The use case behind it is to be able to monitor existence of a key without changing the eviction of that key.

Thanks,
Efi

### PR DESCRIPTION
**Pull request by mikolevy**
Implements getQuiet method for IMap

Misses client side
Developed at Hackergarden in Gdańsk with @ppuzio

Fixes #1540

### CODE REVIEW

**Comment by mikolevy** [comment]
Import collapse in MapDataSerializerHook fixed with two additional commits (by mistake :P) - if somebody would like to resolve it - merge with squash, please :-)

**Comment by Holmistr** [comment]
Hi @mikolevy ,

sorry for no responses. Can I ask you what's the status with the PR? Is it finished? Anything missing?

**Comment by mmedenjak** [comment]
@mikolevy can you work on getting this PR in shape? 3.10 is close to being complete. If you can't work on it, we will move it to 3.11

**Comment by Holmistr** [comment]
@mmedenjak Any plans for this PR?

**Comment by Holmistr** [comment]
Hi @mikolevy , any chance on continuing on this?

**Comment by Holmistr** [comment]
I'm going to close this PR, since there's no activity on it. 
@mikolevy I'm sorry it got abandoned. Please, feel free to comment if you're willing to pick it up again. We appreciate your effort to contribute! :)

**Pull request closed without merging**
