### PR TITLE
Null checking for data has been added into BasePutOperation

### PR DESCRIPTION
**Pull request by toktarev**
Null checking for data has been added into all critical places where we work with RecordStore

### CODE REVIEW

**Comment by serkan-ozal** [comment]
also, in `run` methods at implementations (sub-types) of `BasePutOperation`, `null` `dataValue` should be handled and ignored.

**Comment by toktarev** [comment]
if (dataValue!=null) {
            final Record record = recordStore.putBackup(dataKey, dataValue, ttl);
            if (recordInfo != null) {
                Records.applyRecordInfo(record, recordInfo);
            }
        }

like this ?

**Comment by toktarev** [comment]
What if reall null was in the map ?

**Comment by toktarev** [comment]
ttl = recordInfo != null ? recordInfo.getTtl() : ttl;       
        if (recordInfo != null) {
            final Record record = recordStore.putBackup(dataKey, dataValue, ttl);
            Records.applyRecordInfo(record, recordInfo);
        }
I suppose it would be correct 
isn't it ?

**Comment by serkan-ozal** [comment]
@toktarev AFAIK, `null` values (and also keys) are not supported at put.

And also at `afterRun` method in `PutBackupOperation`, there is no need eviction if value is `null`.

``` java
@Override
public void afterRun() throws Exception {
    if (dataValue != null) {
        evict(true);
    }
}
```

**Comment by serkan-ozal** [comment]
`Null` value is not allowed to put https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java#L93

**Comment by toktarev** [comment]
I'd better check nullability of recordInfo

**Comment by toktarev** [comment]
This is a marker of if it is fake PutBackupOperation

**Comment by toktarev** [comment]
As I see 
recordInfo!=null if and only if datavalue!=null
so it is equal what to check

recordInfo I have to check anyway - we don't need 2 checks here

**Comment by serkan-ozal** [comment]
yes, as I see also, `recordInfo` is always not `null` if `dataValue` is not `null`. 

But I still don't know why the old code checks this case 
``` java 
if (recordInfo != null) {
            Records.applyRecordInfo(record, recordInfo);
}
```

Because at the current implementation, as I tracked, `recordInfo` is always not `null` (I couldn't find a caller that may call this  `recordInfo` value with `null`) and built like this

``` java
final RecordInfo recordInfo = buildRecordInfo(record);

...

public static RecordInfo buildRecordInfo(Record record) {
        final RecordInfo info = new RecordInfo();
        info.setStatistics(record.getStatistics());
        info.setVersion(record.getVersion());
        info.setEvictionCriteriaNumber(record.getEvictionCriteriaNumber());
        info.setLastAccessTime(record.getLastAccessTime());
        info.setLastUpdateTime(record.getLastUpdateTime());
        info.setTtl(record.getTtl());
        return info;
}
```

Anyway, this workaround seems ok to me but the better one should be implemented by destroying the map itself as thread safe with partition aware operations in partition threads.

**Comment by toktarev** [comment]
I am agree.

Will we implement "true" implementation during this 3.5 bug fixing process ?

Or simple workaround will be enough ?

**Comment by serkan-ozal** [comment]
In my opinion, it is enough but not %100 sure about that are we missing some other cases for null `recordInfo` or `dataValue`. 

So, I think also @gurbuzali should have a look this PR. @gurbuzali WDYT?

**Comment by toktarev** [comment]
For recordInfo I fixed all cases because checked all invocations of getRecord

**Comment by gurbuzali** [comment]
@ahmetmircik can you please review ?

**Comment by ahmetmircik** [comment]
__About the issue #4331__:
Afais the main issue is `map#destroy` may run concurrently with a partition operation and as a result of that a partition operation may see some null data. So to me a right fix should handle that concurrent access case. 

__About this PR__:
I'm in favor of to see this work as a refactoring PR. But normally, we should only send processed keys/entries on backups, that means if something is processed on owner, it should be send to backup nodes so the null-ness of a record should not be an issue when preparing backup operations. In this PR all operations can be refactored against this expected behavior. 

For now we can change the milestone of the issue #4331 and this PR to 3.5.1. @gurbuzali ?

**Pull request closed without merging**
