### PR TITLE
Create docs-only PR builder [HZ-2933]

### PR DESCRIPTION
**Pull request by olukas**
https://hazelcast.atlassian.net/browse/HZ-2933

### CODE REVIEW

**Comment by olukas** [comment]
run-docs-only

**Comment by olukas** [comment]
run-docs-only

**Review by kwart — APPROVED** [review]
:+1:

**Comment by kwart** [comment]
Maybe including also `.adoc` suffix could improve the usability. Could you cover it too?

**Review by JackPGreen — APPROVED** [review]

**Comment by JackPGreen** [comment]
run-docs-only

**Comment by olukas** [comment]
Thanks for the review guys. I updated it to pass also for `.adoc` and tried whether it still works as expected. Merging now.

**Comment by JackPGreen** [comment]
@olukas should this go in the EE repo also?

**Comment by olukas** [comment]
@JackPGreen yup, good point, I'll prepare also PR builder for HZ EE.

**Pull request merged**
