### PR TITLE
Initialize HashMap/HashSet sizes. Allow reads to be done without defensive copies.

### PR DESCRIPTION
**Pull request by bokken**
Size HashSet and HashMap (and Linked variants) instances correctly.

### CODE REVIEW

**Comment by bokken** [comment]
I now have a signed CLA submitted.
https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by bokken** [comment]
This at least partially addresses https://github.com/hazelcast/hazelcast/issues/1194 by allowing a new map configuration of forceDefensiveCopy which defaults to true. If the in memory format is OBJECT and forceDefensiveCopy is set to false, then get and getAll operations no longer force a defensive copy for a local read, including read from backups.

**Comment by jerrinot** [comment]
hello @bokken,

many thanks for your effort! Can you please split this into 2 separated PRs? The initialization with size seems like a no-brainer to me - it can be merged quickly, even in the current state of 3.8. (we are in a Feature Freeze)

However the 2nd part might require more thinking, at very least there multiple option for end-user configuration: I can imagine a new `IN-MEMORY-FORMAT` option instead of a brand new configuration attribute.

**Comment by bokken** [comment]
@jerrinot, I created a new PR which just has the hash based collection initialization changes:
https://github.com/hazelcast/hazelcast/pull/9582

**Comment by bokken** [comment]
@jerrinot, I had originally considered a new in memory format option, and that certainly could be done. There appeared to be some other existing issues and suggestions that pointed towards this approach. 

It seems there could be some challenges with using the in memory format as that would appear to impact more than just the Map and the concept of defensive copy does not appear to be applicable to all data structures.

**Comment by bokken** [comment]
I have now created a separate PR which only has the changes to avoid defensive copies when getting out of an IMap.

https://github.com/hazelcast/hazelcast/pull/9620

**Pull request closed without merging**
