### PR TITLE
Remove Map Reduce

### PR DESCRIPTION
**Pull request by taburet**
EE counterpart: https://github.com/hazelcast/hazelcast-enterprise/pull/2910
Protocol counterpart: https://github.com/hazelcast/hazelcast-client-protocol/pull/181

### CODE REVIEW

**Comment by sancar** [comment]
@taburet 
We don't want to delete BinaryCompatibilityNullFileGenerator.java BinaryCompatibilityFileGenerator.java and ReferenceObjects.java from /compatibility folder.

**Comment by sancar** [comment]
@taburet An update. My mistake, file generators are also generated via the protocol. Just keep the ReferenceObjects class. Everything else can be deleted.

**Comment by pveentjer** [comment]
@taburet could you rebase so we can merge this PR?

**Comment by taburet** [comment]
Thanks for the review @pveentjer and @sancar, I'm going to merge the PR.

**Pull request merged**
