### PR TITLE
Fixed NearCacheConfig

### PR DESCRIPTION
**Pull request by Donnerbart**
* fixed JavaDoc
* deprecated constructors with deprecated fields as parameters
* added missing field to serialization
* increased code coverage

### CODE REVIEW

**Comment by pveentjer** [comment]
:+1:

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by jerrinot** [comment]
if a serialized blob with this class is not send to a client (or from a client) then you should remove the `@BinaryInterface` annotation. If it is sent between a member and a client then you cannot add fields.

However keeping the `@BinaryInterface` and adding new fields does not compute :)
cc @vbekiaris

**Comment by Donnerbart** [comment]
I didn't add the annotation for the config classes. But I think those are only used between members and MC to see the configuration of a member. And I also think that the annotation is needed for the automatic test @vbekiaris wrote to check the uniqueness of the IDs etc.

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
`NearCacheConfig` looks like it's not used in client-member communication, so we should remove the `@BinaryInterface` annotation and turn into `IdentifiedDataSerializable`. @Donnerbart I'll do that in a separate PR.

**Pull request merged**
