### PR TITLE
Move read-only config to internal package

### PR DESCRIPTION
**Pull request by mmedenjak**
Moves all read-only config classes to internal package, removes the
deprecation annotations as these classes will stay in 4.0 and marks the
getAsReadOnly methods as PrivateApi.

### CODE REVIEW

**Comment by mmedenjak** [comment]
@devozerov yes, I thought of that. But I was reluctant as I was unsure about the GC pressure and I vaguely remembered some regression where the test was using doing create-use-destroy for many unique instances, eventually leading to OOME because new config instances were created and added to a collection. But I may be just mixing things so I'll take a deeper look before merging. In the light of this, I might remove the method altogether. WDYT @mdogan ?

**Comment by mdogan** [comment]
I am more than ok with the new approach, it's better for the public API.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
@devozerov @mdogan addressed the review comments, now there is no `getAsReadOnly` or similar method on any config. I also checked the regression issue with OOME I was talking about and checked the usage of `Config#findMapConfig` as a sample and saw it is not on any hot path. As such, I'm merging the PR. We should keep a close eye in the stabilisation period on test results to see we don't have any unforeseen performance regression or memory leak.
Thank you all for your reviews!

**Pull request merged**
