### PR TITLE
ClientClusterService apply  events only with version larger than local version

### PR DESCRIPTION
**Pull request by sancar**

### CODE REVIEW

**Comment by sancar** [comment]
run-lab-run

**Comment by mdumandag** [comment]
Can you create a dummy enterprise PR and run the octopus PR builder with it, just to be sure?

**Comment by sancar** [comment]
@mdumandag The enterprise tests has passed. https://github.com/hazelcast/hazelcast-enterprise/pull/4294 Should we merge this one ?

**Review by mdumandag — APPROVED** [review]
Thanks for the tests. OK then.

I couldn't find a reason we would require `>=`.

**Review by ldziedziul — APPROVED** [review]

**Pull request merged**
