### PR TITLE
Revert protocol changes in MC client getCPMembers operation

### LINKED ISSUE #16536: NPE in ManagementCenterService#getCPMembers
**Describe the bug**
NPE is thrown in `ManagementCenterService#getCPMembers` under conditions described here:
https://github.com/hazelcast/management-center/issues/2643

Looks like it was broken by this change: https://github.com/hazelcast/hazelcast/commit/da0e9c24d62949d6a799eb644c1db05534cfef82#diff-8a89e39d2dd4b72cf7e706e150947674R798

As far as I understand, the problem is that `#getCPMembers` returns CP member UUIDs, not AP member UUIDs. Automated tests didn't catch this regression as CP member gets the same UUID as its AP UUID when CP Subsystem starts initially (at least that's what I've seen).

cc @sancar 

**Expected behavior**
No NPE is thrown and the CP member list is returned.

**To Reproduce**

See: https://github.com/hazelcast/management-center/issues/2643

**Additional context**

This regression affects MC 4.0.

### PR DESCRIPTION
**Pull request by puzpuzpuz**
* Fixes #16536 by a partial revert of https://github.com/hazelcast/hazelcast/commit/da0e9c24d62949d6a799eb644c1db05534cfef82 (only MC client's `getCPMembers` operation is affected).
* Migrates to `<UUID, UUID>` pairs instead of `<UUID, Address>` as it was in the original version.

Protocol PR: https://github.com/hazelcast/hazelcast-client-protocol/pull/302

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
As discussed with @mdumandag, we need to avoid `Address` in the client protocol. So, it was decided to come up with `<UUID, UUID>` entries (CP UUID, AP UUID) instead of ``<UUID, Address>`` ones.

**Comment by puzpuzpuz** [comment]
The PR is now ready for another round of review.

@emre-aydin could you take a look at https://github.com/hazelcast/hazelcast/pull/16537/commits/574573e8315d9e88b1ae8e074d9c88fc989e8c94

**Comment by emre-aydin** [comment]
> The PR is now ready for another round of review.
> 
> @emre-aydin could you take a look at [574573e](https://github.com/hazelcast/hazelcast/commit/574573e8315d9e88b1ae8e074d9c88fc989e8c94)

Looks good to me.

**Comment by puzpuzpuz** [comment]
Many thanks for your help @mdumandag!

**Pull request merged**
