### PR TITLE
Update maven wrapper

### LINKED ISSUE #22679: Update maven wrapper
### Update maven wrapper
- use the official [Apache Maven wrapper](https://maven.apache.org/wrapper/) instead of [takari maven wrapper](https://github.com/takari/maven-wrapper)
- use the latest version of Maven v3.8.6
- only include mvnw scripts without maven-wrapper.jar binary

```bash
mvn wrapper:wrapper -Dtype=script -Dmaven=3.8.6
```

### PR DESCRIPTION
**Pull request by jiri-pejchal**
- use the official Apache Maven wrapper
- use maven v3.8.6
- don't store `maven-wrapper.jar` binary in git

Fixes #22679

### CODE REVIEW

**Comment by jiri-pejchal** [comment]
As [requested](https://github.com/hazelcast/hazelcast-hibernate/pull/379#issuecomment-1300369040) by @frant-hartm

**Comment by frant-hartm** [comment]
@TomaszGaweda could you please test it builds fine on mac?
@orcunc could you please test it builds fine on win?

**Comment by frant-hartm** [comment]
@jiri-pejchal Thank you for you contribution!

**Review by frant-hartm — APPROVED** [review]
Tested on Linux, JDK 8, 11 and 17.

**Review by TomaszGaweda — APPROVED** [review]
Tested on MacOS 13 with M1 chip, 
Java: Azul 1.8 x86, Azul 1.8 aarch64, Azul 11, Azul 17 - no issues found.

**Comment by TomaszGaweda** [comment]
run-lab-run

**Review by orcunc — APPROVED** [review]

**Pull request merged**
