### PR TITLE
Fixed Types in Count Aggregations

### PR DESCRIPTION
**Pull request by jerrinot**
We should not force Supplier to provide raw Object(s).

### CODE REVIEW

**Comment by jerrinot** [comment]
@noctarius: can you please have a look?

**Comment by noctarius** [comment]
It actually doesn't make a difference for a count aggregation but yeah as long as everything still compiles I'm fine with that :)

**Comment by jerrinot** [comment]
Type do not make difference for aggregations, but it effectively forced Supplier to supply Objects -> You would have to use different Suppliers for different aggregations on the same map.

**Comment by noctarius** [comment]
Oh yeah ok I see your point! Good catch.

**Comment by jerrinot** [comment]
so is it :+1: from you? :)

**Comment by noctarius** [comment]
sure :D

**Comment by toktarev** [comment]
:+1:

**Pull request merged**
