### PR TITLE
Added an exclusion key to Evictor to be able to exclude the entry which triggered the eviction

### PR DESCRIPTION
**Pull request by gurbuzali**
enterprise part https://github.com/hazelcast/hazelcast-enterprise/pull/688

### CODE REVIEW

**Comment by gurbuzali** [comment]
run-lab-run

**Comment by jerrinot** [comment]
@gurbuzali: are you planning to work on this one?

**Comment by gurbuzali** [comment]
in the near future

**Comment by pveentjer** [comment]
@gurbuzali I'm going to close this one for the time being.

**Pull request closed without merging**
