### PR TITLE
Fixes NPE on ClientExecutionPoolSizeLowTest

### LINKED ISSUE #6853: NPE on ClientExecutionPoolSizeLowTest.testOwnerNodeTerminateWithAsyncOperations()
The test method is logging the following output on the new client module

```
13:00:46,742 ERROR [Invocation] hz._hzInstance_2_dev.async.thread-4 - [127.0.0.1]:5002 [dev] [3.6-RC2-SNAPSHOT] Failed asynchronous execution of execution callback: com.hazelcast.client.impl.protocol.task.map.MapPutMessageTask@46decc20for call Invocation{serviceName='hz:impl:mapService', op=com.hazelcast.map.impl.operation.PutOperation{serviceName='hz:impl:mapService', partitionId=87, replicaIndex=0, callId=0, invocationTime=1448362845673 (Tue Nov 24 13:00:45 EET 2015), waitTimeout=-1, callTimeout=60000, name=0ab1c75e-58e0-4c34-afb9-3031adc7f3fa, name=0ab1c75e-58e0-4c34-afb9-3031adc7f3fa}, partitionId=87, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[127.0.0.1]:5002, backupsExpected=1, backupsCompleted=0, connection=MockConnection{localEndpoint=Address[127.0.0.1]:5002, remoteEndpoint=Address[127.0.0.1]:5002}}
java.lang.NullPointerException
	at com.hazelcast.client.impl.protocol.task.map.AbstractMapPutMessageTask.beforeResponse(AbstractMapPutMessageTask.java:47)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.onFailure(AbstractPartitionMessageTask.java:79)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture$1.run(InvocationFuture.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

### PR DESCRIPTION
**Pull request by eminn**
Pulled service access logic to nodeEngine in order not to return null from getService() method

Fixes #6853

### CODE REVIEW

**Comment by sancar** [comment]
:+1:

**Comment by mdogan** [comment]
You should update/handle the places where `nodeEngine.getService()` is called and returned value is checked for null. For example;

- `TransactionContextImpl.getTransactionalService()`
- `ProxyServiceImpl.destroyLocalDistributedObject()`
- `EventProcessor.getPublishingService()`
- `ClientEngineImpl.ClientPacketProcessor.initService()`
- ...

**Comment by hasancelik** [comment]
run-lan-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by sancar** [comment]
run-lab-run

**Pull request closed without merging**
