### PR TITLE
Test DynamicConfigurationAwareConfig overrides all public methods of Config

### LINKED ISSUE #12010: Ensure all config methods are overridden in client-side dynamic config
We lack a test to ensure`ClientDynamicClusterConfig` overrides all methods. Each new config method introduced in 3.10 must be overridden in the client-side dynamic config support class; it may only make sense to address this once all new config's are in place for 3.10, as each new config will require additional methods in the `DynamicConfigTemplate` in `hazelcast-client-protocol`.

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #12010

I didn't get the comment in the original issue: _"it may only make sense to address this once all new config's are in place for 3.10, as each new config will require additional methods in the DynamicConfigTemplate in hazelcast-client-protocol."_ So I hope I understand the test-case correctly.

### CODE REVIEW

**Comment by jerrinot** [comment]
:man_facepalming:

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
```
com.hazelcast.internal.cluster.impl.MembershipFailureTest.slave_receives_member_list_from_non_master[fd:phi-accrual]
java.lang.AssertionError: Cluster size is not correct. Expected: 2, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:966)
	at com.hazelcast.test.HazelcastTestSupport$14.run(HazelcastTestSupport.java:987)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1158)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:978)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.slave_receives_member_list_from_non_master(MembershipFailureTest.java:371)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13947/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest/slave_receives_member_list_from_non_master_fd_phi_accrual_/

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Pull request merged**
