### PR TITLE
Eclipse compiler problems fix

### PR DESCRIPTION
**Pull request by sbespalov**
Generic type determination fixed by specifying the type parameter.

### CODE REVIEW

**Comment by mmedenjak** [comment]
Hi @sbespalov !

Thank you for your contribution. 
Before we can merge, can you please follow the instructions to sign and send the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)? I know it might seem like a lot of ceremony for a simple fix but it's legally required and once you sign, you can contribute more fixes. 
Alternatively, if you are unable to sign, I may fix it for you and I'll mention you in the commit.

**Comment by sbespalov** [comment]
> Hi @sbespalov !
> 
> Thank you for your contribution.
> Before we can merge, can you please follow the instructions to sign and send the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)? I know it might seem like a lot of ceremony for a simple fix but it's legally required and once you sign, you can contribute more fixes.
> Alternatively, if you are unable to sign, I may fix it for you and I'll mention you in the commit.

@mmedenjak 
I have sent CLA by email

**Comment by kwart** [comment]
run-lab-run

**Comment by kwart** [comment]
@sbespalov Thanks for sending the CLA and workarounding the ECJ issue. Merging.

**Pull request merged**
