### PR TITLE
Update Jetty to 9.4.43 and Update commons-io to 2.7

### PR DESCRIPTION
**Pull request by gurbuzali**
Missing parts of https://github.com/hazelcast/hazelcast/pull/19587

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [ ] Request reviewers if possible
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

### CODE REVIEW

**Review by olukas — APPROVED** [review]

**Comment by gurbuzali** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Has this been ported to master? Can we close https://github.com/hazelcast/hazelcast/issues/19591?

**Comment by mmedenjak** [comment]
Ah, ok, I see there's an open PR. So this also addresses https://github.com/hazelcast/hazelcast/issues/19578 in 5.0.z?

**Comment by gurbuzali** [comment]
this PR is the back-port of this commit https://github.com/hazelcast/hazelcast/pull/19586/commits/cc3e1195e3e8387535f8e6993e96c3965db4362a which is included in this PR https://github.com/hazelcast/hazelcast/pull/19586

and yes address them both

**Pull request merged**
