### PR TITLE
[HZ-803] date-time types support for json_* functions

### LINKED ISSUE #20276: Check how dates are handled in JSON
We need to check how all types are handled in JSON functions:
- `RETURNING DATE` in `JSON_VALUE`
- `$.dateField ? (@ = '2021-01-01')` in JSON_QUERY/JSON_VALUE
- date values in JSON_OBJECT/JSON_ARRAY

Maybe the above cases are correct, but we need to cover them with tests - we need to cover all types.

The SQL standard has `datetime()` function, we also need to have a story around that.

### PR DESCRIPTION
**Pull request by ivanthescientist**
Fixes #20276. 

Adds Date/DateTime support for JSON_* functions.

### CODE REVIEW

**Review by galibey — APPROVED** [review]
LGTM

**Review by viliam-durina — APPROVED** [review]

**Comment by ivanthescientist** [comment]
run-lab-run

**Comment by ivanthescientist** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Pull request merged**
