### PR TITLE
Feature/master/portable enhancement

### PR DESCRIPTION
**Pull request by asimarslan**
Portable Serialization is refactored by @mdogan . This Pull request is borrowed from his repo to make portable serialization new client protocol friendly. Main advantage is the classDefinitions being removed from packets

### CODE REVIEW

**Comment by gurbuzali** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by sancar** [comment]
verify

**Comment by asimarslan** [comment]
verify

**Comment by asimarslan** [comment]
Closing this one. #4795 will take over it.

**Pull request closed without merging**
