### PR TITLE
Removed SelectionHandler

### PR DESCRIPTION
**Pull request by pveentjer**
We have an interface, abstract class and 2 implementations of this
abstract class. There will not be any other implementations, so
having an additional interface is just complexity without value.

So where the SelectionHandler was used, the AbstractHandler is now used.

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by pveentjer** [comment]
run-lab-run

**Comment by pveentjer** [comment]
run-lab-run

**Comment by pveentjer** [comment]
run-lab-run

**Pull request merged**
