### PR TITLE
StringSerializationTest: decrease test string array size from 1 << 20 to 100

### PR DESCRIPTION
**Pull request by mdogan**
Fixes https://github.com/hazelcast/hazelcast/issues/6876

### CODE REVIEW

**Comment by asimarslan** [comment]
:+1:

**Comment by Donnerbart** [comment]
:+1:

**Comment by mdogan** [comment]
Created issue for test failure: `LocalMapStatsTest.testGetAsyncAndHitsGenerated` https://github.com/hazelcast/hazelcast/issues/6885

**Comment by mdogan** [comment]
verify

**Comment by mdogan** [comment]
verify

**Comment by mdogan** [comment]
verify

**Comment by mdogan** [comment]
run-lab-run

**Pull request merged**
