### PR TITLE
Unnecessary data copy on index add

### LINKED ISSUE #13964: Unnecessary data copy on index add
We have following situation:
- cluster contains 16 nodes
- cluster if filled by many Gigabytes of data
- one node is joining after some time
-> code is the same as in other nodes, so addIndex is called.

The index already exists (was created previously by other nodes), so addIndex is de-facto no-op. However, addIndex do full copy of entries which can take much time. Note, that the same is done by MapMigrationAwareService, so the logic is duplicated

### PR DESCRIPTION
**Pull request by TomaszGaweda**
For the the situation when the index already exists, then there is no need to fill it again with the same data

Closes #13964

### CODE REVIEW

**Comment by taburet** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
@mmedenjak @taburet Can you please add me to CloudBees or paste here what the error was?

**Comment by mmedenjak** [comment]
Hi @TomaszGaweda , these are the failed tests:
```
om.hazelcast.client.map.ClientPagingPredicateTest.testIssue3047
com.hazelcast.client.map.ClientPagingPredicateTest.mapPagingPredicateEmployeeObjectWithOrderedIndexSmallTest
com.hazelcast.client.map.ClientPagingPredicateTest.mapPagingPredicateEmployeeObjectWithOrderedIndexLargeTest
com.hazelcast.map.PagingPredicateTest.testPagingWithFilteringAndComparatorAndIndex
```

I've checked the first one and it seems to fail consistently.

**Comment by mmedenjak** [comment]
Can you also please follow the instructions to sign and send the [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)?

**Comment by taburet** [comment]
@TomaszGaweda the tests are failing because of the so called global indexes, which share their index definitions across partitions, so if a global index definition is present that doesn't mean a corresponding index is populated by all partitions. Apparently, to fix that we need to track a set of indexed partitions.

Also, I have discovered another flaw in the distributed map proxies implementation: looks like we are rebuilding all indexes (configured using an xml config) when a new member joins a cluster even if there are no manual calls to `addIndex`. See `com.hazelcast.map.impl.proxy.MapProxySupport#initialize` and `com.hazelcast.map.impl.proxy.MapProxySupport#initializeIndexes`.

If you don't mind, I will take over the issue and fix both problems.

**Comment by TomaszGaweda** [comment]
@taburet Sorry for the late response. It would be great if you can take over this issue, I'm not feeling I can easilly fix the second issue you've written. For the issue with tests, I've  tried to add counter to Indexes class that checks if all partitions are migrated, seems to work, but I didn't have time to check it more than rerun test

**Comment by taburet** [comment]
Superseded by https://github.com/hazelcast/hazelcast/pull/13984, closing.

**Pull request closed without merging**
