### PR TITLE
added support client PartitionLostListener configuration

### LINKED ISSUE #15465: Support client PartitionLostListener configuration
Declarative `PartitionLostListener` configuration is not supported in `ClientConfig.addListenerConfig`.

### PR DESCRIPTION
**Pull request by alex-dukhno**
Back port of #15478 to fix #15465 in hazelcast 3.x

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-laq-run

**Comment by mmedenjak** [comment]
Hi @alex-dukhno , thank you for the backport. HZ 3.12.x still allows JDK6 so can you adapt the code and remove JDK7+ features in a separate commit?

**Comment by alex-dukhno** [comment]
@mmedenjak, sorry I've force pushed changes

**Comment by mmedenjak** [comment]
Nevermind, force-pushing is ok. We only prefer, if there are any comments on a PR, that the comments are addressed in separate commits. So you're good 👍

**Comment by mmedenjak** [comment]
run-lam-run

**Comment by mmedenjak** [comment]
run-lač-run

**Comment by mmedenjak** [comment]
run-lap-run

**Comment by mmedenjak** [comment]
Clean backport, merging with 1 approval. Thanks for the backport @alex-dukhno and the review @taburet !

**Pull request merged**
