### PR TITLE
Do not rollback transaction backups on shutdown

### LINKED ISSUE #7004: BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_PASSIVE
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
    at java.lang.Thread.sleep(Native Method)
    at com.hazelcast.test.TestNodeRegistry$MockJoiner.doJoin(TestNodeRegistry.java:221)
    at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:103)
    at com.hazelcast.instance.Node.join(Node.java:581)
    at com.hazelcast.instance.Node.start(Node.java:339)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:130)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:117)
    at com.hazelcast.cluster.impl.BasicClusterStateTest.testNoMigrationWhenNodeLeaves(BasicClusterStateTest.java:366)
    at com.hazelcast.cluster.impl.BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_PASSIVE(BasicClusterStateTest.java:346)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/641/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_PASSIVE/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/746/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_PASSIVE/

### LINKED ISSUE #7095: BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_FROZEN
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.partition.impl.InternalPartitionServiceImpl.sleepWithBusyWait(InternalPartitionServiceImpl.java:1204)
	at com.hazelcast.partition.impl.InternalPartitionServiceImpl.prepareToSafeShutdown(InternalPartitionServiceImpl.java:1150)
	at com.hazelcast.instance.Node.shutdown(Node.java:368)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:91)
	at com.hazelcast.instance.HazelcastInstanceProxy.shutdown(HazelcastInstanceProxy.java:251)
	at com.hazelcast.cluster.impl.BasicClusterStateTest.testNoMigrationWhenNodeLeaves(BasicClusterStateTest.java:373)
	at com.hazelcast.cluster.impl.BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_FROZEN(BasicClusterStateTest.java:343)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/613/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_FROZEN/

### PR DESCRIPTION
**Pull request by metanet**
When a node shuts down itself, it should not commit / rollback the transactions it was a backup

Fixes #7095 
Fixes #7004

### CODE REVIEW

**Comment by gurbuzali** [comment]
:+1:

**Comment by metanet** [comment]
build failed because of jenkins-related error

**Comment by metanet** [comment]
verify

**Comment by mdogan** [comment]
:+1:

**Comment by mdogan** [comment]
>>_hudson.remoting.ChannelClosedException: channel is already closed_

**Comment by mdogan** [comment]
run-lab-run

**Comment by mdogan** [comment]
verify

**Pull request merged**
