### PR TITLE
Renamed IndexService to Indexes

### PR DESCRIPTION
**Pull request by pveentjer**

### CODE REVIEW

**Comment by jerrinot** [comment]
is there actually any dependency on map?

**Comment by pveentjer** [comment]
Conceptually there is because every map has a MapIndexes instance.

**Comment by jerrinot** [comment]
sure, but you could use it outside the map you wanted, can't you?

**Comment by pveentjer** [comment]
it is linked to querable entry. 

But I could rename it.. to Indexes?

**Comment by jerrinot** [comment]
"Indexes" sounds better. to me anyway. 

I understand the issue with "IndexService" is that it implies there is just one. But in reality there is one per each map. Am I correct?

**Comment by pveentjer** [comment]
Yes. One for each map. Hence 'service' is confusing.

**Comment by pveentjer** [comment]
Renamed to Indexes

**Comment by ahmetmircik** [comment]
`Indexes` makes sense to me. Also this PR needs an enterprise counterpart.
:+1: once green.

**Comment by jerrinot** [comment]
:+1:

**Comment by pveentjer** [comment]
Enterprise PR:
https://github.com/hazelcast/hazelcast-enterprise/pull/376

**Pull request merged**
