### PR TITLE
Added eviction if value loaded from maploader

### LINKED ISSUE #6517: Possible memory leak with IMap.containsKey
I am making some tests with IMap in Hazelcast 3.5.3.  These tests are being run with -Xms100M -Xmx100M.

My Map has <Integer, String> where I had 2MB Strings, running with no eviction  will exhaust memory around 30 items.

First I added an eviction policy at 20 items. This made the test run perfectly with items being evicted when needed.

I then added a MapStore. As these are just local tests the store simply saves and loads to a file in disk, in a real scenario persistence would be done to a distributed persistence. With the MapStore i can recover items that were present in the past and update them.

Problem happens when I use containsKey for a value that exists in the MapStore. I see the Item being loaded from the Store but it does not get added to the Map (no event being triggered in this case), eventually the system crashes with no memory.

The code is a bit long so I added it to a gist: https://gist.github.com/gfelisberto/1075ea5428920c9a2746 I can move it here if needed.

### PR DESCRIPTION
**Pull request by gurbuzali**
Added eviction if value loaded from maploader for readonly operations like get and containsKey, removed postReadCleanup since it is now redundant.
fixes #6517

### CODE REVIEW

**Comment by gurbuzali** [comment]
@ahmetmircik should we do a back-port, WDYT?

**Comment by gurbuzali** [comment]
unrelated test failure
```
	Test Result (1 failure / ±0)

    com.hazelcast.map.IssuesTest.testIssue1067GlobalSerializer
```

**Comment by gurbuzali** [comment]
verify

**Comment by ahmetmircik** [comment]
@gurbuzali this seems good. Can you please also remove unused constants/fields like `POST_READ_CHECK_POINT` ? There should also be some other unneeded ones after removal of `postReadCleanUp` method. Also we need a backport.

:+1:

**Comment by gurbuzali** [comment]
back-port https://github.com/hazelcast/hazelcast/pull/6805

**Comment by hasancelik** [comment]
run-lab-run

**Comment by gurbuzali** [comment]
verify

**Comment by jerrinot** [comment]
:+1:

**Pull request merged**
