### PR TITLE
Add negative guard to `ArrayUtils#getItemAtPositionOrNull`

### PR DESCRIPTION
**Pull request by JackPGreen**

### CODE REVIEW

**Comment by JamesHazelcast** [comment]
My concern with this change is that we're going to be covering up and silencing exceptions that could indicate a larger issue (passing a negative value to this function should be unexpected) - what prompted this change?

**Comment by JackPGreen** [comment]
> what prompted this change?

I was looking at #25610 and wanted a function "safe" array accessing function.

I started writing one, then found it, but noticed it didn't match my implementation because of this case.

**Comment by JamesHazelcast** [comment]
I'm not sure if we should merge this due to the concerns of my previous comment - it would be very easy for issues to be missed that would currently result in a big fat exception to raise a flag for attention. It's one thing to return null if an array has changed length and an index no longer exists, but negative indexes would never succeed with an array, so imo there shouldn't be a scenario where they even reach this function.

I'm being quite picky here, so I'd like to get some more perspective - wdyt @vbekiaris?

**Review by vbekiaris — APPROVED** [review]
In general, hiding exceptions should be avoided. This is particularly risky when changing behaviour of existing methods.
That said, it seems the change in this PR is compatible with the intent of the method & its usages already guard against usage with negative index, so I am ok with merging this PR.

**Pull request merged**
