### PR TITLE
Backport of #16864

### PR DESCRIPTION
**Pull request by leszko**

### CODE REVIEW

**Comment by leszko** [comment]
verify

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/168/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/168/Hazelcast-pr-builder-168.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 3 errors reported by Checkstyle 6.1.1 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
</details>
</pre>

**Comment by leszko** [comment]
verify

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/169/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/169/Hazelcast-pr-builder-169.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.6:check (default) on project hazelcast: failed with 1 bugs and 0 errors -> [Help 1]
--------------------------
</details>
</pre>

**Comment by leszko** [comment]
verify

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/170/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/170/Hazelcast-pr-builder-170.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:checkstyle (default) on project hazelcast-client: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 10 errors reported by Checkstyle 6.1.1 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
</details>
</pre>

**Comment by mmedenjak** [comment]
https://imgflip.com/i/3x167v

**Comment by mmedenjak** [comment]
https://i.imgflip.com/3x167v.jpg

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/171/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/171/Hazelcast-pr-builder-171.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ConfigResolutionTest.testResolveSystemProperty_classpath_yaml_loadedAsYaml:95 ? InvalidConfiguration
[ERROR]   ConfigResolutionTest.testResolveSystemProperty_classpath_yml_loadedAsYaml:117 ? InvalidConfiguration
[ERROR]   ConfigResolutionTest.testResolveSystemProperty_file_yaml_loadedAsYaml:84 ? InvalidConfiguration
[ERROR]   ConfigResolutionTest.testResolveSystemProperty_file_yml_loadedAsYaml:106 ? InvalidConfiguration
[ERROR]   YamlConfigWithSystemPropertyTest.loadingThroughSystemPropertyWithLocator_existingClasspathResource:125 ? InvalidConfiguration
[INFO] 
[ERROR] Tests run: 2845, Failures: 0, Errors: 5, Skipped: 11
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Pull request merged**
