### PR TITLE
Register WANReplicationQueueFullException to client error codes

### LINKED ISSUE #7241: For WAN Replication exception on overrun, UnknownException is thrown
3.6-122315-Enterprise:

On WAN Replication Q overrun, I expect to receive a WANReplicationQueueFullException, instead the client receives an UndefinedErrorCodeException.

Client code has to be:

```java
			catch( UndefinedErrorCodeException e )
			{
				String originClassName = e.getOriginClassName();
				if( originClassName.equals( WANReplicationQueueFullException.class.getName() ) )
				{
					log.warn( "WAN Replication Queue is full - throttling..." );
					Thread.sleep( 5000 );
				}
			}
```

It would be more elegant if the WRQFException could be caught directly:

```java
			catch( WANReplicationQueueFullException e )
			{
				log.warn( "WAN Replication Queue is full - throttling..." );
				Thread.sleep( 5000 );
			}
```

### PR DESCRIPTION
**Pull request by emrahkocaman**
Fixes #7241

### CODE REVIEW

**Comment by emrahkocaman** [comment]
@sancar Can you please have a look at this?

**Comment by sancar** [comment]
:+1:

**Comment by mesutcelik** [comment]
run-lan-run

**Comment by mesutcelik** [comment]
:+1:

**Pull request merged**
