### PR TITLE
Send -1 instead Long.Max for leasetime by default

### PR DESCRIPTION
**Pull request by sancar**
fixes https://github.com/hazelcast/hazelcast/issues/17637

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2590/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2590/Hazelcast-pr-builder-2590.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MigrationInvocationsSafetyTest.migrationCommit_shouldRollback_whenTargetCrashes:324->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:221->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:225->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253->PartitionCorrectnessTestSupport.access$000:66->PartitionCorrectnessTestSupport.assertSizeAndData:237->PartitionCorrectnessTestSupport.assertPartitionAssignments:179->PartitionCorrectnessTestSupport.assertPartitionAssignments:216 expected:<-1669084290458575971> but was:<8917940183757797572>
[INFO] 
[ERROR] Tests run: 31979, Failures: 1, Errors: 0, Skipped: 978
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by asimarslan** [comment]
@sancar Should this part( `ClientMapProxy.tryLock(key)` )
```
    @Override
    public boolean tryLock(@Nonnull K key) {
        try {
            return tryLock(key, 0, null);
        } catch (InterruptedException e) {
            currentThread().interrupt();
            return false;
        }
    }
```
passing zero value be updated to UNSET as well?

**Comment by sancar** [comment]
@asimarslan I think it should stay as is. This is the `timeout` before we give up trying to get a lock. 
For `tryLock()` it should be 0 so that it will try once. 
For `lock()` it should be UNSET so that it will wait indefinitely.

**Comment by sancar** [comment]
run-lab-run

**Review by ihsandemir — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2619/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2619/Hazelcast-pr-builder-2619.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PartitionAssignmentsCorrectnessTest>AbstractPartitionAssignmentsCorrectnessTest.testPartitionAssignments_whenNodesStartedTerminated:48->AbstractPartitionAssignmentsCorrectnessTest.assertPartitionAssignmentsEventually:76->AbstractPartitionAssignmentsCorrectnessTest.assertPartitionAssignmentsEventually:80->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253->PartitionCorrectnessTestSupport.assertPartitionAssignments:211 On Member [127.0.0.1]:5703 - 6d85335d-d6e8-4785-b4f0-be6b2c46591b this, Not member: [127.0.0.1]:5701 - d3b1342d-234e-4650-bccf-5fca7d23cf35
[INFO] 
[ERROR] Tests run: 31997, Failures: 1, Errors: 0, Skipped: 979
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Review by asimarslan — APPROVED** [review]

**Comment by Holmistr** [comment]
run-lab-run

**Pull request merged**
