### PR TITLE
[DO NOT MERGE] Fix Solaris multicast problems

### PR DESCRIPTION
**Pull request by hakanmemisoglu**
* Do not set interface

Fixes: https://github.com/hazelcast/hazelcast/issues/17834

### CODE REVIEW

**Comment by hakanmemisoglu** [comment]
Fix #17834 on Solaris

Can someone comment on possible outcomes on other settings?

**Comment by mmedenjak** [comment]
Setting milestone to 5.0. If it gets reviewed and merged before release branch is created, feel free to change back to 4.2.

**Review by kwart — COMMENTED** [review]
I'm afraid we could experience a regression in #17979 with the fix. I'm not able to reproduce the Windows issue in my environment, but it also mentioned e.g. in this stackoverflow question: https://stackoverflow.com/questions/583950/multicastsocket-not-responding-after-failure

Maybe we should introduce a new config parameter that would control if the `setInterface` is called.

**Comment by hakanmemisoglu** [comment]
Temporarily closing...

**Pull request closed without merging**
