### PR TITLE
Partial indexing implementation

### PR DESCRIPTION
**Pull request by buremba**
This is the partial indexing implementation that I develop during my internship last summer. I tried to rebase the branch in my repository in order to keep it clean but since there are too many changes it didn't work so I had to merge it.

I won't go into details about this feature since I already wrote a [specification] (https://gist.github.com/buremba/becd46dc40b920fc073f). Even though I couldn't get any feedback from [the post] (https://groups.google.com/forum/#!topic/hazelcast/yLIRhCpDeCg) in Google Groups and the private e-mails that I sent you, I believe that at some point you will have to implement this kind of feature. Because if your customers have this kind of #3253 complex queries, as far as I can see from other database engines there is no way to provide the perfect querying mechanism without this kind of advanced technique so almost all of the advanced databases (Postgresql, MongoDB, Oracle Database) and Hazelcast competitor Coherence leverage this feature for complex queries.

I know that you have a strict rule that developers who are not senior cannot contribute to Hazelcast but I also know that you have some plans to improve querying performance in 3.5 release so even though this implementation is not bug-free since I'm not really an expert on this area, I spent some time on it and I think you may benefit from it when working on 3.5 release. Therefore I wanted to send this pull request because otherwise it would most likely be forgotten in my Hazelcast fork.

### CODE REVIEW

**Comment by bilalyasar** [comment]
Can one of the admins verify this patch?

**Comment by bwzhang2011** [comment]
@buremba, could such feature solve the spatial index searching while querying for the geographical data ? 
and @mdogan, could such also be merged into hz3.5 ?

**Comment by buremba** [comment]
@bwzhang2011 Since it works for all comparable types, you can create a partial index for such data type using this implementation.

**Comment by bwzhang2011** [comment]
@buremba, any update with such issue ?

**Comment by bwzhang2011** [comment]
@devOpsHazelcast  or @buremba, could such issue be merged into 3.5 branch,  long time since for the first proposal but very useful.

**Comment by buremba** [comment]
Unfortunately the decision is not up to me, I implemented this feature during my internship last year but couldn't get any feedback from the core developers. I don't really know their thoughts about this pull request but I heard that they have been working on improving query execution performance for 3.5.

**Comment by buremba** [comment]
Sorry, I didn't mean to close it.

**Comment by bwzhang2011** [comment]
@devOpsHazelcast, any progress with such issue ? I think it's a very useful feature and enhancement for hazelcast. and @buremba, will you try to submit another issue that make it compatible with hz3.5 and afterwards ?

**Comment by bwzhang2011** [comment]
@buremba, any update with such issue.

**Comment by buremba** [comment]
Sorry @bwzhang2011, I don't have the answer you're looking for. You may send an email to core Hazelcast contributors if you wish. Even if I can fix the merge conflicts and send a new pull request, the decision is up to them so there is no other way than waiting their response.

**Comment by noctarius** [comment]
@buremba I would like to close this pull request BUT I would love to invite you to the effort of creating a real indexing SPI. I really would love to see you sharing your knowledge as part of the group to define the SPI and create some reference implementations. I bet partial indexes would be a super good addition to Hazelcast though!

Feel free to contact me on twitter, gitter or mail: https://hazelcast.atlassian.net/wiki/display/COM/HEP+%23+-+Hazelcast+Indexing+SPI

**Comment by buremba** [comment]
@noctarius thanks for the answer but it's been a while and I forgot the internals of Hazelcast. From my understanding, indexing SPI is useful for using custom types and functions in indexes but partial indexing is actually a core feature.
I already wrote a specification, shared my benchmark results, wrote a post in Google Groups and sent a mail to core team members about my findings when developing this feature so I'm not sure how I can help at this point.

**Pull request closed without merging**
