### PR TITLE
Ensure that one millisecond has passed to validate the update of last ac...

### LINKED ISSUE #4796: [TEST-FAILURE] LocalMapStatsTest.testLastAccessTime_updatedConcurrently
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK8/173/com.hazelcast$hazelcast/testReport/com.hazelcast.map/LocalMapStatsTest/testLastAccessTime_updatedConcurrently/

### PR DESCRIPTION
**Pull request by metanet**
...cess time

Fixes #4796

### CODE REVIEW

**Comment by jerrinot** [comment]
do you know what's the point of this test? It starts a new thread & calls join() immediately.

**Comment by pveentjer** [comment]
Seems fragile to me. Who says you get a millisecond?

**Comment by metanet** [comment]
Test tries to validate that updates to the local map stats objects from another thread is visible to the current thread. It is why current thread joins to the other one. Since localmapstats object provides last update time as milliseconds, I tried to force it. 

@pveentjer Now I recall that thread.sleep() does not guarantee the duration of sleep. How can I test it properly other than increasing the sleep duration?

**Comment by jerrinot** [comment]
void sleepAtLeastMs(long ms) {

long targetTime = System.getCurrentMillis() + ms;
while (System.getCurrentMillis() < targetTime) {
  sleepMillis(1);
};

}

I still don't see the point of this test as both start() & join() are
happens-before edges. It will be the same as if it was running on a single
thread. (unless I'm missing something)



On Sat, Mar 14, 2015 at 5:52 PM, Ensar Basri Kahveci <
notifications@github.com> wrote:

> Test tries to validate that updates to the local map stats objects from
> another thread is visible to the current thread. It is why current thread
> joins to the other one. Since localmapstats object provides last update
> time as milliseconds, I tried to force it.
>
> @pveentjer <https://github.com/pveentjer> Now I recall that
> thread.sleep() does not guarantee the duration of sleep. How can I test it
> properly other than increasing the sleep duration?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hazelcast/hazelcast/pull/4802#issuecomment-80548265>.
>



-- 
“Perfection is achieved, not when there is nothing more to add, but when
there is nothing left to take away.”
Antoine de Saint Exupéry

**Comment by metanet** [comment]
Thanks jaromir. You are right about the happens before but the field is
already volatile. I used it to ensure the other operation is ended.

I will fix this test code.

On Saturday, March 14, 2015, Jaromir Hamala <notifications@github.com>
wrote:

> void sleepAtLeastMs(long ms) {
>
> long targetTime = System.getCurrentMillis() + ms;
> while (System.getCurrentMillis() < targetTime) {
> sleepMillis(1);
> };
>
> }
>
> I still don't see the point of this test as both start() & join() are
> happens-before edges. It will be the same as if it was running on a single
> thread. (unless I'm missing something)
>
>
>
> On Sat, Mar 14, 2015 at 5:52 PM, Ensar Basri Kahveci <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Test tries to validate that updates to the local map stats objects from
> > another thread is visible to the current thread. It is why current thread
> > joins to the other one. Since localmapstats object provides last update
> > time as milliseconds, I tried to force it.
> >
> > @pveentjer <https://github.com/pveentjer> Now I recall that
> > thread.sleep() does not guarantee the duration of sleep. How can I test
> it
> > properly other than increasing the sleep duration?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hazelcast/hazelcast/pull/4802#issuecomment-80548265
> >.
> >
>
>
>
> --
> “Perfection is achieved, not when there is nothing more to add, but when
> there is nothing left to take away.”
> Antoine de Saint Exupéry
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hazelcast/hazelcast/pull/4802#issuecomment-80553541>.
>


-- 
Ensar Basri Kahveci
Software Engineer

**Comment by mtopolnik** [comment]
@jerrinot Your implementation is off by one: if we read current time as x millis, the next nanosecond we may already read x+1 millis and satisfy the condition to wait "at least one" millisecond.

As for the questioned test code, Ensar has *deleted* the `join` logic.

**Comment by jerrinot** [comment]
@mtopolnik: that's a good catch, thanks!

**Comment by mtopolnik** [comment]
@metanet Since this sleeping logic is a part of this commit, I would advise fixing it.

**Comment by mtopolnik** [comment]
:+1:

**Comment by serkan-ozal** [comment]
:+1:

**Pull request merged**
