### PR TITLE
Doc update for NearCache configuration on Client

### PR DESCRIPTION
**Pull request by wildnez**
Updates on online documentation about NearCache configuration on client side. Changes include mention and example of declarative configuration (XML) in JavaClient.md and rephrasing of doc in Map-NearCache.md.

### CODE REVIEW

**Comment by ahmetmircik** [comment]
seems to need a rebase

**Comment by Serdaro** [comment]
@ahmetmircik..

@wildnez should do that?

**Comment by ahmetmircik** [comment]
@Serdaro right.

**Comment by wildnez** [comment]
Done.

**Pull request merged**
