### PR TITLE
Use returned object from ManagedContext#initialize

### PR DESCRIPTION
**Pull request by pertsodian**
Fix https://github.com/hazelcast/hazelcast/issues/16845

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/188/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/188/Hazelcast-pr-builder-188.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientJmxMetricsTest.testNoMBeanLeak:52 expected:<0> but was:<13>
[INFO] 
[ERROR] Tests run: 3852, Failures: 1, Errors: 0, Skipped: 14
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by pertsodian** [comment]
@mmedenjak Hmmm this test passes locally for me.. from the look of it, it is not related to this change. I wonder if it was the same case that failed in my previous PR.

**Comment by mmedenjak** [comment]
It's an unrelated test failure, we're going to take a closer look internally. You can ignore it.

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Thank you for your contribution @pertsodian ! I rebased your PR since there was a merge conflict and added some generics to avoid casts all over the place. Hope to see you around soon! cc @Holmistr

**Comment by pertsodian** [comment]
Thanks @mmedenjak for the edit 👍

**Pull request merged**
