### PR TITLE
Run step if met with preconditions

### PR DESCRIPTION
**Pull request by ramizdundar**
Step should only run if preconditions are met. This was the case before
https://github.com/hazelcast/hazelcast/pull/23131.

### CODE REVIEW

**Comment by ahmetmircik** [comment]
@ramizdundar How did you encounter this? Is there a failing test? Or is it just for aligning behavior with current operation runners?

**Comment by ramizdundar** [comment]
I was investigating a wan related issue. While debugging, I see that merge operation's first step was executing 1000 times but the next step function of that very same first step was executed 975 times. I realized it was caused by https://github.com/hazelcast/hazelcast/pull/23131 unintentionally (IIUC) and hence opened this PR.

**Comment by ahmetmircik** [comment]
>first step ([this](https://github.com/hazelcast/hazelcast/blob/42bba124ccaddfcadabe93374bd8b20285cd819f/hazelcast/src/main/java/com/hazelcast/map/impl/operation/steps/MergeOpSteps.java#L46)) was executing 1000 times but the next step function of that very same first step ([this](https://github.com/hazelcast/hazelcast/blob/42bba124ccaddfcadabe93374bd8b20285cd819f/hazelcast/src/main/java/com/hazelcast/map/impl/operation/steps/MergeOpSteps.java#L93)) was executed 975 times.

It is not required to run 2nd step as much as 1st one because there is a condition to decide 2nd should run or not. 

Precondition check is only needed by 1st steps to detect potential timeout, otherwise we don't need to run it. This PR makes sense from this perspective. If you can create a test for a timed-out operation run attempt for this PR, it will be gold.

**Comment by ramizdundar** [comment]
> It is not required to run 2nd step as much as 1st one because there is a condition to decide 2nd should run or not.

This isn't about 2nd step run count vs 1st step run count. Please check the second link. I found weird that 1st steps `runStep()` was running 1000 times but 1st steps `nextStep()` was running 975 times.

In any case, IMO, it's not proper to run a step (for example `MergeOpSteps.READ.runStep()`) when operation is timed out or cluster is not healthy.

> 
Precondition check is only needed by 1st steps to detect potential timeout, otherwise we don't need to run it. This PR makes sense from this perspective.

Yes exactly. In the future it would be useful if someone were to add a new false returns to `metWithPreconditions()`. Because someone could expect if this method returns false, steps shouldn't run.

> If you can create a test for a timed-out operation run attempt for this PR, it will be gold.

I will try 👍

**Comment by ahmetmircik** [comment]
Test seems passing even with current master. I expect failure on master.

**Comment by ramizdundar** [comment]
Are you sure? On my machine the test commit on top of master fails consistently.

**Comment by ahmetmircik** [comment]
@ramizdundar don't know what the issue was before but this time it has failed. Seems working as expected.

**Review by ahmetmircik — APPROVED** [review]
good finding

**Review by TomaszGaweda — APPROVED** [review]

**Comment by ahmetmircik** [comment]
@ramizdundar can you please create backport for 5.2.z also?

**Review by vbekiaris — APPROVED** [review]
good finding @ramizdundar

**Pull request merged**
