### PR TITLE
CP Subsystem test fixes

### LINKED ISSUE #14552: SessionManagerServiceTest. acquireSession_returnsNewSession_whenSessionExpiredAndNotInUse
```
java.lang.AssertionError: Values should be different. Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:199)
	at org.junit.Assert.assertNotEquals(Assert.java:211)
	at com.hazelcast.cp.internal.session.AbstractProxySessionManagerTest$11.run(AbstractProxySessionManagerTest.java:236)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.cp.internal.session.AbstractProxySessionManagerTest.acquireSession_returnsNewSession_whenSessionExpiredAndNotInUse(AbstractProxySessionManagerTest.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/547/testReport/junit/com.hazelcast.cp.internal.session/SessionManagerServiceTest/acquireSession_returnsNewSession_whenSessionExpiredAndNotInUse/

### LINKED ISSUE #14553: FencedLockAdvancedTest.testLockAcquired_whenLockOwnerShutsDown
```
java.lang.NullPointerException
	at com.hazelcast.cp.internal.datastructures.lock.FencedLockAdvancedTest$18.run(FencedLockAdvancedTest.java:377)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.cp.internal.datastructures.lock.FencedLockAdvancedTest.testLockAcquired_whenLockOwnerShutsDown(FencedLockAdvancedTest.java:373)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/528/testReport/junit/com.hazelcast.cp.internal.datastructures.lock/FencedLockAdvancedTest/testLockAcquired_whenLockOwnerShutsDown/

### LINKED ISSUE #14554: MetadataRaftGroupTest.when_membersLeaveDuringDiscoveryAfterCPSubsystemRestart_then_discoveryIsCancelled
```
14:23:03 [ERROR] when_membersLeaveDuringDiscoveryAfterCPSubsystemRestart_then_discoveryIsCancelled(com.hazelcast.cp.internal.MetadataRaftGroupTest)  Time elapsed: 21.861 s  <<< ERROR!
14:23:03 com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[127.0.0.1]:5706] is not active!
14:23:03     at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:370)
14:23:03     at com.hazelcast.cp.internal.HazelcastRaftTestSupport.getRaftService(HazelcastRaftTestSupport.java:214)
14:23:03     at com.hazelcast.cp.internal.MetadataRaftGroupTest$27.run(MetadataRaftGroupTest.java:759)
14:23:03     at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
14:23:03     at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
14:23:03     at com.hazelcast.cp.internal.MetadataRaftGroupTest.when_membersLeaveDuringDiscoveryAfterCPSubsystemRestart_then_discoveryIsCancelled(MetadataRaftGroupTest.java:755)
14:23:03     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:23:03     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:23:03     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:23:03     at java.lang.reflect.Method.invoke(Method.java:498)
14:23:03     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
14:23:03     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
14:23:03     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
14:23:03     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
14:23:03     at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
14:23:03     at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
14:23:03     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:23:03     at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by mdogan**
Fixes #14552
Fixes #14553
Fixes #14554

### CODE REVIEW

**Comment by metanet** [comment]
run-lab-run

**Comment by metanet** [comment]
run-lab-run

**Comment by Holmistr** [comment]
run-lab-run

**Comment by Holmistr** [comment]
run-lab-run

**Pull request merged**
