### PR TITLE
Added support for Map merge operation #14913

### PR DESCRIPTION
**Pull request by webashutosh**

### CODE REVIEW

**Comment by webashutosh** [comment]
@mmedenjak @sancar this is the new PR for merge() operation.
All feedback so far has been addressed.
Can you please have a look?

**Comment by sancar** [comment]
run-lab-run

**Review by sancar — COMMENTED** [review]
Looks good to me. Thanks for your contribution.

**Review by mmedenjak — APPROVED** [review]

**Review by sancar — APPROVED** [review]

**Comment by mmedenjak** [comment]
Thank you for the contribution @webashutosh ! I'll double check if, as you say, all default methods are now covered. Till next time!

**Pull request merged**
