### PR TITLE
Fixed for [TEST-FAILURE] map.BasicMapTest.testPutWithTtl

### LINKED ISSUE #6196: [TEST-FAILURE] BasicMapTest.testPutWithTtl
```
java.lang.AssertionError: expected:<value> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.BasicMapTest.testPutWithTtl(BasicMapTest.java:1107)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3739/testReport/junit/com.hazelcast.map/BasicMapTest/testPutWithTtl/

### PR DESCRIPTION
**Pull request by tombujok**

### CODE REVIEW

**Comment by gurbuzali** [comment]
how about this 
```
    @Test
    public void testPutWithTtl() throws InterruptedException {
        final IMap<String, String> map = getInstance().getMap("testPutWithTtl");

        map.put("key", "value", 2, TimeUnit.SECONDS);
        assertTrueEventually(new AssertTask() {
            @Override
            public void run() throws Exception {
                assertNull(map.get("key"));
            }
        });
    }
```

**Comment by tombujok** [comment]
@gurbuzali Looks much simpler, but I thought this test is also supposed to verify whether the `entryEvicted` listener has been fired. If we can skip it, I prefer your option too.

**Comment by gurbuzali** [comment]
listener is used for detecting that the ttl expired for this test. we may want to test `entryEvicted` listener too in a separate test, maybe we already have tests for that, I don't know.

**Comment by pveentjer** [comment]
Can you add short description in title? This makes an overview of issues resolves easier to understand.

**Comment by tombujok** [comment]
Fixed as suggested

**Comment by gurbuzali** [comment]
do we need a back-port here ?

**Pull request merged**
