### PR TITLE
[BACKPORT] Make client-side map queries tolerant to cluster migrations

### LINKED ISSUE #9724: ClientQueryDuringMigrationsStressTest testQueryMapWithIndexes_whileShutdownStartup
```
Error Message

[A query thread failed with: Not Member! target: [127.0.0.1]:5014, partitionId: -1, operation: com.hazelcast.map.impl.query.QueryOperation, service: hz:impl:mapService, A query thread failed with: Not Member! target: [127.0.0.1]:5014, partitionId: -1, operation: com.hazelcast.map.impl.query.QueryOperation, service: hz:impl:mapService]
Stacktrace

java.lang.AssertionError: [A query thread failed with: Not Member! target: [127.0.0.1]:5014, partitionId: -1, operation: com.hazelcast.map.impl.query.QueryOperation, service: hz:impl:mapService, A query thread failed with: Not Member! target: [127.0.0.1]:5014, partitionId: -1, operation: com.hazelcast.map.impl.query.QueryOperation, service: hz:impl:mapService]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.hazelcast.map.QueryDuringMigrationsStressTest$1.run(QueryDuringMigrationsStressTest.java:128)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:895)
	at com.hazelcast.map.QueryDuringMigrationsStressTest.queryDuringMigrations(QueryDuringMigrationsStressTest.java:125)
	at com.hazelcast.map.QueryDuringMigrationsStressTest.testQueryMapWithIndexes_whileShutdownStartup(QueryDuringMigrationsStressTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-client/1106/testReport/junit/com.hazelcast.client.map/ClientQueryDuringMigrationsStressTest/testQueryMapWithIndexes_whileShutdownStartup/

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #9724
Backport of #9098

The test was backported in #9689, but the original fix was missing
->
the test was consistently failing.

### CODE REVIEW

**Comment by jerrinot** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
Test `com.hazelcast.internal.management.PartitionServiceBeanDTOTest.testJMXStatsWithPublicAdressHost` failed with `java.net.UnknownHostException: hazelcast.org`

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Pull request merged**
