### PR TITLE
Fix ArrayDataSerializableFactoryTest

### LINKED ISSUE #6864: ArrayDataSerializableFactoryTest
This test ignored by https://github.com/hazelcast/hazelcast/commit/4293be6ecc928a21d75861323e7de68bcfcbd581

### PR DESCRIPTION
**Pull request by cangencer**
Fixes #6864

### CODE REVIEW

**Comment by asimarslan** [comment]
:+1:

**Comment by jerrinot** [comment]
:+1:

**Comment by asimarslan** [comment]
run-lan-run

**Comment by asimarslan** [comment]
run-lab-run

**Comment by asimarslan** [comment]
run-lab-run

**Pull request merged**
