### PR TITLE
[FORWARD-PORT] Security Vulnerability Fixes

### PR DESCRIPTION
**Pull request by gurbuzali**
Back-Port PR: https://github.com/hazelcast/hazelcast/pull/19582

Fixes: https://github.com/hazelcast/hazelcast/issues/19591
Fixes: https://github.com/hazelcast/hazelcast/issues/19578

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [x] Request reviewers if possible

### CODE REVIEW

**Comment by mmedenjak** [comment]
@gurbuzali does this fix https://github.com/hazelcast/hazelcast/issues/19578 or https://github.com/hazelcast/hazelcast/issues/19591, or both?

**Comment by mmedenjak** [comment]
I see [here](https://github.com/hazelcast/hazelcast-jet/commit/946906f6279546801900fe48890caeb78ddceb2a) you bumped jetty to 9.4.43, how come this PR doesn't bump it to the same?

**Comment by gurbuzali** [comment]
looks like instead of updating to the fixed version I've updated to the version on the Jet repo, my mistake.
I've also added commons-io update too, it was missing too.

**Review by kwart — APPROVED** [review]

**Comment by gurbuzali** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Does this fix https://github.com/hazelcast/hazelcast/issues/19591 and https://github.com/hazelcast/hazelcast/issues/19578 now?

**Comment by gurbuzali** [comment]
@mmedenjak yes

**Pull request merged**
