### PR TITLE
Client protocol version 1 compatibility tests

### PR DESCRIPTION
**Pull request by sancar**
ftl templates that is used to generate these tests can be found at
https://github.com/sancar/hazelcast-client-protocol/tree/testGeneratorFiles

Backport of #7935

### CODE REVIEW

**Comment by ihsandemir** [comment]
verify

**Comment by pveentjer** [comment]
run-lab-run

**Comment by pveentjer** [comment]
@ihsandemir @asimarslan can someone from the client team take over this PR?

**Comment by ihsandemir** [comment]
Closing this PR since another one is created. PR #8098 replaces this PR.

**Pull request closed without merging**
