### PR TITLE
Skip Testcontainer-dependent tests on platforms without Docker installed

### PR DESCRIPTION
**Pull request by kwart**
This PR adds assumptions to tests that use the testcontainers library.

### CODE REVIEW

**Comment by ufukyilmaz** [comment]
The failing tests started to fail after the network config change that I made in https://github.com/hazelcast/hazelcast/pull/19437. These tests fail because members from one of the other test classes are connected to 127.0.0.1:5701 and 5702 addresses. My changes badly affected the resistance of these tests against this type of interference.

**Review by ufukyilmaz — APPROVED** [review]
Checked all usages of the testcontainers by searching for `org.testcontainers.*` imports in the project. All of the tests using these test containers are covered with the assume blocks. This pr looks good to me.
Just to note that we also use these containers in the EE-side: https://github.com/hazelcast/hazelcast-enterprise/blob/master/hazelcast-enterprise/src/test/java/com/hazelcast/client/security/jet/ConnectorSecurityTest.java (As far as I see, there is only a single occurrence).

**Review by ufukyilmaz — APPROVED** [review]

**Comment by kwart** [comment]
Mac OS run for this branch: http://jenkins.hazelcast.com/job/Hazelcast-Macos-josef/3/

**Review by gurbuzali — APPROVED** [review]

**Comment by kwart** [comment]
Thanks for the reviews, Ufuk & Ali.

**Pull request merged**
