### PR TITLE
Added the "Connection.writeOrdered" method

### LINKED ISSUE #16776: Method for ordered message delivery
Both Jet and Mustang require ordered delivery of messages through the same `Connection` instance. The current interface makes an explicit emphasis that the order is not guaranteed. But current implementations have this guarantee in fact. 
We should add a new method `Connection.writeOrdered`. It will simply delegate to `Connection.write` at the moment, but future advanced implementations of `Connection` must ensure that the order is preserved.

### PR DESCRIPTION
**Pull request by devozerov**
Please pay special attention to my wording in JavaDocs. Change to Jet will be made in a separate PR.

Closes #16776

### CODE REVIEW

**Comment by sancar** [comment]
@devozerov This does not sound correct. Our current implementation does guarantee the order. If you put message A then B, you will always read message A then B on the other side. There are lots of implementations that depends on this. And example could be events. When we write events to connection, we know that order will not be broken.

I think the javadoc of the write method, does not say anything about order. But it just says about the delivery. And I think we should discuss how we plan to guarantee the delivery. Does the idea to wait for a response before write method returns ?

**Comment by devozerov** [comment]
@sancar the thing is that because we do not explicitly mention the order in JavaDoc, it cannot be assumed. In the future, we are going to add more implementations of `Connection`, which may not provide any order. An example of such implementation is a `Connection` which has multiple sockets inside, and balance packets between them. Such implementation is important for the cloud environment.

The very goal of this PR is to add a method, which guarantees the delivery order explicitly so that future implementations of `Connection` interface provide such ordering capability. 

The implementation of delivery guarantees is out of the scope of this PR. Current connection implementations already have the delivery guarantees mentioned in the PR.

**Comment by sancar** [comment]
We can always say that javadoc was wrong and fix it, if the implementation has the guarantee. The fact that it does not say the order, does not change the fact that we have implemented it to have the guarantee in the first place. The javadoc was wrong. 

We had a long chat with Peter. There are code that depends on connection order. But I am convinced that the order is broken on the eventing system, when we have temporary disconnections. That place also should be fixed. 

Althougt your choice is ok. I would go the other way around. I would introduce, connection.writeRelaxed, because current usages of the connectio.write assumes that order is there. 
Or We should change the usages of ` connection.write` with `connection.writeOrdered` in every place that we expect the order currently.

**Comment by devozerov** [comment]
I would prefer to change to `connection.writeOrdered` because there is a much smaller number of usages which require this, as opposed to usages where unordered delivery is ok. 

But in any case, this will increase the scope of the PR significantly, because all teams must analyze their usages of `Connection`. This is the reason why I would like to keep the PR as small as possible - it doesn't do any harm, but established the foundation for future improvements. I personally will create a separate PRs for Jet and for SQL to apply the `writeOrdered` method.

**Comment by devozerov** [comment]
@sancar @pveentjer Regarding the eventing system, could you please provide more info on the problem? I see the method `EventServiceImpl.sendEvent`, which sends the packet through the `EndpointManager`. This place has no ordering guarantees, because `EndpointManager` may pick different `Connection` instances for two subsequent events, thus causing reordering. 
Is this the problem you are referring to? If yes, then it is out of scope, since the PR is concerned with `Connection` only. Jet and SQL use connection objects directly to maintain the order.

**Comment by sancar** [comment]
The eventing system seems broken when there are disconnections(it does not pick another connection when there is no disconnect). Because it will pick another connection and old packets that is transmitted via `EndpointManager.transmit` might be retried on new connection. Hence the order is broken. And I agree that it is not in the scope of this pr. 

I think the scope of the pr will increase if we introduce `writeOrdered` . It is safe to use an ordered guarantee method where a relaxed method enough but not vice versa. I would just add a new method named `writeRelaxed` and don't use it anywhere today. We can slowly migrate the usages in other pr's where applicable. 
We can also rename `write` to `writeOrdered` to make it more obvious. Or we can change the javadoc only.

**Comment by devozerov** [comment]
@sancar @pveentjer any additional comments on the PR? My original goal was to put this method into order-sensitive places that use a `Connection` object directly (SQL and Jet) so that we do not break the ordering semantics accidentally in the future. 
AFAIK we already work on multi-channel connections, so I'd like this new implementation to take SQL/Jet constraints in count.

**Comment by devozerov** [comment]
@sancar I performed the analysis of existing usages. We have not that many usages as I expected, however, I still cannot decide on all of them on my own. Please see the summary of `Connection.write` below:
1. `ServerEndpointManager` - two usages, used for operation invocation. Order is not needed here since operations are considered independent of each other
1. `TextEncoder` - two usages, used by REST and Memcached protocols. Both protocols use independent request-response operations, hence the ordering is not required
1. `SendMemberHandshakeTask` - looks very suspicious! We use `write` here to send the very message to the remote side. The remote member uses it to register the connection in some internal data structures. It is not clear what will happen if subsequent operations will be reordered with the handshake processing
1. Client classes (`ClusterViewListenerService`, `AbstractMessageTask`, `ClientInvocationServiceImpl`) - hard to reason for me. I think `ClusterViewListenerService` should be ordered to ensure that membership changes are delivered in the specified order. By for the other two usages, I cannot give any conclusion.

As a result of this superficial analysis, I propose to open two issues - to investigate client usages and to investigate `SendMemberHandshakeTask`.

**Comment by devozerov** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/37/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/37/Hazelcast-pr-builder-37.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain 
information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapPutAllMessageTask.java:50: Line is longer than 130 characters (found 153). [LineLength]
--------------------------
</details>
</pre>

**Comment by devozerov** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
As mentioned, there are also hidden assumptions behind _some_ usages of the operation system. Case in point - WAN is trying to replicate an ordered set of mutation events between two clusters by batching events in separate operations. Each operation is sent independently [here](https://github.com/hazelcast/hazelcast-enterprise/blob/c3f62c11cb3af7c6ae744f848fe9f294173adbdc/hazelcast-enterprise/src/main/java/com/hazelcast/enterprise/wan/impl/replication/DefaultWanBatchSender.java#L60-L63). Even though this does not use `Connection.write`, it still assumes the ordering will be kept.

There might be some other hidden cases where ordering is assumed. It may be best to "flush" them out by crafting a special mock connection and running the whole test framework by periodically reordering packets.

**Comment by sancar** [comment]
ClientInvocation and Operations are using connection.write but the important part is if the users of these two depends on the order or not. And that basically means all the codebase. If we can manage to write a test to catch them, it would be easier. 
One part I know , `AbstractMessageTask` relies on the order when an event is returned as response.
`ClusterViewListenerService` works with versions so order is not important.

**Comment by devozerov** [comment]
Ok, seems that are quite a few subtleties and hidden ordering assumptions within the codebase. I propose to solve them on a case-by-case basis. This PR should lay out the foundation of this activity. Perhaps a product-wide review of ordering guarantees should be part of the multi-channel connection PRD, because it may break ordering invariants easily, and we will observe test failures there.

Meanwhile, the new method will be used in the SQL module in the nearest PR. I'll also propose a relevant change to Jet.

**Pull request merged**
