### PR TITLE
[BACKPORT] Remove destroyed cache proxy from owner `CacheManager` on destroy

### PR DESCRIPTION
**Pull request by serkan-ozal**
Backport of https://github.com/hazelcast/hazelcast/pull/8198

### CODE REVIEW

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
run-lab-run

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
run-lab-run

**Comment by hasancelik** [comment]
verify

**Comment by serkan-ozal** [comment]
could you please verify

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
Passed https://github.com/hazelcast/hazelcast/pull/8200#issuecomment-219960209

**Pull request merged**
