### PR TITLE
Improve ClientTransactionalMapQuorumTest

### PR DESCRIPTION
**Pull request by cangencer**
Improved tests while investigating #7693. Add tests for positive case,
and made exception handling more sensitive to catching the correct exception.

### CODE REVIEW

**Comment by mustafaiman** [comment]
👍 however I find `@Test(expected = Exception.class)` more readable compared to `ExpectedException.expect()`. I guess we do not have any rule for asserting exceptions so it should be fine either way.

**Comment by cangencer** [comment]
The problem with `@Test(expected=Exception.class)` is that it doesn't specify where the exception can happen, so if some other method than the intended throws the exception, the test still passes.

**Comment by mustafaiman** [comment]
I see. Thanks for explanation.

**Comment by eminn** [comment]
👍

**Pull request merged**
