### PR TITLE
MapContainerSupport Folded into MapContainer

### PR DESCRIPTION
**Pull request by pveentjer**
MapContainerSupport can't carry its weight. It increases code complexity and doesn't serve a real purpose from a reusability or abstraction point of view.

### CODE REVIEW

**Comment by pveentjer** [comment]
verify

**Comment by pveentjer** [comment]
verify

**Comment by Donnerbart** [comment]
:+1:

Makes it much more easy to mock the `MapContainer`.

**Comment by ahmetmircik** [comment]
seems ok.

**Pull request merged**
