### PR TITLE
Remove RU 4.1 compatibility code paths

### PR DESCRIPTION
**Pull request by ahmetmircik**
ee counterpart: https://github.com/hazelcast/hazelcast-enterprise/pull/4243

### CODE REVIEW

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Review by fbarotov — APPROVED** [review]

**Comment by fbarotov** [comment]
Do we also need to remove [MigrationManager#L425](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/partition/impl/MigrationManager.java#L425) and [MigrationManager#L1042](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/partition/impl/MigrationManager.java#L1042) ?

**Comment by ahmetmircik** [comment]
@fbarotov yes, we do. But my scope is only map module for this PR.

**Comment by mmedenjak** [comment]
I'd prefer if we abstain from cleaning up RU paths until 5.0 is released. They do no harm, it should be dead code but if we remove them, we risk introducing a bug and it's quite late in the release cycle. Let's do the rest after 5.0 is released.

**Pull request merged**
