### PR TITLE
Remove JetBuildInfo

### PR DESCRIPTION
**Pull request by mdumandag**
After the merge, it seems that the JetBuildInfo does not carry useful
information and can be removed.

There are two problematic places, where we were using the JetBuildInfo:

- In `GetClusterMetadataMessageTask`, we were sending the Jet version to MC,
if it exists
- In `BuildInfoCollector`, we were sending the Jet version to the phone home server,
if it exists

Now, in both of these cases, we were behaving as if there were no JetBuildInfo
in the first place. If it is okay to break things, we might do further cleanups.

### CODE REVIEW

**Comment by mdumandag** [comment]
run-lab-run

**Review by ufukyilmaz — APPROVED** [review]
It looks good to me. For those two cases you mentioned, let's ask man center team whether we should break them or not.

**Comment by emre-aydin** [comment]
* For the first usage, we use it understand that the cluster is a Jet 4.5 cluster. As a result, we warn the user that they should upgrade their Jet cluster to a Hazelcast 5.0 cluster. I think we can clean that up though, we will already document that we don't support Jet clusters elsewhere. We can adapt MC code accordingly once this PR gets merged.
* Phone home server handles the case where the value is absent. No code changes required. Feel free to remove that usage.

P.S. You can use `@hazelcast/management-and-monitoring` to notify us all next time :)

**Comment by mdumandag** [comment]
@emre-aydin @ufukyilmaz I removed the parts I mentioned in the commit https://github.com/hazelcast/hazelcast/pull/18972/commits/44fd78dbc3ac80118088aca73bb0cfd56ecdec6a

**Review by emre-aydin — APPROVED** [review]
MC compile will fail after merging this. https://github.com/hazelcast/management-center/pull/4513 will fix that.

**Review by ufukyilmaz — APPROVED** [review]

**Review by gurbuzali — APPROVED** [review]

**Review by sancar — APPROVED** [review]

**Pull request merged**
