### PR TITLE
Upgrade Java to 11

### PR DESCRIPTION
**Pull request by TomaszGaweda**
Animal-sniffer is no longer needed, replaced by the usage of `-release` flag, which takes care of signatures.
Modulepath tests are moved as standard module, always active.
Upgraded Maven compiler plugin and made usage of properties in whole pom.xml

EE PR: https://github.com/hazelcast/hazelcast-enterprise/pull/6021

Breaking changes (list specific methods/types/messages):
* Minimal Java version is now 11.

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
run-lab-run

**Review by frant-hartm — APPROVED** [review]
LGTM.

I suppose we will remove the use of `com.hazelcast.internal.util.JVMUtil#upcast` and any other leftovers we find in follow-up PRs?

**Comment by TomaszGaweda** [comment]
Yes, I want to keep this PR minimal (only configuration changes if possible), any cleanups later

**Comment by TomaszGaweda** [comment]
run-ee-compile

**Comment by TomaszGaweda** [comment]
run-ee-compile

**Review by vbekiaris — APPROVED** [review]

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
run-lab-run

**Review by pveentjer — APPROVED** [review]

**Comment by pveentjer** [comment]
Happy to see that we are dropping support for such old JREs. Hope to see an upgrade to Java 17 soon.

**Pull request merged**
