### PR TITLE
Removed encryption doc from ChannelInboundHandler

### PR DESCRIPTION
**Pull request by pveentjer**
The suggested approach isn't valid; especially with the introduction
of the io pipeline

### CODE REVIEW

**Comment by pveentjer** [comment]
run-lab-run

**Comment by Holmistr** [comment]
I'm looking at the failure, but I fail to understand how it's possible that the com.hazelcast.instance.HazelcastInstanceFactoryTest gets executed. The PR builder is using -PparallelTest, when I try it, the HazelcastInstanceFactoryTest is not getting run because it's not marked as ParallelTest. @Donnerbart any idea?

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
`HazelcastInstanceFactoryTest` is a `QuickTest`, so it gets executed in the PR builder. Nothing fancy here. The non-parallel tests are just executed after the parallel tests (there are two test executions per module).

**Comment by pveentjer** [comment]
Since this is just the removal of outdated/invalid javadoc for internal usage only, I'm going to merge this one.

**Pull request merged**
