### PR TITLE
Fix the v4 signer

### PR DESCRIPTION
**Pull request by igmar**
- The signature wasn't correct : It needs more then just the resulting
  hash
- x-amz-date is required

### CODE REVIEW

**Comment by igmar** [comment]
I'll properly fix the pull, this is to start the discussion.

**Comment by bilalyasar** [comment]
@igmar , in my local hz aws joiner works correctly. so is there a bug in the code?

**Comment by igmar** [comment]
@bilalyasar You're sure that's a v4 signer ? I'm pretty sure it's broken in it's current state.

**Comment by jarosite** [comment]
any updates for this?

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/5778

**Pull request closed without merging**
