### PR TITLE
[BACKPORT 4.1-BETA-1] Remove the hazelcast-sql JAR from the ZIP distribution lib folder

### PR DESCRIPTION
**Pull request by kwart**
Backport of #17494

### CODE REVIEW

**Review by Holmistr — APPROVED** [review]

**Review by devozerov — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2247/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2247/Hazelcast-pr-builder-2247.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AntiEntropyCorrectnessTest.testPartitionData:82->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:221->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:225->HazelcastTestSupport.assertTrueEventually:1350->HazelcastTestSupport.assertTrueEventually:1248->PartitionCorrectnessTestSupport.access$000:66->PartitionCorrectnessTestSupport.assertSizeAndData:269->PartitionCorrectnessTestSupport.assertReplicaVersionsAndBackupValues:333 Replica version mismatch! Owner: [127.0.0.1]:5701, Backup: [127.0.0.1]:5702, Partition: Partition {ID: 13, Version: 7} [
	0:[127.0.0.1]:5701 - 2684ef34-4d12-462c-b80e-5acea56b4233
	1:[127.0.0.1]:5702 - 46284075-831e-4c72-87ff-31647c2f7c0d
	2:[127.0.0.1]:5706 - 94f121d3-fdc5-4bc4-b661-e5af4fd1b9d9
	3:[127.0.0.1]:5704 - 749a23ac-8817-4644-8a02-0c3fb316d2b2
	4:[127.0.0.1]:5705 - 903e7db4-2d6a-4902-b1de-f87da1fa4838
	5:[127.0.0.1]:5707 - fa72dde9-5834-4aea-8ae4-fdb0b5289b84
	6:[127.0.0.1]:5703 - 04a409b4-ef65-4af0-8da0-8714ce3a8af1
], Replica: 1 owner versions: [7, 0, 0, 0, 0, 0] backup versions: [4, 0, 0, 0, 0, 0] expected:<7> but was:<4>
[INFO] 
[ERROR] Tests run: 31486, Failures: 1, Errors: 0, Skipped: 977
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by Holmistr** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2256/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2256/Hazelcast-pr-builder-2256.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR] com.hazelcast.sql.SqlErrorClientTest.testExecutionError_fromSecondMember[smartRouting:false](com.hazelcast.sql.SqlErrorClientTest)
[ERROR]   Run 1: SqlErrorClientTest.testExecutionError_fromSecondMember:97->SqlErrorAbstractTest.checkExecutionError:115 ? NullPointer
[INFO]   Run 2: PASS
[INFO] 
[INFO] 
[ERROR] Tests run: 2901, Failures: 0, Errors: 1, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by kwart** [comment]
run-lab-run

**Pull request merged**
