### PR TITLE
Default validate target should be set true

### PR DESCRIPTION
**Pull request by ahmetmircik**
resolves https://github.com/hazelcast/hazelcast/issues/4500 and resolves https://github.com/hazelcast/hazelcast/issues/4493

### CODE REVIEW

**Comment by gurbuzali** [comment]
:+1:

**Comment by ahmetmircik** [comment]
__Failed test:__
`com.hazelcast.client.cache.JCacheClientListenerTest.testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown`
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client/11603/testReport/junit/com.hazelcast.client.cache/JCacheClientListenerTest/testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown/

**Comment by ahmetmircik** [comment]
verify

**Comment by pveentjer** [comment]
Good spotting!

**Comment by pveentjer** [comment]
I'll merge this one since I created it and it is an obvious bug.

**Pull request merged**
