### PR TITLE
Fix for accessing expired cache entry

### PR DESCRIPTION
**Pull request by serkan-ozal**
If `processExpiredEntry` expires and removes record, `isExpiredAt` should not be called on that record since it may be native memory based record and it is disposed.

Without this PR, `CacheMemoryLeakStressTest::testNativeMemoryLeakWithExpiryPolicy` test causes JVM crash.

### CODE REVIEW

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
verify

**Comment by mdogan** [comment]
:+1: 

fortunately we have `CacheMemoryLeakStressTest::testNativeMemoryLeakWithExpiryPolicy` test...

**Comment by mdogan** [comment]
I'm merging this one because it fixes a critical JVM crash issue.

**Pull request merged**
