### PR TITLE
initialize sequence before adding to queue

### LINKED ISSUE #18670: Writes to a persistent map store may be lost when coalescing is turned on.
It is a continuation of issue #15060. 
Correction of this issue used sequence number of DelayedEntry to detect a situation when at the time of removing already persisted DelayedEntries there is already a newer DelayedEntry.
But there is still a small window when sequence number is not yet initialized but the DelayedEntry has already been added to the queue. See `WriteBehindStore::add()` @ version 4.1.1

```
public void add(DelayedEntry<Data, Object> delayedEntry) {
        writeBehindQueue.addLast(delayedEntry, false);

        stagingArea.put(delayedEntry.getKey(), delayedEntry);

        delayedEntry.setSequence(sequence.incrementAndGet());
    }
```
	
We are still observing occasional lost updates and we think this is the reason. Under normal circumstances the issue reproduces very rarely. To increase chances of reproduction it is needed to increase frequency of StoreWorker runs. 

Attached a diagram of the problematic mechanism
image

Attached a test case. Contains a modified StoreWorker to increase chance of reproduction.
[CoalescedSequenceTest.zip](https://github.com/hazelcast/hazelcast/files/6466074/CoalescedSequenceTest.zip)

### PR DESCRIPTION
**Pull request by palisie**
Fixes #18670

### CODE REVIEW

**Comment by nfrankel** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
Hi @palisie, could you please add a test to verify the fix?

**Comment by palisie** [comment]
Added a unit test. I'm not sure if it is in line with the style of existing tests in the project. However the problem is difficult to reproduce deterministically (and in limited time) in an integration test.

**Comment by ahmetmircik** [comment]
@palisie thx for the test, it seems ok to me.

**Review by ahmetmircik — APPROVED** [review]

**Comment by ahmetmircik** [comment]
run-lab-run

**Review by mmedenjak — APPROVED** [review]

**Comment by mmedenjak** [comment]
Thank you @palisie for the issue, analysis and fix!

**Pull request merged**
