### PR TITLE
Removed static members from SqlIndexResolutionTest (#17429)

### LINKED ISSUE #17429: Multiple SqlIndexResolutionTest case failures
- Fails on `Hazelcast-4.master-sonar` and others. i.e. `Hazelcast-4.master-Windows-OracleJDK8`
- Fails on [Build #606 (Aug 29, 2020 9:17:00 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/606/#showFailuresLink)
- We have `968` failing test case in `SqlIndexResolutionTest`
- Sample Error
```
Hazelcast instance is not active!
```
- Stacktrace
```
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.instance.impl.HazelcastInstanceProxy.getOriginal(HazelcastInstanceProxy.java:315)
	at com.hazelcast.instance.impl.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:95)
	at com.hazelcast.sql.index.SqlIndexResolutionTest.after(SqlIndexResolutionTest.java:120)
	at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:404)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
....
```
- Kindly check.

### PR DESCRIPTION
**Pull request by devozerov**
This PR refactors members start/stop in the `SqlIndexResolutionTest` to avoid `static` members.

Closes #17429

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2132/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2132/Hazelcast-pr-builder-2132.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TransactionQueueTest.testIssue859And863_WhenInQueueOnSecondInstance_OutQueueOnFirstInstance:379->testIssue859And863:412->HazelcastTestSupport.assertTrueEventually:1350->HazelcastTestSupport.assertTrueEventually:1248 expected:<3000> but was:<2999>
[INFO] 
[ERROR] Tests run: 31284, Failures: 1, Errors: 0, Skipped: 976
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by devozerov** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2141/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2141/Hazelcast-pr-builder-2141.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CacheExpirationTest.test_whenEntryIsRemovedBackupIsCleaned:310 Expected to remove entry 0 but entry was not present. Expired entry count: 1
[INFO] 
[ERROR] Tests run: 31283, Failures: 1, Errors: 0, Skipped: 976
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by devozerov** [comment]
run-lab-run

**Review by mdogan — APPROVED** [review]

**Review by mmedenjak — APPROVED** [review]

**Pull request merged**
