### PR TITLE
Add systemAttributes Map to Member's Cluster

### PR DESCRIPTION
**Pull request by Fabryprog**
Hello everybody,

i added a new map to Member interface. 

The new map contains node's system informations:

- java.vm.version
- java.vm.vendor
- java.runtime.version
- os.arch
- os.name
- available.processors

### CODE REVIEW

**Comment by Fabryprog** [comment]
NOTE: 

Unfortunately I could not test the functionality because i am unable to launch the command *mvn clean package*. The maven task remains blocked into "Running com.hazelcast.cache.BasicCacheTest"

cattura

Please, Can you help me?

King Regards

**Comment by Fabryprog** [comment]
Hello, i found the right command to install locally jumping tests: *mvn clean install -Dskiptests*

Now i can test my code!!!

Tonight (italian GMT) will commit style code fix.

Stay tuned!

**Comment by Fabryprog** [comment]
Ok. 

The feature is done.

Can you merge it?

thanks!

King Regards

**Comment by Fabryprog** [comment]
@mdogan because you move the milestone from 3.6 into PENDING?

**Comment by sancar** [comment]
Hi @Fabryprog,
This feature does not seem to implemented in correct place. For example, We do not want to change how member serialized if we don`t have to. Information like these are also available in management center. You may want to take a look at that.

**Comment by mdogan** [comment]
This PR changes public API by adding new methods and also changes the serialized form of some classes. We can't promise this is going to be in 3.6 or in any release without our product management decides it to do so. That's why this is moved to pending list.

**Comment by Fabryprog** [comment]
@mdogan and @sancar thanks a lot! 

I hope this feature will be into 3.6. 

Today i am sharing this informations using a shared map!

**Comment by Fabryprog** [comment]
Hello boys (there is no woman?),

There are any news?

**Comment by enesakar** [comment]
Hi @Fabryprog ;

Talked to the team, they think the code you send is not necessary enough to change serialization. But also the information is reachable via JMX and management center.
So I am sorry but I am closing this PR.
Thanks for your attention and contribution.

**Pull request closed without merging**
