### PR TITLE
Implement client partitioning strategy for map & near cached map

### LINKED ISSUE #13950: Map's PartitioningStrategy configuration is broken for clients
One can configure a map with a different partitioning strategy (eg `StringPartitioningStrategy`). In this case server side will calculate the partitionId of a key according to the configured partition strategy. But client side is not aware of this configuration. Below example produces a null value:

```
        Config config = new Config();
        MapConfig mapConfig = config.getMapConfig("map");
        PartitioningStrategyConfig partitioningStrategyConfig = new PartitioningStrategyConfig();
        partitioningStrategyConfig.setPartitioningStrategyClass(StringPartitioningStrategy.class.getName());
        mapConfig.setPartitioningStrategyConfig(partitioningStrategyConfig);

        HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);

        String key = "key@actualPartition";

        hz.getMap("map").put(key, "val");


        HazelcastInstance client = HazelcastClient.newHazelcastClient();
        Object value = client.getMap("map").get(key);
        System.out.println(value);
```

### PR DESCRIPTION
**Pull request by mdumandag**
This PR introduces custom partitioning strategy per map for map and near cached map.

To do so, a way to set `PartitioningStrategyConfig` to `ClientConfig` is added.

fixes #13950

### CODE REVIEW

**Comment by yozank** [comment]
are we going to backport this to v3.12.x?

**Comment by mmedenjak** [comment]
@mdumandag can you close or rebase this PR and get some reviewers?

**Comment by mmedenjak** [comment]
@mdumandag @sancar should this PR go to 4.2?

**Comment by mdumandag** [comment]
No, we were planning this for the 4.0 release, but couldn't agree on configuration format itself after discussing it with David and the team. Let me close this PR. Maybe we can think about this more on the upcoming releases

**Pull request closed without merging**
