### PR TITLE
(Forward Port) Fixes MapListener addition issue via EntryListenerConfig 

### LINKED ISSUE #5648: Not possible to add MapClearedListener to EntryListenerConfig as an implementation

### PR DESCRIPTION
**Pull request by ahmetmircik**
closes #5648 

Fixed addition of a MapListener impl. via EntryListenerConfig object

### CODE REVIEW

**Comment by gurbuzali** [comment]
:+1:

**Comment by mdogan** [comment]
Why don't we introduce a new `MapListenerConfig` for the new interfaces and possibly deprecate the `EntryListenerConfig`?

**Comment by ahmetmircik** [comment]
`MapListenerConfig` was my first option and work. But cared about source-binary-naming compatibility issues and thought extra changes/additions needed to use `MapListenerConfig`(especially in declaratively configured use-cases), gave up that work and decided to stick what we have currently. I think we can merge this PR into 3.5 due to that reasons, since it is a patch release. 

For 3.6, we can change the return type of `EntryListenerConfig#getImplementation` to `MapListener` by breaking the binary compatibility and that can fix the issue instead of a `MapListenerConfig` addition. 

WDYT @mdogan ?

**Comment by jerrinot** [comment]
@ahmetmircik: What's status of this PR?

**Comment by pveentjer** [comment]
@ahmetmircik we are we going to do with this PR?

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by mdogan** [comment]
:+1:

**Pull request merged**
