### PR TITLE
Fix 3.10 version in hazelcast configuration.

### LINKED ISSUE #11586: Wrong hazelcast-config XSD schema is used when minor major or minor has more than 1 digit
Wrong hazelcast-config XSD schema is used when minor major or minor has more than 1 digit.

Currently a Member with default configuration is not able to start from the master branch (version `3.10-SNAPSHOT`), because it uses XSD for version `3.1`. 

The stack trace:

```
Exception in thread "main" com.hazelcast.core.HazelcastException: org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'listener-base' to a(n) 'type definition' component.
	at com.hazelcast.util.ExceptionUtil$1.create(ExceptionUtil.java:40)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:124)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:69)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:129)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:218)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:209)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:121)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:92)
	at ClientServer.main(ClientServer.java:24)
Caused by: org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'listener-base' to a(n) 'type definition' component.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:195)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:131)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:384)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:2537)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:2528)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1472)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseSimpleContent(XSDComplexTypeTraverser.java:373)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexTypeDecl(XSDComplexTypeTraverser.java:249)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseGlobal(XSDComplexTypeTraverser.java:160)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1255)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:579)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:556)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:523)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:489)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:224)
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:183)
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:235)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:216)
	... 4 more
```

### PR DESCRIPTION
**Pull request by kwart**
These PR comes with 2 commits. 
* The first fixes #11586 - problem with using XSD for Hazelcast version where major or minor has more than one digit;
* The second commit updates XSD version in hazelcast default and example configurations.

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
@kwart seems like the `com.hazelcast.internal.cluster.Versions` needs to be updated as well:
```
public static final Version PREVIOUS_CLUSTER_VERSION = V3_8;
public static final Version CURRENT_CLUSTER_VERSION = V3_9;
```
These constants are used only in tests. Can we somehow refactor the tests so that we don't need to update this on every release? If you aren't sure, just update the values to `V3_9` and `V3_10`.

**Comment by Donnerbart** [comment]
I have a PR pending for that: https://github.com/hazelcast/hazelcast/pull/11588

**Comment by Donnerbart** [comment]
I would merge this PR despite the failing tests, since we know exactly where they are coming from (and know that they are unrelated to this PR).

**Comment by mmedenjak** [comment]
@Donnerbart I guess we would either need to combine the PRs or merge one with a failing build as none of them will turn green without the other one.

**Comment by Donnerbart** [comment]
As I said, I have no problem to merge this one with the existing test failures. It resolves the most urgent issue for the OS and EE builds. We also do direct commits sometimes, which by-pass all checks, so I have no problem to merge a PR, which partly solves an issue (since we know, that the remaining test failures are not related).

**Comment by kwart** [comment]
I've cherry-picked the Danny's commit. Let's see how it works together.

**Pull request merged**
