### PR TITLE
Add memory management design doc

### PR DESCRIPTION
**Pull request by gierlachg**

### CODE REVIEW

**Review by frant-hartm — APPROVED** [review]

**Review by viliam-durina — APPROVED** [review]

**Comment by Holmistr** [comment]
@gierlachg Could you please provide an example in the design document how you set that property via configuration as an end user? The Documentation team will ask that question to you anyway :)

**Comment by gierlachg** [comment]
That's pretty much what `Implementation` section does.

**Comment by Holmistr** [comment]
Sorry, I wasn't clear enough. I assumed that there's a way how to set it declaratively via `hazelcast.xml` or `hazelcast.yaml`. I understand that this is a job specific setup but imagine the scenario, which is actually the main driver of this change - a user performing an SQL query with `ORDER BY` without having an index on it. Or GROUP BY ... 

How does a user running a SQL query make sure that his query won't crash a cluster with OOME?

**Comment by Holmistr** [comment]
I believe that https://github.com/hazelcast/hazelcast/pull/18692 is the answer :)

**Pull request merged**
