### PR TITLE
SampleableConcurrentHashMap improvements

### PR DESCRIPTION
**Pull request by mdogan**
- Added optional methods to `SampleableConcurrentHashMap` to allow
subclasses to override fetching and sampling.
- Removed unused `c.h.u.CacheConcurrentHashMap` class.

### CODE REVIEW

**Comment by serkan-ozal** [comment]
:+1:

**Comment by gurbuzali** [comment]
:+1:

**Comment by mdogan** [comment]
verify

**Comment by pveentjer** [comment]
:+1:

**Comment by pveentjer** [comment]
verify

**Comment by noctarius** [comment]
Just as a short question, if there are only Expirable entries and non of them is expired, don't we have to select candidates anyways?

**Pull request merged**
