### PR TITLE
Fixes invalidation message sending problem to client near-caches upon…

### PR DESCRIPTION
**Pull request by ahmetmircik**
… member side putAll/loadAll call

closes https://github.com/hazelcast/hazelcast/issues/7715

### CODE REVIEW

**Comment by Donnerbart** [comment]
Do I understand this fix correctly?
If only clients have a NearCache configured the `isNearCacheEnabled()` returned `false` (since it just checks the member configuration) and no `invalidationKeys` were generated. Therefor you changed this to `isInvalidationEnabled()`, which checks if member invalidation is configured OR a listener for invalidation is registered (which seems to be the clients then).

You also renamed `isNearCacheEnabled()` to `hasMemberNearCache()` to point out what is really checked by that method.

If this is the fix you get a big :+1: from me for the improvement and the new tests :)

**Comment by jerrinot** [comment]
oh, I'd love to have explanations similar the one @Donnerbart provided as a part of changeset. It makes reviewing so much easier and it's also good for history keeping.

**Comment by ahmetmircik** [comment]
@Donnerbart you are absolutely correct.

@jerrinot i thought that it is self-explanatory.

**Comment by jerrinot** [comment]
:+1:

**Comment by jerrinot** [comment]
@ahmetmircik: this PR is rather simple, but @Donnerbart's comment still makes review process easier.

**Pull request merged**
