### PR TITLE
Replicatedmap speed improvements backport

### PR DESCRIPTION
**Pull request by noctarius**
Added all lazy views to ReplicatedMap to prevent copying and re-hashing (HashSet) while retrieving values - speed improvement ~100x

### CODE REVIEW

**Comment by gurbuzali** [comment]
ReplicatedMapTests are failing

**Comment by noctarius** [comment]
verify

**Comment by dbrimley** [comment]
This is an important improvement for us.  Thanks to Chris for helping me on this to improve performance that I needed.

**Comment by noctarius** [comment]
verify

**Comment by noctarius** [comment]
verify

**Comment by noctarius** [comment]
verify

**Pull request merged**
