### PR TITLE
Update Spring dependency to 5.2.8.RELEASE

### PR DESCRIPTION
**Pull request by leszko**

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1724/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1724/Hazelcast-pr-builder-1724.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.12:check (default) on project hazelcast-spring: failed with 1 bugs and 0 errors -> [Help 1]
--------------------------
</details>
</pre>

**Comment by jerrinot** [comment]
shouldn't we have integration tests for each major Spring version?

**Comment by leszko** [comment]
> shouldn't we have integration tests for each major Spring version?

We could have it, but then we'll need a separate `pom.xml`, then a separate directory, like `hazelcast-spring-4-tests`. I'm not sure it's worth adding it. What do you think?

**Comment by jerrinot** [comment]
spring is arguable the most popular integration we have. I think it's worth adding. 
otherwise we cannot guarantee not to have a regression in all but the latest version.

**Comment by leszko** [comment]
Ok, I'll add some regression tests.

**Comment by leszko** [comment]
@jerrinot I copied all tests to `hazelcast-spring-4-tests` to test the regression. Is this what you had on your mind?

**Comment by jerrinot** [comment]
well, my idea was something more ... maintainable, perhaps more _dry_ :)

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1729/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1729/Hazelcast-pr-builder-1729.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.12:check (default) on project hazelcast-spring: failed with 1 bugs and 0 errors -> [Help 1]
--------------------------
</details>
</pre>

**Comment by leszko** [comment]
As discussed, I moved all the (integration) tests to `hazelcast-spring-tests`. Now if you want to execute Spring 5 tests you need to run the following command (in `hazelcast-spring-tests` directory):
```
mvn test
```

And to execute Spring 4 tests, run the following command.
```
mvn test -P spring-4
```

@jerrinot PTAL.

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1737/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1737/Hazelcast-pr-builder-1737.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.12:check (default) on project hazelcast-spring: failed with 1 bugs and 0 errors -> [Help 1]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1738/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1738/Hazelcast-pr-builder-1738.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   BackupTest.testBackupRemoveWhenOwnerNodeDead:344 ? TestTimedOut test timed out...
[INFO] 
[ERROR] Tests run: 31168, Failures: 0, Errors: 1, Skipped: 1000
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by leszko** [comment]
verify

**Comment by leszko** [comment]
run-lab-run

**Pull request merged**
