### PR TITLE
Implement MultiMap asynchronous bulk get  (#9079)

### PR DESCRIPTION
**Pull request by abdulazizali77**
Apologies for the delay @mmedenjak @Holmistr @vbekiaris 
This is implementation for `MultiMap.getAllAsync`, please take a look

__Design Issues, Thoughts__
- Currently `GetAllOperationFactory` is instantiated once for all partitions and nodes, this is different than the `PutAllAsync` implementation where one `PutAllOperationFactory` is instantiated per member. Am unsure if this should also be the case for `GetAllAsync`
- Have renamed the preexisting `MultiMap.GetAllOperation` to `MultiMap.GetOperation`, looking at the commit history this was something related to collections. 
It doesnt look like there was anything else that was actually `MultiMap.GetOperation`
- Potentially `GetAllOperation` shouldnt be implementing `BlockingOperation` given that its async but unsure about this. Related change is the new `LockWaitNotifyKeySet` class. Will remove if it shouldnt implement `BlockingOperation`

related client protocol PR is https://github.com/hazelcast/hazelcast-client-protocol/pull/320

### CODE REVIEW

**Comment by abdulazizali77** [comment]
relatedly apparently #3840 is a subset/duplicate of #9079

**Comment by Holmistr** [comment]
Hi @abdulazizali77 , great to see another PR from you! :) We'll get on it soon hopefully.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by pveentjer** [comment]
Closing PR since it seems to be abandoned.

**Comment by abdulazizali77** [comment]
> Closing PR since it seems to be abandoned.

abandoned by whom? likely its that the maintainers decided not to review it?

**Comment by c-attila** [comment]
Hi! Does anyone know why was this not implemented in the end?
We would need this feature in our project using Hazelcast 5 Enterprise. A QueryCache for MultiMaps would be also good.
FYI @mmedenjak, @pveentjer, @hazelcast
(see also #9079 and #3840 still open)

**Comment by Holmistr** [comment]
@c-attila In general, we never got it prioritized enough. MultiMap is not the most used datastructure (it was way behind Map, Queue, Topic, ...) and we just had bigger fish to fry. I would suggest you to reach through the Hazelcast Support and make a case for your usecase.

Disclaimer: I no longer work at Hazelcast.

**Pull request closed without merging**
