### PR TITLE
[DO NOT MERGE yet] A new Maven profile to run tests in multiple JVMs in parallel

### PR DESCRIPTION
**Pull request by jerrinot**
This PR introduces a new test category `ParallelTest`. 

When a new Maven profile `parallelTest` is selected then tests in this category will be executed in multiple JVMs in parallel. 

I also moved bunch of slow tests into the `Slow` category so they are not executed with each build. I moved only the tests with running time >30s and only if they cannot be executed in parallel. Moreover I slightly changed the Aggregations tests so they can be executed in parallel now. I also moved bunch of other tests to the `ParallelTest` category where I found it safe. 

Full build now takes less than 19 minutes on C4.4xLarge EC2 machine when the parallelTest profile is activated. 
Here are build times per category:
```
[INFO] Hazelcast Root .................................... SUCCESS [0.387s]
[INFO] hazelcast-code-generator .......................... SUCCESS [1.126s]
[INFO] hazelcast ......................................... SUCCESS [5:32.541s]
[INFO] hazelcast-cloud ................................... SUCCESS [1.751s]
[INFO] hazelcast-client .................................. SUCCESS [3:30.870s]
[INFO] hazelcast-client-new .............................. SUCCESS [3:16.694s]
[INFO] hazelcast-hibernate ............................... SUCCESS [0.220s]
[INFO] hazelcast-hibernate3 .............................. SUCCESS [1:55.815s]
[INFO] hazelcast-hibernate4 .............................. SUCCESS [2:04.291s]
[INFO] hazelcast-wm ...................................... SUCCESS [1:12.304s]
[INFO] hazelcast-spring .................................. SUCCESS [35.157s]
[INFO] hazelcast-ra ...................................... SUCCESS [0.011s]
[INFO] hazelcast-jca ..................................... SUCCESS [3.334s]
[INFO] hazelcast-jca-rar ................................. SUCCESS [0.017s]
[INFO] hazelcast-build-utils ............................. SUCCESS [0.671s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18:15.475s

```

Known Issue:
We currently have 3 custom JUnit runners:
- `HazelcastParallelClassRunner`
- `HazelcastSerialClassRunner`
- `HazelcastTestRunner`

This PR introduces a kind of duplication as the `ParallelTest` category has a similar semantic as `HazelcastParallelClassRunner`. I guess the next step would be to use just `HazelcastTestRunner` with combination of `ParallelCategory` where appropriate.

### CODE REVIEW

**Comment by ahmetmircik** [comment]
:+1: good work

**Comment by jerrinot** [comment]
With the latest commits the total build time is just under 20 minutes

**Comment by mesutcelik** [comment]
Thanks @jerrinot ,
That is incredible contribution.

* I think we should create a guidance for how to mark tests as `Parallel,Slow,Nightly,Quick`. We are a living organism so without rules of setting right category, we can easily mess up the things. When we introduce a new test, we should clearly know what to set as test category. 
* SlowTests are somehow hidden because they are only executed in Sonar Builds. 
* Some of NightlyTests are not really a long running tests but stressing system so they can be a simulator test candidates. 
* In order to make things simpler, we might merge Slow+Nightly Category into more meaningful category.

We still have things to improve but this PR is very good start....

This PR is too big to review so we can split into several PRs like maven profile related changes as one PR followed by several PRs marking right categories in unittests.

**Comment by Donnerbart** [comment]
We already revered @jerrinot during our standup. This is really a huge improvement.

+1 for splitting up this PR into "change category only" and the remaining changes. I'd really like to have a look at the code, but GitHub doesn't even show it (and I'm too lazy to clone your branch).

**Comment by jerrinot** [comment]
I'm going to send bunch of smaller PRs as suggested.

**Comment by serkan-ozal** [comment]
@jerrinot 

As I seen, our PR builds before this improvement takes `75` mins and with this PR takes `55` min on `m1.large` machine. 

After this improvement, as you said the build takes `19` mins on `C4.4xLarge` machine. Do you know how much does it take without this improvement on `C4.4xLarge` machine?

**Comment by jerrinot** [comment]
@serkan-ozal: I'll try to run the current master on the C4.4xLarge. It took 55 minutes because in order to use the parallel execution on multiple JVMs you have to active the new `parallelTest` profile.

**Comment by serkan-ozal** [comment]
@jerrinot Do you know how long does it take on `m1.large` (the current PR builder machine type) machine when `parallelTest` is activated?

**Comment by jerrinot** [comment]
@serkan-ozal: I have no idea. I reckon it'll be much longer is it does have just 2 cores. 
Moreover the `m1.large` is pretty old instance and its cores probably aren't fastest.

**Comment by serkan-ozal** [comment]
@jerrinot yes, I know. I just want to wonder comparison results. Of course, if you don't have many (enough) core, you don't get the fully advantage of multi-threaded run.

**Comment by jerrinot** [comment]
@serkan-ozal This is the master branch(c850e1f9d) on c4.4xlarge:
```
[INFO] Hazelcast Root .................................... SUCCESS [0.164s]
[INFO] hazelcast-code-generator .......................... SUCCESS [2.531s]
[INFO] hazelcast ......................................... SUCCESS [34:48.462s]
[INFO] hazelcast-cloud ................................... SUCCESS [1.627s]
[INFO] hazelcast-client .................................. SUCCESS [8:59.204s]
[INFO] hazelcast-client-new .............................. SUCCESS [8:52.784s]
[INFO] hazelcast-hibernate ............................... SUCCESS [0.222s]
[INFO] hazelcast-hibernate3 .............................. SUCCESS [1:49.622s]
[INFO] hazelcast-hibernate4 .............................. SUCCESS [2:04.043s]
[INFO] hazelcast-wm ...................................... SUCCESS [4:52.718s]
[INFO] hazelcast-spring .................................. SUCCESS [34.430s]
[INFO] hazelcast-ra ...................................... SUCCESS [0.002s]
[INFO] hazelcast-jca ..................................... SUCCESS [3.345s]
[INFO] hazelcast-jca-rar ................................. SUCCESS [0.017s]
[INFO] hazelcast-build-utils ............................. SUCCESS [1.012s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:02:10.491s
```

I'm not quite sure why the `hazelcast-wm` took so much time this time.

**Comment by jerrinot** [comment]
closing the PR in favour of multiple smaller PRs.

**Pull request closed without merging**
