### PR TITLE
Removes invalidate method from Record interface

### PR DESCRIPTION
**Pull request by ahmetmircik**
It causes complexity and adds no value.

### CODE REVIEW

**Comment by ahmetmircik** [comment]
@mdogan @mtopolnik can you have a look?

**Comment by mdogan** [comment]
:+1: 

This is also a fix for NPE issue found in map hot-restart test.

**Comment by mdogan** [comment]
run-lab-run

**Comment by mtopolnik** [comment]
:+1:

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Pull request merged**
