### PR TITLE
Java 8 Assumption for AddressUtilTest

### PR DESCRIPTION
**Pull request by lazerion**
verified [on this](https://hazelcast-l337.ci.cloudbees.com/view/Suicide%20Branches/job/code-cov-address-util-zulu/8/console) jenkins against zulu jdk 7

### CODE REVIEW

**Comment by lazerion** [comment]
@Holmistr it failure relevant for JDKs prior to JDK8.

**Comment by Holmistr** [comment]
Oh, ok. I see it now in the Jenkins job results. @lazerion So could you please just add a comment that the reason why we're doing it is that PowerMock is behaving differently on prior-JDK8s?

**Comment by Holmistr** [comment]
@lazerion Btw nice catch with the explanation :clap: 

I'm sure that we'll forget why there is the assume* in those tests. How about you would just add a comment like this:

```
assumeThatJDK8(); // see: https://github.com/hazelcast/hazelcast/pull/13069#issuecomment-388719847
```

I know myself and if I ever look at that test again, I will think like "why is there is assume thing?", that's why I'm paying that (maybe too) much attention to it.

**Comment by lazerion** [comment]
@Holmistr thanks, comment added as advised.

**Comment by Holmistr** [comment]
LGTM, thanks :)

**Pull request merged**
