### PR TITLE
Upgrade JMH to 1.14.1

### PR DESCRIPTION
**Pull request by monkey-mas**
It'd be usually good to use the latest library version. :)

ref.
JMH 1.13:   http://mail.openjdk.java.net/pipermail/jmh-dev/2016-July/002269.html
JMH 1.14:   http://mail.openjdk.java.net/pipermail/jmh-dev/2016-September/002326.html
JMH 1.14.1: http://mail.openjdk.java.net/pipermail/jmh-dev/2016-September/002351.html

### CODE REVIEW

**Comment by tombujok** [comment]
run-lab-run

**Comment by tombujok** [comment]
Thx for the PR. In order to merge it I would a CLA signed from you.
https://hazelcast.atlassian.net/wiki/download/attachments/6357071/Hazelcast%2C%20Inc.%20Individual%20Contrbutor%20License%20Agreement%20v100113.pdf?version=2&modificationDate=1394826512258&api=v2

**Comment by monkey-mas** [comment]
Do you have a _digital_ CLA format that I can sign to online? Currently I don't have MicroSoft Word on my machine so it's hard for me to sign to a doc file :(

**Comment by monkey-mas** [comment]
FYI, the latest JMH is now `1.15` not `1.14.1` :) The new version was just released.
ref. http://mail.openjdk.java.net/pipermail/jmh-dev/2016-September/002371.html

**Comment by pveentjer** [comment]
@monkey-mas have you returned the CLA?

**Comment by Donnerbart** [comment]
@monkey-mas The document is actually a PDF, so you should be able to use it.

**Comment by monkey-mas** [comment]
Hi @Donnerbart ,
Well the problem is that I can't modify or scan the PDF to sign CLA :(  (I don't have a scanner...)
Happy to close this PR so that you can upgrade JMH in your own PR though :)

**Comment by Donnerbart** [comment]
I think you can print it, sign it and make a photo with your smartphone. I did the same before joining the company (didn't have a scanner either) :D

**Comment by monkey-mas** [comment]
All right, thanks :) Unfortunately I don't have one now as mine was broken the other day... :(

**Comment by pveentjer** [comment]
Closing this one due to inactivity.

**Pull request closed without merging**
