### PR TITLE
Fixed object identity issue in ReplicatedMap when using OBJECT in-memory format

### PR DESCRIPTION
**Pull request by Donnerbart**
* added test for `ReplicatedMap` with custom key/value classes
* fixed key marshalling in `ReplicatedMap` (always store serialized keys)

### CODE REVIEW

**Comment by Donnerbart** [comment]
The issue behind this is in the `AbstractReplicatedRecordStore´, which handles the keys in the same way as the values:
```java
private Object put(InternalReplicatedMapStorage<K, V> storage, Object key, Object value,
                   long ttl, TimeUnit timeUnit, boolean incrementHits) {
    isNotNull(key, "key");
    isNotNull(value, "value");
    isNotNull(timeUnit, "timeUnit");
    if (ttl < 0) {
        throw new IllegalArgumentException("ttl must be a positive integer");
    }
    long time = Clock.currentTimeMillis();
    V oldValue = null;
    K marshalledKey = (K) marshall(key);
    V marshalledValue = (V) marshall(value);
    (...)
}
```
With in-memory-format `OBJECT` this stores the key by-reference. Then a following `get()` cannot find that key again, since it's a new key instance and `equals()`/`hashCode()` are not implemented.

**Comment by Donnerbart** [comment]
I've added a fix candidate. This will fix the issue by always storing serialized keys. It should not have too much side effects, but may decrease the performance on reading methods with `OBJECT` in-memory format. For writing methods we need to serialize the key anyway for the replication operations (but I didn't check for duplicate serializations yet).

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
@Donnerbart is this PR still valid? Can we assign it to a milestone?

**Comment by Donnerbart** [comment]
We made this configurable for the Near Cache, so per default the keys are not serialized anymore. But if you have keys which don't work with references, you can switch back to serialize all keys. The Near Cache and `ReplicatedMap` are comparable in the way, that both are based on local maps (the `ReplicatedMap` just adds the replication of the local values to it, while the Near Cache just has invalidation as remote part). So I guess we could apply the same solution for the `ReplicatedMap` and make this configurable. But this would imply more work. Maybe a PRD is advisable.

The result would basically be this PR + new Near Cache like config `<serialize-keys>`.

**Pull request closed without merging**
