### PR TITLE
Optimized toArray(new Object[]) calls

### PR DESCRIPTION
**Pull request by Donnerbart**
Inspired by an IDEA warning and some good reads it seems safe to say, that calling `toArray(new T[0])` is faster than `toArray(new T[size])` since about 5 years.

Using array constants like Peter Lawrey suggests, doesn't seem to be justified and may have unwanted side effects (the constant array may be returned in some edge cases, so object identity issues can come up).

For further details I recommend the article from Aleksey Shipilёv.

screenshot from 2018-05-11 15-22-54
https://shipilev.net/blog/2016/arrays-wisdom-ancients/
https://vanillajava.blogspot.de/2011/06/performance-tip-avoid.html

### CODE REVIEW

**Comment by Holmistr** [comment]
@pveentjer We're actually trying it out, whether or not it will be useful for us. I would like to have a test run and gather opinions on this. I count yours as "I hate it" :) Please don't get annoyed by this, if there will be general disagreement with this, I'm happy to remove it, but let's see its pros and cons, ok?

**Comment by pveentjer** [comment]
Perhaps there is some low level trickery going on to prevent creating the array. 

This is from a JMH benchmark

```

Benchmark                                                  Mode  Cnt    Score     Error   Units
ArrayBenchmark.cached                                      avgt   20   26.313 ±   0.766   ns/op
ArrayBenchmark.cached:·gc.alloc.rate                       avgt   20  870.505 ±  24.178  MB/sec
ArrayBenchmark.cached:·gc.alloc.rate.norm                  avgt   20   24.000 ±   0.001    B/op
ArrayBenchmark.cached:·gc.churn.PS_Eden_Space              avgt   20  880.841 ± 115.797  MB/sec
ArrayBenchmark.cached:·gc.churn.PS_Eden_Space.norm         avgt   20   24.273 ±   3.122    B/op
ArrayBenchmark.cached:·gc.churn.PS_Survivor_Space          avgt   20    0.366 ±   0.504  MB/sec
ArrayBenchmark.cached:·gc.churn.PS_Survivor_Space.norm     avgt   20    0.010 ±   0.014    B/op
ArrayBenchmark.cached:·gc.count                            avgt   20   71.000            counts
ArrayBenchmark.cached:·gc.time                             avgt   20  155.000                ms
ArrayBenchmark.notCached                                   avgt   20   25.143 ±   0.394   ns/op
ArrayBenchmark.notCached:·gc.alloc.rate                    avgt   20  910.358 ±  13.810  MB/sec
ArrayBenchmark.notCached:·gc.alloc.rate.norm               avgt   20   24.000 ±   0.001    B/op
ArrayBenchmark.notCached:·gc.churn.PS_Eden_Space           avgt   20  931.804 ± 125.762  MB/sec
ArrayBenchmark.notCached:·gc.churn.PS_Eden_Space.norm      avgt   20   24.582 ±   3.424    B/op
ArrayBenchmark.notCached:·gc.churn.PS_Survivor_Space       avgt   20    0.178 ±   0.073  MB/sec
ArrayBenchmark.notCached:·gc.churn.PS_Survivor_Space.norm  avgt   20    0.005 ±   0.002    B/op
ArrayBenchmark.notCached:·gc.count                         avgt   20   75.000            counts
ArrayBenchmark.notCached:·gc.time                          avgt   20  179.000                ms

Process finished with exit code 0
```

As you can see the allocation rate in both cases is nearly identical.

```
package com.hazelcast;

import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Fork;
import org.openjdk.jmh.annotations.Measurement;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.openjdk.jmh.annotations.Warmup;
import org.openjdk.jmh.infra.Blackhole;

import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.TimeUnit;


@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Thread)
@Fork(value = 4, warmups = 1)
@Warmup(iterations = 2)
@Measurement(iterations = 5)
public class ArrayBenchmark {

    public static Integer[] emptyArray = new Integer[0];
    public Set<Integer> items;


    @Setup
    public void prepare() {
        items = new HashSet<Integer>();
        items.add(1);
    }

    @Benchmark
    public void cached(Blackhole blackhole) {
        blackhole.consume(items.toArray(emptyArray));
    }

    @Benchmark
    public void notCached(Blackhole blackhole) {
        blackhole.consume(items.toArray(new Integer[0]));
    }
}

```

**Comment by Donnerbart** [comment]
The case in question is `toArray(new T[size])` vs. `toArray(new T[0])`, not so much the constant optimization. Kudos to Vassilis for digging out this article, which goes down the whole road of debugging:
> Bottom line: toArray(new T[0]) seems faster, safer, and contractually cleaner, and therefore should be the default choice now. Future VM optimizations may close this performance gap for toArray(new T[size]), rendering the current "believed to be optimal" usages on par with an actually optimal one. 

https://shipilev.net/blog/2016/arrays-wisdom-ancients/

Aleksey Shipilёv also tested the `toArray(new T[0])` vs. `toArray(EMPTY_T_ARRAY)`, and it seems to be better to create an empty array.

**Comment by Donnerbart** [comment]
run-lab-run

**Comment by Donnerbart** [comment]
Oh, and I came to very similar result like Aleksey with an adapted JMH benchmark:
```java
Benchmark                        (setSize)  Mode  Cnt      Score     Error  Units
ArrayBenchmark.noArray                   0  avgt  200     20.843 ±   0.051  ns/op
ArrayBenchmark.cachedEmptyArray          0  avgt  200      3.699 ±   0.019  ns/op
ArrayBenchmark.emptyArray                0  avgt  200      4.545 ±   0.031  ns/op
ArrayBenchmark.preSizedArray             0  avgt  200     20.831 ±   0.054  ns/op

ArrayBenchmark.noArray                   1  avgt  200     23.077 ±   0.096  ns/op
ArrayBenchmark.cachedEmptyArray          1  avgt  200     23.652 ±   0.116  ns/op
ArrayBenchmark.emptyArray                1  avgt  200     23.563 ±   0.109  ns/op
ArrayBenchmark.preSizedArray             1  avgt  200     23.030 ±   0.122  ns/op

ArrayBenchmark.noArray                  10  avgt  200     38.718 ±   0.158  ns/op
ArrayBenchmark.cachedEmptyArray         10  avgt  200     44.853 ±   0.278  ns/op
ArrayBenchmark.emptyArray               10  avgt  200     44.730 ±   0.267  ns/op
ArrayBenchmark.preSizedArray            10  avgt  200     45.288 ±   0.227  ns/op

ArrayBenchmark.noArray                  50  avgt  200    144.001 ±   0.964  ns/op
ArrayBenchmark.cachedEmptyArray         50  avgt  200    168.194 ±   1.086  ns/op
ArrayBenchmark.emptyArray               50  avgt  200    167.198 ±   0.969  ns/op
ArrayBenchmark.preSizedArray            50  avgt  200    178.760 ±   1.003  ns/op

ArrayBenchmark.noArray                 100  avgt  200    294.647 ±   1.789  ns/op
ArrayBenchmark.cachedEmptyArray        100  avgt  200    296.556 ±   1.768  ns/op
ArrayBenchmark.emptyArray              100  avgt  200    298.059 ±   1.833  ns/op
ArrayBenchmark.preSizedArray           100  avgt  200    333.617 ±   2.596  ns/op

ArrayBenchmark.noArray                1000  avgt  200   4109.029 ±  26.947  ns/op
ArrayBenchmark.cachedEmptyArray       1000  avgt  200   4400.846 ±  28.378  ns/op
ArrayBenchmark.emptyArray             1000  avgt  200   4424.966 ±  39.082  ns/op
ArrayBenchmark.preSizedArray          1000  avgt  200   4484.918 ±  35.367  ns/op

ArrayBenchmark.noArray                5000  avgt  200  18423.170 ± 107.772  ns/op
ArrayBenchmark.cachedEmptyArray       5000  avgt  200  12349.205 ± 102.671  ns/op
ArrayBenchmark.emptyArray             5000  avgt  200  12216.233 ±  99.082  ns/op
ArrayBenchmark.preSizedArray          5000  avgt  200  12230.137 ±  75.299  ns/op

ArrayBenchmark.noArray               10000  avgt  200  36212.119 ± 233.342  ns/op
ArrayBenchmark.cachedEmptyArray      10000  avgt  200  40320.663 ± 316.933  ns/op
ArrayBenchmark.emptyArray            10000  avgt  200  41002.732 ± 313.835  ns/op
ArrayBenchmark.preSizedArray         10000  avgt  200  40410.324 ± 305.093  ns/op
```
(didn't want the spent energy of those numbers to be wasted)

**Comment by pveentjer** [comment]
:+1:

**Pull request merged**
