### PR TITLE
Fixes possible NPE case for removeFirstOccurence method

### PR DESCRIPTION
**Pull request by ahmetmircik**
closes https://github.com/hazelcast/hazelcast/issues/7082

### CODE REVIEW

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
verify

**Comment by eminn** [comment]
:+1:

**Comment by ahmetmircik** [comment]
this needs for simulator runs, merging it.

**Pull request merged**
