### PR TITLE
Fixed wrong calculation of eviction removal size when PER_NODE max-si…

### PR DESCRIPTION
**Pull request by ahmetmircik**
…ze-policy is used

### CODE REVIEW

**Comment by gurbuzali** [comment]
:+1:

**Comment by Serdaro** [comment]
Does this have a documentation impact?

**Comment by ahmetmircik** [comment]
@Serdaro It can be included in fixes part of 3.5.4.

**Comment by Serdaro** [comment]
Will do, thank you.

**Pull request merged**
