### PR TITLE
FindBugs fix, Iterator.next should throw NoSuchElementException

### PR DESCRIPTION
**Pull request by ajermakovics**
checkHasNext does throw NoSuchElementException but that's not picked up by FindBugs. Need to throw explicitly.

### CODE REVIEW

**Comment by Donnerbart** [comment]
Hmm, strange bug. Fix looks okay for me, since it does the same as the `ValidationUtil`. Did you run FindBugs locally and it stops complaining now?

**Comment by jerrinot** [comment]
technically it's not the same as now there is no message passed into the `NoSuchElementException` ;-)

**Comment by ajermakovics** [comment]
Indeed, the findbugs rule could be enhanced. It passes now.

**Comment by ajermakovics** [comment]
The rule http://findbugs.sourceforge.net/bugDescriptions.html#IT_NO_SUCH_ELEMENT

**Comment by jerrinot** [comment]
:+1:

**Pull request merged**
