### PR TITLE
MapService refactorings

### PR DESCRIPTION
**Pull request by ahmetmircik**
Mainly contains:
- Relaxed some strictness of MapService related functionality like MapService, MapServiceContext and related auxiliary services in order to make them more extendible for future uses.
- Removed unused methods

### CODE REVIEW

**Comment by gurbuzali** [comment]
:+1:

**Comment by eminn** [comment]
:+1:

**Comment by serkan-ozal** [comment]
@gurbuzali @ahmetmircik Similar enhancements should be done on enterprise part (in `EnterpriseNodeExtension`)

**Comment by serkan-ozal** [comment]
such as 

``` java
public <T> T createService(Class<T> clazz) {
         ...
         else if (MapService.class.isAssignableFrom(clazz)) {
                  return createMapService();
         }
         throw new IllegalArgumentException("Unknown service class: " + clazz);
}
```

Otherwise, causes this exception 

```
java.lang.IllegalArgumentException: Unknown service class: class com.hazelcast.map.impl.MapService
	at com.hazelcast.instance.EnterpriseNodeExtension.createService(EnterpriseNodeExtension.java:329)
	at com.hazelcast.spi.impl.ServiceManager.createService(ServiceManager.java:135)
	at com.hazelcast.spi.impl.ServiceManager.registerDefaultServices(ServiceManager.java:114)
	at com.hazelcast.spi.impl.ServiceManager.registerServices(ServiceManager.java:92)
	at com.hazelcast.spi.impl.ServiceManager.start(ServiceManager.java:82)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:90)
	at com.hazelcast.instance.Node.start(Node.java:327)
	...
```

**Comment by serkan-ozal** [comment]
on `EnterpriseNodeExtension` instead of throwing exception, `super.createService(clazz)` can be called simply.

**Pull request merged**
