### PR TITLE
Removed unnecessary CheckStyle suppressions for DataAwareMessage and TopicEvent

### PR DESCRIPTION
**Pull request by Donnerbart**
* Removed unnecessary CheckStyle suppressions of `DataAwareMessage` and `TopicEvent`.
* Removed simple warning in `DataAwareMessage`.
* Aligned assignment order in `TopicEvent` to field order (and remaning methods).

### CODE REVIEW

**Comment by Donnerbart** [comment]
run-parallel

**Comment by Donnerbart** [comment]
run-parallel

**Comment by Donnerbart** [comment]
verify

**Comment by jerrinot** [comment]
:+1:

**Pull request merged**
