### PR TITLE
Fixes IOBalancer Memory Leak 

### LINKED ISSUE #6199: IOBalancer has a memory leak
IOBalancer keeps references of all the socket reader/writers but when destroying the connection they release the references for only the ones which has endpoints.

It could be seen from the image below that socket writers consume %77 of the total memory after all the connections to hazelcast are destroyed.

screen shot 2015-09-14 at 10 55 32 am

### PR DESCRIPTION
**Pull request by eminn**
If the connection is destroyed and removed from active connections, it should be removed from iobalancer regardless of connection endpoint. 

After this fix memory consumption pattern is like below when hundreds of connections are opened/closed to the hazelcast instance. 

screen shot 2015-09-14 at 10 54 47 am

### CODE REVIEW

**Comment by pveentjer** [comment]
Good work. 

a few questions:
- can you create a unit test which verifies the behavior?
- when does this particular exception happen; so how did you stumble on this issue?

**Comment by eminn** [comment]
I won't write a stress test by checking the memory size for detecting a leak since it is fragile but I will try to write a unit test with mocks if possible.

This issue happens when REST API is used, after some time oome happens even though cluster is not doing any data storage etc.

**Comment by pveentjer** [comment]
Hi Emin, a regular unit test is perfectly fine.

We should add rest simulator tests :)

**Comment by bwzhang2011** [comment]
@eminn, could it be back port ?

**Comment by eminn** [comment]
@bwzhang2011 see #6201

**Pull request merged**
