### PR TITLE
Fixes lite member attribute in spring configuration parsing

### PR DESCRIPTION
**Pull request by mustafaiman**
Fixes https://github.com/hazelcast/hazelcast/issues/6945

### CODE REVIEW

**Comment by emrahkocaman** [comment]
:+1:

**Comment by emrahkocaman** [comment]
run-lab-run

**Comment by bilalyasar** [comment]
Can you write test for this comment? https://github.com/hazelcast/hazelcast/issues/6945#issuecomment-161316598

**Comment by mustafaiman** [comment]
@bilalyasar I verified it works with PropertyPlaceholders using following configuration:
hazelcast.properties
```
hazelcast.lite-member-enabled=true
```

application-context.xml
```
    <hz:hazelcast id="instance">
        <hz:config>
            <hz:spring-aware/>
            <hz:group name="test" password="test-pass"/>
            <hz:network port="5701" port-auto-increment="false">
                <hz:join>
                    <hz:multicast enabled="false"/>
                    <hz:tcp-ip enabled="true">
                        <hz:interface>127.0.0.1:5701</hz:interface>
                    </hz:tcp-ip>
                </hz:join>
                <hz:interfaces enabled="true">
                    <hz:interface>127.0.0.1</hz:interface>
                </hz:interfaces>
            </hz:network>
            <hz:lite-member enabled="${hazelcast.lite-member-enabled}"/>
        </hz:config>
    </hz:hazelcast>

    <bean class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer" >
        <property name="location">
            <value>hazelcast.properties</value>
        </property>
    </bean>
```

However I think this should not be a part of our tests because this is Spring's feature to replace some placeholders in application-context with values from a file you provide. It is not related to our implementation.

**Comment by mustafaiman** [comment]
run-lab-run

**Comment by mesutcelik** [comment]
:+1:

**Pull request merged**
