### PR TITLE
Remove logging of client requests failures

### PR DESCRIPTION
**Pull request by sancar**
These exceptions are already send to client and handled on client
side.

### CODE REVIEW

**Comment by pveentjer** [comment]
:+1:

**Comment by sancar** [comment]
@pveentjer Sorry but I have changed the pr on the fly. I found a couple of places where try catch is used but actually not needed. And instead of deleting the logging. I made all logged in FINEST level. You may need to re-review.

**Comment by pveentjer** [comment]
:+1:

**Comment by mdogan** [comment]
:+1:

**Pull request merged**
