### PR TITLE
Remove legacy CountdownLatch

### PR DESCRIPTION
**Pull request by mdogan**
Removed legacy CountdownLatch implementation and `HazelcastInstance.getCountdownLatch(..)` method. Instead we provide _unsafe_ mode for all CP data structures (See https://github.com/hazelcast/hazelcast/pull/15184).

EE: https://github.com/hazelcast/hazelcast-enterprise/pull/3155

See TDD: https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1749057609/Concurrency+API+Clean-up+Design

Protocol change: https://github.com/hazelcast/hazelcast-client-protocol/pull/225

### CODE REVIEW

**Comment by asimarslan** [comment]
@mdogan Can you send the client protocol changes to protocol repo too?

**Comment by mdogan** [comment]
@asimarslan: I'm planning to send changes to the protocol repo. But I want to do that as the final step, since after `ICountDownLatch` and `ISemaphore`, I will cleanup `IAtomicLong`, `IAtomicReference` and `ILock` too. 

Last week I confirmed this with @mdumandag, he said that protocol and Hazelcast repo are not dependent to each other, so it's possible to do protocol changes after removing message-tasks and codecs. 

Are you ok with this?

**Comment by asimarslan** [comment]
We removed the dependency for better development experience.  We don't need to make protocol releases anymore but I think we still need to review the protocol PR before merging this PR.

**Comment by mdogan** [comment]
See https://github.com/hazelcast/hazelcast-client-protocol/pull/222

**Comment by mdogan** [comment]
@hazelcast/clients: Hunting down consistency bugs are easier than changing client related code.🤦‍♂

**Pull request merged**
