### PR TITLE
Removes patched surefire dependency

### PR DESCRIPTION
**Pull request by mmedenjak**
Upgrade surefire dependency version and reverts using patched surefire
dependency from #10352.

### CODE REVIEW

**Comment by jerrinot** [comment]
I agree we should remove it before the GA release. the problem is it will most likely cause stalling loggers (on AWS) again, etc..

**Comment by mmedenjak** [comment]
@jerrinot I know, I just added this so we don't forget it. My idea was that we merge it as the last PR and revert it after we release GA.

**Comment by mmedenjak** [comment]
@jerrinot updated the PR with the new surefire dependency

**Comment by mdogan** [comment]
run-lab-run

**Pull request merged**
