### PR TITLE
Quorum support left-overs

### PR DESCRIPTION
**Pull request by tombujok**
Best to review commit by commit.

### CODE REVIEW

**Comment by ahmetmircik** [comment]
can we have tests for workable-version fix and leak fix?

**Comment by tombujok** [comment]
@ahmetmircik Thx for comments. Just added a rolling upgrade test. 
When it comes to the cache it is an internal concern, I don't want to expose it via API. Don't know if it makes sense to test it via reflection... The cache & bug is there already in production so maybe we can create an issue to test it more properly in the future. I need to focus on other parts now.

**Comment by tombujok** [comment]
run-lab-run

**Comment by tombujok** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by tombujok** [comment]
Fixes #12101 
Fixes #12102 
Fixes #12108

**Comment by tombujok** [comment]
@vbekiaris @metanet thx for reviews!

**Pull request merged**
