### PR TITLE
Copyright year update (2020->2021)

### PR DESCRIPTION
**Pull request by mmedenjak**
... removing traces of 2020

EE: https://github.com/hazelcast/hazelcast-enterprise/pull/3917

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CodecHashTest.testCodecHashCodes:53->testCodecsInternal:78 AtomicLongAddAndGetCodec.java modified by hand. Instead, use hazelcast-client-protocol to generate this codec. Cause: Hash code does not match with the file content. expected:<[6371abd926d3735f254d22d17d894cc2]> but was:<[4e3edd3721efd115236a275e72c3f705]>
[ERROR]   CodecHashTest.testCustomCodecHashCodes:58->testCodecsInternal:78 AddressCodec.java modified by hand. Instead, use hazelcast-client-protocol to generate this codec. Cause: Hash code does not match with the file content. expected:<[aaa5bd7c97c35661926df5947ccdbb1b]> but was:<[53f582521f77759b1867a030fe771489]>
[INFO] 
[ERROR] Tests run: 35480, Failures: 2, Errors: 0, Skipped: 979
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

**Comment by mdumandag** [comment]
@mmedenjak I updated the codec templates in the protocol repo accordingly. Could you re-create the codecs?

Checksum tests for the codecs make sure that nothing is changed by hand, so a codec regeneration is required.

**Review by Fly-Style — APPROVED** [review]

**Review by sancar — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqlNoDeserializationTest.testClient:149 Failed to resolve key metadata: java.io.IOException: KEY FAILURE
[INFO] 
[ERROR] Tests run: 1111, Failures: 1, Errors: 0, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

**Comment by mmedenjak** [comment]
Merging with unrelated test failure to unblock further PRs generating the codecs. Thank you for the quick reviews.

**Pull request merged**
