### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by petprog**
I feel there is a need for the changes for the version name
4.0.1 to `4.0.1`

### CODE REVIEW

**Comment by kwart** [comment]
run-lab-run

**Review by kwart — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2776/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2776/Hazelcast-pr-builder-2776.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PartitionMigrationListenerTest.testMigrationListenerCalledOnlyOnceWhenMigrationHappens:280->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253->lambda$testMigrationListenerCalledOnlyOnceWhenMigrationHappens$2:281 expected:<1> but was:<2>
[INFO] 
[ERROR] Tests run: 32031, Failures: 1, Errors: 0, Skipped: 979
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by kwart** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Thank you for the contribution @petprog !

**Pull request merged**
